<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=0",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=0&pg_no=2",
		"RB_LINK=DB_INFO.PHP?lang=0&pg_no=4",
		"MOVE_CHAR=./GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=./GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					25/9 Update Information ②<BR>
				<tr><td>
					25/9 Update Information ①<BR>
					18/9 Update Information ②<BR>
					18/9 Update Information ①<BR>
					11/9 Update Information ④<BR>
					11/9 Update Information ③<BR>
					11/9 Update Information ②<BR>
					11/9 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>25/9 Update Information ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Challenge Quest 6</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>25/9 Update Information ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Challenge Quest 6--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Instructor<BR>I got a request to do<BR>something about all the huge<BR>bugs that have popped up in<BR>the Old Jungle. Just an<BR>idea, but you might want to<BR>go for the leader here. Make<BR>a beeline for the Queen!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/c61006.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					25/9 Update Information ②<BR>
				<tr><td bgcolor=green>
					25/9 Update Information ①<BR>
				<tr><td>
					18/9 Update Information ②<BR>
					18/9 Update Information ①<BR>
					11/9 Update Information ④<BR>
					11/9 Update Information ③<BR>
					11/9 Update Information ②<BR>
					11/9 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>25/9 Update Information ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>The Big Daddy</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>25/9 Update Information ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--The Big Daddy--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Pure White Felyne<BR>Master! Do you plan to check<BR>out the old Tower? You<BR>can't afford to miss it,<BR>meow... And if you do go,<BR>you'll see something pretty<BR>incredible... Though I have<BR>a bad feeling about going...<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60029.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					25/9 Update Information ②<BR>
					25/9 Update Information ①<BR>
				<tr><td bgcolor=green>
					18/9 Update Information ②<BR>
				<tr><td>
					18/9 Update Information ①<BR>
					11/9 Update Information ④<BR>
					11/9 Update Information ③<BR>
					11/9 Update Information ②<BR>
					11/9 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>18/9 Update Information ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Arena of Blood and Tears</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>18/9 Update Information ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Arena of Blood and Tears--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Serious Lady Knight<BR>It is not my usual practice,<BR>however, there is no other<BR>way for me to test your<BR>strength. Therefore, show me<BR>your true power. You may<BR>expect to be compensated for<BR>your trouble.<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60017.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					25/9 Update Information ②<BR>
					25/9 Update Information ①<BR>
					18/9 Update Information ②<BR>
				<tr><td bgcolor=green>
					18/9 Update Information ①<BR>
				<tr><td>
					11/9 Update Information ④<BR>
					11/9 Update Information ③<BR>
					11/9 Update Information ②<BR>
					11/9 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>18/9 Update Information ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Its name is 'Mega Kut-Ku'!?</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>18/9 Update Information ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Its name is 'Mega Kut-Ku'!?--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Food Connoisseur<BR>I came here in search of a<BR>meal yet to be tasted by<BR>mortal buds. I hear there is<BR>a legendary creature that<BR>lives on that hill nearby.<BR>Help me fulfill my life-long<BR>ambition! Hurry to the hunt!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60023.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					25/9 Update Information ②<BR>
					25/9 Update Information ①<BR>
					18/9 Update Information ②<BR>
					18/9 Update Information ①<BR>
				<tr><td bgcolor=green>
					11/9 Update Information ④<BR>
				<tr><td>
					11/9 Update Information ③<BR>
					11/9 Update Information ②<BR>
					11/9 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>11/9 Update Information ④</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update will include<BR>5 new Bonus Items, meow!<BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>11/9 Update Information ④</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
The Bonus Items will be added.
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
<font color=orange>Piggie Fashions:<BR>　Sleepy&nbsp;Pig&nbsp;White<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br></font>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/b00004.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					25/9 Update Information ②<BR>
					25/9 Update Information ①<BR>
					18/9 Update Information ②<BR>
					18/9 Update Information ①<BR>
					11/9 Update Information ④<BR>
				<tr><td bgcolor=green>
					11/9 Update Information ③<BR>
				<tr><td>
					11/9 Update Information ②<BR>
					11/9 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>11/9 Update Information ③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update will include<BR>5 new Bonus Items, meow!<BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>11/9 Update Information ③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
The Bonus Items will be added.
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
<font color=orange>Wandering Chefs:<BR>　Jet&nbsp;Black<BR>Titles:<BR>　E.Dragon&nbsp;King<BR>　Schrade<BR>　Famous<BR>　　　　　　　　　　　　　　<br></font>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/b00003.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					25/9 Update Information ②<BR>
					25/9 Update Information ①<BR>
					18/9 Update Information ②<BR>
					18/9 Update Information ①<BR>
					11/9 Update Information ④<BR>
					11/9 Update Information ③<BR>
				<tr><td bgcolor=green>
					11/9 Update Information ②<BR>
				<tr><td>
					11/9 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>11/9 Update Information ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Challenge Quest 5</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>11/9 Update Information ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Challenge Quest 5--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Instructor<BR>Running on an empty tank is<BR>the worst thing a hunter can<BR>do. That is to say, to<BR>master eating is to master<BR>the hunt! I'm going to turn<BR>you into the best cook ever!<BR>Or at least the best BBQer!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/c61005.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					25/9 Update Information ②<BR>
					25/9 Update Information ①<BR>
					18/9 Update Information ②<BR>
					18/9 Update Information ①<BR>
					11/9 Update Information ④<BR>
					11/9 Update Information ③<BR>
					11/9 Update Information ②<BR>
				<tr><td bgcolor=green>
					11/9 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>11/9 Update Information ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Porky Panic Party!</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>11/9 Update Information ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Porky Panic Party!--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Showy Suspect Dame<BR>I require some entertainment<BR>at my party, for which I am<BR>recruiting hunters. Hee hee<BR>hee... It's a veritable<BR>buffet of free-roaming<BR>porkers, if you will. Can<BR>you outrun them, I wonder...<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60020.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
</body>
</html>
