<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=0",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=0&pg_no=5",
		"RB_LINK=DB_INFO.PHP?lang=0&pg_no=1",
		"MOVE_CHAR=./GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=./GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					5/4 Update Information ②<BR>
				<tr><td>
					5/4 Update Information ①<BR>
					2/4 Update Information ③<BR>
					2/4 Update Information ②<BR>
					2/4 Update Information ①<BR>
					25/12 Update Information ③<BR>
					25/12 Update Information ②<BR>
					25/12 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>5/4 Update Information ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Twin Terrors</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>5/4 Update Information ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Twin Terrors--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:DeathlyPaleMercenary<BR>I can't believe what I saw!<BR>It was terrible! There they<BR>were, 2 Rajang just sitting<BR>there in the arena...<BR>Listen, if you value your<BR>life at all, absolutely do<BR>not go near there! Got it!?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60038.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Update Information ②<BR>
				<tr><td bgcolor=green>
					5/4 Update Information ①<BR>
				<tr><td>
					2/4 Update Information ③<BR>
					2/4 Update Information ②<BR>
					2/4 Update Information ①<BR>
					25/12 Update Information ③<BR>
					25/12 Update Information ②<BR>
					25/12 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>5/4 Update Information ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>High Altitude King</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>5/4 Update Information ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--High Altitude King--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Benevolent Monarch<BR>The profoundly powerful<BR>Akantor... <BR>We chased it this far,<BR>however, we've sustained<BR>heavy damage. Hunters of<BR>this land! I ask for your<BR>immediate help!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60034.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Update Information ②<BR>
					5/4 Update Information ①<BR>
				<tr><td bgcolor=green>
					2/4 Update Information ③<BR>
				<tr><td>
					2/4 Update Information ②<BR>
					2/4 Update Information ①<BR>
					25/12 Update Information ③<BR>
					25/12 Update Information ②<BR>
					25/12 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>2/4 Update Information ③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Hunting God's Free-For-All</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>2/4 Update Information ③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Hunting God's Free-For-All--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Red-Clad Knight<BR>O ye who would take up this<BR>test! Believe in thine own<BR>strength, and the strength<BR>of thy companions, for it is<BR>in the thick of danger that<BR>fortitude is tested. Keep<BR>hope and fight to the end!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60019.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Update Information ②<BR>
					5/4 Update Information ①<BR>
					2/4 Update Information ③<BR>
				<tr><td bgcolor=green>
					2/4 Update Information ②<BR>
				<tr><td>
					2/4 Update Information ①<BR>
					25/12 Update Information ③<BR>
					25/12 Update Information ②<BR>
					25/12 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>2/4 Update Information ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Mountain in the Sky</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>2/4 Update Information ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Mountain in the Sky--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Long-Haired Old Lady<BR>One time, when I was a<BR>little girl, I saw a giant<BR>shadow in the sky. It was<BR>bigger than any wyvern I'd<BR>ever seen... Was it all just<BR>a dream? Would you look into<BR>this for me, please, deary?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60010.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Update Information ②<BR>
					5/4 Update Information ①<BR>
					2/4 Update Information ③<BR>
					2/4 Update Information ②<BR>
				<tr><td bgcolor=green>
					2/4 Update Information ①<BR>
				<tr><td>
					25/12 Update Information ③<BR>
					25/12 Update Information ②<BR>
					25/12 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>2/4 Update Information ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Demon's Teardrop Mountain</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>2/4 Update Information ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Demon's Teardrop Mountain--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Young Nobleman<BR>Two Rajang stole my lovely,<BR>unwilling bride and escaped<BR>into the mountains. I don't<BR>care that she doesn't want<BR>me, but I can't live without<BR>her! Please, lend me your<BR>strength!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60016.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Update Information ②<BR>
					5/4 Update Information ①<BR>
					2/4 Update Information ③<BR>
					2/4 Update Information ②<BR>
					2/4 Update Information ①<BR>
				<tr><td bgcolor=green>
					25/12 Update Information ③<BR>
				<tr><td>
					25/12 Update Information ②<BR>
					25/12 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>25/12 Update Information ③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update will include<BR>1 new Bonus Items, meow!<BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>25/12 Update Information ③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
The Bonus Items will be added.
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
<font color=orange>Piggie Fashions:<BR>　Mafumofu&nbsp;Jumpsuit<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br></font>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/b00011.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Update Information ②<BR>
					5/4 Update Information ①<BR>
					2/4 Update Information ③<BR>
					2/4 Update Information ②<BR>
					2/4 Update Information ①<BR>
					25/12 Update Information ③<BR>
				<tr><td bgcolor=green>
					25/12 Update Information ②<BR>
				<tr><td>
					25/12 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>25/12 Update Information ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Four Kings of Fire</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>25/12 Update Information ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Four Kings of Fire--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:White-Clad Scientist<BR>We've confirmed that the<BR>Volcano zone is ripe feeding<BR>grounds for a large variety<BR>of monsters. If you please,<BR>go to that area and hunt<BR>down 4 species for us to use<BR>in our research, would you?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60018.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Update Information ②<BR>
					5/4 Update Information ①<BR>
					2/4 Update Information ③<BR>
					2/4 Update Information ②<BR>
					2/4 Update Information ①<BR>
					25/12 Update Information ③<BR>
					25/12 Update Information ②<BR>
				<tr><td bgcolor=green>
					25/12 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>25/12 Update Information ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Two Cliffs! Dark Hot Winds</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>25/12 Update Information ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Two Cliffs! Dark Hot Winds--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Arena Manager<BR>Come one, come all, to the<BR>ultimate arena! I've got 2,<BR>yes, count 'em, 2 fearsome<BR>Black Gravios right here<BR>in this very arena! Think<BR>you've got what it takes to<BR>beat these wild beasts?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60015.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
</body>
</html>
