<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=0",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=0&pg_no=1",
		"RB_LINK=DB_INFO.PHP?lang=0&pg_no=3",
		"MOVE_CHAR=./GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=./GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					23/10 Update Information ②<BR>
				<tr><td>
					23/10 Update Information ①<BR>
					16/10 Update Information ②<BR>
					16/10 Update Information ①<BR>
					9/10 Update Information ②<BR>
					9/10 Update Information ①<BR>
					2/10 Update Information ②<BR>
					2/10 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>23/10 Update Information ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Monster Hunter Fiesta 4</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>23/10 Update Information ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Monster Hunter Fiesta 4--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Virtuous Promoter<BR>Thanks to the participation<BR>of so many strong hunters,<BR>we've been able to reach<BR>this stage, the finale! We<BR>hope that all the hunters<BR>will join in one last hunt<BR>in a show of true might!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/f00004.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					23/10 Update Information ②<BR>
				<tr><td bgcolor=green>
					23/10 Update Information ①<BR>
				<tr><td>
					16/10 Update Information ②<BR>
					16/10 Update Information ①<BR>
					9/10 Update Information ②<BR>
					9/10 Update Information ①<BR>
					2/10 Update Information ②<BR>
					2/10 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>23/10 Update Information ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Hunter's Fiesta!</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>23/10 Update Information ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Hunter's Fiesta!--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Short-Haired Girl<BR>I... I'm the one in charge<BR>of the festival this time,<BR>and, um... *ahem* The reward<BR>for skillfully winning this<BR>challenge is a very special<BR>ticket! So, um, I hope you<BR>will all give it a try!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60035.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					23/10 Update Information ②<BR>
					23/10 Update Information ①<BR>
				<tr><td bgcolor=green>
					16/10 Update Information ②<BR>
				<tr><td>
					16/10 Update Information ①<BR>
					9/10 Update Information ②<BR>
					9/10 Update Information ①<BR>
					2/10 Update Information ②<BR>
					2/10 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>16/10 Update Information ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Scarlet Skies</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>16/10 Update Information ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Scarlet Skies--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Guild Heavyweight<BR>Look at that fiery scarlet<BR>sky! The legends are true!<BR>The wrath of a Fatalis turns<BR>even the sky blood red.<BR>Please, someone, anyone!<BR>Quell the rage and return<BR>the sky to its normal color!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60031.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					23/10 Update Information ②<BR>
					23/10 Update Information ①<BR>
					16/10 Update Information ②<BR>
				<tr><td bgcolor=green>
					16/10 Update Information ①<BR>
				<tr><td>
					9/10 Update Information ②<BR>
					9/10 Update Information ①<BR>
					2/10 Update Information ②<BR>
					2/10 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>16/10 Update Information ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Monster Hunter Fiesta 3</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>16/10 Update Information ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Monster Hunter Fiesta 3--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Voluptuous Promoter<BR>It appears that we have<BR>arrived at the best part of<BR>these competitions. I wonder<BR>who will stand tall in the<BR>end and take home the proof!<BR>I look forward to seeing<BR>your magnificent technique.<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/f00003.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					23/10 Update Information ②<BR>
					23/10 Update Information ①<BR>
					16/10 Update Information ②<BR>
					16/10 Update Information ①<BR>
				<tr><td bgcolor=green>
					9/10 Update Information ②<BR>
				<tr><td>
					9/10 Update Information ①<BR>
					2/10 Update Information ②<BR>
					2/10 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>9/10 Update Information ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Challenge Quest 7</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>9/10 Update Information ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Challenge Quest 7--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Instructor<BR>Fight 2 Nargacugas back to<BR>back! Be wary of their<BR>intense speed and their<BR>super-strong tails! One<BR>swish is all it takes! Stay<BR>cool and think things out.<BR>They'll fall soon enough.<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/c61007.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					23/10 Update Information ②<BR>
					23/10 Update Information ①<BR>
					16/10 Update Information ②<BR>
					16/10 Update Information ①<BR>
					9/10 Update Information ②<BR>
				<tr><td bgcolor=green>
					9/10 Update Information ①<BR>
				<tr><td>
					2/10 Update Information ②<BR>
					2/10 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>9/10 Update Information ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Two Walls? Dark Winds</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>9/10 Update Information ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Two Walls? Dark Winds--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Suspicious Manager<BR>Come one, come all, to the<BR>ultimate arena! I've got 2<BR>of the hardest, strongest,<BR>and most terrifying monsters<BR>around! Step on up! Prove<BR>you've got the right stuff!<BR>　　　　　　　　　　　　　　<br>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60011.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					23/10 Update Information ②<BR>
					23/10 Update Information ①<BR>
					16/10 Update Information ②<BR>
					16/10 Update Information ①<BR>
					9/10 Update Information ②<BR>
					9/10 Update Information ①<BR>
				<tr><td bgcolor=green>
					2/10 Update Information ②<BR>
				<tr><td>
					2/10 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>2/10 Update Information ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Beasts of the Dunes</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>2/10 Update Information ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Beasts of the Dunes--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Wounded Creatures<BR>We made a promise to our<BR>master, meow! We've just got<BR>to get this letter to its<BR>destination! We were so<BR>close, but there were these<BR>monsters hanging about...<BR>Please... Help us... Meow...<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60012.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					23/10 Update Information ②<BR>
					23/10 Update Information ①<BR>
					16/10 Update Information ②<BR>
					16/10 Update Information ①<BR>
					9/10 Update Information ②<BR>
					9/10 Update Information ①<BR>
					2/10 Update Information ②<BR>
				<tr><td bgcolor=green>
					2/10 Update Information ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=./GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>2/10 Update Information ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Laurel, Please.</font><BR><BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=./GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=./GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>2/10 Update Information ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>--Laurel, Please.--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Young Arena Manager<BR>Wanna show off? Then the<BR>arena is perfect for you!<BR>Today on the menu, we've<BR>got a Congalala, a Rathian,<BR>a Shogun Ceanataur, and a<BR>whole lot more! Use those<BR>few Potions you find well!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=./PNG/e60025.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
</body>
</html>
