<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=0",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:7",
		"MOVE_CHAR=./GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=./GIF/PIG.gif,64,48,1,1,3,10,480,050",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=./GIF/BG.gif>
<basefont size=2>
<B>
<img src=./GIF/EN/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=./GIF/HUKIDASI.gif>
<form action="BONUS/bonus.mib" BDOWNLOAD method=post>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td width=432 height=131 valign=top>
<img src="" width=10 height=10><BR>
All Bonus Items have been released, meow!<BR>Press the <img src=./GIF/B_REC.gif width=16 height=16> button for more details.<BR><BR><BR><BR><BR><BR>
			</td>
		</tr>
		<tr>
			<td height=46 align=center>
				<img ANIME=10 src=./GIF/EN/BDL.gif width=210 height=46 alt="[O] DOWNLOAD"><BR>
				<input type=image src="" name=submit width=0 height=0>
			</td>
		</tr>
		<tr>
			<td align=right height=20>
			</td>
		</tr>
		</table>
	</td>
</tr>
</form>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<a name=002></a>
<img src=./GIF/EN/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=./GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
				<tr>
					<td align=center>
						<B>１/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Items yet to be downloaded are in yellow, meow!<BR></font>
-Wandering Felyne Chef-<BR>It seems a colored Felyne has wandered into<BR>the village, nya.<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=00>・Red Tiger</a><BR>
<a href=#003 qname=01>・Orange</a><BR>
<a href=#003 qname=02>・Jet Black</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=./PNG/bonus03.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<a name=003></a>
<img src=./GIF/EN/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=./GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
				<tr>
					<td align=center>
						<B>２/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Items yet to be downloaded are in yellow, meow!<BR></font>
-Felyne Comrade Armor-<BR>New sets of Felyne Comrade Armor have been<BR>added, nya!<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=25>・Felyne Samurai</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=./PNG/bonus19.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<a name=004></a>
<img src=./GIF/EN/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=./GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
				<tr>
					<td align=center>
						<B>３/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Items yet to be downloaded are in yellow, meow!<BR></font>
-Comrade Skills-<BR>New learnable Comrade Skills have been<BR>added, nya!<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=26>・Element Atk Dragon</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=./PNG/bonus15.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<a name=005></a>
<img src=./GIF/EN/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=./GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
				<tr>
					<td align=center>
						<B>４/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Items yet to be downloaded are in yellow, meow!<BR></font>
-Titles-<BR>New Titles for your Guild Card have been<BR>added, nya!<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=03>・Kokoto</a><BR>
<a href=#003 qname=04>・Jumbo</a><BR>
<a href=#003 qname=05>・Minegarde</a><BR>
<a href=#003 qname=06>・Dondruma</a><BR>
			</td>
			<td width=232 height=90 valign=top>
<a href=#003 qname=20>・Bookworm</a><BR>
<a href=#003 qname=21>・Imper.Scholar</a><BR>
<a href=#003 qname=23>・E.Dragon King</a><BR>
<a href=#003 qname=22>・Schrade</a><BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<a name=006></a>
<img src=./GIF/EN/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=./GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
				<tr>
					<td align=center>
						<B>５/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Items yet to be downloaded are in yellow, meow!<BR></font>
-Titles-<BR>New Titles for your Guild Card have been<BR>added, nya!<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=17>・Bee's Knees 　　　　　</a><BR>
<a href=#003 qname=15>・Electric　　　　　　　</a><BR>
<a href=#003 qname=16>・Reaver</a><BR>
<a href=#003 qname=14>・Famous</a><BR>
			</td>
			<td width=232 height=90 valign=top>
<a href=#003 qname=18>・Hunter's Soul</a><BR>
<a href=#003 qname=19>・Diva</a><BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<a name=007></a>
<img src=./GIF/EN/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=./GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
				<tr>
					<td align=center>
						<B>６/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Items yet to be downloaded are in yellow, meow!<BR></font>
-Piggie Fashions-<BR>New clothes for Piggie have been added, nya!<BR><BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=07>・Angel Leotard</a><BR>
<a href=#003 qname=08>・Sleepy Pig White</a><BR>
<a href=#003 qname=13>・Mafumofu Jumpsuit</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=./PNG/bonus14.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<a name=008></a>
<img src=./GIF/EN/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=./GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
				<tr>
					<td align=center>
						<B>７/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Items yet to be downloaded are in yellow, meow!<BR></font>
-Pokke Points-<BR>You can gain 3000 Pokke Points, nya.<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=24>・3000 Pokke Points</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=./PNG/bonus11.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<a name=009></a>
<img src=./GIF/EN/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=./GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
				<tr>
					<td align=center>
						<B>８/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Items yet to be downloaded are in yellow, meow!<BR></font>
-Farm Equipment-<BR>You can add Trenya's Boat to Pokke Farm, nya.<BR><BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=11>・Trenya's Boat</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=./PNG/bonus12.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<a name=010></a>
<img src=./GIF/EN/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=./GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
				<tr>
					<td align=center>
						<B>９/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Items yet to be downloaded are in yellow, meow!<BR></font>
-Peddling Granny Items-<BR>The Peddling Granny has gotten some items<BR>that are even better than usual, nya!<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=12>・Special Items</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=./PNG/bonus13.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
</body>
</html>
