<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=0",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_CMENU.PHP?lang=0&pg_no=0",
		"RB_LINK=DL_CMENU.PHP?lang=0&pg_no=0",
		"MOVE_CHAR=./GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=./GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=./GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=./GIF/EN/LOGO15.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61005.mib" DOWNLOAD CSUM=25603 FSIZE=3816 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m61005>Challenge Quest 5</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m61012>Monster Hunter Fiesta 2</a><BR>
				<a href=#003 qname=m61004>Challenge Quest 4</a><BR>
				<a href=#004 qname=m61003>Challenge Quest 3</a><BR>
				<a href=#005 qname=m61002>Challenge Quest 2</a><BR>
				<a href=#006 qname=m61011>Monster Hunter Fiesta 1</a><BR>
				<a href=#007 qname=m61001>Challenge Quest 1</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Challenge Quest 5
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>4800z<br>
				<font color=orangered>&nbsp;Contract:</font>0z<br>
				<font color=orangered>&nbsp;Time　　:</font>20 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Great Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;No<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=./GIF/EN/LOGO15.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_RED2.gif></td>
					<td width=219 height=18 background=./GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Challenge Quest 5
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Slay 2 Bulldromes<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★<BR>
					<font color=orangered>Client：</font>Instructor<BR>
					Running on an empty tank is<BR>the worst thing a hunter can<BR>do. That is to say, to<BR>master eating is to master<BR>the hunt! I'm going to turn<BR>you into the best cook ever!<BR>Or at least the best BBQer!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=./GIF/EN/LOGO15.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61012.mib" DOWNLOAD CSUM=45650 FSIZE=3420 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61005>Challenge Quest 5</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m61012>Monster Hunter Fiesta 2</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m61004>Challenge Quest 4</a><BR>
				<a href=#004 qname=m61003>Challenge Quest 3</a><BR>
				<a href=#005 qname=m61002>Challenge Quest 2</a><BR>
				<a href=#006 qname=m61011>Monster Hunter Fiesta 1</a><BR>
				<a href=#007 qname=m61001>Challenge Quest 1</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Monster Hunter Fiesta 2
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>3000z<br>
				<font color=orangered>&nbsp;Contract:</font>0z<br>
				<font color=orangered>&nbsp;Time　　:</font>15 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Great Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;No<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=./GIF/EN/LOGO15.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_RED2.gif></td>
					<td width=219 height=18 background=./GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Monster Hunter Fiesta 2
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Slay the Tigrex<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>Client：</font>Hearty Promoter<BR>
					It's festival time! Your<BR>opponent is the mighty<BR>Tigrex! As you know, its<BR>strength is suffocating,<BR>but in order to advance,<BR>you must break on through<BR>to the other side!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=./GIF/EN/LOGO15.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61004.mib" DOWNLOAD CSUM=12064 FSIZE=7340 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61005>Challenge Quest 5</a><BR>
				<a href=#002 qname=m61012>Monster Hunter Fiesta 2</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m61004>Challenge Quest 4</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m61003>Challenge Quest 3</a><BR>
				<a href=#005 qname=m61002>Challenge Quest 2</a><BR>
				<a href=#006 qname=m61011>Monster Hunter Fiesta 1</a><BR>
				<a href=#007 qname=m61001>Challenge Quest 1</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Challenge Quest 4
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>21000z<br>
				<font color=orangered>&nbsp;Contract:</font>0z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Old Jungle<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=./GIF/EN/LOGO15.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_RED2.gif></td>
					<td width=219 height=18 background=./GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Challenge Quest 4
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Slay all of the Large<BR>Monsters<BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Client：</font>Instructor<BR>
					Become one with the monsters<BR>by knowing how they think;<BR>that's the best way to beat<BR>them! That's what this<BR>training is for. Use this<BR>equipment and get inside the<BR>heads of those beasts!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=./GIF/EN/LOGO15.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61003.mib" DOWNLOAD CSUM=6176 FSIZE=3140 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61005>Challenge Quest 5</a><BR>
				<a href=#002 qname=m61012>Monster Hunter Fiesta 2</a><BR>
				<a href=#003 qname=m61004>Challenge Quest 4</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m61003>Challenge Quest 3</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m61002>Challenge Quest 2</a><BR>
				<a href=#006 qname=m61011>Monster Hunter Fiesta 1</a><BR>
				<a href=#007 qname=m61001>Challenge Quest 1</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Challenge Quest 3
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>60000z<br>
				<font color=orangered>&nbsp;Contract:</font>0z<br>
				<font color=orangered>&nbsp;Time　　:</font>40 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Moat Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=./GIF/EN/LOGO15.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_RED2.gif></td>
					<td width=219 height=18 background=./GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Challenge Quest 3
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Slay the Plesioth<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>Client：</font>Instructor<BR>
					The battlefield this time<BR>will be the Moat Arena. The<BR>prize money is pretty good,<BR>so no harm in trying. Huh?<BR>Where's the fine print? Aww,<BR>you'll do fine! You'll win!<BR>...Maybe. Ha ha.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=./GIF/EN/LOGO15.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61002.mib" DOWNLOAD CSUM=386 FSIZE=3600 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61005>Challenge Quest 5</a><BR>
				<a href=#002 qname=m61012>Monster Hunter Fiesta 2</a><BR>
				<a href=#003 qname=m61004>Challenge Quest 4</a><BR>
				<a href=#004 qname=m61003>Challenge Quest 3</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m61002>Challenge Quest 2</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m61011>Monster Hunter Fiesta 1</a><BR>
				<a href=#007 qname=m61001>Challenge Quest 1</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Challenge Quest 2
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>7500z<br>
				<font color=orangered>&nbsp;Contract:</font>0z<br>
				<font color=orangered>&nbsp;Time　　:</font>20 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Great Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 4 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=./GIF/EN/LOGO15.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_RED2.gif></td>
					<td width=219 height=18 background=./GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Challenge Quest 2
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Slay 2 King Shakalakas<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★<BR>
					<font color=orangered>Client：</font>Instructor<BR>
					Oho! A challenge from the<BR>Shakalaka! Now normally, I'd<BR>go myself, but I just<BR>remembered I have something<BR>very important to take care<BR>of! Go stand in for me and<BR>bring back that trophy!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=./GIF/EN/LOGO15.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61011.mib" DOWNLOAD CSUM=53259 FSIZE=4552 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61005>Challenge Quest 5</a><BR>
				<a href=#002 qname=m61012>Monster Hunter Fiesta 2</a><BR>
				<a href=#003 qname=m61004>Challenge Quest 4</a><BR>
				<a href=#004 qname=m61003>Challenge Quest 3</a><BR>
				<a href=#005 qname=m61002>Challenge Quest 2</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m61011>Monster Hunter Fiesta 1</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m61001>Challenge Quest 1</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Monster Hunter Fiesta 1
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>2400z<br>
				<font color=orangered>&nbsp;Contract:</font>0z<br>
				<font color=orangered>&nbsp;Time　　:</font>15 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Great Forest (Day)<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;No<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=./GIF/EN/LOGO15.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_RED2.gif></td>
					<td width=219 height=18 background=./GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Monster Hunter Fiesta 1
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Slay the Nargacuga<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>Client：</font>Youth Promoter<BR>
					Welcome to the competition!<BR>In this challenge, we are<BR>asking participants to slay<BR>a Nargacuga of the Great<BR>Forest. Trust yourself and<BR>show us the strength that<BR>lies within!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=./GIF/EN/LOGO15.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61001.mib" DOWNLOAD CSUM=50690 FSIZE=7104 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61005>Challenge Quest 5</a><BR>
				<a href=#002 qname=m61012>Monster Hunter Fiesta 2</a><BR>
				<a href=#003 qname=m61004>Challenge Quest 4</a><BR>
				<a href=#004 qname=m61003>Challenge Quest 3</a><BR>
				<a href=#005 qname=m61002>Challenge Quest 2</a><BR>
				<a href=#006 qname=m61011>Monster Hunter Fiesta 1</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m61001>Challenge Quest 1</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Challenge Quest 1
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>6000z<br>
				<font color=orangered>&nbsp;Contract:</font>0z<br>
				<font color=orangered>&nbsp;Time　　:</font>40 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Jungle(Night)<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;No<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=./GIF/EN/LOGO15.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_RED2.gif></td>
					<td width=219 height=18 background=./GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Challenge Quest 1
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Slay the Yian Garuga<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★<BR>
					<font color=orangered>Client：</font>Instructor<BR>
					A Yian Garuga has been<BR>spotted in the jungle, and<BR>as your esteemed instructor,<BR>I deem this to be a great<BR>chance to do some training.<BR>I'll lend ya some equipment,<BR>so get out there already!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
</body>
</html>
