<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=0",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=0&pg_no=2",
		"RB_LINK=DL_MENU.PHP?lang=0&pg_no=0",
		"MOVE_CHAR=./GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=./GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=./GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60027.mib" DOWNLOAD CSUM=54524 FSIZE=7664 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>４/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60027>Jungle Hunt!</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m60037>Tiger of the Desert</a><BR>
				<a href=#003 qname=m60028>Aquatic Festival</a><BR>
				<a href=#004 qname=m60033>2 Colors of Meow - Sm. Arena</a><BR>
				<a href=#005 qname=m60024>Triumvirate of the Sands</a><BR>
				<a href=#006 qname=m60026>Baby Boom! Flocking to Sleep</a><BR>
				<a href=#007 qname=m60013>Expunge the Funk!</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Jungle Hunt!
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>14100z<br>
				<font color=orangered>&nbsp;Contract:</font>1200z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Jungle(Day)<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 4 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_PNK2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Jungle Hunt!
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt all of the Large<BR>Monsters<BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★★<BR>
					<font color=orangered>Client：</font>Overbearing Noble<BR>
					For our commoners' sake, we<BR>took it upon ourselves to be<BR>brave and investigate the<BR>forest. But even Mother Dear<BR>did not warn us that such a<BR>dangerous place existed!<BR>I demand you keep us safe!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60037.mib" DOWNLOAD CSUM=39899 FSIZE=7532 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>４/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60027>Jungle Hunt!</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60037>Tiger of the Desert</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m60028>Aquatic Festival</a><BR>
				<a href=#004 qname=m60033>2 Colors of Meow - Sm. Arena</a><BR>
				<a href=#005 qname=m60024>Triumvirate of the Sands</a><BR>
				<a href=#006 qname=m60026>Baby Boom! Flocking to Sleep</a><BR>
				<a href=#007 qname=m60013>Expunge the Funk!</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Tiger of the Desert
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>14100z<br>
				<font color=orangered>&nbsp;Contract:</font>1200z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Old Desert<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_WHT2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Tiger of the Desert
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt the Tigrex<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Client：</font>Very Curious Maiden<BR>
					Wow! Sounds like there's a<BR>striped monster somewhere on<BR>the other side! Let's hurry<BR>and try to catch a glimpse!<BR>If it's a violent beast, you<BR>will be there for me, right?<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60028.mib" DOWNLOAD CSUM=29746 FSIZE=3336 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>４/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60027>Jungle Hunt!</a><BR>
				<a href=#002 qname=m60037>Tiger of the Desert</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60028>Aquatic Festival</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m60033>2 Colors of Meow - Sm. Arena</a><BR>
				<a href=#005 qname=m60024>Triumvirate of the Sands</a><BR>
				<a href=#006 qname=m60026>Baby Boom! Flocking to Sleep</a><BR>
				<a href=#007 qname=m60013>Expunge the Funk!</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Aquatic Festival
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>24000z<br>
				<font color=orangered>&nbsp;Contract:</font>2000z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Moat Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 4 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_PNK2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Aquatic Festival
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt all of the Large<BR>Monsters<BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★★★<BR>
					<font color=orangered>Client：</font>Suave Show Producer<BR>
					I want this to be one fun<BR>festival, and you know what<BR>I think would make it fun?<BR>Letting the people see some<BR>top-notch hunters in action!<BR>I've got 4 monsters ready,<BR>so let's give them a show!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60033.mib" DOWNLOAD CSUM=18767 FSIZE=2700 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>４/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60027>Jungle Hunt!</a><BR>
				<a href=#002 qname=m60037>Tiger of the Desert</a><BR>
				<a href=#003 qname=m60028>Aquatic Festival</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60033>2 Colors of Meow - Sm. Arena</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m60024>Triumvirate of the Sands</a><BR>
				<a href=#006 qname=m60026>Baby Boom! Flocking to Sleep</a><BR>
				<a href=#007 qname=m60013>Expunge the Funk!</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				2 Colors of Meow - Sm. Arena
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>4500z<br>
				<font color=orangered>&nbsp;Contract:</font>400z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 4 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_RED2.gif></td>
					<td width=219 height=18 background=./GIF/T_RED.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				2 Colors of Meow - Sm. Arena
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Defeat 20 Felynes<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★<BR>
					<font color=orangered>Client：</font>Ying-Yang Creatures<BR>
					To the one million Felyne<BR>fans out there: <BR>At long last we bring you<BR>our special challenge!<BR>Skillfully clear this and<BR>your reward will be a<BR>very special ticket!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60024.mib" DOWNLOAD CSUM=48755 FSIZE=7604 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>４/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60027>Jungle Hunt!</a><BR>
				<a href=#002 qname=m60037>Tiger of the Desert</a><BR>
				<a href=#003 qname=m60028>Aquatic Festival</a><BR>
				<a href=#004 qname=m60033>2 Colors of Meow - Sm. Arena</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60024>Triumvirate of the Sands</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m60026>Baby Boom! Flocking to Sleep</a><BR>
				<a href=#007 qname=m60013>Expunge the Funk!</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Triumvirate of the Sands
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>12300z<br>
				<font color=orangered>&nbsp;Contract:</font>1050z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Desert(Day)<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;No<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_PNK2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Triumvirate of the Sands
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt all of the Large<BR>Monsters<BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Client：</font>Northern Meds Seller<BR>
					What's up with this desert!?<BR>That's the 3rd time today!!<BR>I had to leave all my goods<BR>behind. All those large<BR>Potions... I wonder if<BR>they're sitting in some<BR>monster's stomach out there?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60026.mib" DOWNLOAD CSUM=58434 FSIZE=7128 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>４/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60027>Jungle Hunt!</a><BR>
				<a href=#002 qname=m60037>Tiger of the Desert</a><BR>
				<a href=#003 qname=m60028>Aquatic Festival</a><BR>
				<a href=#004 qname=m60033>2 Colors of Meow - Sm. Arena</a><BR>
				<a href=#005 qname=m60024>Triumvirate of the Sands</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60026>Baby Boom! Flocking to Sleep</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m60013>Expunge the Funk!</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Baby Boom! Flocking to Sleep
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>9000z<br>
				<font color=orangered>&nbsp;Contract:</font>750z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Great Forest(Day)<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 4 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_WHT2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Baby Boom! Flocking to Sleep
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Survive until Time Over or<BR>Deliver the Paw Pass Ticket<BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero, or Time Over<BR>before hunting 2 down.<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★★<BR>
					<font color=orangered>Client：</font>Determined Creature<BR>
					I thought I was moving into<BR>a peaceful neighborhood when<BR>I bought the place, but<BR>there are Hypnocatrices all<BR>over, meow! Please help me<BR>protect my house by hunting<BR>down at least two of them!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60013.mib" DOWNLOAD CSUM=10403 FSIZE=6164 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>４/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60027>Jungle Hunt!</a><BR>
				<a href=#002 qname=m60037>Tiger of the Desert</a><BR>
				<a href=#003 qname=m60028>Aquatic Festival</a><BR>
				<a href=#004 qname=m60033>2 Colors of Meow - Sm. Arena</a><BR>
				<a href=#005 qname=m60024>Triumvirate of the Sands</a><BR>
				<a href=#006 qname=m60026>Baby Boom! Flocking to Sleep</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60013>Expunge the Funk!</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Expunge the Funk!
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>18000z<br>
				<font color=orangered>&nbsp;Contract:</font>1500z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Swamp(Day)<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_WHT2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Expunge the Funk!
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt the Emerald Congalala<BR>and the Congalala<BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★<BR>
					<font color=orangered>Client：</font>Lakeside Housewife<BR>
					Please, hear me out! Lately,<BR>my village's water has<BR>started smelling like<BR>sewage! Surely there must<BR>be something wrong at the<BR>source... Please find the<BR>problem and exterminate it!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
</body>
</html>
