<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=0",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=0&pg_no=1",
		"RB_LINK=DL_MENU.PHP?lang=0&pg_no=3",
		"MOVE_CHAR=./GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=./GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=./GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60012.mib" DOWNLOAD CSUM=17793 FSIZE=6272 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60012>Beasts of the Dunes</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m60025>Laurel, Please.</a><BR>
				<a href=#003 qname=m60029>The Big Daddy</a><BR>
				<a href=#004 qname=m60017>Arena of Blood and Tears</a><BR>
				<a href=#005 qname=m60023>Its name is 'Mega Kut-Ku'!?</a><BR>
				<a href=#006 qname=m60020>Porky Panic Party!</a><BR>
				<a href=#007 qname=m60030>Black Wings of Fate</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Beasts of the Dunes
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>24000z<br>
				<font color=orangered>&nbsp;Contract:</font>2000z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Desert(Day)<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_WHT2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Beasts of the Dunes
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt 2 Copper Blangongas<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>Client：</font>Wounded Creatures<BR>
					We made a promise to our<BR>master, meow! We've just got<BR>to get this letter to its<BR>destination! We were so<BR>close, but there were these<BR>monsters hanging about...<BR>Please... Help us... Meow...<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60025.mib" DOWNLOAD CSUM=4576 FSIZE=3136 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Beasts of the Dunes</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60025>Laurel, Please.</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m60029>The Big Daddy</a><BR>
				<a href=#004 qname=m60017>Arena of Blood and Tears</a><BR>
				<a href=#005 qname=m60023>Its name is 'Mega Kut-Ku'!?</a><BR>
				<a href=#006 qname=m60020>Porky Panic Party!</a><BR>
				<a href=#007 qname=m60030>Black Wings of Fate</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Laurel, Please.
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>12000z<br>
				<font color=orangered>&nbsp;Contract:</font>1000z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Great Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;No<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_PNK2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Laurel, Please.
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt all of the Large<BR>Monsters<BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Client：</font>Young Arena Manager<BR>
					Wanna show off? Then the<BR>arena is perfect for you!<BR>Today on the menu, we've<BR>got a Congalala, a Rathian,<BR>a Shogun Ceanataur, and a<BR>whole lot more! Use those<BR>few Potions you find well!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60029.mib" DOWNLOAD CSUM=14869 FSIZE=4804 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Beasts of the Dunes</a><BR>
				<a href=#002 qname=m60025>Laurel, Please.</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60029>The Big Daddy</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m60017>Arena of Blood and Tears</a><BR>
				<a href=#005 qname=m60023>Its name is 'Mega Kut-Ku'!?</a><BR>
				<a href=#006 qname=m60020>Porky Panic Party!</a><BR>
				<a href=#007 qname=m60030>Black Wings of Fate</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				The Big Daddy
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>36000z<br>
				<font color=orangered>&nbsp;Contract:</font>3000z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Tower<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 6 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_PPL2.gif></td>
					<td width=219 height=18 background=./GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				The Big Daddy
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Slay the Fatalis<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★★★<BR>
					<font color=orangered>Client：</font>Pure White Felyne<BR>
					Master! Do you plan to check<BR>out the old Tower? You<BR>can't afford to miss it,<BR>meow... And if you do go,<BR>you'll see something pretty<BR>incredible... Though I have<BR>a bad feeling about going...<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60017.mib" DOWNLOAD CSUM=37796 FSIZE=3360 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Beasts of the Dunes</a><BR>
				<a href=#002 qname=m60025>Laurel, Please.</a><BR>
				<a href=#003 qname=m60029>The Big Daddy</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60017>Arena of Blood and Tears</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m60023>Its name is 'Mega Kut-Ku'!?</a><BR>
				<a href=#006 qname=m60020>Porky Panic Party!</a><BR>
				<a href=#007 qname=m60030>Black Wings of Fate</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Arena of Blood and Tears
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>39000z<br>
				<font color=orangered>&nbsp;Contract:</font>3250z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Moat Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_PNK2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Arena of Blood and Tears
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt all of the Large<BR>Monsters<BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>Client：</font>Serious Lady Knight<BR>
					It is not my usual practice,<BR>however, there is someone<BR>who wishes to test your<BR>strength. Therefore, can you<BR>show me your true power? You<BR>may expect to be compensated<BR>for your trouble.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60023.mib" DOWNLOAD CSUM=54531 FSIZE=6144 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Beasts of the Dunes</a><BR>
				<a href=#002 qname=m60025>Laurel, Please.</a><BR>
				<a href=#003 qname=m60029>The Big Daddy</a><BR>
				<a href=#004 qname=m60017>Arena of Blood and Tears</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60023>Its name is 'Mega Kut-Ku'!?</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m60020>Porky Panic Party!</a><BR>
				<a href=#007 qname=m60030>Black Wings of Fate</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Its name is 'Mega Kut-Ku'!?
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>6000z<br>
				<font color=orangered>&nbsp;Contract:</font>500z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Forest & Hills(Day)<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;Initiating & joining quest<BR>　reqs. No equipped armor.<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_WHT2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Its name is 'Mega Kut-Ku'!?
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt 2 Yian Kut-Ku (?)<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★<BR>
					<font color=orangered>Client：</font>Food Connoisseur<BR>
					I came here in search of a<BR>meal yet to be tasted by<BR>mortal buds. I hear there is<BR>a legendary creature that<BR>lives on that hill nearby.<BR>Help me fulfill my life-long<BR>ambition! Hurry to the hunt!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60020.mib" DOWNLOAD CSUM=25038 FSIZE=2796 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Beasts of the Dunes</a><BR>
				<a href=#002 qname=m60025>Laurel, Please.</a><BR>
				<a href=#003 qname=m60029>The Big Daddy</a><BR>
				<a href=#004 qname=m60017>Arena of Blood and Tears</a><BR>
				<a href=#005 qname=m60023>Its name is 'Mega Kut-Ku'!?</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60020>Porky Panic Party!</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m60030>Black Wings of Fate</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Porky Panic Party!
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>8400z<br>
				<font color=orangered>&nbsp;Contract:</font>700z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_RED2.gif></td>
					<td width=219 height=18 background=./GIF/T_RED.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Porky Panic Party!
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Slay 30 Bullfangos<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★<BR>
					<font color=orangered>Client：</font>Showy Suspect Dame<BR>
					I require some entertainment<BR>at my party, for which I am<BR>recruiting hunters. Hee hee<BR>hee... It's a veritable<BR>buffet of free-roaming<BR>porkers, if you will. Can<BR>you outrun them, I wonder...<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60030.mib" DOWNLOAD CSUM=64928 FSIZE=2524 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Beasts of the Dunes</a><BR>
				<a href=#002 qname=m60025>Laurel, Please.</a><BR>
				<a href=#003 qname=m60029>The Big Daddy</a><BR>
				<a href=#004 qname=m60017>Arena of Blood and Tears</a><BR>
				<a href=#005 qname=m60023>Its name is 'Mega Kut-Ku'!?</a><BR>
				<a href=#006 qname=m60020>Porky Panic Party!</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60030>Black Wings of Fate</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Black Wings of Fate
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>54000z<br>
				<font color=orangered>&nbsp;Contract:</font>4500z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Castle Schrade<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 9 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_PPL2.gif></td>
					<td width=219 height=18 background=./GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Black Wings of Fate
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Slay the Fatalis<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Client：</font>Sly Guild Master<BR>
					We received word that a<BR>black-winged dragon was<BR>spotted at the ruins of an<BR>old castle. Our expedition<BR>team has disappeared, and I<BR>fear the worst. Is there no<BR>one who will go take a look?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
</body>
</html>
