<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=0",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=0&pg_no=3",
		"RB_LINK=DL_MENU.PHP?lang=0&pg_no=1",
		"MOVE_CHAR=./GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=./GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=./GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60038.mib" DOWNLOAD CSUM=60310 FSIZE=2520 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60038>Twin Terrors</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m60034>High Altitude King</a><BR>
				<a href=#003 qname=m60019>Hunting God's Free-For-All</a><BR>
				<a href=#004 qname=m60010>Mountain in the Sky</a><BR>
				<a href=#005 qname=m60016>Demon's Teardrop Mountain</a><BR>
				<a href=#006 qname=m60018>Four Kings of Fire</a><BR>
				<a href=#007 qname=m60015>Two Cliffs! Dark Hot Winds</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Twin Terrors
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>42000z<br>
				<font color=orangered>&nbsp;Contract:</font>3500z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Great Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_WHT2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Twin Terrors
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt 2 Rajang<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Client：</font>DeathlyPaleMercenary<BR>
					I can't believe what I saw!<BR>It was terrible! There they<BR>were, 2 Rajang just sitting<BR>there in the arena...<BR>Listen, if you value your<BR>life at all, absolutely do<BR>not go near there! Got it!?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60034.mib" DOWNLOAD CSUM=30781 FSIZE=2332 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60038>Twin Terrors</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60034>High Altitude King</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m60019>Hunting God's Free-For-All</a><BR>
				<a href=#004 qname=m60010>Mountain in the Sky</a><BR>
				<a href=#005 qname=m60016>Demon's Teardrop Mountain</a><BR>
				<a href=#006 qname=m60018>Four Kings of Fire</a><BR>
				<a href=#007 qname=m60015>Two Cliffs! Dark Hot Winds</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				High Altitude King
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>60000z<br>
				<font color=orangered>&nbsp;Contract:</font>5000z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Battleground<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 9 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_RED2.gif></td>
					<td width=219 height=18 background=./GIF/T_RED.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				High Altitude King
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Slay the Akantor<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Client：</font>Benevolent Monarch<BR>
					The profoundly powerful<BR>Akantor... <BR>We chased it this far,<BR>however, we've sustained<BR>heavy damage. Hunters of<BR>this land! I ask for your<BR>immediate help!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60019.mib" DOWNLOAD CSUM=8338 FSIZE=3596 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60038>Twin Terrors</a><BR>
				<a href=#002 qname=m60034>High Altitude King</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60019>Hunting God's Free-For-All</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m60010>Mountain in the Sky</a><BR>
				<a href=#005 qname=m60016>Demon's Teardrop Mountain</a><BR>
				<a href=#006 qname=m60018>Four Kings of Fire</a><BR>
				<a href=#007 qname=m60015>Two Cliffs! Dark Hot Winds</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Hunting God's Free-For-All
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>60000z<br>
				<font color=orangered>&nbsp;Contract:</font>5000z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Great Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 9 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_PNK2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Hunting God's Free-For-All
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt all of the Large<BR>Monsters<BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Client：</font>Red-Clad Knight<BR>
					O ye who would take up this<BR>test! Believe in thine own<BR>strength, and the strength<BR>of thy companions, for it is<BR>in the thick of danger that<BR>fortitude is tested. Keep<BR>hope and fight to the end!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60010.mib" DOWNLOAD CSUM=18506 FSIZE=4772 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60038>Twin Terrors</a><BR>
				<a href=#002 qname=m60034>High Altitude King</a><BR>
				<a href=#003 qname=m60019>Hunting God's Free-For-All</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60010>Mountain in the Sky</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m60016>Demon's Teardrop Mountain</a><BR>
				<a href=#006 qname=m60018>Four Kings of Fire</a><BR>
				<a href=#007 qname=m60015>Two Cliffs! Dark Hot Winds</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Mountain in the Sky
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>30000z<br>
				<font color=orangered>&nbsp;Contract:</font>2500z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Tower<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 9 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_RED2.gif></td>
					<td width=219 height=18 background=./GIF/T_RED.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Mountain in the Sky
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Slay the Yama Tsukami<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Client：</font>Long-Haired Old Lady<BR>
					One time, when I was a<BR>little girl, I saw a giant<BR>shadow in the sky. It was<BR>bigger than any wyvern I'd<BR>ever seen... Was it all just<BR>a dream? Would you look into<BR>this for me, please, deary?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60016.mib" DOWNLOAD CSUM=35192 FSIZE=5384 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60038>Twin Terrors</a><BR>
				<a href=#002 qname=m60034>High Altitude King</a><BR>
				<a href=#003 qname=m60019>Hunting God's Free-For-All</a><BR>
				<a href=#004 qname=m60010>Mountain in the Sky</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60016>Demon's Teardrop Mountain</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m60018>Four Kings of Fire</a><BR>
				<a href=#007 qname=m60015>Two Cliffs! Dark Hot Winds</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Demon's Teardrop Mountain
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>30000z<br>
				<font color=orangered>&nbsp;Contract:</font>2500z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Snowy Mountains(Day)<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_WHT2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Demon's Teardrop Mountain
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt 2 Rajang<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Client：</font>Young Nobleman<BR>
					Two Rajang stole my lovely,<BR>unwilling bride and escaped<BR>into the mountains. I don't<BR>care that she doesn't want<BR>me, but I can't live without<BR>her! Please, lend me your<BR>strength!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60018.mib" DOWNLOAD CSUM=21719 FSIZE=7952 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60038>Twin Terrors</a><BR>
				<a href=#002 qname=m60034>High Altitude King</a><BR>
				<a href=#003 qname=m60019>Hunting God's Free-For-All</a><BR>
				<a href=#004 qname=m60010>Mountain in the Sky</a><BR>
				<a href=#005 qname=m60016>Demon's Teardrop Mountain</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60018>Four Kings of Fire</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m60015>Two Cliffs! Dark Hot Winds</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Four Kings of Fire
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>42000z<br>
				<font color=orangered>&nbsp;Contract:</font>3500z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Volcano(Day)<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_PNK2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Four Kings of Fire
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt all of the Large<BR>Monsters<BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Client：</font>White-Clad Scientist<BR>
					We've confirmed that the<BR>Volcano zone is ripe feeding<BR>grounds for a large variety<BR>of monsters. If you please,<BR>go to that area and hunt<BR>down 4 species for us to use<BR>in our research, would you?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=./GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60015.mib" DOWNLOAD CSUM=17420 FSIZE=2700 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60038>Twin Terrors</a><BR>
				<a href=#002 qname=m60034>High Altitude King</a><BR>
				<a href=#003 qname=m60019>Hunting God's Free-For-All</a><BR>
				<a href=#004 qname=m60010>Mountain in the Sky</a><BR>
				<a href=#005 qname=m60016>Demon's Teardrop Mountain</a><BR>
				<a href=#006 qname=m60018>Four Kings of Fire</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60015>Two Cliffs! Dark Hot Winds</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=./GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=./GIF/EN/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Two Cliffs! Dark Hot Winds
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>36000z<br>
				<font color=orangered>&nbsp;Contract:</font>3000z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Great Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=./GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=./GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=./GIF/EN/T_WHT2.gif></td>
					<td width=219 height=18 background=./GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Two Cliffs! Dark Hot Winds
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt 2 Black Gravios<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Client：</font>Arena Manager<BR>
					Come one, come all, to the<BR>ultimate arena! I've got 2,<BR>yes, count 'em, 2 fearsome<BR>Black Gravios right here<BR>in this very arena! Think<BR>you've got what it takes to<BR>beat these wild beasts?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/EN/BUTTON4.gif></td></tr></table>
</body>
</html>
