<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO2.PHP",
		"RB_LINK=DB_INFO4.PHP",
		"MOVE_CHAR=./GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white background=./GIF/BG.gif bgcolor=#0DA5DE>
<!--480 x 272-->
<basefont size=2>
<B>
<a name=001></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td bgcolor=green>
				<B>０６／０１更新予告③<BR></B>
			<tr><td height=110 valign=top>
				<B>
					０６／０１更新予告②<BR>
					０６／０１更新予告①<BR>
					０５／２５更新予告④<BR>
					０５／２５更新予告③<BR>
					０５／２５更新予告②<BR>
					０５／２５更新予告①<BR>
					０５／１８更新予告②<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０６／０１更新予告③</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【モンハンフェスタ　０４】</font><BR>
を追加予定ニャ！<BR>
大会に向けて思いっきり<BR>
練習しておくのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０６／０１更新予告③</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【モンハンフェスタ　０４】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：神秘的な大会運営者<BR>
皆さん、これが最後です。<BR>
金色に輝く金獅子と対面し、<BR>
見事打ち倒して来て下さい。<BR>
ここまで勝ち残れたと言え、<BR>
油断は禁物です。ご武運を！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/c61017.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=002></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０６／０１更新予告③<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０６／０１更新予告②<BR></B>
			<tr><td>
				<B>
					０６／０１更新予告①<BR>
					０５／２５更新予告④<BR>
					０５／２５更新予告③<BR>
					０５／２５更新予告②<BR>
					０５／２５更新予告①<BR>
					０５／１８更新予告②<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０６／０１更新予告②</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【チャレンジクエスト　０８】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０６／０１更新予告②</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【チャレンジクエスト　０８】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：教官<BR>
我輩だ、教官だ。今回はティガ<BR>
レックス、しかも２頭連続で相<BR>
手をして貰う。怒り状態では<BR>
手がつけられない。あらゆる手<BR>
を使って隙を作るのだ！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/c61008.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=003></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０６／０１更新予告③<BR>
					０６／０１更新予告②<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０６／０１更新予告①<BR></B>
			<tr><td>
				<B>
					０５／２５更新予告④<BR>
					０５／２５更新予告③<BR>
					０５／２５更新予告②<BR>
					０５／２５更新予告①<BR>
					０５／１８更新予告②<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０６／０１更新予告①</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【ファミ通　奇面族の宴】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０６／０１更新予告①</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【ファミ通　奇面族の宴】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：ファミ通ＭＨＰ攻略班<BR>
ファミ通が秘密のパーティーを<BR>
開催します。参加者は鋼の意思<BR>
とヘコたれない根性を持参の上<BR>
闘技場までお越しください。<BR>
ご来訪をお待ちしております。<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60020.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=004></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０６／０１更新予告③<BR>
					０６／０１更新予告②<BR>
					０６／０１更新予告①<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０５／２５更新予告④<BR></B>
			<tr><td>
				<B>
					０５／２５更新予告③<BR>
					０５／２５更新予告②<BR>
					０５／２５更新予告①<BR>
					０５／１８更新予告②<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０５／２５更新予告④</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【モンハンフェスタ　０３】</font><BR>
を追加予定ニャ！<BR>
大会に向けて思いっきり<BR>
練習しておくのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０５／２５更新予告④</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【モンハンフェスタ　０３】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：豪腕の大会運営者<BR>
ここが正念場だ！恐怖の古龍<BR>
を相手にハンターが<BR>
どこまで立ち向かえるか…！？<BR>
お前らの実力を、ここで示せ！<BR>
そして勝ち上がって来い！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/c61016.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=005></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０６／０１更新予告③<BR>
					０６／０１更新予告②<BR>
					０６／０１更新予告①<BR>
					０５／２５更新予告④<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０５／２５更新予告③<BR></B>
			<tr><td>
				<B>
					０５／２５更新予告②<BR>
					０５／２５更新予告①<BR>
					０５／１８更新予告②<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０５／２５更新予告③</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【モンハンフェスタ　０２】</font><BR>
を追加予定ニャ！<BR>
大会に向けて思いっきり<BR>
練習しておくのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０５／２５更新予告③</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【モンハンフェスタ　０２】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：情熱の大会運営者<BR>
さあッ！お祭りよッ！<BR>
ハンターさん達には大闘技場で<BR>
轟竜とガチンコバトルしてもら<BR>
うわッ！誰よりも早くッ！<BR>
誰よりも華麗に戦うのよッ！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/c61015.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=006></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０６／０１更新予告③<BR>
					０６／０１更新予告②<BR>
					０６／０１更新予告①<BR>
					０５／２５更新予告④<BR>
					０５／２５更新予告③<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０５／２５更新予告②<BR></B>
			<tr><td>
				<B>
					０５／２５更新予告①<BR>
					０５／１８更新予告②<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０５／２５更新予告②</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【祖龍】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０５／２５更新予告②</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【祖龍】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：謎の赤衣の男<BR>
フフフ…刻は満ちた！さぁ、舞<BR>
踏会へ招待しよう。とびきりの<BR>
衣装を着て、とびきりの得物を<BR>
もっておいで。でなければ王の<BR>
相手はつとまらないのでね。<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60017.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=007></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０６／０１更新予告③<BR>
					０６／０１更新予告②<BR>
					０６／０１更新予告①<BR>
					０５／２５更新予告④<BR>
					０５／２５更新予告③<BR>
					０５／２５更新予告②<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０５／２５更新予告①<BR></B>
			<tr><td>
				<B>
					０５／１８更新予告②<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０５／２５更新予告①</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【「マ）王　片角のマオウ】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０５／２５更新予告①</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【「マ）王　片角のマオウ】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：ギレル<BR>
角竜の討伐…。戦ってみたが、<BR>
返り討ちにあって動けない。ヤ<BR>
ツを倒してある治療薬を作るた<BR>
めにも、勇気ある者はヤツを倒<BR>
すため名乗りを上げてくれ。<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60027.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=008></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０６／０１更新予告③<BR>
					０６／０１更新予告②<BR>
					０６／０１更新予告①<BR>
					０５／２５更新予告④<BR>
					０５／２５更新予告③<BR>
					０５／２５更新予告②<BR>
					０５／２５更新予告①<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０５／１８更新予告②<BR></B>
			<tr><td valign=top>
				<B>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０５／１８更新予告②</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【チャレンジクエスト　０７】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０５／１８更新予告②</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【チャレンジクエスト　０７】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：教官<BR>
我輩だ、教官だ。狩りには<BR>
効率の良い動き方というものが<BR>
ある。どのルートで回れば<BR>
より早いか、貴様にはその<BR>
最速の道が見えるか？<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/c61007.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
