<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO3.PHP",
		"RB_LINK=DB_INFO5.PHP",
		"MOVE_CHAR=./GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white background=./GIF/BG.gif bgcolor=#0DA5DE>
<!--480 x 272-->
<basefont size=2>
<B>
<a name=001></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td bgcolor=green>
				<B>０５／１８更新予告①<BR></B>
			<tr><td height=110 valign=top>
				<B>
					０５／１１更新予告<BR>
					０５／０４更新予告③<BR>
					０５／０４更新予告②<BR>
					０５／０４更新予告①<BR>
					０４／２７更新予告②<BR>
					０４／２７更新予告①<BR>
					０４／２０更新予告②<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０５／１８更新予告①</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【火山地帯に潜む罠】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０５／１８更新予告①</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【火山地帯に潜む罠】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：一攫千金を狙う男<BR>
高価な鉱石を狙って火山に来た<BR>
んだがイヤな気配がずっとしや<BR>
がる。…誰かに見られている？<BR>
…そんな気配を複数感じたぜ。<BR>
気配の正体をつきとめてくれ！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60006.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=002></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０５／１８更新予告①<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０５／１１更新予告<BR></B>
			<tr><td>
				<B>
					０５／０４更新予告③<BR>
					０５／０４更新予告②<BR>
					０５／０４更新予告①<BR>
					０４／２７更新予告②<BR>
					０４／２７更新予告①<BR>
					０４／２０更新予告②<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０５／１１更新予告</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【白黒つけるぜ！闘技場！】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０５／１１更新予告</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【白黒つけるぜ！闘技場！】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：獣人族の勇者<BR>
ハンター共への挑戦状だニャ！<BR>
いつもやられている仲間の分も<BR>
含めて、闘技場で恐ろしい目に<BR>
あわせてやるから、度胸のある<BR>
ヤツはかかってくるのニャー！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60003.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=003></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０５／１８更新予告①<BR>
					０５／１１更新予告<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０５／０４更新予告③<BR></B>
			<tr><td>
				<B>
					０５／０４更新予告②<BR>
					０５／０４更新予告①<BR>
					０４／２７更新予告②<BR>
					０４／２７更新予告①<BR>
					０４／２０更新予告②<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０５／０４更新予告③</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回は特典をさらに３つ<BR>
追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０５／０４更新予告③</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=left colspan=2>
				<B><font size=2>
				以下の特典が追加されるのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
・プーギーの服<BR>
　【眠りを誘う白】<BR>
・さすらいの料理ネコ<BR>
　【漆黒】<BR>
・称号<BR>
　【ミナガルデ】<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/b00002.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=004></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０５／１８更新予告①<BR>
					０５／１１更新予告<BR>
					０５／０４更新予告③<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０５／０４更新予告②<BR></B>
			<tr><td>
				<B>
					０５／０４更新予告①<BR>
					０４／２７更新予告②<BR>
					０４／２７更新予告①<BR>
					０４／２０更新予告②<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０５／０４更新予告②</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【チャレンジクエスト　０６】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０５／０４更新予告②</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【チャレンジクエスト　０６】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：教官<BR>
我輩だ、教官だ。<BR>
ドスファンゴへの挑戦だな！<BR>
ドスファンゴと侮るな。お前は<BR>
この演習で世界に更なる高みが<BR>
ある事を知るだろう！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/c61006.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=005></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０５／１８更新予告①<BR>
					０５／１１更新予告<BR>
					０５／０４更新予告③<BR>
					０５／０４更新予告②<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０５／０４更新予告①<BR></B>
			<tr><td>
				<B>
					０４／２７更新予告②<BR>
					０４／２７更新予告①<BR>
					０４／２０更新予告②<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０５／０４更新予告①</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【光と毒の狂騒曲】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０５／０４更新予告①</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【光と毒の狂騒曲】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：闘技場の運営者<BR>
ハンターが己の腕前を披露する<BR>
闘技場！今回の相手は閃光を発<BR>
する毒怪鳥です！しかも１匹で<BR>
はありません！さぁ、存分にそ<BR>
の力を我々に見せてください。<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60021.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=006></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０５／１８更新予告①<BR>
					０５／１１更新予告<BR>
					０５／０４更新予告③<BR>
					０５／０４更新予告②<BR>
					０５／０４更新予告①<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０４／２７更新予告②<BR></B>
			<tr><td>
				<B>
					０４／２７更新予告①<BR>
					０４／２０更新予告②<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０４／２７更新予告②</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【紅の災厄】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０４／２７更新予告②</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【紅の災厄】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：ギルドの大老<BR>
ミラボレアス…その者の怒りは<BR>
大地を震わし、天をも焦がす…<BR>
最早、後はない。勇なる者よ！<BR>
この声が届くのならば、怒りを<BR>
鎮め、紅の闇を祓ってくれ！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60016.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=007></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０５／１８更新予告①<BR>
					０５／１１更新予告<BR>
					０５／０４更新予告③<BR>
					０５／０４更新予告②<BR>
					０５／０４更新予告①<BR>
					０４／２７更新予告②<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０４／２７更新予告①<BR></B>
			<tr><td>
				<B>
					０４／２０更新予告②<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０４／２７更新予告①</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【ＪＵＭＰ　炎帝の凱旋】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０４／２７更新予告①</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【ＪＵＭＰ　炎帝の凱旋】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：隻眼黒髭の男<BR>
街は今、炎王龍によって蹂躙さ<BR>
れようとしている。そこでだ…<BR>
どうだ、俺にお前が街を救うと<BR>
ころを見せてはくれねぇか？<BR>
勿論、報酬は期待していいぜ。<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60028.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=008></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０５／１８更新予告①<BR>
					０５／１１更新予告<BR>
					０５／０４更新予告③<BR>
					０５／０４更新予告②<BR>
					０５／０４更新予告①<BR>
					０４／２７更新予告②<BR>
					０４／２７更新予告①<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０４／２０更新予告②<BR></B>
			<tr><td valign=top>
				<B>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０４／２０更新予告②</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【チャレンジクエスト　０５】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０４／２０更新予告②</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【チャレンジクエスト　０５】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：教官<BR>
これは我輩からの試練だ！<BR>
相手はショウグンギザミ２匹、<BR>
どちらか片方を倒した時点で<BR>
クエストクリアになるぞ！<BR>
お前の腕を見せてみるのだ！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/c61005.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
