<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO6.PHP",
		"RB_LINK=DB_INFO2.PHP",
		"MOVE_CHAR=./GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white background=./GIF/BG.gif bgcolor=#0DA5DE>
<!--480 x 272-->
<basefont size=2>
<B>
<a name=001></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td bgcolor=green>
				<B>２ｎｄＧ発売日決定！<BR></B>
			<tr><td height=110 valign=top>
				<B>
					０９／２１更新予告<BR>
					０８／０３更新予告<BR>
					０７／２７更新予告②<BR>
					０７／２７更新予告①<BR>
					０７／２０更新予告<BR>
					０７／１３更新予告②<BR>
					０７／１３更新予告①<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>２ｎｄＧ発売日決定！</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
<img src="" width=5 height=8><BR>
ＭＨＰ２ｎｄＧの発売日が<BR>
決まったのニャ！<BR>
<img src="" width=5 height=6><BR>
<center>
<img src=./PNG/title.png width=200 height=96>
</center>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td align=center>
				<B><font size=2>
				<font color=yellow>２ｎｄＧ発売日決定！</font><br>
				</font></B>
			</td>
		</tr>
		<tr>
			<td align=center valign=center>
				<B><font size=2>
モンスターハンターポータブル 2nd Gは<BR>
<font color=orange>２００８年　３月　２７日</font>に発売日が決まったのニャ！<BR>
ＰＣサイトは<BR>
<font color=orange>http://www.capcom.co.jp/monsterhunter/P2ndG/</font><BR>
ケータイからは<BR>
<font color=orange>http://mobile.capcom.jp/</font><BR>
にアクセスでちょっと内容を知ることができるのニャ　<BR>
				</font></B>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=002></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					２ｎｄＧ発売日決定！<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０９／２１更新予告<BR></B>
			<tr><td>
				<B>
					０８／０３更新予告<BR>
					０７／２７更新予告②<BR>
					０７／２７更新予告①<BR>
					０７／２０更新予告<BR>
					０７／１３更新予告②<BR>
					０７／１３更新予告①<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０９／２１更新予告</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
来週のこの時間に特別クエスト<BR>
<font color=orange>【鋼の来訪者】</font><BR>
を配信予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０９／２１更新予告</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【鋼の来訪者】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：ギルドマスター<BR>
非常事態じゃ！ワシらの街に褐<BR>
色のクシャルダオラが迫ってお<BR>
る。力に自信のある者は、速や<BR>
かにこちらへ来てもらいたい。<BR>
おヌシの力で街を救ってくれ！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60025.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=003></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					２ｎｄＧ発売日決定！<BR>
					０９／２１更新予告<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０８／０３更新予告<BR></B>
			<tr><td>
				<B>
					０７／２７更新予告②<BR>
					０７／２７更新予告①<BR>
					０７／２０更新予告<BR>
					０７／１３更新予告②<BR>
					０７／１３更新予告①<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０８／０３更新予告</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【天と地の怒り】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０８／０３更新予告</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【天と地の怒り】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：ココット村の村長<BR>
皆の衆、久しぶりじゃの。<BR>
これは、ワシからの挑戦じゃ！<BR>
巨大な２頭の飛竜、リオレウス<BR>
とリオレイア。果たしてヌシは<BR>
両者を屈服させられるかな？<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60022.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=004></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					２ｎｄＧ発売日決定！<BR>
					０９／２１更新予告<BR>
					０８／０３更新予告<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０７／２７更新予告②<BR></B>
			<tr><td>
				<B>
					０７／２７更新予告①<BR>
					０７／２０更新予告<BR>
					０７／１３更新予告②<BR>
					０７／１３更新予告①<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０７／２７更新予告②</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はサマーボーナスパック<BR>
発売を記念してクエスト<BR>
<font color=orange>【チャレンジクエスト　１２】</font><BR>
を追加予定ニャ！<BR>
□ボタンで詳細なのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０７／２７更新予告②</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【チャレンジクエスト　１２】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：教官<BR>
我輩だ、教官だ。圧倒的な力を<BR>
持つ古龍と言えども、弱点は<BR>
存在する。どの道具が効き、<BR>
どの瞬間で使うかを知る。<BR>
それが腕を磨くと言う事だぞ！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/c61012.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=005></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					２ｎｄＧ発売日決定！<BR>
					０９／２１更新予告<BR>
					０８／０３更新予告<BR>
					０７／２７更新予告②<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０７／２７更新予告①<BR></B>
			<tr><td>
				<B>
					０７／２０更新予告<BR>
					０７／１３更新予告②<BR>
					０７／１３更新予告①<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０７／２７更新予告①</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【金色の雷帝】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０７／２７更新予告①</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【金色の雷帝】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：闘技場の運営者<BR>
た…たた…た…大変です！<BR>
私の闘技場が黒いモンスターに<BR>
占拠されてしまいました！この<BR>
ままでは闘技場が使えません。<BR>
早くあいつを狩ってください！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60019.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=006></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					２ｎｄＧ発売日決定！<BR>
					０９／２１更新予告<BR>
					０８／０３更新予告<BR>
					０７／２７更新予告②<BR>
					０７／２７更新予告①<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０７／２０更新予告<BR></B>
			<tr><td>
				<B>
					０７／１３更新予告②<BR>
					０７／１３更新予告①<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０７／２０更新予告</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【蛇竜の巣窟】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０７／２０更新予告</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【蛇竜の巣窟】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：闘技場の運営者<BR>
ハンターが己の腕前を披露する<BR>
闘技場！今回の相手は空を占拠<BR>
するガブラスたちです！毒だら<BR>
けの闘技場で、あなたは見事に<BR>
生き残ることができますか？<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60018.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=007></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					２ｎｄＧ発売日決定！<BR>
					０９／２１更新予告<BR>
					０８／０３更新予告<BR>
					０７／２７更新予告②<BR>
					０７／２７更新予告①<BR>
					０７／２０更新予告<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０７／１３更新予告②<BR></B>
			<tr><td>
				<B>
					０７／１３更新予告①<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０７／１３更新予告②</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【チャレンジクエスト　１１】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０７／１３更新予告②</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【チャレンジクエスト　１１】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：教官<BR>
我輩だ、教官だ。最早常識だが<BR>
相手が寝こけているときに入っ<BR>
た最初のダメージは絶大だ！<BR>
強力な爆弾を１撃目に叩き<BR>
込まねば勝利はかなわんぞ！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/c61011.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=008></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					２ｎｄＧ発売日決定！<BR>
					０９／２１更新予告<BR>
					０８／０３更新予告<BR>
					０７／２７更新予告②<BR>
					０７／２７更新予告①<BR>
					０７／２０更新予告<BR>
					０７／１３更新予告②<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０７／１３更新予告①<BR></B>
			<tr><td valign=top>
				<B>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０７／１３更新予告①</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【スカーフェイス】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０７／１３更新予告①</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【スカーフェイス】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：十字傷の男<BR>
俺と同じ傷を持つ飛竜を密林ま<BR>
で追い詰めたんだが、無傷では<BR>
いられなくてな…俺の身体も限<BR>
界らしい。頼む、動けない俺の<BR>
代わりにあいつを狩ってくれ！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60010.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
