<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO5.PHP",
		"RB_LINK=DB_INFO1.PHP",
		"MOVE_CHAR=./GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white background=./GIF/BG.gif bgcolor=#0DA5DE>
<!--480 x 272-->
<basefont size=2>
<B>
<a name=001></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>６/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td bgcolor=green>
				<B>０３／２３更新予告①<BR></B>
			<tr><td height=110 valign=top>
				<B>
					０３／１６更新予告②<BR>
					０３／１６更新予告①<BR>
					０３／０９更新予告②<BR>
					０３／０９更新予告①<BR>
					０３／０２更新予告<BR>
					オープン！！<BR>
					<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０３／２３更新予告①</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【雲霞の如く】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０３／２３更新予告①</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【雲霞の如く】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：イライラ顔の村娘<BR>
最近うちの村の周りが騒がしい<BR>
と思ったら、おっきな虫が大発<BR>
生してるじゃない！夜もうるさ<BR>
くて眠れないわ！ハンターなん<BR>
でしょ？早く何とかしなさい！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60024.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=002></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>６/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０３／２３更新予告①<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０３／１６更新予告②<BR></B>
			<tr><td>
				<B>
					０３／１６更新予告①<BR>
					０３／０９更新予告②<BR>
					０３／０９更新予告①<BR>
					０３／０２更新予告<BR>
					オープン！！<BR>
					<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０３／１６更新予告②</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【シュレイドの伝説】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０３／１６更新予告②</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【シュレイドの伝説】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：ギルドマスター<BR>
古シュレイド王国の城跡で黒龍<BR>
ミラボレアスの存在が確認され<BR>
た！放っておけば国一つが亡び<BR>
るやもしれぬ…彼奴の討伐にお<BR>
ヌシらの力を貸してくれぃ！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60015.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=003></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>６/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０３／２３更新予告①<BR>
					０３／１６更新予告②<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０３／１６更新予告①<BR></B>
			<tr><td>
				<B>
					０３／０９更新予告②<BR>
					０３／０９更新予告①<BR>
					０３／０２更新予告<BR>
					オープン！！<BR>
					<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０３／１６更新予告①</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【猿蟹合戦！「猿ノ巻」】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０３／１６更新予告①</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【猿蟹合戦！「猿ノ巻」】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：闘技場の運営者<BR>
ハンターが己の腕前を披露する<BR>
闘技場！今回の相手はドドブラ<BR>
ンゴ！ただし、周囲にはヤオザ<BR>
ミ、ガミザミがワラワラと…！<BR>
さぁ、見事クリアできますか？<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60014.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=004></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>６/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０３／２３更新予告①<BR>
					０３／１６更新予告②<BR>
					０３／１６更新予告①<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０３／０９更新予告②<BR></B>
			<tr><td>
				<B>
					０３／０９更新予告①<BR>
					０３／０２更新予告<BR>
					オープン！！<BR>
					<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０３／０９更新予告②</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【チャレンジクエスト　０２】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０３／０９更新予告②</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【チャレンジクエスト　０２】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：教官<BR>
我輩だ、教官だ。今回の演習は<BR>
２匹の盾蟹のどちらか片方を<BR>
倒せばクエストクリアだ！<BR>
ペイントボールを上手く使って<BR>
片方に攻撃を集中させるのだ！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/c61002.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=005></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>６/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０３／２３更新予告①<BR>
					０３／１６更新予告②<BR>
					０３／１６更新予告①<BR>
					０３／０９更新予告②<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０３／０９更新予告①<BR></B>
			<tr><td>
				<B>
					０３／０２更新予告<BR>
					オープン！！<BR>
					<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０３／０９更新予告①</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【アメザリ釣り大会！】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０３／０９更新予告①</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【アメザリ釣り大会！】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：アメリカザリガニ<BR>
アメリカザリガニから挑戦状！<BR>
時間内に砂漠のどこかにいる黄<BR>
金魚を５匹釣って納品すれば<BR>
クエスト成功！クリアできたら<BR>
スゴい防具が手に入るかも！？<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60001.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=006></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>６/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０３／２３更新予告①<BR>
					０３／１６更新予告②<BR>
					０３／１６更新予告①<BR>
					０３／０９更新予告②<BR>
					０３／０９更新予告①<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０３／０２更新予告<BR></B>
			<tr><td>
				<B>
					オープン！！<BR>
					<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０３／０２更新予告</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【ファミ通　桃毛獣連続狩猟】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０３／０２更新予告</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【ファミ通　桃毛獣連続狩猟】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：ファミ通ＭＨＰ攻略班<BR>
沼地に続々と現れるババコンガ<BR>
を討伐しまくれ！２頭以上狩猟<BR>
してタイムアップかネコタクチ<BR>
ケット納品でクリアだ。ただし<BR>
武器はガンランス限定！！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60004.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=007></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>６/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０３／２３更新予告①<BR>
					０３／１６更新予告②<BR>
					０３／１６更新予告①<BR>
					０３／０９更新予告②<BR>
					０３／０９更新予告①<BR>
					０３／０２更新予告<BR>
				</B>
			<tr><td bgcolor=green>
				<B>オープン！！<BR></B>
			<tr><td>
				<B>
					<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>オープン！！</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
ダウンロードページを<BR>
オープンしたのニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td align=center>
				<B><font size=2>
				<font color=yellow>オープン！！</font><br>
				</font></B>
			</td>
		</tr>
		<tr>
			<td align=center valign=center>
				<B><font size=2>
ダウンロードページをオープンしたのニャ！<BR>
いろんなクエストや、特典をドンドン追加していくから<BR>
みんなバンバン！ダウンロードしていってほしいニャ！<BR>
　　　　　　　　　　　　　　<br>
　　　　　　　　　　　　　　<br>
　　　　　　　　　　　　　　<br>
　　　　　　　　　　　　　　<br>
				</font></B>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
