<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO1.PHP",
		"RB_LINK=DB_INFO3.PHP",
		"MOVE_CHAR=./GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white background=./GIF/BG.gif bgcolor=#0DA5DE>
<!--480 x 272-->
<basefont size=2>
<B>
<a name=001></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td bgcolor=green>
				<B>０７／０６更新予告<BR></B>
			<tr><td height=110 valign=top>
				<B>
					０６／２９更新予告②<BR>
					０６／２９更新予告①<BR>
					０６／２２更新予告<BR>
					０６／１５更新予告②<BR>
					０６／１５更新予告①<BR>
					０６／０８更新予告<BR>
					０６／０１更新予告④<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０７／０６更新予告</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【双璧！黒き熱風】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０７／０６更新予告</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【双璧！黒き熱風】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：闘技場の運営者<BR>
ハンターが己の腕前を披露する<BR>
闘技場！今回は世にも恐ろしい<BR>
黒鎧竜を闘技場に放しました！<BR>
しかも２頭！ハンターの皆さん<BR>
この難関を突破できますか？<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60012.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=002></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０７／０６更新予告<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０６／２９更新予告②<BR></B>
			<tr><td>
				<B>
					０６／２９更新予告①<BR>
					０６／２２更新予告<BR>
					０６／１５更新予告②<BR>
					０６／１５更新予告①<BR>
					０６／０８更新予告<BR>
					０６／０１更新予告④<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０６／２９更新予告②</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【チャレンジクエスト　１０】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０６／２９更新予告②</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【チャレンジクエスト　１０】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：教官<BR>
我輩だ、教官だ。雄の火竜と<BR>
雌の火竜、その行動は大きく<BR>
異なる。ハンターとしての経験<BR>
と技術をフル活用して短時間で<BR>
の討伐を目指すのだ！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/c61010.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=003></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０７／０６更新予告<BR>
					０６／２９更新予告②<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０６／２９更新予告①<BR></B>
			<tr><td>
				<B>
					０６／２２更新予告<BR>
					０６／１５更新予告②<BR>
					０６／１５更新予告①<BR>
					０６／０８更新予告<BR>
					０６／０１更新予告④<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０６／２９更新予告①</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【電撃祭　幻の決戦】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０６／２９更新予告①</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【電撃祭　幻の決戦】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：電撃ＰＳ　ポリタン<BR>
ポリタンからのスンゲー挑戦！<BR>
渦巻く炎の中で立ちはだかるの<BR>
は白き幻獣だ！決戦に勝利し、<BR>
スンゲー報酬を手に入れよう！<BR>
今回の相手は…大きい！？<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60026.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=004></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０７／０６更新予告<BR>
					０６／２９更新予告②<BR>
					０６／２９更新予告①<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０６／２２更新予告<BR></B>
			<tr><td>
				<B>
					０６／１５更新予告②<BR>
					０６／１５更新予告①<BR>
					０６／０８更新予告<BR>
					０６／０１更新予告④<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０６／２２更新予告</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【最強の矛、最強の盾】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０６／２２更新予告</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【最強の矛、最強の盾】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：闘技場の運営者<BR>
ハンターが己の腕前を披露する<BR>
闘技場！今回は性質の違う２匹<BR>
の大蟹を闘技場に放しました！<BR>
個人参加や腕試しも大歓迎！<BR>
振るってご参加ください！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60008.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=005></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０７／０６更新予告<BR>
					０６／２９更新予告②<BR>
					０６／２９更新予告①<BR>
					０６／２２更新予告<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０６／１５更新予告②<BR></B>
			<tr><td>
				<B>
					０６／１５更新予告①<BR>
					０６／０８更新予告<BR>
					０６／０１更新予告④<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０６／１５更新予告②</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【チャレンジクエスト　０９】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０６／１５更新予告②</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【チャレンジクエスト　０９】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：教官<BR>
我輩だ、教官だ。イャンガルル<BR>
ガへの挑戦だな！奴は全ての<BR>
能力が高く、生半可な実力では<BR>
太刀打ち出来ないぞ。己の腕を<BR>
磨き上げて挑戦するのだ！<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/c61009.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=006></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０７／０６更新予告<BR>
					０６／２９更新予告②<BR>
					０６／２９更新予告①<BR>
					０６／２２更新予告<BR>
					０６／１５更新予告②<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０６／１５更新予告①<BR></B>
			<tr><td>
				<B>
					０６／０８更新予告<BR>
					０６／０１更新予告④<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０６／１５更新予告①</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【神秘の怪鳥】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０６／１５更新予告①</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【神秘の怪鳥】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：ハンターズギルド<BR>
密林地帯の村から救難信号を受<BR>
けました。奇妙な怪鳥の群れに<BR>
襲われ畑に被害が出ている模様<BR>
です。至急現場へ向かい、事態<BR>
の収拾に当たってください。<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60023.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=007></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０７／０６更新予告<BR>
					０６／２９更新予告②<BR>
					０６／２９更新予告①<BR>
					０６／２２更新予告<BR>
					０６／１５更新予告②<BR>
					０６／１５更新予告①<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０６／０８更新予告<BR></B>
			<tr><td>
				<B>
					０６／０１更新予告④<BR>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０６／０８更新予告</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回はクエスト<BR>
<font color=orange>【緑萌ゆる季節】</font><BR>
を追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０６／０８更新予告</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=center colspan=2>
				<B><font size=2>
				<font color=orange>【緑萌ゆる季節】</font><BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
依頼主：兄の帰りを待つ女性<BR>
今度、久しぶりに兄が帰郷する<BR>
のですが、最近村の周りの丘陵<BR>
地帯に多数のリオレイアが現れ<BR>
て困っています。兄が帰ってく<BR>
る前に何とかしてください。<BR>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/e60007.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<a name=008></a>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=204 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/６</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			<tr><td>
				<B>
					０７／０６更新予告<BR>
					０６／２９更新予告②<BR>
					０６／２９更新予告①<BR>
					０６／２２更新予告<BR>
					０６／１５更新予告②<BR>
					０６／１５更新予告①<BR>
					０６／０８更新予告<BR>
				</B>
			<tr><td bgcolor=green>
				<B>０６／０１更新予告④<BR></B>
			<tr><td valign=top>
				<B>
				</B>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=./GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2><B>
				<font color=yellow>０６／０１更新予告④</font><br>
				</B></font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><B>
				<BR>
次回は特典をさらに２つ<BR>
追加予定ニャ！<BR>
詳しく知りたかったら<BR>
□ボタンを押すのニャ！<BR>
<BR>
<BR>
<BR>
<BR>
				</B></font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON5.gif></td></tr></table>
<img src=./GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=./GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=5 cellpadding=0>
		<tr>
			<td height=34 40 51 align=center valign=top colspan=2>
				<B><font size=2>
				<font color=yellow>０６／０１更新予告④</font><br>
				次回の内容をちょっとだけ教えちゃうのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td height=17 align=left colspan=2>
				<B><font size=2>
				以下の特典が追加されるのニャ！<BR>
				</font></B>
			</td>
		</tr>
		<tr>
			<td width=238 heighT=106 111 align=left valign=center>
				<B><font size=2>
・称号<BR>
　【ドンドルマ】<BR>
・行商ばあちゃんの品揃え<BR>
　【特別な品揃え】<BR>
　　　　　　　　　　　　　　<br>
　　　　　　　　　　　　　　<br>
				</font></B>
			</td>
			<td width=200 height=106 111 align=center valign=center>
				<img src=./PNG/b00003.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
