<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:7",
		"MOVE_CHAR=./GIF/NEKO.gif,58,62,0,,16,,417,185",
		"MOVE_CHAR=./GIF/PIG.gif,64,48,1,1,3,10,480,050",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=#0DA5DE background=./GIF/BG.gif>
<!--480 x 272-->
<basefont size=2>
<B>
<!-- ########  01  ######################################################## -->
<img src=./GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 476 height=197 201 cellspacing=4 5 6>
<tr>
	<td><center>
		<table background=./GIF/BONUS_F.gif cellspacing=0 cellpadding width=460 height=188>
		<form action="BONUS/bonus.mib" BDOWNLOAD method=post>
		<tr>
			<td width=460 height=136 valign=top>
			<BR>
			　特典は全て開放されているニャ！<BR>
			　詳細は□ボタンで確認してほしいのニャー。
			</td>
		</tr>
		<tr>
			<td height=27 align=center>
				<img ANIME=10 src=./GIF/BDL.gif width=193 height=27 alt="[O] DOWNLOAD"><BR>
				<input type=image src="" name=submit width=0 height=0>
			</td>
		</tr>
		<tr>
			<td align=right height=25>
			</td>
		</tr>
		</form>
		</table>
	</center></td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>
<!-- ########  02  ######################################################## -->
<a name=002></a>
<img src=./GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 476 height=197 201 cellspacing=4 6>
<tr>
	<td><center>
		<table background=./GIF/BONUS_F.gif cellspacing=0 cellpadding=0 width=460 height=188>
		<tr>
			<td width=460 align=center>
				<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
						<B>１/６</B>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td width=460 height=55 63 80 valign=center>
				<font color=orange>
				　まだ獲得していない特典は黄色で表示されるニャ！</font><BR>
				　【プーギーの服】<BR>
				　プーギーの着せ替え用の服が追加されるニャ。<BR>
			</td>
		</tr>
		<tr>
			<td width=405 height=90 65 valign=top>
				<table width=405 cellspacing=0 cellpadding=0>
					<tr>
						<td width=200 valign=top>
						　<a href=#002 qname=09>・ファミ通ヒゲ眼鏡</a><BR>
						　<a href=#002 qname=07>・天使のレオタード</a><BR>
						　<a href=#002 qname=08>・眠りを誘う白</a><BR>
						</td>
						<td width=205 align=right>
							<img src=./PNG/bonus09.png width=200 height=90>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=right height=26 43>
			</td>
		</tr>
		</table>
	</center></td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<!-- ########  03  ######################################################## -->
<a name=003></a>
<img src=./GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 476 height=197 201 cellspacing=4 6>
<tr>
	<td><center>
		<table background=./GIF/BONUS_F.gif cellspacing=0 cellpadding=0 width=460 height=188>
		<tr>
			<td width=460 align=center>
				<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
						<B>２/６</B>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td width=460 height=55 63 80 valign=center>
				<font color=orange>
					　まだ獲得していない特典は黄色で表示されるニャ！</font><BR>
					　【さすらいの料理ネコ】<BR>
					　この毛並みのアイルーが村を訪れるようになる…かもニャ。<BR>
			</td>
		</tr>
		<tr>
			<td width=405 height=90 65 valign=top>
				<table width=405 cellspacing=0 cellpadding=0>
					<tr>
						<td width=200 valign=top>
						　<a href=#003 qname=00>・赤虎</a><BR>
						　<a href=#003 qname=01>・オレンジ</a><BR>
						　<a href=#003 qname=02>・漆黒</a><BR>
						</td>
						<td width=205 align=right>
							<img src=./PNG/bonus03.png width=200 height=90>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=right height=26 43>
			</td>
		</tr>
		</table>
	</center></td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<!-- ########  04  ######################################################## -->
<a name=004></a>
<img src=./GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 476 height=197 201 cellspacing=4 6>
<tr>
	<td><center>
		<table background=./GIF/BONUS_F.gif cellspacing=0 cellpadding=0 width=460 height=188>
		<tr>
			<td width=460 align=center>
				<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
						<B>３/６</B>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td width=460 height=55 63 80 valign=center>
				<font color=orange>
					　まだ獲得していない特典は黄色で表示されるニャ！</font><BR>
					　【称号】<BR>
					　ギルドカードで使う称号が追加されるニャ。<BR>
			</td>
		</tr>
		<tr>
			<td width=405 height=90 65 valign=top>
				<table width=405 cellspacing=0 cellpadding=0>
					<tr>
						<td width=200 valign=top>
						　<a href=#004 qname=03>・ココット</a><BR>
						　<a href=#004 qname=04>・ジャンボ</a><BR>
						　<a href=#004 qname=05>・ミナガルデ</a><BR>
						　<a href=#004 qname=06>・ドンドルマ</a><BR>
						</td>
						<td width=205 align=right>
							<img src=./PNG/bonus07.png width=200 height=90>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=right height=26 43>
			</td>
		</tr>
		</table>
	</center></td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<!-- ########  05  ######################################################## -->
<a name=005></a>
<img src=./GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 476 height=197 201 cellspacing=4 6>
<tr>
	<td><center>
		<table background=./GIF/BONUS_F.gif cellspacing=0 cellpadding=0 width=460 height=188>
		<tr>
			<td width=460 align=center>
				<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
						<B>４/６</B>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td width=460 height=55 63 80 valign=center>
				<font color=orange>
					　まだ獲得していない特典は黄色で表示されるニャ！</font><BR>
					　【ポッケポイント】<BR>
					　ポッケポイントが１０００ポイント貰えるニャ。<BR>
			</td>
		</tr>
		<tr>
			<td width=405 height=90 65 valign=top>
				<table width=405 cellspacing=0 cellpadding=0>
					<tr>
						<td width=200 valign=top>
						　<a href=#005 qname=10>・１０００ポイント入手</a><BR>
						</td>
						<td width=205 align=right>
							<img src=./PNG/bonus11.png width=200 height=90>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=right height=26 43>
			</td>
		</tr>
		</table>
	</center></td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<!-- ########  06  ######################################################## -->
<a name=006></a>
<img src=./GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 476 height=197 201 cellspacing=4 6>
<tr>
	<td><center>
		<table background=./GIF/BONUS_F.gif cellspacing=0 cellpadding=0 width=460 height=188>
		<tr>
			<td width=460 align=center>
				<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
						<B>５/６</B>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td width=460 height=55 63 80 valign=center>
				<font color=orange>
					　まだ獲得していない特典は黄色で表示されるニャ！</font><BR>
					　【農場施設】<BR>
					　トレニャーの船が建造可能になるニャ。<BR>
			</td>
		</tr>
		<tr>
			<td width=405 height=90 65 valign=top>
				<table width=405 cellspacing=0 cellpadding=0>
					<tr>
						<td width=200 valign=top>
						　<a href=#006 qname=11>・トレニャーの船</a><BR>
						</td>
						<td width=205 align=right>
							<img src=./PNG/bonus12.png width=200 height=90>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=right height=26 43>
			</td>
		</tr>
		</table>
	</center></td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<!-- ########  07  ######################################################## -->
<a name=007></a>
<img src=./GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 476 height=197 201 cellspacing=4 6>
<tr>
	<td><center>
		<table background=./GIF/BONUS_F.gif cellspacing=0 cellpadding=0 width=460 height=188>
		<tr>
			<td width=460 align=center>
				<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
					<tr>
						<td align=center>
						<B>６/６</B>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td width=460 height=55 63 80 valign=center>
				<font color=orange>
					　まだ獲得していない特典は黄色で表示されるニャ！</font><BR>
					　【行商ばあちゃんの品揃え】<BR>
					　いつもよりずっと良い品を仕入れてくれる…かもニャ。<BR>
			</td>
		</tr>
		<tr>
			<td width=405 height=90 65 valign=top>
				<table width=405 cellspacing=0 cellpadding=0>
					<tr>
						<td width=200 valign=top>
						　<a href=#007 qname=12>・特別な品揃え</a><BR>
						</td>
						<td width=205 align=right>
							<img src=./PNG/bonus13.png width=200 height=90>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=right height=26 43>
			</td>
		</tr>
		</table>
	</center></td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
<!-- ###################################################################### -->
</body>
</html>
