<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
<GAME-STYLE>
	"MOUSE=OFF",
	"SCROLL=OFF",
	"TITLE=OFF",
	"BACK=ON:DL_SELECT.PHP",
	"FORWARD=OFF",
	"CANCEL=OFF",
	"RELOAD=OFF",
	"CHOICE_MV=OFF",
	"LINK_U=OFF",
	"FRONT_LABEL=ON:2",
	"LB_LINK=DL_CMENU1.PHP",
	"RB_LINK=DL_CMENU3.PHP",
	"MOVE_CHAR=./GIF/rio.gif,82,52,1,1,0,40,-82,180",
	"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=#0DA5DE background=./GIF/BG.gif>
<!--480 x 272-->
<basefont size=2>
<B>

<a name=001></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61015.mib" DOWNLOAD CSUM=30363 FSIZE=1960 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>２/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td bgcolor=green>
	<B><a href=#001 qname=m61015.mib>モンハンフェスタ　０２</a><BR></B>
<tr><td height=110 valign=top>
	<B>
	<a href=#002 qname=m61007.mib>チャレンジクエスト　０７</a><BR>
	<a href=#003 qname=m61006.mib>チャレンジクエスト　０６</a><BR>
	<a href=#004 qname=m61005.mib>チャレンジクエスト　０５</a><BR>
	<a href=#005 qname=m61014.mib>モンハンフェスタ　０１</a><BR>
	<a href=#006 qname=m61004.mib>チャレンジクエスト　０４</a><BR>
	<a href=#007 qname=m61003.mib>チャレンジクエスト　０３</a><BR>
	</B>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>モンハンフェスタ　０２</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ３０００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> １５分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ１以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	モンハンフェスタ　０２
</B>
</td>
<td>
<B>
	★★★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ティガレックス１頭の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>情熱の大会運営者<br>
さあッ！お祭りよッ！<BR>
ハンターさん達には大闘技場で<BR>
轟竜とガチンコバトルしてもら<BR>
うわッ！誰よりも早くッ！<BR>
誰よりも華麗に戦うのよッ！<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=002></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61007.mib" DOWNLOAD CSUM=34989 FSIZE=6596 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>２/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td>
	<B>
	<a href=#001 qname=m61015.mib>モンハンフェスタ　０２</a><BR>
	</B>
<tr><td bgcolor=green>
	<B><a href=#002 qname=m61007.mib>チャレンジクエスト　０７</a><BR></B>
<tr><td height=93 valign=top>
	<B>
	<a href=#003 qname=m61006.mib>チャレンジクエスト　０６</a><BR>
	<a href=#004 qname=m61005.mib>チャレンジクエスト　０５</a><BR>
	<a href=#005 qname=m61014.mib>モンハンフェスタ　０１</a><BR>
	<a href=#006 qname=m61004.mib>チャレンジクエスト　０４</a><BR>
	<a href=#007 qname=m61003.mib>チャレンジクエスト　０３</a><BR>
	</B>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>チャレンジクエスト　０７</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> １２００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> １０分<br>
<font color=orange>指定地　：</font> 密林＜昼＞<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ１以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	チャレンジクエスト　０７
</B>
</td>
<td>
<B>
	★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ランポス３０頭の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>教官<br>
我輩だ、教官だ。狩りには<BR>
効率の良い動き方というものが<BR>
ある。どのルートで回れば<BR>
より早いか、貴様にはその<BR>
最速の道が見えるか？<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=003></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61006.mib" DOWNLOAD CSUM=23021 FSIZE=2304 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>２/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td>
	<B>
	<a href=#001 qname=m61015.mib>モンハンフェスタ　０２</a><BR>
	<a href=#002 qname=m61007.mib>チャレンジクエスト　０７</a><BR>
	</B>
<tr><td bgcolor=green>
	<B><a href=#003 qname=m61006.mib>チャレンジクエスト　０６</a><BR></B>
<tr><td height=76 valign=top>
	<B>
	<a href=#004 qname=m61005.mib>チャレンジクエスト　０５</a><BR>
	<a href=#005 qname=m61014.mib>モンハンフェスタ　０１</a><BR>
	<a href=#006 qname=m61004.mib>チャレンジクエスト　０４</a><BR>
	<a href=#007 qname=m61003.mib>チャレンジクエスト　０３</a><BR>
	</B>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>チャレンジクエスト　０６</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ３００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> １５分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ１以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	チャレンジクエスト　０６
</B>
</td>
<td>
<B>
	★★★★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ドスファンゴ１頭の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>教官<br>
我輩だ、教官だ。<BR>
ドスファンゴへの挑戦だな！<BR>
ドスファンゴと侮るな。お前は<BR>
この演習で世界に更なる高みが<BR>
ある事を知るだろう！<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=004></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61005.mib" DOWNLOAD CSUM=32722 FSIZE=2040 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>２/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td>
	<B>
	<a href=#001 qname=m61015.mib>モンハンフェスタ　０２</a><BR>
	<a href=#002 qname=m61007.mib>チャレンジクエスト　０７</a><BR>
	<a href=#003 qname=m61006.mib>チャレンジクエスト　０６</a><BR>
	</B>
<tr><td bgcolor=green>
	<B><a href=#004 qname=m61005.mib>チャレンジクエスト　０５</a><BR></B>
<tr><td height=59 valign=top>
	<B>
	<a href=#005 qname=m61014.mib>モンハンフェスタ　０１</a><BR>
	<a href=#006 qname=m61004.mib>チャレンジクエスト　０４</a><BR>
	<a href=#007 qname=m61003.mib>チャレンジクエスト　０３</a><BR>
	</B>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>チャレンジクエスト　０５</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ５１００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> １５分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ４以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	チャレンジクエスト　０５
</B>
</td>
<td>
<B>
	★★★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ショウグンギザミ１匹の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>教官<br>
これは我輩からの試練だ！<BR>
相手はショウグンギザミ２匹、<BR>
どちらか片方を倒した時点で<BR>
クエストクリアになるぞ！<BR>
お前の腕を見せてみるのだ！<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=005></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61014.mib" DOWNLOAD CSUM=7107 FSIZE=5508 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>２/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td>
	<B>
	<a href=#001 qname=m61015.mib>モンハンフェスタ　０２</a><BR>
	<a href=#002 qname=m61007.mib>チャレンジクエスト　０７</a><BR>
	<a href=#003 qname=m61006.mib>チャレンジクエスト　０６</a><BR>
	<a href=#004 qname=m61005.mib>チャレンジクエスト　０５</a><BR>
	</B>
<tr><td bgcolor=green>
	<B><a href=#005 qname=m61014.mib>モンハンフェスタ　０１</a><BR></B>
<tr><td height=42 valign=top>
	<B>
	<a href=#006 qname=m61004.mib>チャレンジクエスト　０４</a><BR>
	<a href=#007 qname=m61003.mib>チャレンジクエスト　０３</a><BR>
	</B>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>モンハンフェスタ　０１</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ３０００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> ２０分<br>
<font color=orange>指定地　：</font> 雪山＜夜＞<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ１以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	モンハンフェスタ　０１
</B>
</td>
<td>
<B>
	★★★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ティガレックス１頭の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>新米運営者<br>
大会へようこそ！<BR>
この度はティガレックス討伐を<BR>
依頼させていただきます。<BR>
腕を疑うわけではありません<BR>
が、実力の程見せてください。<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=006></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61004.mib" DOWNLOAD CSUM=10780 FSIZE=5584 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>２/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td>
	<B>
	<a href=#001 qname=m61015.mib>モンハンフェスタ　０２</a><BR>
	<a href=#002 qname=m61007.mib>チャレンジクエスト　０７</a><BR>
	<a href=#003 qname=m61006.mib>チャレンジクエスト　０６</a><BR>
	<a href=#004 qname=m61005.mib>チャレンジクエスト　０５</a><BR>
	<a href=#005 qname=m61014.mib>モンハンフェスタ　０１</a><BR>
	</B>
<tr><td bgcolor=green>
	<B><a href=#006 qname=m61004.mib>チャレンジクエスト　０４</a><BR></B>
<tr><td height=25 valign=top>
	<B>
	<a href=#007 qname=m61003.mib>チャレンジクエスト　０３</a><BR>
	</B>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>チャレンジクエスト　０４</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ４２００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> ３０分<br>
<font color=orange>指定地　：</font> 雪山＜夜＞<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ１以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	チャレンジクエスト　０４
</B>
</td>
<td>
<B>
	★★★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ドドブランゴ１頭の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>教官<br>
我輩だ、教官だ。ドドブランゴ<BR>
への挑戦だな！素早く狩る為に<BR>
は、攻撃をいかに短時間で集中<BR>
させるかが鍵だ。隙を作って<BR>
仲間と攻撃を叩き込め！<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=007></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61003.mib" DOWNLOAD CSUM=19875 FSIZE=5712 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>２/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td>
	<B>
	<a href=#001 qname=m61015.mib>モンハンフェスタ　０２</a><BR>
	<a href=#002 qname=m61007.mib>チャレンジクエスト　０７</a><BR>
	<a href=#003 qname=m61006.mib>チャレンジクエスト　０６</a><BR>
	<a href=#004 qname=m61005.mib>チャレンジクエスト　０５</a><BR>
	<a href=#005 qname=m61014.mib>モンハンフェスタ　０１</a><BR>
	<a href=#006 qname=m61004.mib>チャレンジクエスト　０４</a><BR>
	</B>
<tr><td bgcolor=green>
	<B><a href=#007 qname=m61003.mib>チャレンジクエスト　０３</a><BR></B>
<tr><td valign=top>
	<B>
	</B>
<tr><td height=8>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>チャレンジクエスト　０３</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ３０００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> ３０分<br>
<font color=orange>指定地　：</font> 密林＜夜＞<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ１以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	チャレンジクエスト　０３
</B>
</td>
<td>
<B>
	★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ガノトトス１頭の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>教官<br>
我輩だ、教官だ。今日の密林は<BR>
雨天。崖崩れがあったようで<BR>
どこかが岩で塞がれたようだ。<BR>
爆弾は使えないがこんな天気の<BR>
時には≪アレ≫が使えるぞ！<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
