<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
<GAME-STYLE>
	"MOUSE=OFF",
	"SCROLL=OFF",
	"TITLE=OFF",
	"BACK=ON:DL_SELECT.PHP",
	"FORWARD=OFF",
	"CANCEL=OFF",
	"RELOAD=OFF",
	"CHOICE_MV=OFF",
	"LINK_U=OFF",
	"FRONT_LABEL=ON:2",
	"LB_LINK=DL_CMENU3.PHP",
	"RB_LINK=DL_CMENU2.PHP",
	"MOVE_CHAR=./GIF/rio.gif,82,52,1,1,0,40,-82,180",
	"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=#0DA5DE background=./GIF/BG.gif>
<!--480 x 272-->
<basefont size=2>
<B>

<a name=001></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61012.mib" DOWNLOAD CSUM=62036 FSIZE=4208 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>１/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td bgcolor=green>
	<B><a href=#001 qname=m61012.mib>チャレンジクエスト　１２</a><BR></B>
<tr><td height=110 valign=top>
	<B>
	<a href=#002 qname=m61011.mib>チャレンジクエスト　１１</a><BR>
	<a href=#003 qname=m61010.mib>チャレンジクエスト　１０</a><BR>
	<a href=#004 qname=m61009.mib>チャレンジクエスト　０９</a><BR>
	<a href=#005 qname=m61017.mib>モンハンフェスタ　０４</a><BR>
	<a href=#006 qname=m61008.mib>チャレンジクエスト　０８</a><BR>
	<a href=#007 qname=m61016.mib>モンハンフェスタ　０３</a><BR>
	</B>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>チャレンジクエスト　１２</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ３０００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> ４０分<br>
<font color=orange>指定地　：</font> 雪山＜昼＞<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ４以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	チャレンジクエスト　１２
</B>
</td>
<td>
<B>
	★★★★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
クシャルダオラ１体の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>教官<br>
我輩だ、教官だ。圧倒的な力を<BR>
持つ古龍と言えども、弱点は<BR>
存在する。どの道具が効き、<BR>
どの瞬間で使うかを知る。<BR>
それが腕を磨くと言う事だぞ！<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=002></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61011.mib" DOWNLOAD CSUM=36185 FSIZE=1964 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>１/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td>
	<B>
	<a href=#001 qname=m61012.mib>チャレンジクエスト　１２</a><BR>
	</B>
<tr><td bgcolor=green>
	<B><a href=#002 qname=m61011.mib>チャレンジクエスト　１１</a><BR></B>
<tr><td height=93 valign=top>
	<B>
	<a href=#003 qname=m61010.mib>チャレンジクエスト　１０</a><BR>
	<a href=#004 qname=m61009.mib>チャレンジクエスト　０９</a><BR>
	<a href=#005 qname=m61017.mib>モンハンフェスタ　０４</a><BR>
	<a href=#006 qname=m61008.mib>チャレンジクエスト　０８</a><BR>
	<a href=#007 qname=m61016.mib>モンハンフェスタ　０３</a><BR>
	</B>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>チャレンジクエスト　１１</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> １２００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> ３０分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ１以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	チャレンジクエスト　１１
</B>
</td>
<td>
<B>
	★★★★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
グラビモス亜種１頭の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>教官<br>
我輩だ、教官だ。最早常識だが<BR>
相手が寝こけているときに入っ<BR>
た最初のダメージは絶大だ！<BR>
強力な爆弾を１撃目に叩き<BR>
込まねば勝利はかなわんぞ！<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=003></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61010.mib" DOWNLOAD CSUM=56386 FSIZE=3984 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>１/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td>
	<B>
	<a href=#001 qname=m61012.mib>チャレンジクエスト　１２</a><BR>
	<a href=#002 qname=m61011.mib>チャレンジクエスト　１１</a><BR>
	</B>
<tr><td bgcolor=green>
	<B><a href=#003 qname=m61010.mib>チャレンジクエスト　１０</a><BR></B>
<tr><td height=76 valign=top>
	<B>
	<a href=#004 qname=m61009.mib>チャレンジクエスト　０９</a><BR>
	<a href=#005 qname=m61017.mib>モンハンフェスタ　０４</a><BR>
	<a href=#006 qname=m61008.mib>チャレンジクエスト　０８</a><BR>
	<a href=#007 qname=m61016.mib>モンハンフェスタ　０３</a><BR>
	</B>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>チャレンジクエスト　１０</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ６０００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> ４０分<br>
<font color=orange>指定地　：</font> 森丘<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ４以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	チャレンジクエスト　１０
</B>
</td>
<td>
<B>
	★★★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
リオレウス１頭と<BR>
リオレイア１頭の討伐<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>教官<br>
我輩だ、教官だ。雄の火竜と<BR>
雌の火竜、その行動は大きく<BR>
異なる。ハンターとしての経験<BR>
と技術をフル活用して短時間で<BR>
の討伐を目指すのだ！<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=004></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61009.mib" DOWNLOAD CSUM=26390 FSIZE=6264 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>１/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td>
	<B>
	<a href=#001 qname=m61012.mib>チャレンジクエスト　１２</a><BR>
	<a href=#002 qname=m61011.mib>チャレンジクエスト　１１</a><BR>
	<a href=#003 qname=m61010.mib>チャレンジクエスト　１０</a><BR>
	</B>
<tr><td bgcolor=green>
	<B><a href=#004 qname=m61009.mib>チャレンジクエスト　０９</a><BR></B>
<tr><td height=59 valign=top>
	<B>
	<a href=#005 qname=m61017.mib>モンハンフェスタ　０４</a><BR>
	<a href=#006 qname=m61008.mib>チャレンジクエスト　０８</a><BR>
	<a href=#007 qname=m61016.mib>モンハンフェスタ　０３</a><BR>
	</B>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>チャレンジクエスト　０９</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ４５００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> ３０分<br>
<font color=orange>指定地　：</font> 密林＜夜＞<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ１以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	チャレンジクエスト　０９
</B>
</td>
<td>
<B>
	★★★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
イャンガルルガ１頭の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>教官<br>
我輩だ、教官だ。イャンガルル<BR>
ガへの挑戦だな！奴は全ての<BR>
能力が高く、生半可な実力では<BR>
太刀打ち出来ないぞ。己の腕を<BR>
磨き上げて挑戦するのだ！<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=005></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61017.mib" DOWNLOAD CSUM=33766 FSIZE=1956 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>１/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td>
	<B>
	<a href=#001 qname=m61012.mib>チャレンジクエスト　１２</a><BR>
	<a href=#002 qname=m61011.mib>チャレンジクエスト　１１</a><BR>
	<a href=#003 qname=m61010.mib>チャレンジクエスト　１０</a><BR>
	<a href=#004 qname=m61009.mib>チャレンジクエスト　０９</a><BR>
	</B>
<tr><td bgcolor=green>
	<B><a href=#005 qname=m61017.mib>モンハンフェスタ　０４</a><BR></B>
<tr><td height=42 valign=top>
	<B>
	<a href=#006 qname=m61008.mib>チャレンジクエスト　０８</a><BR>
	<a href=#007 qname=m61016.mib>モンハンフェスタ　０３</a><BR>
	</B>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>モンハンフェスタ　０４</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ６０００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> １５分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ１以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	モンハンフェスタ　０４
</B>
</td>
<td>
<B>
	★★★★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ラージャン１頭の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>神秘的な大会運営者<br>
皆さん、これが最後です。<BR>
金色に輝く金獅子と対面し、<BR>
見事打ち倒して来て下さい。<BR>
ここまで勝ち残れたと言え、<BR>
油断は禁物です。ご武運を！<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=006></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61008.mib" DOWNLOAD CSUM=37244 FSIZE=1976 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>１/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td>
	<B>
	<a href=#001 qname=m61012.mib>チャレンジクエスト　１２</a><BR>
	<a href=#002 qname=m61011.mib>チャレンジクエスト　１１</a><BR>
	<a href=#003 qname=m61010.mib>チャレンジクエスト　１０</a><BR>
	<a href=#004 qname=m61009.mib>チャレンジクエスト　０９</a><BR>
	<a href=#005 qname=m61017.mib>モンハンフェスタ　０４</a><BR>
	</B>
<tr><td bgcolor=green>
	<B><a href=#006 qname=m61008.mib>チャレンジクエスト　０８</a><BR></B>
<tr><td height=25 valign=top>
	<B>
	<a href=#007 qname=m61016.mib>モンハンフェスタ　０３</a><BR>
	</B>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>チャレンジクエスト　０８</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ６０００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> ３０分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ４以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	チャレンジクエスト　０８
</B>
</td>
<td>
<B>
	★★★★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ティガレックス２頭の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>教官<br>
我輩だ、教官だ。今回はティガ<BR>
レックス、しかも２頭連続で相<BR>
手をして貰う。怒り状態では<BR>
手がつけられない。あらゆる手<BR>
を使って隙を作るのだ！<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=007></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61016.mib" DOWNLOAD CSUM=24180 FSIZE=4800 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>１/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td>
	<B>
	<a href=#001 qname=m61012.mib>チャレンジクエスト　１２</a><BR>
	<a href=#002 qname=m61011.mib>チャレンジクエスト　１１</a><BR>
	<a href=#003 qname=m61010.mib>チャレンジクエスト　１０</a><BR>
	<a href=#004 qname=m61009.mib>チャレンジクエスト　０９</a><BR>
	<a href=#005 qname=m61017.mib>モンハンフェスタ　０４</a><BR>
	<a href=#006 qname=m61008.mib>チャレンジクエスト　０８</a><BR>
	</B>
<tr><td bgcolor=green>
	<B><a href=#007 qname=m61016.mib>モンハンフェスタ　０３</a><BR></B>
<tr><td valign=top>
	<B>
	</B>
<tr><td height=8>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>モンハンフェスタ　０３</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ４５００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> １５分<br>
<font color=orange>指定地　：</font> 砂漠＜昼＞<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ１以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	モンハンフェスタ　０３
</B>
</td>
<td>
<B>
	★★★★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
テオ・テスカトル１体の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>豪腕の大会運営者<br>
ここが正念場だ！恐怖の古龍<BR>
を相手にハンターが<BR>
どこまで立ち向かえるか…！？<BR>
お前らの実力を、ここで示せ！<BR>
そして勝ち上がって来い！<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
