<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
<GAME-STYLE>
	"MOUSE=OFF",
	"SCROLL=OFF",
	"TITLE=OFF",
	"BACK=ON:DL_SELECT.PHP",
	"FORWARD=OFF",
	"CANCEL=OFF",
	"RELOAD=OFF",
	"CHOICE_MV=OFF",
	"LINK_U=OFF",
	"FRONT_LABEL=ON:2",
	"LB_LINK=DL_CMENU2.PHP",
	"RB_LINK=DL_CMENU1.PHP",
	"MOVE_CHAR=./GIF/rio.gif,82,52,1,1,0,40,-82,180",
	"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=#0DA5DE background=./GIF/BG.gif>
<!--480 x 272-->
<basefont size=2>
<B>

<a name=001></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61002.mib" DOWNLOAD CSUM=36421 FSIZE=2048 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>３/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td bgcolor=green>
	<B><a href=#001 qname=m61002.mib>チャレンジクエスト　０２</a><BR></B>
<tr><td height=110 valign=top>
	<B>
	<a href=#002 qname=m61001.mib>チャレンジクエスト　０１</a><BR>
	<BR>
	<BR>
	<BR>
	<BR>
	<BR>
	</B>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>チャレンジクエスト　０２</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ３０００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> ３０分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ１以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	チャレンジクエスト　０２
</B>
</td>
<td>
<B>
	★★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ダイミョウザザミ１匹の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>教官<br>
我輩だ、教官だ。今回の演習は<BR>
２匹の盾蟹のどちらか片方を<BR>
倒せばクエストクリアだ！<BR>
ペイントボールを上手く使って<BR>
片方に攻撃を集中させるのだ！<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=002></a>
<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61001.mib" DOWNLOAD CSUM=39130 FSIZE=3648 method=post>
<tr>
<td height=40 width=204 align=center valign=center>
	<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
	<tr>
	<td align=center>
		<B>３/３</B>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr><td>
	<B>
	<a href=#001 qname=m61002.mib>チャレンジクエスト　０２</a><BR>
	</B>
<tr><td bgcolor=green>
	<B><a href=#002 qname=m61001.mib>チャレンジクエスト　０１</a><BR></B>
<tr><td height=93 valign=top>
	<B>
	<BR>
	<BR>
	<BR>
	<BR>
	<BR>
	</B>
	<input type=image src="" name=submit width=0 height=0>
</tr>
</form>
</table>
</td>
<td width=241>
<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
<tr>
<td width=237 height=25 align=center valign=bottom>
	<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
	<tr>
	<td height=21 align=center valign=bottom>
		<font color=red><B>討伐クエスト</B></font>
	</td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
	<B>チャレンジクエスト　０１</B>
</td>
</tr>
<tr>
<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ３０００ｚ<br>
<font color=orange>契約金　：</font> ０ｚ<br>
<font color=orange>制限時間：</font> ３０分<br>
<font color=orange>指定地　：</font> 沼地＜夜＞<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ１以上<BR>
<BR>

</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO15.gif width=200 height=50 alt="Challenge"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
<tr>
<td colspan=2>
	<table cellspacing=0 cellpadding=0 width=468 height=21>
	<tr>
	<td height=8 ></td>
	</tr>
	<tr>
	<td width=8></td>
	<td width=452 height=21 background=./GIF/T_RED.gif>
	<B>
		　 　　<font color=red>討伐クエスト</font>
		　　　<font color=orange>クエストＬＶ：</font>
	</B>
	<td width=8></td>
	</tr>
	</table>
</td>
</tr>
<tr>
<td align=center>
<B>
	チャレンジクエスト　０１
</B>
</td>
<td>
<B>
	★★★
</B>
</td>
</tr>
<tr>
<td width=227 221 valign=top>
	<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ゲリョス１頭と<BR>
ゲリョス亜種１頭の討伐<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
	</TABLE>
</td>
<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>教官<br>
我輩だ、教官だ。ゲリョスを<BR>
２頭同時に相手にするのは得策<BR>
とは言えない！２手に分断する<BR>
か、攻撃を片方に集中させるか<BR>
…。道は一つではないぞ！<BR>
　　　　　　　　　　　　　　<br>
</B>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
