<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
<GAME-STYLE>
	"MOUSE=OFF",
	"SCROLL=OFF",
	"TITLE=OFF",
	"BACK=ON:DL_SELECT.PHP",
	"FORWARD=OFF",
	"CANCEL=OFF",
	"RELOAD=OFF",
	"CHOICE_MV=OFF",
	"LINK_U=OFF",
	"FRONT_LABEL=ON:2",
	"LB_LINK=DL_MENU4.PHP",
	"RB_LINK=DL_MENU2.PHP",
	"MOVE_CHAR=./GIF/rio.gif,82,52,1,1,0,40,-82,180",
	"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=#0DA5DE background=./GIF/BG.gif>
<!--480 x 272-->
<basefont size=2>
<B>

<a name=001></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60025.mib" DOWNLOAD CSUM=33147 FSIZE=1512 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>１/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td bgcolor=green>
		<B><a href=#001 qname=m60025.mib>鋼の来訪者</a><BR></B>
	<tr><td height=110 valign=top>
		<B>
		<a href=#002 qname=m60022.mib>天と地の怒り</a><BR>
		<a href=#003 qname=m60019.mib>金色の雷帝</a><BR>
		<a href=#004 qname=m60018.mib>蛇竜の巣窟</a><BR>
		<a href=#005 qname=m60010.mib>スカーフェイス</a><BR>
		<a href=#006 qname=m60012.mib>双璧！黒き熱風</a><BR>
		<a href=#007 qname=m60026.mib>電撃祭　幻の決戦</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=red><B>討伐クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>鋼の来訪者</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> １０５００ｚ<br>
<font color=orange>契約金　：</font> ８７０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 街<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ６以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_RED.gif>
		<B>
			　 　　<font color=red>討伐クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		鋼の来訪者
	</B>
	</td>
	<td>
	<B>
		★★★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
クシャルダオラ１体の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>ギルドマスター<br>
非常事態じゃ！ワシらの街に褐<BR>
色のクシャルダオラが迫ってお<BR>
る。力に自信のある者は、速や<BR>
かにこちらへ来てもらいたい。<BR>
おヌシの力で街を救ってくれ！<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=002></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60022.mib" DOWNLOAD CSUM=35849 FSIZE=1464 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>１/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60025.mib>鋼の来訪者</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#002 qname=m60022.mib>天と地の怒り</a><BR></B>
	<tr><td height=93 valign=top>
		<B>
		<a href=#003 qname=m60019.mib>金色の雷帝</a><BR>
		<a href=#004 qname=m60018.mib>蛇竜の巣窟</a><BR>
		<a href=#005 qname=m60010.mib>スカーフェイス</a><BR>
		<a href=#006 qname=m60012.mib>双璧！黒き熱風</a><BR>
		<a href=#007 qname=m60026.mib>電撃祭　幻の決戦</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>天と地の怒り</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ９９００ｚ<br>
<font color=orange>契約金　：</font> ８３０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ４以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		天と地の怒り
	</B>
	</td>
	<td>
	<B>
		★★★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
リオレウス希少種１頭と<BR>
リオレイア希少種１頭の狩猟<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>ココット村の村長<br>
皆の衆、久しぶりじゃの。<BR>
これは、ワシからの挑戦じゃ！<BR>
巨大な２頭の飛竜、リオレウス<BR>
とリオレイア。果たしてヌシは<BR>
両者を屈服させられるかな？<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=003></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60019.mib" DOWNLOAD CSUM=22054 FSIZE=1292 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>１/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60025.mib>鋼の来訪者</a><BR>
		<a href=#002 qname=m60022.mib>天と地の怒り</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#003 qname=m60019.mib>金色の雷帝</a><BR></B>
	<tr><td height=76 valign=top>
		<B>
		<a href=#004 qname=m60018.mib>蛇竜の巣窟</a><BR>
		<a href=#005 qname=m60010.mib>スカーフェイス</a><BR>
		<a href=#006 qname=m60012.mib>双璧！黒き熱風</a><BR>
		<a href=#007 qname=m60026.mib>電撃祭　幻の決戦</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>金色の雷帝</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ９０００ｚ<br>
<font color=orange>契約金　：</font> ７５０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ４以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		金色の雷帝
	</B>
	</td>
	<td>
	<B>
		★★★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ラージャン１頭の狩猟<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>闘技場の運営者<br>
た…たた…た…大変です！<BR>
私の闘技場が黒いモンスターに<BR>
占拠されてしまいました！この<BR>
ままでは闘技場が使えません。<BR>
早くあいつを狩ってください！<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=004></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60018.mib" DOWNLOAD CSUM=26994 FSIZE=1524 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>１/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60025.mib>鋼の来訪者</a><BR>
		<a href=#002 qname=m60022.mib>天と地の怒り</a><BR>
		<a href=#003 qname=m60019.mib>金色の雷帝</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#004 qname=m60018.mib>蛇竜の巣窟</a><BR></B>
	<tr><td height=59 valign=top>
		<B>
		<a href=#005 qname=m60010.mib>スカーフェイス</a><BR>
		<a href=#006 qname=m60012.mib>双璧！黒き熱風</a><BR>
		<a href=#007 qname=m60026.mib>電撃祭　幻の決戦</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=red><B>討伐クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>蛇竜の巣窟</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ６０００ｚ<br>
<font color=orange>契約金　：</font> ５００ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ４以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_RED.gif>
		<B>
			　 　　<font color=red>討伐クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		蛇竜の巣窟
	</B>
	</td>
	<td>
	<B>
		★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ガブラス１５頭の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>闘技場の運営者<br>
ハンターが己の腕前を披露する<BR>
闘技場！今回の相手は空を占拠<BR>
するガブラスたちです！毒だら<BR>
けの闘技場で、あなたは見事に<BR>
生き残ることができますか？<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=005></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60010.mib" DOWNLOAD CSUM=36832 FSIZE=6124 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>１/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60025.mib>鋼の来訪者</a><BR>
		<a href=#002 qname=m60022.mib>天と地の怒り</a><BR>
		<a href=#003 qname=m60019.mib>金色の雷帝</a><BR>
		<a href=#004 qname=m60018.mib>蛇竜の巣窟</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#005 qname=m60010.mib>スカーフェイス</a><BR></B>
	<tr><td height=42 valign=top>
		<B>
		<a href=#006 qname=m60012.mib>双璧！黒き熱風</a><BR>
		<a href=#007 qname=m60026.mib>電撃祭　幻の決戦</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>スカーフェイス</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ６６００ｚ<br>
<font color=orange>契約金　：</font> ５５０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 密林＜夜＞<br>
<font color=orange>特殊条件：</font><br>
なし<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		スカーフェイス
	</B>
	</td>
	<td>
	<B>
		★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
イャンガルルガ１頭の狩猟<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>十字傷の男<br>
俺と同じ傷を持つ飛竜を密林ま<BR>
で追い詰めたんだが、無傷では<BR>
いられなくてな…俺の身体も限<BR>
界らしい。頼む、動けない俺の<BR>
代わりにあいつを狩ってくれ！<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=006></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60012.mib" DOWNLOAD CSUM=28067 FSIZE=1416 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>１/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60025.mib>鋼の来訪者</a><BR>
		<a href=#002 qname=m60022.mib>天と地の怒り</a><BR>
		<a href=#003 qname=m60019.mib>金色の雷帝</a><BR>
		<a href=#004 qname=m60018.mib>蛇竜の巣窟</a><BR>
		<a href=#005 qname=m60010.mib>スカーフェイス</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#006 qname=m60012.mib>双璧！黒き熱風</a><BR></B>
	<tr><td height=25 valign=top>
		<B>
		<a href=#007 qname=m60026.mib>電撃祭　幻の決戦</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>双璧！黒き熱風</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ９０００ｚ<br>
<font color=orange>契約金　：</font> ７５０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ４以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		双璧！黒き熱風
	</B>
	</td>
	<td>
	<B>
		★★★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
グラビモス亜種２頭の狩猟<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>闘技場の運営者<br>
ハンターが己の腕前を披露する<BR>
闘技場！今回は世にも恐ろしい<BR>
黒鎧竜を闘技場に放しました！<BR>
しかも２頭！ハンターの皆さん<BR>
この難関を突破できますか？<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=007></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60026.mib" DOWNLOAD CSUM=20042 FSIZE=1192 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>１/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60025.mib>鋼の来訪者</a><BR>
		<a href=#002 qname=m60022.mib>天と地の怒り</a><BR>
		<a href=#003 qname=m60019.mib>金色の雷帝</a><BR>
		<a href=#004 qname=m60018.mib>蛇竜の巣窟</a><BR>
		<a href=#005 qname=m60010.mib>スカーフェイス</a><BR>
		<a href=#006 qname=m60012.mib>双璧！黒き熱風</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#007 qname=m60026.mib>電撃祭　幻の決戦</a><BR></B>
	<tr><td valign=top>
		<B>
		</B>
	<tr><td height=8>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=red><B>討伐クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>電撃祭　幻の決戦</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ８１００ｚ<br>
<font color=orange>契約金　：</font> ６７０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 決戦場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ４以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_RED.gif>
		<B>
			　 　　<font color=red>討伐クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		電撃祭　幻の決戦
	</B>
	</td>
	<td>
	<B>
		★★★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
キリン１頭の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>電撃ＰＳ　ポリタン<br>
ポリタンからのスンゲー挑戦！<BR>
渦巻く炎の中で立ちはだかるの<BR>
は白き幻獣だ！決戦に勝利し、<BR>
スンゲー報酬を手に入れよう！<BR>
今回の相手は…大きい！？<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
