<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
<GAME-STYLE>
	"MOUSE=OFF",
	"SCROLL=OFF",
	"TITLE=OFF",
	"BACK=ON:DL_SELECT.PHP",
	"FORWARD=OFF",
	"CANCEL=OFF",
	"RELOAD=OFF",
	"CHOICE_MV=OFF",
	"LINK_U=OFF",
	"FRONT_LABEL=ON:2",
	"LB_LINK=DL_MENU1.PHP",
	"RB_LINK=DL_MENU3.PHP",
	"MOVE_CHAR=./GIF/rio.gif,82,52,1,1,0,40,-82,180",
	"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=#0DA5DE background=./GIF/BG.gif>
<!--480 x 272-->
<basefont size=2>
<B>

<a name=001></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60008.mib" DOWNLOAD CSUM=36188 FSIZE=1448 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>２/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td bgcolor=green>
		<B><a href=#001 qname=m60008.mib>最強の矛、最強の盾</a><BR></B>
	<tr><td height=110 valign=top>
		<B>
		<a href=#002 qname=m60023.mib>神秘の怪鳥</a><BR>
		<a href=#003 qname=m60007.mib>緑萌ゆる季節</a><BR>
		<a href=#004 qname=m60020.mib>ファミ通　奇面族の宴</a><BR>
		<a href=#005 qname=m60017.mib>祖龍</a><BR>
		<a href=#006 qname=m60027.mib>「マ）王　片角のマオウ</a><BR>
		<a href=#007 qname=m60006.mib>火山地帯に潜む罠</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>最強の矛、最強の盾</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ６０００ｚ<br>
<font color=orange>契約金　：</font> ５００ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
なし<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		最強の矛、最強の盾
	</B>
	</td>
	<td>
	<B>
		★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ダイミョウザザミ１匹と<BR>
ショウグンギザミ１匹の狩猟<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>闘技場の運営者<br>
ハンターが己の腕前を披露する<BR>
闘技場！今回は性質の違う２匹<BR>
の大蟹を闘技場に放しました！<BR>
個人参加や腕試しも大歓迎！<BR>
振るってご参加ください！<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=002></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60023.mib" DOWNLOAD CSUM=56213 FSIZE=6340 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>２/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60008.mib>最強の矛、最強の盾</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#002 qname=m60023.mib>神秘の怪鳥</a><BR></B>
	<tr><td height=93 valign=top>
		<B>
		<a href=#003 qname=m60007.mib>緑萌ゆる季節</a><BR>
		<a href=#004 qname=m60020.mib>ファミ通　奇面族の宴</a><BR>
		<a href=#005 qname=m60017.mib>祖龍</a><BR>
		<a href=#006 qname=m60027.mib>「マ）王　片角のマオウ</a><BR>
		<a href=#007 qname=m60006.mib>火山地帯に潜む罠</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>神秘の怪鳥</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ７２００ｚ<br>
<font color=orange>契約金　：</font> ６００ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 密林＜夜＞<br>
<font color=orange>特殊条件：</font><br>
なし<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		神秘の怪鳥
	</B>
	</td>
	<td>
	<B>
		★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
タイムアップもしくは、<BR>
ネコタクチケットの納品<BR>
<BR>
<font color=orange>失敗条件：</font><br>
２頭以上を狩猟せずにタイム<BR>
アップ、もしくは報酬金ゼロ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>ハンターズギルド<br>
密林地帯の村から救難信号を受<BR>
けました。奇妙な怪鳥の群れに<BR>
襲われ畑に被害が出ている模様<BR>
です。至急現場へ向かい、事態<BR>
の収拾に当たってください。<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=003></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60007.mib" DOWNLOAD CSUM=16392 FSIZE=6472 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>２/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60008.mib>最強の矛、最強の盾</a><BR>
		<a href=#002 qname=m60023.mib>神秘の怪鳥</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#003 qname=m60007.mib>緑萌ゆる季節</a><BR></B>
	<tr><td height=76 valign=top>
		<B>
		<a href=#004 qname=m60020.mib>ファミ通　奇面族の宴</a><BR>
		<a href=#005 qname=m60017.mib>祖龍</a><BR>
		<a href=#006 qname=m60027.mib>「マ）王　片角のマオウ</a><BR>
		<a href=#007 qname=m60006.mib>火山地帯に潜む罠</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>緑萌ゆる季節</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ４５００ｚ<br>
<font color=orange>契約金　：</font> ３８０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 森丘<br>
<font color=orange>特殊条件：</font><br>
なし<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		緑萌ゆる季節
	</B>
	</td>
	<td>
	<B>
		★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
タイムアップもしくは、<BR>
ネコタクチケットの納品<BR>
<BR>
<font color=orange>失敗条件：</font><br>
２頭以上を狩猟せずにタイム<BR>
アップ、もしくは報酬金ゼロ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>兄の帰りを待つ女性<br>
今度、久しぶりに兄が帰郷する<BR>
のですが、最近村の周りの丘陵<BR>
地帯に多数のリオレイアが現れ<BR>
て困っています。兄が帰ってく<BR>
る前に何とかしてください。<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=004></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60020.mib" DOWNLOAD CSUM=31500 FSIZE=1728 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>２/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60008.mib>最強の矛、最強の盾</a><BR>
		<a href=#002 qname=m60023.mib>神秘の怪鳥</a><BR>
		<a href=#003 qname=m60007.mib>緑萌ゆる季節</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#004 qname=m60020.mib>ファミ通　奇面族の宴</a><BR></B>
	<tr><td height=59 valign=top>
		<B>
		<a href=#005 qname=m60017.mib>祖龍</a><BR>
		<a href=#006 qname=m60027.mib>「マ）王　片角のマオウ</a><BR>
		<a href=#007 qname=m60006.mib>火山地帯に潜む罠</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=red><B>討伐クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>ファミ通　奇面族の宴</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ６０００ｚ<br>
<font color=orange>契約金　：</font> ５００ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 闘技場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ４以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_RED.gif>
		<B>
			　 　　<font color=red>討伐クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		ファミ通　奇面族の宴
	</B>
	</td>
	<td>
	<B>
		★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
チャチャブー１５匹の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>ファミ通ＭＨＰ攻略班<br>
ファミ通が秘密のパーティーを<BR>
開催します。参加者は鋼の意思<BR>
とヘコたれない根性を持参の上<BR>
闘技場までお越しください。<BR>
ご来訪をお待ちしております。<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=005></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60017.mib" DOWNLOAD CSUM=2336 FSIZE=3924 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>２/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60008.mib>最強の矛、最強の盾</a><BR>
		<a href=#002 qname=m60023.mib>神秘の怪鳥</a><BR>
		<a href=#003 qname=m60007.mib>緑萌ゆる季節</a><BR>
		<a href=#004 qname=m60020.mib>ファミ通　奇面族の宴</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#005 qname=m60017.mib>祖龍</a><BR></B>
	<tr><td height=42 valign=top>
		<B>
		<a href=#006 qname=m60027.mib>「マ）王　片角のマオウ</a><BR>
		<a href=#007 qname=m60006.mib>火山地帯に潜む罠</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_PPL.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=#ff60ff><B>特殊クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>祖龍</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ３６０００ｚ<br>
<font color=orange>契約金　：</font> ３０００ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 塔<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ６以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_PPL.gif>
		<B>
			　 　　<font color=#ff60ff>特殊クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		祖龍
	</B>
	</td>
	<td>
	<B>
		★★★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ミラボレアス１体の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>謎の赤衣の男<br>
フフフ…刻は満ちた！さぁ、舞<BR>
踏会へ招待しよう。とびきりの<BR>
衣装を着て、とびきりの得物を<BR>
もっておいで。でなければ王の<BR>
相手はつとまらないのでね。<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=006></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60027.mib" DOWNLOAD CSUM=61574 FSIZE=6240 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>２/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60008.mib>最強の矛、最強の盾</a><BR>
		<a href=#002 qname=m60023.mib>神秘の怪鳥</a><BR>
		<a href=#003 qname=m60007.mib>緑萌ゆる季節</a><BR>
		<a href=#004 qname=m60020.mib>ファミ通　奇面族の宴</a><BR>
		<a href=#005 qname=m60017.mib>祖龍</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#006 qname=m60027.mib>「マ）王　片角のマオウ</a><BR></B>
	<tr><td height=25 valign=top>
		<B>
		<a href=#007 qname=m60006.mib>火山地帯に潜む罠</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>「マ）王　片角のマオウ</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ９０００ｚ<br>
<font color=orange>契約金　：</font> ７５０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 砂漠＜昼＞<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ４以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		「マ）王　片角のマオウ
	</B>
	</td>
	<td>
	<B>
		★★★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ディアブロス１頭の狩猟<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>ギレル<br>
角竜の討伐…。戦ってみたが、<BR>
返り討ちにあって動けない。ヤ<BR>
ツを倒してある治療薬を作るた<BR>
めにも、勇気ある者はヤツを倒<BR>
すため名乗りを上げてくれ。<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=007></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60006.mib" DOWNLOAD CSUM=17169 FSIZE=4612 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>２/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60008.mib>最強の矛、最強の盾</a><BR>
		<a href=#002 qname=m60023.mib>神秘の怪鳥</a><BR>
		<a href=#003 qname=m60007.mib>緑萌ゆる季節</a><BR>
		<a href=#004 qname=m60020.mib>ファミ通　奇面族の宴</a><BR>
		<a href=#005 qname=m60017.mib>祖龍</a><BR>
		<a href=#006 qname=m60027.mib>「マ）王　片角のマオウ</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#007 qname=m60006.mib>火山地帯に潜む罠</a><BR></B>
	<tr><td valign=top>
		<B>
		</B>
	<tr><td height=8>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>火山地帯に潜む罠</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ３６００ｚ<br>
<font color=orange>契約金　：</font> ３００ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 火山＜昼＞<br>
<font color=orange>特殊条件：</font><br>
なし<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		火山地帯に潜む罠
	</B>
	</td>
	<td>
	<B>
		★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
バサルモス２頭の狩猟<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>一攫千金を狙う男<br>
高価な鉱石を狙って火山に来た<BR>
んだがイヤな気配がずっとしや<BR>
がる。…誰かに見られている？<BR>
…そんな気配を複数感じたぜ。<BR>
気配の正体をつきとめてくれ！<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
