<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
<GAME-STYLE>
	"MOUSE=OFF",
	"SCROLL=OFF",
	"TITLE=OFF",
	"BACK=ON:DL_SELECT.PHP",
	"FORWARD=OFF",
	"CANCEL=OFF",
	"RELOAD=OFF",
	"CHOICE_MV=OFF",
	"LINK_U=OFF",
	"FRONT_LABEL=ON:2",
	"LB_LINK=DL_MENU3.PHP",
	"RB_LINK=DL_MENU1.PHP",
	"MOVE_CHAR=./GIF/rio.gif,82,52,1,1,0,40,-82,180",
	"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=#0DA5DE background=./GIF/BG.gif>
<!--480 x 272-->
<basefont size=2>
<B>

<a name=001></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60005.mib" DOWNLOAD CSUM=24308 FSIZE=4584 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>４/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td bgcolor=green>
		<B><a href=#001 qname=m60005.mib>電撃祭　２ｎｄ！</a><BR></B>
	<tr><td height=110 valign=top>
		<B>
		<a href=#002 qname=m60024.mib>雲霞の如く</a><BR>
		<a href=#003 qname=m60015.mib>シュレイドの伝説</a><BR>
		<a href=#004 qname=m60014.mib>猿蟹合戦！「猿ノ巻」</a><BR>
		<a href=#005 qname=m60001.mib>アメザリ釣り大会！</a><BR>
		<a href=#006 qname=m60004.mib>ファミ通　桃毛獣連続狩猟</a><BR>
		<a href=#007 qname=m60013.mib>猿蟹合戦！「蟹ノ巻」</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>電撃祭　２ｎｄ！</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ４５００ｚ<br>
<font color=orange>契約金　：</font> ３８０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 沼地＜夜＞<br>
<font color=orange>特殊条件：</font><br>
なし<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		電撃祭　２ｎｄ！
	</B>
	</td>
	<td>
	<B>
		★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
フルフル２頭の狩猟<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>電撃ＰＳ　ポリタン<br>
ポリタンからのスンゴい挑戦！<BR>
あのハンマーを手にすることが<BR>
できるのは、電撃を放つあの飛<BR>
竜を２頭倒せる者だけだ！<BR>
今回の相手はちょっと違う！？<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=002></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60024.mib" DOWNLOAD CSUM=63717 FSIZE=9848 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>４/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60005.mib>電撃祭　２ｎｄ！</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#002 qname=m60024.mib>雲霞の如く</a><BR></B>
	<tr><td height=93 valign=top>
		<B>
		<a href=#003 qname=m60015.mib>シュレイドの伝説</a><BR>
		<a href=#004 qname=m60014.mib>猿蟹合戦！「猿ノ巻」</a><BR>
		<a href=#005 qname=m60001.mib>アメザリ釣り大会！</a><BR>
		<a href=#006 qname=m60004.mib>ファミ通　桃毛獣連続狩猟</a><BR>
		<a href=#007 qname=m60013.mib>猿蟹合戦！「蟹ノ巻」</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=red><B>討伐クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>雲霞の如く</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ４５００ｚ<br>
<font color=orange>契約金　：</font> ３８０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 密林＜昼＞<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ４以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_RED.gif>
		<B>
			　 　　<font color=red>討伐クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		雲霞の如く
	</B>
	</td>
	<td>
	<B>
		★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ランゴスタ５０匹の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>イライラ顔の村娘<br>
最近うちの村の周りが騒がしい<BR>
と思ったら、おっきな虫が大発<BR>
生してるじゃない！夜もうるさ<BR>
くて眠れないわ！ハンターなん<BR>
でしょ？早く何とかしなさい！<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=003></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60015.mib" DOWNLOAD CSUM=22297 FSIZE=1224 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>４/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60005.mib>電撃祭　２ｎｄ！</a><BR>
		<a href=#002 qname=m60024.mib>雲霞の如く</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#003 qname=m60015.mib>シュレイドの伝説</a><BR></B>
	<tr><td height=76 valign=top>
		<B>
		<a href=#004 qname=m60014.mib>猿蟹合戦！「猿ノ巻」</a><BR>
		<a href=#005 qname=m60001.mib>アメザリ釣り大会！</a><BR>
		<a href=#006 qname=m60004.mib>ファミ通　桃毛獣連続狩猟</a><BR>
		<a href=#007 qname=m60013.mib>猿蟹合戦！「蟹ノ巻」</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_PPL.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=#ff60ff><B>特殊クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>シュレイドの伝説</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ３６０００ｚ<br>
<font color=orange>契約金　：</font> ３０００ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> シュレイド城<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ６以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_PPL.gif>
		<B>
			　 　　<font color=#ff60ff>特殊クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		シュレイドの伝説
	</B>
	</td>
	<td>
	<B>
		★★★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ミラボレアス１体の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>ギルドマスター<br>
古シュレイド王国の城跡で黒龍<BR>
ミラボレアスの存在が確認され<BR>
た！放っておけば国一つが亡び<BR>
るやもしれぬ…彼奴の討伐にお<BR>
ヌシらの力を貸してくれぃ！<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=004></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60014.mib" DOWNLOAD CSUM=26284 FSIZE=1520 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>４/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60005.mib>電撃祭　２ｎｄ！</a><BR>
		<a href=#002 qname=m60024.mib>雲霞の如く</a><BR>
		<a href=#003 qname=m60015.mib>シュレイドの伝説</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#004 qname=m60014.mib>猿蟹合戦！「猿ノ巻」</a><BR></B>
	<tr><td height=59 valign=top>
		<B>
		<a href=#005 qname=m60001.mib>アメザリ釣り大会！</a><BR>
		<a href=#006 qname=m60004.mib>ファミ通　桃毛獣連続狩猟</a><BR>
		<a href=#007 qname=m60013.mib>猿蟹合戦！「蟹ノ巻」</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>猿蟹合戦！「猿ノ巻」</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ７５００ｚ<br>
<font color=orange>契約金　：</font> ６２０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ４以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		猿蟹合戦！「猿ノ巻」
	</B>
	</td>
	<td>
	<B>
		★★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ドドブランゴ１頭の狩猟<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>闘技場の運営者<br>
ハンターが己の腕前を披露する<BR>
闘技場！今回の相手はドドブラ<BR>
ンゴ！ただし、周囲にはヤオザ<BR>
ミ、ガミザミがワラワラと…！<BR>
さぁ、見事クリアできますか？<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=005></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60001.mib" DOWNLOAD CSUM=41939 FSIZE=5616 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>４/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60005.mib>電撃祭　２ｎｄ！</a><BR>
		<a href=#002 qname=m60024.mib>雲霞の如く</a><BR>
		<a href=#003 qname=m60015.mib>シュレイドの伝説</a><BR>
		<a href=#004 qname=m60014.mib>猿蟹合戦！「猿ノ巻」</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#005 qname=m60001.mib>アメザリ釣り大会！</a><BR></B>
	<tr><td height=42 valign=top>
		<B>
		<a href=#006 qname=m60004.mib>ファミ通　桃毛獣連続狩猟</a><BR>
		<a href=#007 qname=m60013.mib>猿蟹合戦！「蟹ノ巻」</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_GRN.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=lime><B>採取クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>アメザリ釣り大会！</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ３０００ｚ<br>
<font color=orange>契約金　：</font> ２５０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 砂漠＜昼＞<br>
<font color=orange>特殊条件：</font><br>
なし<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_GRN.gif>
		<B>
			　 　　<font color=lime>採取クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		アメザリ釣り大会！
	</B>
	</td>
	<td>
	<B>
		★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
黄金魚５匹の納品<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>アメリカザリガニ<br>
アメリカザリガニから挑戦状！<BR>
時間内に砂漠のどこかにいる黄<BR>
金魚を５匹釣って納品すれば<BR>
クエスト成功！クリアできたら<BR>
スゴい防具が手に入るかも！？<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=006></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60004.mib" DOWNLOAD CSUM=60111 FSIZE=5936 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>４/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60005.mib>電撃祭　２ｎｄ！</a><BR>
		<a href=#002 qname=m60024.mib>雲霞の如く</a><BR>
		<a href=#003 qname=m60015.mib>シュレイドの伝説</a><BR>
		<a href=#004 qname=m60014.mib>猿蟹合戦！「猿ノ巻」</a><BR>
		<a href=#005 qname=m60001.mib>アメザリ釣り大会！</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#006 qname=m60004.mib>ファミ通　桃毛獣連続狩猟</a><BR></B>
	<tr><td height=25 valign=top>
		<B>
		<a href=#007 qname=m60013.mib>猿蟹合戦！「蟹ノ巻」</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>ファミ通　桃毛獣連続狩猟</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ３０００ｚ<br>
<font color=orange>契約金　：</font> ２５０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 沼地＜昼＞<br>
<font color=orange>特殊条件：</font><br>
ガンランス・限定クエスト<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		ファミ通　桃毛獣連続狩猟
	</B>
	</td>
	<td>
	<B>
		★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
タイムアップもしくは、<BR>
ネコタクチケットの納品<BR>
<BR>
<font color=orange>失敗条件：</font><br>
２頭以上を狩猟せずにタイム<BR>
アップ、もしくは報酬金ゼロ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>ファミ通ＭＨＰ攻略班<br>
沼地に続々と現れるババコンガ<BR>
を討伐しまくれ！２頭以上狩猟<BR>
してタイムアップかネコタクチ<BR>
ケット納品でクリアだ。ただし<BR>
武器はガンランス限定！！<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=007></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60013.mib" DOWNLOAD CSUM=29091 FSIZE=1536 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>４/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60005.mib>電撃祭　２ｎｄ！</a><BR>
		<a href=#002 qname=m60024.mib>雲霞の如く</a><BR>
		<a href=#003 qname=m60015.mib>シュレイドの伝説</a><BR>
		<a href=#004 qname=m60014.mib>猿蟹合戦！「猿ノ巻」</a><BR>
		<a href=#005 qname=m60001.mib>アメザリ釣り大会！</a><BR>
		<a href=#006 qname=m60004.mib>ファミ通　桃毛獣連続狩猟</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#007 qname=m60013.mib>猿蟹合戦！「蟹ノ巻」</a><BR></B>
	<tr><td valign=top>
		<B>
		</B>
	<tr><td height=8>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>猿蟹合戦！「蟹ノ巻」</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ４２００ｚ<br>
<font color=orange>契約金　：</font> ３５０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
なし<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		猿蟹合戦！「蟹ノ巻」
	</B>
	</td>
	<td>
	<B>
		★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ダイミョウザザミ１匹の狩猟<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>闘技場の運営者<br>
ハンターが己の腕前を披露する<BR>
闘技場！今回の相手は赤い盾蟹<BR>
です。周りにいるコンガに気を<BR>
つけて、討伐を果たしてくださ<BR>
い。ご参加お待ちしています。<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
