<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
<GAME-STYLE>
	"MOUSE=OFF",
	"SCROLL=OFF",
	"TITLE=OFF",
	"BACK=ON:DL_SELECT.PHP",
	"FORWARD=OFF",
	"CANCEL=OFF",
	"RELOAD=OFF",
	"CHOICE_MV=OFF",
	"LINK_U=OFF",
	"FRONT_LABEL=ON:2",
	"LB_LINK=DL_MENU2.PHP",
	"RB_LINK=DL_MENU4.PHP",
	"MOVE_CHAR=./GIF/rio.gif,82,52,1,1,0,40,-82,180",
	"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=#0DA5DE background=./GIF/BG.gif>
<!--480 x 272-->
<basefont size=2>
<B>

<a name=001></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60003.mib" DOWNLOAD CSUM=20833 FSIZE=1412 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>３/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td bgcolor=green>
		<B><a href=#001 qname=m60003.mib>白黒つけるぜ！闘技場！</a><BR></B>
	<tr><td height=110 valign=top>
		<B>
		<a href=#002 qname=m60021.mib>光と毒の狂騒曲</a><BR>
		<a href=#003 qname=m60016.mib>紅の災厄</a><BR>
		<a href=#004 qname=m60028.mib>ＪＵＭＰ　炎帝の凱旋</a><BR>
		<a href=#005 qname=m60011.mib>ファミ通　２頭の女王</a><BR>
		<a href=#006 qname=m60009.mib>怪鳥の嵐！</a><BR>
		<a href=#007 qname=m60002.mib>雨夜のエッグシーフ！</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=red><B>討伐クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>白黒つけるぜ！闘技場！</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ２１００ｚ<br>
<font color=orange>契約金　：</font> １５０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 闘技場<br>
<font color=orange>特殊条件：</font><br>
なし<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_RED.gif>
		<B>
			　 　　<font color=red>討伐クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		白黒つけるぜ！闘技場！
	</B>
	</td>
	<td>
	<B>
		★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
アイルー２０匹の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>獣人族の勇者<br>
ハンター共への挑戦状だニャ！<BR>
いつもやられている仲間の分も<BR>
含めて、闘技場で恐ろしい目に<BR>
あわせてやるから、度胸のある<BR>
ヤツはかかってくるのニャー！<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=002></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60021.mib" DOWNLOAD CSUM=22786 FSIZE=1372 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>３/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60003.mib>白黒つけるぜ！闘技場！</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#002 qname=m60021.mib>光と毒の狂騒曲</a><BR></B>
	<tr><td height=93 valign=top>
		<B>
		<a href=#003 qname=m60016.mib>紅の災厄</a><BR>
		<a href=#004 qname=m60028.mib>ＪＵＭＰ　炎帝の凱旋</a><BR>
		<a href=#005 qname=m60011.mib>ファミ通　２頭の女王</a><BR>
		<a href=#006 qname=m60009.mib>怪鳥の嵐！</a><BR>
		<a href=#007 qname=m60002.mib>雨夜のエッグシーフ！</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>光と毒の狂騒曲</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ５１００ｚ<br>
<font color=orange>契約金　：</font> ４２０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
なし<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		光と毒の狂騒曲
	</B>
	</td>
	<td>
	<B>
		★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ゲリョス２頭の狩猟<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>闘技場の運営者<br>
ハンターが己の腕前を披露する<BR>
闘技場！今回の相手は閃光を発<BR>
する毒怪鳥です！しかも１匹で<BR>
はありません！さぁ、存分にそ<BR>
の力を我々に見せてください。<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=003></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60016.mib" DOWNLOAD CSUM=19485 FSIZE=1200 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>３/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60003.mib>白黒つけるぜ！闘技場！</a><BR>
		<a href=#002 qname=m60021.mib>光と毒の狂騒曲</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#003 qname=m60016.mib>紅の災厄</a><BR></B>
	<tr><td height=76 valign=top>
		<B>
		<a href=#004 qname=m60028.mib>ＪＵＭＰ　炎帝の凱旋</a><BR>
		<a href=#005 qname=m60011.mib>ファミ通　２頭の女王</a><BR>
		<a href=#006 qname=m60009.mib>怪鳥の嵐！</a><BR>
		<a href=#007 qname=m60002.mib>雨夜のエッグシーフ！</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_PPL.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=#ff60ff><B>特殊クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>紅の災厄</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ３６０００ｚ<br>
<font color=orange>契約金　：</font> ３０００ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 決戦場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ６以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_PPL.gif>
		<B>
			　 　　<font color=#ff60ff>特殊クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		紅の災厄
	</B>
	</td>
	<td>
	<B>
		★★★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
ミラボレアス１体の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>ギルドの大老<br>
ミラボレアス…その者の怒りは<BR>
大地を震わし、天をも焦がす…<BR>
最早、後はない。勇なる者よ！<BR>
この声が届くのならば、怒りを<BR>
鎮め、紅の闇を祓ってくれ！<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=004></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60028.mib" DOWNLOAD CSUM=36498 FSIZE=1528 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>３/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60003.mib>白黒つけるぜ！闘技場！</a><BR>
		<a href=#002 qname=m60021.mib>光と毒の狂騒曲</a><BR>
		<a href=#003 qname=m60016.mib>紅の災厄</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#004 qname=m60028.mib>ＪＵＭＰ　炎帝の凱旋</a><BR></B>
	<tr><td height=59 valign=top>
		<B>
		<a href=#005 qname=m60011.mib>ファミ通　２頭の女王</a><BR>
		<a href=#006 qname=m60009.mib>怪鳥の嵐！</a><BR>
		<a href=#007 qname=m60002.mib>雨夜のエッグシーフ！</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_RED.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=red><B>討伐クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>ＪＵＭＰ　炎帝の凱旋</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> １２０００ｚ<br>
<font color=orange>契約金　：</font> １０００ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 街<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ６以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_RED.gif>
		<B>
			　 　　<font color=red>討伐クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		ＪＵＭＰ　炎帝の凱旋
	</B>
	</td>
	<td>
	<B>
		★★★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
テオ・テスカトル１体の討伐<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>隻眼黒髭の男<br>
街は今、炎王龍によって蹂躙さ<BR>
れようとしている。そこでだ…<BR>
どうだ、俺にお前が街を救うと<BR>
ころを見せてはくれねぇか？<BR>
勿論、報酬は期待していいぜ。<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=005></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60011.mib" DOWNLOAD CSUM=30298 FSIZE=1416 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>３/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60003.mib>白黒つけるぜ！闘技場！</a><BR>
		<a href=#002 qname=m60021.mib>光と毒の狂騒曲</a><BR>
		<a href=#003 qname=m60016.mib>紅の災厄</a><BR>
		<a href=#004 qname=m60028.mib>ＪＵＭＰ　炎帝の凱旋</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#005 qname=m60011.mib>ファミ通　２頭の女王</a><BR></B>
	<tr><td height=42 valign=top>
		<B>
		<a href=#006 qname=m60009.mib>怪鳥の嵐！</a><BR>
		<a href=#007 qname=m60002.mib>雨夜のエッグシーフ！</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>ファミ通　２頭の女王</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ６０００ｚ<br>
<font color=orange>契約金　：</font> ５００ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 大闘技場<br>
<font color=orange>特殊条件：</font><br>
参加資格はＨＲ４以上<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		ファミ通　２頭の女王
	</B>
	</td>
	<td>
	<B>
		★★★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
リオレイア１頭と<BR>
リオレイア亜種１頭の狩猟<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>ファミ通ＭＨＰ攻略班<br>
ファミ通からの挑戦状！<BR>
闘技場に舞い降りた２頭のリオ<BR>
レイア！キミは同時に相手にす<BR>
ることができるか？クリアでき<BR>
たら素敵なチケットを大進呈！<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=006></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60009.mib" DOWNLOAD CSUM=61935 FSIZE=5348 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>３/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60003.mib>白黒つけるぜ！闘技場！</a><BR>
		<a href=#002 qname=m60021.mib>光と毒の狂騒曲</a><BR>
		<a href=#003 qname=m60016.mib>紅の災厄</a><BR>
		<a href=#004 qname=m60028.mib>ＪＵＭＰ　炎帝の凱旋</a><BR>
		<a href=#005 qname=m60011.mib>ファミ通　２頭の女王</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#006 qname=m60009.mib>怪鳥の嵐！</a><BR></B>
	<tr><td height=25 valign=top>
		<B>
		<a href=#007 qname=m60002.mib>雨夜のエッグシーフ！</a><BR>
		</B>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_WHT.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=white><B>狩猟クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>怪鳥の嵐！</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ２４００ｚ<br>
<font color=orange>契約金　：</font> ２００ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 密林＜昼＞<br>
<font color=orange>特殊条件：</font><br>
なし<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_WHT.gif>
		<B>
			　 　　<font color=white>狩猟クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		怪鳥の嵐！
	</B>
	</td>
	<td>
	<B>
		★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
タイムアップもしくは、<BR>
ネコタクチケットの納品<BR>
<BR>
<font color=orange>失敗条件：</font><br>
２頭以上を狩猟せずにタイム<BR>
アップ、もしくは報酬金ゼロ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>ハンターズギルド<br>
密林地帯の村から「付近で大怪<BR>
鳥が異常発生している」との報<BR>
告を受けました！ハンターの皆<BR>
さんは至急現場へ向かい、事態<BR>
の収拾に当たってください！<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>

<a name=007></a>
<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
<td width=224>
	<table width=208 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
	<form action="QUEST/m60002.mib" DOWNLOAD CSUM=23594 FSIZE=8356 method=post>
	<tr>
	<td height=40 width=204 align=center valign=center>
		<table width=103 height=17 cellspacing=0 cellpadding=0 background=./GIF/LR.gif>
		<tr>
		<td align=center>
			<B>３/４</B>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr><td>
		<B>
		<a href=#001 qname=m60003.mib>白黒つけるぜ！闘技場！</a><BR>
		<a href=#002 qname=m60021.mib>光と毒の狂騒曲</a><BR>
		<a href=#003 qname=m60016.mib>紅の災厄</a><BR>
		<a href=#004 qname=m60028.mib>ＪＵＭＰ　炎帝の凱旋</a><BR>
		<a href=#005 qname=m60011.mib>ファミ通　２頭の女王</a><BR>
		<a href=#006 qname=m60009.mib>怪鳥の嵐！</a><BR>
		</B>
	<tr><td bgcolor=green>
		<B><a href=#007 qname=m60002.mib>雨夜のエッグシーフ！</a><BR></B>
	<tr><td valign=top>
		<B>
		</B>
	<tr><td height=8>
		<input type=image src="" name=submit width=0 height=0>
	</tr>
	</form>
	</table>
</td>
<td width=241>
	<table width=241 background=./GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
	<tr>
	<td width=237 height=25 align=center valign=bottom>
		<table width=227 height=21 cellspacing=0 cellpadding=0 background=./GIF/T_GRN.gif>
		<tr>
		<td height=21 align=center valign=bottom>
			<font color=lime><B>採取クエスト</B></font>
		</td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
		<B>雨夜のエッグシーフ！</B>
	</td>
	</tr>
	<tr>
	<td height=133 valign=top>
<font size=1><br></font>
<B>
<font color=orange>報酬金　：</font> ４２００ｚ<br>
<font color=orange>契約金　：</font> ３５０ｚ<br>
<font color=orange>制限時間：</font> ５０分<br>
<font color=orange>指定地　：</font> 密林＜夜＞<br>
<font color=orange>特殊条件：</font><br>
なし<BR>
<BR>

</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON3.gif></td></tr></table>

<img src=./GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
<td>
	<table background=./GIF/QBOARD2.gif cellspacing=0 height=187>
	<tr>
	<td colspan=2>
		<table cellspacing=0 cellpadding=0 width=468 height=21>
		<tr>
		<td height=8 ></td>
		</tr>
		<tr>
		<td width=8></td>
		<td width=452 height=21 background=./GIF/T_GRN.gif>
		<B>
			　 　　<font color=lime>採取クエスト</font>
			　　　<font color=orange>クエストＬＶ：</font>
		</B>
		<td width=8></td>
		</tr>
		</table>
	</td>
	</tr>
	<tr>
	<td align=center>
	<B>
		雨夜のエッグシーフ！
	</B>
	</td>
	<td>
	<B>
		★★★★
	</B>
	</td>
	</tr>
	<tr>
	<td width=227 221 valign=top>
		<TABLE cellspacing=3><TR><TD>
<B>
<font color=orange>成功条件：</font><br>
飛竜の卵３個の納品<BR>
<BR>
<BR>
<font color=orange>失敗条件：</font><br>
報酬金ゼロ<BR>
タイムアップ<BR>
</B>
		</TABLE>
	</td>
	<td width=242 valign=top>
<font size=1><br></font>
<B>
<font color=orange>依頼主：</font>食道楽を究めた貴婦人<br>
私、卵料理に凝ってるざます。<BR>
やはり美味なのは飛竜の卵！<BR>
私もすっかり味の虜ざます。<BR>
満足できるだけの量…３個は<BR>
持ってきてほしいざますわね！<BR>
　　　　　　　　　　　　　　<br>
</B>
	</td>
	</tr>
	</table>
</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
