<html>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:6",
		"MOVE_CHAR=./GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=./GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=./GIF/BG.gif>

<basefont size=2>
<B>
<img src=./GIF/LOGO10.gif width=200 height=50 alt="Quest"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>

<table width=480 height=197 201 cellspacing=0 cellpadding=0 border=0>
<!-- 1段目 -->
<tr>
		<form action="DL_MENU1.PHP" method=get>
	<td width=240 height=196 align=center valign=center>
		 <input ANIME=1 type=image src=./GIF/SELECT1.gif name=submit width=220 height=160 alt="Event">
	</td>
		</form>
		<form action="DL_CMENU1.PHP" method=get>
	<td width=240 height=196 align=center valign=center>
		 <input ANIME=1 type=image src=./GIF/SELECT2.gif name=submit width=220 height=160 alt="Challeng">
	</td>
		</form>
</tr>
</table>

<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON2.gif></td></tr></table>

</body>
</html>
