<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=OFF",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:1",
		"MOVE_CHAR=./GIF/NEKO.gif,58,62,0,,16,,417,185",
		"MOVE_CHAR=./GIF/PIG.gif,64,48,1,0,3,10,480,050",
		"MOVE_CHAR=./GIF/rio.gif,82,52,1,1,0,40,-82,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white background=./GIF/BG.gif bgcolor=#0DA5DE >
<basefont size=2>
<B>
<img src=./GIF/LOGO1.gif width=200 height=50 alt="Top"><img src=./GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 cellpadding=0 border=0>
<tr>
	<td width=15>
	</td>
	<td width=210>
	<table width=210 cellspacing=0 cellpadding=0>
		<form action="DL_SELECT.PHP" method=get><tr><td>
		 <input type=image ANIME=20 src="GIF/DOWNLOAD.gif"    name=submit width=210 height=50 alt="Quest">
		</td></tr></form>
		<form action="DL_BONUS.PHP" method=get><tr><td>
		 <input type=image ANIME=16 src="GIF/BONUS.gif"       name=submit width=210 height=50 alt="Bonus">
		</td></tr></form>
		<form action="DB_INFO1.PHP" method=get><tr><td>
		 <input type=image ANIME=16 src="GIF/INFORMATION.gif" name=submit width=210 height=50 alt="Information"></a>
		</td></tr></form>
	</table>
	</td>
	<td width=240>
	<table width=238 height=187 border=0 bordercolor=#1C64FE cellspacing=0 background=./GIF/KANBAN.gif>
		<tr>
			<td valign=top height=187>
			<BR>
				<B>
				<center>
				<font color=orange>最新更新情報</font><br>
				</center>
<BR>
≪９／２１≫<BR>
ＭＨＰ２ｎｄＧ発表記念！<BR>
クエスト<BR>
【鋼の来訪者】<BR>
を追加したのニャ！<BR>
<BR>
<BR>

			</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=./GIF/BUTTON1.gif></td></tr></table>
</body>
</html>
