<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?pg_no=1",
		"RB_LINK=DL_MENU.PHP?pg_no=0",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60015.mib" DOWNLOAD CSUM=52608 FSIZE=1148 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60015.mib>The Legend of Schrade</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m60009.mib>Tempest of Yian Kut-Ku</a><BR>
					<a href=#003 qname=m60002.mib>Late Night Egg Thief</a><BR>
					<a href=#004 qname=m60024.mib>Swarms Upon Swarms</a><BR>
					<a href=#005 qname=m60014.mib>Monkeys and Crabs!</a><BR>
					<a href=#006 qname=m60013.mib>Crabs and Monkeys!</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_PPL.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=#ff60ff>Special Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					The Legend of Schrade
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Reward　：</font> 36000z<br>
<font color=orange>Contract：</font> 3000z<br>
<font color=orange>Time　　：</font> 50min<br>
<font color=orange>Zone　　：</font> Castle Schrade<br>
<font color=orange>Special Conditions：</font><br>HR 6 Or Above Only<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_PPL.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=#ff60ff>Special Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest Level：</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				The Legend of Schrade
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Goal Condition：</font><br>Slay the Fatalis<BR><BR><BR>
<font color=orange>Fail Condition：</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client：</font>Guild Master<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
The black dragon Fatalis,<BR>referred to in Schradian<BR>legend, has been confirmed<BR>to exist! Left to roam free,<BR>countries will fall to its<BR>might. We need your help to<BR>end its reign of terror!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60009.mib" DOWNLOAD CSUM=21277 FSIZE=5248 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>The Legend of Schrade</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60009.mib>Tempest of Yian Kut-Ku</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m60002.mib>Late Night Egg Thief</a><BR>
					<a href=#004 qname=m60024.mib>Swarms Upon Swarms</a><BR>
					<a href=#005 qname=m60014.mib>Monkeys and Crabs!</a><BR>
					<a href=#006 qname=m60013.mib>Crabs and Monkeys!</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_WHT.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=white>Hunting Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Tempest of Yian Kut-Ku
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Reward　：</font> 2400z<br>
<font color=orange>Contract：</font> 200z<br>
<font color=orange>Time　　：</font> 50min<br>
<font color=orange>Zone　　：</font> Jungle(Day)<br>
<font color=orange>Special Conditions：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_WHT.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=white>Hunting Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest Level：</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Tempest of Yian Kut-Ku
			</td>
			<td>
				&nbsp;★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Goal Condition：</font><br>Survive until Time Over or<BR>Deliver the Paw Pass Ticket<BR><BR>
<font color=orange>Fail Condition：</font><br>Hunt less than 2 Kut-Ku<BR>before Time Up, Reward Zero<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client：</font>Hunter's Guild<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
We've just received a report<BR>from the jungle village that<BR>they are being plagued by<BR>multiple Yian Kut-Ku! Make<BR>haste towards the area and<BR>get the situation under<BR>control!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60002.mib" DOWNLOAD CSUM=51368 FSIZE=8276 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>The Legend of Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Tempest of Yian Kut-Ku</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60002.mib>Late Night Egg Thief</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m60024.mib>Swarms Upon Swarms</a><BR>
					<a href=#005 qname=m60014.mib>Monkeys and Crabs!</a><BR>
					<a href=#006 qname=m60013.mib>Crabs and Monkeys!</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_GRN.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=lime>Gathering Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Late Night Egg Thief
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Reward　：</font> 4200ｚ<br>
<font color=orange>Contract：</font> 350z<br>
<font color=orange>Time　　：</font> 50min<br>
<font color=orange>Zone　　：</font> Jungle(Night)<br>
<font color=orange>Special Conditions：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_GRN.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=lime>Gathering Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest Level：</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Late Night Egg Thief
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Goal Condition：</font><br>Deliver 3 Wyvern Eggs<BR><BR><BR>
<font color=orange>Fail Condition：</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client：</font>The Lady Gourmet<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
As an absolute fanatic of<BR>egg dishes, I can say<BR>without hesitation that the<BR>tastiest of all eggs are<BR>Wyvern Eggs. Satisfy my<BR>hunger for this treat and<BR>bring me 3 Wyvern Eggs!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60024.mib" DOWNLOAD CSUM=29712 FSIZE=9772 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>The Legend of Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Tempest of Yian Kut-Ku</a><BR>
					<a href=#003 qname=m60002.mib>Late Night Egg Thief</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60024.mib>Swarms Upon Swarms</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m60014.mib>Monkeys and Crabs!</a><BR>
					<a href=#006 qname=m60013.mib>Crabs and Monkeys!</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Slaying Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Swarms Upon Swarms
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Reward　：</font> 4500z<br>
<font color=orange>Contract：</font> 380z<br>
<font color=orange>Time　　：</font> 50min<br>
<font color=orange>Zone　　：</font> Jungle(Day)<br>
<font color=orange>Special Conditions：</font><br>HR 4 Or Above Only<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Slaying Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest Level：</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Swarms Upon Swarms
			</td>
			<td>
				&nbsp;★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Goal Condition：</font><br>Slay 50 Vespoids<BR><BR><BR>
<font color=orange>Fail Condition：</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client：</font>Annoyed Maiden<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Lately, the area around the<BR>village has been very noisy,<BR>and it's all because of that<BR>swarm of bugs! They are so<BR>loud, I can't sleep at<BR>night! You're a hunter<BR>right? Then do something!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60014.mib" DOWNLOAD CSUM=58630 FSIZE=1460 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>The Legend of Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Tempest of Yian Kut-Ku</a><BR>
					<a href=#003 qname=m60002.mib>Late Night Egg Thief</a><BR>
					<a href=#004 qname=m60024.mib>Swarms Upon Swarms</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60014.mib>Monkeys and Crabs!</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m60013.mib>Crabs and Monkeys!</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_WHT.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=white>Hunting Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Monkeys and Crabs!
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Reward　：</font> 7500z<br>
<font color=orange>Contract：</font> 620z<br>
<font color=orange>Time　　：</font> 50min<br>
<font color=orange>Zone　　：</font> Great Arena<br>
<font color=orange>Special Conditions：</font><br>HR 4 Or Above Only<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_WHT.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=white>Hunting Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest Level：</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Monkeys and Crabs!
			</td>
			<td>
				&nbsp;★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Goal Condition：</font><br>Hunt the Blangonga<BR><BR><BR>
<font color=orange>Fail Condition：</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client：</font>Arena Manager<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
The Arena! A place to show<BR>your skills to the world! In<BR>this event, your opponent is<BR>a Blangonga; however, we've<BR>also released Ceanataurs and<BR>Hermitaurs! Beware the crabs<BR>and bring down the beast!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60013.mib" DOWNLOAD CSUM=58554 FSIZE=1456 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>The Legend of Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Tempest of Yian Kut-Ku</a><BR>
					<a href=#003 qname=m60002.mib>Late Night Egg Thief</a><BR>
					<a href=#004 qname=m60024.mib>Swarms Upon Swarms</a><BR>
					<a href=#005 qname=m60014.mib>Monkeys and Crabs!</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60013.mib>Crabs and Monkeys!</a><BR>
			<tr><td height=30 valign=top>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_WHT.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=white>Hunting Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Crabs and Monkeys!
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Reward　：</font> 4200z<br>
<font color=orange>Contract：</font> 350z<br>
<font color=orange>Time　　：</font> 50min<br>
<font color=orange>Zone　　：</font> Great Arena<br>
<font color=orange>Special Conditions：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_WHT.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=white>Hunting Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest Level：</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Crabs and Monkeys!
			</td>
			<td>
				&nbsp;★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Goal Condition：</font><br>Hunt the Daimyo Hermitaur<BR><BR><BR>
<font color=orange>Fail Condition：</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client：</font>Arena Manager<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
The Arena! A place to show<BR>your skills to the world! In<BR>this event, your opponent is<BR>a red Daimyo Hermitaur.<BR>Beware the surrounding<BR>Congas and slay the crab! We<BR>await your return!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
