<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?pg_no=2",
		"RB_LINK=DL_MENU.PHP?pg_no=1",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60022.mib" DOWNLOAD CSUM=60986 FSIZE=1372 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60022.mib>Anger of Heaven and Earth</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m60025.mib>The Visitor of Steel</a><BR>
					<a href=#003 qname=m60019.mib>Golden Thunder God</a><BR>
					<a href=#004 qname=m60018.mib>The Remobra Den</a><BR>
					<a href=#005 qname=m60017.mib>Ancestral Dragon</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>The Hot, Dark Wind</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_WHT.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=white>Hunting Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Anger of Heaven and Earth
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Reward　：</font> 9900z<br>
<font color=orange>Contract：</font> 830z<br>
<font color=orange>Time　　：</font> 50min<br>
<font color=orange>Zone　　：</font> Great Arena<br>
<font color=orange>Special Conditions：</font><br>HR 4 Or Above Only<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_WHT.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=white>Hunting Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest Level：</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Anger of Heaven and Earth
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Goal Condition：</font><br>Slay the Silver Rathalos<BR>and Gold Rathian<BR><BR>
<font color=orange>Fail Condition：</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client：</font>Kokoto Village Chief<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
It has been a long time my<BR>friends... Here is my<BR>challenge to you all! Defeat<BR>the two giant wyverns<BR>Rathalos and Rathian. Do you<BR>have the skill to drive them<BR>into submission?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60025.mib" DOWNLOAD CSUM=63374 FSIZE=1424 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Anger of Heaven and Earth</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60025.mib>The Visitor of Steel</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m60019.mib>Golden Thunder God</a><BR>
					<a href=#004 qname=m60018.mib>The Remobra Den</a><BR>
					<a href=#005 qname=m60017.mib>Ancestral Dragon</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>The Hot, Dark Wind</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Slaying Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					The Visitor of Steel
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Reward　：</font> 10500z<br>
<font color=orange>Contract：</font> 870z<br>
<font color=orange>Time　　：</font> 50min<br>
<font color=orange>Zone　　：</font> Town<br>
<font color=orange>Special Conditions：</font><br>HR 6 Or Above Only<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Slaying Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest Level：</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				The Visitor of Steel
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Goal Condition：</font><br>Slay the Kushala Daora<BR><BR><BR>
<font color=orange>Fail Condition：</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client：</font>Guild Master<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Emergency! Emergency! A<BR>brown Kushala Daora is<BR>closing in on our town! All<BR>hunters of worth should rush<BR>here as soon as possible! We<BR>need your help to save the<BR>town!!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60019.mib" DOWNLOAD CSUM=51630 FSIZE=1196 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Anger of Heaven and Earth</a><BR>
					<a href=#002 qname=m60025.mib>The Visitor of Steel</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60019.mib>Golden Thunder God</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m60018.mib>The Remobra Den</a><BR>
					<a href=#005 qname=m60017.mib>Ancestral Dragon</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>The Hot, Dark Wind</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_WHT.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=white>Hunting Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Golden Thunder God
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Reward　：</font> 9000z<br>
<font color=orange>Contract：</font> 750z<br>
<font color=orange>Time　　：</font> 50min<br>
<font color=orange>Zone　　：</font> Great Arena<br>
<font color=orange>Special Conditions：</font><br>HR 4 Or Above Only<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_WHT.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=white>Hunting Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest Level：</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Golden Thunder God
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Goal Condition：</font><br>Hunt the Rajang<BR><BR><BR>
<font color=orange>Fail Condition：</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client：</font>Arena Manager<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
This is awful! Absolutely<BR>awful! A huge black monster<BR>took over my arena! With<BR>that thing in there, we<BR>can't do any business!! Get<BR>rid of it quickly! Please!!<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60018.mib" DOWNLOAD CSUM=58074 FSIZE=1440 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Anger of Heaven and Earth</a><BR>
					<a href=#002 qname=m60025.mib>The Visitor of Steel</a><BR>
					<a href=#003 qname=m60019.mib>Golden Thunder God</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60018.mib>The Remobra Den</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m60017.mib>Ancestral Dragon</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>The Hot, Dark Wind</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Slaying Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					The Remobra Den
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Reward　：</font> 6000z<br>
<font color=orange>Contract：</font> 500z<br>
<font color=orange>Time　　：</font> 50min<br>
<font color=orange>Zone　　：</font> Great Arena<br>
<font color=orange>Special Conditions：</font><br>HR 4 Or Above Only<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Slaying Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest Level：</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				The Remobra Den
			</td>
			<td>
				&nbsp;★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Goal Condition：</font><br>Slay 15 Remobras<BR><BR><BR>
<font color=orange>Fail Condition：</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client：</font>Arena Manager<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
The Arena! A place to show<BR>your skills to the world!<BR>Your opponents for this<BR>event are flying Remobras!<BR>With their poison filling<BR>the arena, it will take true<BR>courage to survive!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60017.mib" DOWNLOAD CSUM=36000 FSIZE=3872 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Anger of Heaven and Earth</a><BR>
					<a href=#002 qname=m60025.mib>The Visitor of Steel</a><BR>
					<a href=#003 qname=m60019.mib>Golden Thunder God</a><BR>
					<a href=#004 qname=m60018.mib>The Remobra Den</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60017.mib>Ancestral Dragon</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>The Hot, Dark Wind</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_PPL.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=#ff60ff>Special Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Ancestral Dragon
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Reward　：</font> 36000z<br>
<font color=orange>Contract：</font> 3000z<br>
<font color=orange>Time　　：</font> 50min<br>
<font color=orange>Zone　　：</font> Tower<br>
<font color=orange>Special Conditions：</font><br>HR 6 Or Above Only<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_PPL.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=#ff60ff>Special Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest Level：</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Ancestral Dragon
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Goal Condition：</font><br>Slay the Fatalis<BR><BR><BR>
<font color=orange>Fail Condition：</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client：</font>Scarlet Mystery Man<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
He he he... The time is<BR>come. Here is your<BR>invitation to the ball. Wear<BR>your Sunday best and bring<BR>your greatest weapon, for it<BR>is time to go to the dance<BR>with the king of disaster.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60010.mib" DOWNLOAD CSUM=355 FSIZE=6028 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Anger of Heaven and Earth</a><BR>
					<a href=#002 qname=m60025.mib>The Visitor of Steel</a><BR>
					<a href=#003 qname=m60019.mib>Golden Thunder God</a><BR>
					<a href=#004 qname=m60018.mib>The Remobra Den</a><BR>
					<a href=#005 qname=m60017.mib>Ancestral Dragon</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60010.mib>Scarface</a><BR>
			<tr><td height=30 valign=top>
					<a href=#007 qname=m60012.mib>The Hot, Dark Wind</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_WHT.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=white>Hunting Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Scarface
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Reward　：</font> 6600z<br>
<font color=orange>Contract：</font> 550z<br>
<font color=orange>Time　　：</font> 50min<br>
<font color=orange>Zone　　：</font> Jungle(Night)<br>
<font color=orange>Special Conditions：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_WHT.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=white>Hunting Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest Level：</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Scarface
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Goal Condition：</font><br>Hunt the Yian Garuga<BR><BR><BR>
<font color=orange>Fail Condition：</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client：</font>Wounded Fighter<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
I chased down the injured<BR>wyvern in the jungle;<BR>however, being injured<BR>myself, I reach the limit of<BR>my body's strength. Avenge<BR>my honor and hunt him down<BR>in my stead!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60012.mib" DOWNLOAD CSUM=55586 FSIZE=1328 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Anger of Heaven and Earth</a><BR>
					<a href=#002 qname=m60025.mib>The Visitor of Steel</a><BR>
					<a href=#003 qname=m60019.mib>Golden Thunder God</a><BR>
					<a href=#004 qname=m60018.mib>The Remobra Den</a><BR>
					<a href=#005 qname=m60017.mib>Ancestral Dragon</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60012.mib>The Hot, Dark Wind</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_WHT.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=white>Hunting Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					The Hot, Dark Wind
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Reward　：</font> 9000z<br>
<font color=orange>Contract：</font> 750z<br>
<font color=orange>Time　　：</font> 50min<br>
<font color=orange>Zone　　：</font> Great Arena<br>
<font color=orange>Special Conditions：</font><br>HR 4 Or Above Only<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_WHT.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=white>Hunting Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest Level：</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				The Hot, Dark Wind
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Goal Condition：</font><br>Hunt 2 Black Gravios<BR><BR><BR>
<font color=orange>Fail Condition：</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client：</font>Arena Manager<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
The Arena! A place to show<BR>your skills to the world!<BR>For this event, we have<BR>released not one, but two of<BR>the dreadful Black Gravios<BR>into the arena! Are you up<BR>to the challenge?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
