<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=OFF",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:8",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,,16,,417,185",
		"MOVE_CHAR=GIF/PIG.gif,64,48,1,0,3,10,480,050",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<B>
<img src=GIF/LOGO1.gif width=200 height=50 alt="Top"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=201 cellspacing=2 cellpadding=0 border=0>
<tr>
	<td width=15>
	</td>
	<td width=210>
	<table width=210 cellspacing=0 cellpadding=0>
		<form action="DL_SELECT.PHP" method=get><tr><td>
		 <input type=image ANIME=20 src="GIF/DOWNLOAD.gif"    name=submit width=210 height=50 alt="Quest">
		</td></tr></form>
		<form action="DL_BONUS.PHP" method=get><tr><td>
		 <input type=image ANIME=16 src="GIF/BONUS.gif"       name=submit width=210 height=50 alt="Bonus">
		</td></tr></form>
		<form action="DB_INFO.PHP" method=get><tr><td>
		 <input type=hidden name=pg_no value=0>
		 <input type=image ANIME=16 src="GIF/INFORMATION.gif" name=submit width=210 height=50 alt="Information"></a>
		</td></tr></form>
	</table>
	</td>
	<td width=240>
	<table width=238 height=187 border=0 bordercolor=#1C64FE cellspacing=0 background=GIF/KANBAN.gif>
		<tr>
			<td valign=top height=187>
			<BR>
				<B>
<center><font color=orange>[Latest Update Information] </font></center>
<img src="" width=5 height=5><BR>
≪12/28≫<BR>The Quests below:<BR><font color=orange>Anger of Heaven and Earth<BR></font>have been added, nya!<BR><BR><BR><BR>
				</B>
			</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON1.gif></td></tr></table>
</body>
</html>
