<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?pg_no=0",
		"RB_LINK=DB_INFO.PHP?pg_no=2",
		"MOVE_CHAR=GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					０８／１５更新予告<BR>
				<tr><td>
					０８／０８更新予告<BR>
					０８／０１更新予告②<BR>
					０８／０１更新予告①<BR>
					０７／２５更新予告<BR>
					０７／１８更新予告②<BR>
					０７／１８更新予告①<BR>
					０７／１１更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０８／１５更新予告</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【二色の双角・闘技場】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０８／１５更新予告</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【二色の双角・闘技場】</font><BR>
依頼主：初老の闘技場支配人<BR>この仕事とは離れていたんだが<BR>あの時の興奮が忘れられなくて<BR>戻ってきてしまったよ！さぁ、<BR>今回は２頭のディアブロスが君<BR>達の相手だ！頑張ってくれよ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60014.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０８／１５更新予告<BR>
				<tr><td bgcolor=green>
					０８／０８更新予告<BR>
				<tr><td>
					０８／０１更新予告②<BR>
					０８／０１更新予告①<BR>
					０７／２５更新予告<BR>
					０７／１８更新予告②<BR>
					０７／１８更新予告①<BR>
					０７／１１更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０８／０８更新予告</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【マグマの海に擁かれて】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０８／０８更新予告</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【マグマの海に擁かれて】</font><BR>
依頼主：浅黒い肌の鉱夫<BR>俺っちが一仕事終えて帰ろうと<BR>した時の話さ…火山の奥でマグ<BR>マに浮かぶ巨大な黒い影を見た<BR>んだ！きっとこの火山のヌシに<BR>違いねぇ！調査を頼むぜ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60022.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０８／１５更新予告<BR>
					０８／０８更新予告<BR>
				<tr><td bgcolor=green>
					０８／０１更新予告②<BR>
				<tr><td>
					０８／０１更新予告①<BR>
					０７／２５更新予告<BR>
					０７／１８更新予告②<BR>
					０７／１８更新予告①<BR>
					０７／１１更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０８／０１更新予告②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【チャレンジクエスト　１０】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０８／０１更新予告②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【チャレンジクエスト　１０】</font><BR>
依頼主：教官<BR>最早何も言うまい…金色の怒り<BR>しラージャン！最強とよぶに相<BR>応しい相手だ！だがこれに挑戦<BR>できる貴様ならば心配はあるま<BR>い…全力を出し、勝利を掴め！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/c61010.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０８／１５更新予告<BR>
					０８／０８更新予告<BR>
					０８／０１更新予告②<BR>
				<tr><td bgcolor=green>
					０８／０１更新予告①<BR>
				<tr><td>
					０７／２５更新予告<BR>
					０７／１８更新予告②<BR>
					０７／１８更新予告①<BR>
					０７／１１更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０８／０１更新予告①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【ＪＵＭＰ　赤き闘技会】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０８／０１更新予告①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【ＪＵＭＰ　赤き闘技会】</font><BR>
依頼主：海賊団の副長<BR>ウチのボスが誕生日だってんで<BR>祝いに闘技会を開催するんだ。<BR>そんで参加する命知らずを募集<BR>したい。強いヤツは大歓迎！<BR>力の無いヤツは勘弁してくれ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60007.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０８／１５更新予告<BR>
					０８／０８更新予告<BR>
					０８／０１更新予告②<BR>
					０８／０１更新予告①<BR>
				<tr><td bgcolor=green>
					０７／２５更新予告<BR>
				<tr><td>
					０７／１８更新予告②<BR>
					０７／１８更新予告①<BR>
					０７／１１更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０７／２５更新予告</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【白光】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０７／２５更新予告</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【白光】</font><BR>
依頼主：白いドレスの少女<BR>うふふ、あなたハンターなんで<BR>しょ？ある場所まで一緒に来て<BR>欲しいの…素敵な所よ。白い光<BR>が綺羅星のように舞い散って…<BR>退屈なんてさせないんだから…<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60032.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０８／１５更新予告<BR>
					０８／０８更新予告<BR>
					０８／０１更新予告②<BR>
					０８／０１更新予告①<BR>
					０７／２５更新予告<BR>
				<tr><td bgcolor=green>
					０７／１８更新予告②<BR>
				<tr><td>
					０７／１８更新予告①<BR>
					０７／１１更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０７／１８更新予告②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【チャレンジクエスト　０９】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０７／１８更新予告②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【チャレンジクエスト　０９】</font><BR>
依頼主：教官<BR>今回は趣向を変えたクエストを<BR>用意した！大闘技場でランポス<BR>の群れを相手にしてもらう！<BR>だが雑魚と侮るな、奴等の背後<BR>には暴君が君臨しているぞ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/c61009.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０８／１５更新予告<BR>
					０８／０８更新予告<BR>
					０８／０１更新予告②<BR>
					０８／０１更新予告①<BR>
					０７／２５更新予告<BR>
					０７／１８更新予告②<BR>
				<tr><td bgcolor=green>
					０７／１８更新予告①<BR>
				<tr><td>
					０７／１１更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０７／１８更新予告①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【ヒプノック大乱闘！】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０７／１８更新予告①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【ヒプノック大乱闘！】</font><BR>
依頼主：闘技場の運営者<BR>ハンターが己の腕前を披露する<BR>闘技場！２頭のヒプノックが待<BR>つ場内へ足を踏み入れた者は、<BR>深い眠りへ誘われるでしょう！<BR>あなたの実力見せてください！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60021.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０８／１５更新予告<BR>
					０８／０８更新予告<BR>
					０８／０１更新予告②<BR>
					０８／０１更新予告①<BR>
					０７／２５更新予告<BR>
					０７／１８更新予告②<BR>
					０７／１８更新予告①<BR>
				<tr><td bgcolor=green>
					０７／１１更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０７／１１更新予告</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【電撃祭Ｇ　イカヅチの山】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０７／１１更新予告</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【電撃祭Ｇ　イカヅチの山】</font><BR>
依頼主：電撃ＰＳ　ポリタン<BR>ポリタンからグレートな挑戦！<BR>キミは雪山に現れた電撃を放つ<BR>モンスターに勝利できるか！？<BR>達成できたら豪華チケットが…<BR>だけども相手は１頭じゃない？<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60005.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
