<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?pg_no=7",
		"RB_LINK=DB_INFO.PHP?pg_no=1",
		"MOVE_CHAR=GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					１２／１９更新予告<BR>
				<tr><td>
					１０／３０更新予告<BR>
					０９／２６更新予告<BR>
					０９／１９更新予告<BR>
					０９／１２更新予告<BR>
					０９／０５更新予告<BR>
					０８／２９更新予告<BR>
					０８／２２更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>１２／１９更新予告</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回は特典をさらに１つ<BR>追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>１２／１９更新予告</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
・プーギーの服<BR>
<font color=orange>　【マフモフウォーマー】<BR><BR><BR><BR><BR><BR></font>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/b00011.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					１２／１９更新予告<BR>
				<tr><td bgcolor=green>
					１０／３０更新予告<BR>
				<tr><td>
					０９／２６更新予告<BR>
					０９／１９更新予告<BR>
					０９／１２更新予告<BR>
					０９／０５更新予告<BR>
					０８／２９更新予告<BR>
					０８／２２更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>１０／３０更新予告</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【双獅激天】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>１０／３０更新予告</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【双獅激天】</font><BR>
依頼主：血相を変えた傭兵<BR>信じられない光景だった…！<BR>激昂したラージャン２頭が、<BR>闘技場に居座っていたんだ…。<BR>いいか？命が惜しかったら、<BR>近づくんじゃない！絶対にな！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60038.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					１２／１９更新予告<BR>
					１０／３０更新予告<BR>
				<tr><td bgcolor=green>
					０９／２６更新予告<BR>
				<tr><td>
					０９／１９更新予告<BR>
					０９／１２更新予告<BR>
					０９／０５更新予告<BR>
					０８／２９更新予告<BR>
					０８／２２更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０９／２６更新予告</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【覇王烈昂】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０９／２６更新予告</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【覇王烈昂】</font><BR>
依頼主：人望厚い国王<BR>凄まじい力の覇竜…いよいよの<BR>ところまで追い詰めたものの、<BR>すでにこちらの被害も甚大…！<BR>最早猶予などありはしない！狩<BR>人よ！その力余に貸してくれ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60034.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					１２／１９更新予告<BR>
					１０／３０更新予告<BR>
					０９／２６更新予告<BR>
				<tr><td bgcolor=green>
					０９／１９更新予告<BR>
				<tr><td>
					０９／１２更新予告<BR>
					０９／０５更新予告<BR>
					０８／２９更新予告<BR>
					０８／２２更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０９／１９更新予告</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【武神闘宴】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０９／１９更新予告</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【武神闘宴】</font><BR>
依頼主：赤衣の男を従えた騎士<BR>この試練に挑戦するものよ！<BR>お前の力とお前の頼れる仲間の<BR>力を信じ進むのだ。人の力は危<BR>地にこそ試される…ならば！最<BR>後まで気高く足掻いてみせよ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60019.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					１２／１９更新予告<BR>
					１０／３０更新予告<BR>
					０９／２６更新予告<BR>
					０９／１９更新予告<BR>
				<tr><td bgcolor=green>
					０９／１２更新予告<BR>
				<tr><td>
					０９／０５更新予告<BR>
					０８／２９更新予告<BR>
					０８／２２更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０９／１２更新予告</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【浮かぶ山岳】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０９／１２更新予告</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【浮かぶ山岳】</font><BR>
依頼主：長い白髪の老婆<BR>アタシが若い頃の話さ、空に巨<BR>大な影を見たことがあってね。<BR>そりゃ飛竜なんて比べ物になら<BR>ん大きさでね…幻じゃないさ。<BR>何ならアンタ調べてくるかい？<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60010.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					１２／１９更新予告<BR>
					１０／３０更新予告<BR>
					０９／２６更新予告<BR>
					０９／１９更新予告<BR>
					０９／１２更新予告<BR>
				<tr><td bgcolor=green>
					０９／０５更新予告<BR>
				<tr><td>
					０８／２９更新予告<BR>
					０８／２２更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０９／０５更新予告</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【鬼の哭く山】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０９／０５更新予告</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【鬼の哭く山】</font><BR>
依頼主：執事を従えた青年貴族<BR>僕との結婚を嫌った彼女が金獅<BR>子２頭が棲む山へ挑みに行って<BR>しまった。フラれるのは構わな<BR>いが、彼女を失うのは耐えられ<BR>ない。頼む！力を貸してくれ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60016.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					１２／１９更新予告<BR>
					１０／３０更新予告<BR>
					０９／２６更新予告<BR>
					０９／１９更新予告<BR>
					０９／１２更新予告<BR>
					０９／０５更新予告<BR>
				<tr><td bgcolor=green>
					０８／２９更新予告<BR>
				<tr><td>
					０８／２２更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０８／２９更新予告</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【焔の四天王】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０８／２９更新予告</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【焔の四天王】</font><BR>
依頼主：白衣を着た研究員<BR>火山地帯に良い餌場があって、<BR>多種のモンスターが確認されて<BR>いるんだ。そこで依頼だ。現地<BR>へ行って研究の資料用に４種の<BR>モンスターを狩ってきてくれ。<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60018.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					１２／１９更新予告<BR>
					１０／３０更新予告<BR>
					０９／２６更新予告<BR>
					０９／１９更新予告<BR>
					０９／１２更新予告<BR>
					０９／０５更新予告<BR>
					０８／２９更新予告<BR>
				<tr><td bgcolor=green>
					０８／２２更新予告<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０８／２２更新予告</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【双璧！黒き熱風】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０８／２２更新予告</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【双璧！黒き熱風】</font><BR>
依頼主：闘技場の運営者<BR>ハンターが己の腕前を披露する<BR>闘技場！今回は世にも恐ろしい<BR>黒鎧竜を闘技場に放しました！<BR>しかも２頭！ハンターの皆さん<BR>この難関を突破できますか？<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60015.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
