<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?pg_no=2",
		"RB_LINK=DB_INFO.PHP?pg_no=4",
		"MOVE_CHAR=GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					０６／０６更新予告②<BR>
				<tr><td>
					０６／０６更新予告①<BR>
					０５／３０更新予告③<BR>
					０５／３０更新予告②<BR>
					０５／３０更新予告①<BR>
					０５／２３更新予告②<BR>
					０５／２３更新予告①<BR>
					０５／１６更新予告③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０６／０６更新予告②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【チャレンジクエスト　０６】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０６／０６更新予告②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【チャレンジクエスト　０６】</font><BR>
依頼主：教官<BR>旧密林で巨大昆虫が大発生して<BR>いるので何とかしてほしいと依<BR>頼があった。このような場合は<BR>群れのリーダーとなるものを狙<BR>えば良い。女王を討ち取れ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/c61006.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０６／０６更新予告②<BR>
				<tr><td bgcolor=green>
					０６／０６更新予告①<BR>
				<tr><td>
					０５／３０更新予告③<BR>
					０５／３０更新予告②<BR>
					０５／３０更新予告①<BR>
					０５／２３更新予告②<BR>
					０５／２３更新予告①<BR>
					０５／１６更新予告③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０６／０６更新予告①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【激戦！血煙闘技場】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０６／０６更新予告①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【激戦！血煙闘技場】</font><BR>
依頼主：生真面目な女騎士<BR>これは私の趣味ではないのだが<BR>キミたちの力が見たいという方<BR>がいてな。その実力、見せては<BR>もらえまいか？報酬に関しては<BR>無論期待してくれていいぞ。<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60017.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０６／０６更新予告②<BR>
					０６／０６更新予告①<BR>
				<tr><td bgcolor=green>
					０５／３０更新予告③<BR>
				<tr><td>
					０５／３０更新予告②<BR>
					０５／３０更新予告①<BR>
					０５／２３更新予告②<BR>
					０５／２３更新予告①<BR>
					０５／１６更新予告③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０５／３０更新予告③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回は特典をさらに５つ<BR>追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０５／３０更新予告③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
以下の特典が追加されるのニャ！<BR>
<font color=orange>・プーギーの服<BR>　【眠りを誘う白】<BR><BR><BR><BR><BR></font>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/b00004.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０６／０６更新予告②<BR>
					０６／０６更新予告①<BR>
					０５／３０更新予告③<BR>
				<tr><td bgcolor=green>
					０５／３０更新予告②<BR>
				<tr><td>
					０５／３０更新予告①<BR>
					０５／２３更新予告②<BR>
					０５／２３更新予告①<BR>
					０５／１６更新予告③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０５／３０更新予告②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回は特典をさらに５つ<BR>追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０５／３０更新予告②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
以下の特典が追加されるのニャ！<BR>
<font color=orange>・さすらいの料理ネコ<BR>　【漆黒】<BR>・称号<BR>　【古龍観測隊】<BR>　【シュレイド】<BR>　【ファミ通】<BR></font>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/b00003.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０６／０６更新予告②<BR>
					０６／０６更新予告①<BR>
					０５／３０更新予告③<BR>
					０５／３０更新予告②<BR>
				<tr><td bgcolor=green>
					０５／３０更新予告①<BR>
				<tr><td>
					０５／２３更新予告②<BR>
					０５／２３更新予告①<BR>
					０５／１６更新予告③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０５／３０更新予告①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【ファミ通　吹雪を討つもの】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０５／３０更新予告①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【ファミ通　吹雪を討つもの】</font><BR>
依頼主：あるガンランス使い<BR>あの雪山に僕が長年追い続けた<BR>古龍がいる。あいつの素材で僕<BR>の求めたガンランスが完成する<BR>んだが、…恐ろしく強いんだ！<BR>報酬は弾むよ！手伝ってくれ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60002.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０６／０６更新予告②<BR>
					０６／０６更新予告①<BR>
					０５／３０更新予告③<BR>
					０５／３０更新予告②<BR>
					０５／３０更新予告①<BR>
				<tr><td bgcolor=green>
					０５／２３更新予告②<BR>
				<tr><td>
					０５／２３更新予告①<BR>
					０５／１６更新予告③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０５／２３更新予告②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【チャレンジクエスト　０５】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０５／２３更新予告②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【チャレンジクエスト　０５】</font><BR>
依頼主：教官<BR>ハンターたるもの腹が減っては<BR>大ピンチ！すなわち、食を制す<BR>る者が狩りをも制するのだ！<BR>貴様を最強のコックに仕上げて<BR>やる！肉の調理へ向かうのだ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/c61005.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０６／０６更新予告②<BR>
					０６／０６更新予告①<BR>
					０５／３０更新予告③<BR>
					０５／３０更新予告②<BR>
					０５／３０更新予告①<BR>
					０５／２３更新予告②<BR>
				<tr><td bgcolor=green>
					０５／２３更新予告①<BR>
				<tr><td>
					０５／１６更新予告③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０５／２３更新予告①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【宿命の黒き翼】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０５／２３更新予告①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【宿命の黒き翼】</font><BR>
依頼主：老獪なギルドマスター<BR>古代の城跡で黒い翼の龍の姿を<BR>見たと連絡があってな。調査隊<BR>は消息不明…こりゃ嫌な予感が<BR>するわい。誰か次の調査へ行っ<BR>てくれる者は…おらんかの？<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60030.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>４/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０６／０６更新予告②<BR>
					０６／０６更新予告①<BR>
					０５／３０更新予告③<BR>
					０５／３０更新予告②<BR>
					０５／３０更新予告①<BR>
					０５／２３更新予告②<BR>
					０５／２３更新予告①<BR>
				<tr><td bgcolor=green>
					０５／１６更新予告③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０５／１６更新予告③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回は特典をさらに１つ<BR>追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０５／１６更新予告③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
以下の特典が追加されるのニャ！<BR>
<font color=orange>・称号<BR>　【ジャンプ】<BR><BR><BR><BR><BR></font>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/b00000.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
