<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?pg_no=5",
		"RB_LINK=DB_INFO.PHP?pg_no=7",
		"MOVE_CHAR=GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>７/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					０４／１８更新予告②<BR>
				<tr><td>
					０４／１８更新予告①<BR>
					０４／１１更新予告④<BR>
					０４／１１更新予告③<BR>
					０４／１１更新予告②<BR>
					０４／１１更新予告①<BR>
					０４／０４更新予告③<BR>
					０４／０４更新予告②<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０４／１８更新予告②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【アメザリカーニバル！】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０４／１８更新予告②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【アメザリカーニバル！】</font><BR>
依頼主：アメリカザリガニ<BR>アメリカザリガニから挑戦状！<BR>舞台は逃げ場無き水上闘技場、<BR>２匹の巨大な甲殻種を相手に勝<BR>利できるか！？クリアできたら<BR>スゴい武具が手に入るかも！？<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60001.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>７/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０４／１８更新予告②<BR>
				<tr><td bgcolor=green>
					０４／１８更新予告①<BR>
				<tr><td>
					０４／１１更新予告④<BR>
					０４／１１更新予告③<BR>
					０４／１１更新予告②<BR>
					０４／１１更新予告①<BR>
					０４／０４更新予告③<BR>
					０４／０４更新予告②<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０４／１８更新予告①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【その名は大怪鳥！？】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０４／１８更新予告①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【その名は大怪鳥！？】</font><BR>
依頼主：食の求道者<BR>未知の食材を求めて我はこの地<BR>へ参った。聞けば近辺の丘に幻<BR>ともされる獲物が居るとか…？<BR>我の本懐を遂げんがため…狩人<BR>たちよ、急ぎ狩りへ向かえ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60023.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>７/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０４／１８更新予告②<BR>
					０４／１８更新予告①<BR>
				<tr><td bgcolor=green>
					０４／１１更新予告④<BR>
				<tr><td>
					０４／１１更新予告③<BR>
					０４／１１更新予告②<BR>
					０４／１１更新予告①<BR>
					０４／０４更新予告③<BR>
					０４／０４更新予告②<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０４／１１更新予告④</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【モンハンフェスタ　０１】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０４／１１更新予告④</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【モンハンフェスタ　０１】</font><BR>
依頼主：若き大会運営者<BR>大会へようこそ！<BR>此度は樹海でのナルガクルガ討<BR>伐を依頼させていただきます。<BR>腕を疑うわけではありませんが<BR>その実力、見せてください！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/f00001.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>７/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０４／１８更新予告②<BR>
					０４／１８更新予告①<BR>
					０４／１１更新予告④<BR>
				<tr><td bgcolor=green>
					０４／１１更新予告③<BR>
				<tr><td>
					０４／１１更新予告②<BR>
					０４／１１更新予告①<BR>
					０４／０４更新予告③<BR>
					０４／０４更新予告②<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０４／１１更新予告③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【チャレンジクエスト　０２】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０４／１１更新予告③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【チャレンジクエスト　０２】</font><BR>
依頼主：教官<BR>奇面族からの挑戦だ！ハンター<BR>を代表して挑戦を受けたのだが<BR>我輩大事な用があったのを忘れ<BR>ておった。貴様が代わりに行っ<BR>て見事勝利を飾ってくるのだ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/c61002.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>７/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０４／１８更新予告②<BR>
					０４／１８更新予告①<BR>
					０４／１１更新予告④<BR>
					０４／１１更新予告③<BR>
				<tr><td bgcolor=green>
					０４／１１更新予告②<BR>
				<tr><td>
					０４／１１更新予告①<BR>
					０４／０４更新予告③<BR>
					０４／０４更新予告②<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０４／１１更新予告②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【猪突乱撃！】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０４／１１更新予告②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【猪突乱撃！】</font><BR>
依頼主：目つきの怪しい貴婦人<BR>アタクシのパーティの余興に参<BR>加してくださるハンターさんを<BR>募集していますの。ウフフフ…<BR>縦横無尽に駆け回る猪の群れ…<BR>あなたは避けきれるかしらッ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60020.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>７/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０４／１８更新予告②<BR>
					０４／１８更新予告①<BR>
					０４／１１更新予告④<BR>
					０４／１１更新予告③<BR>
					０４／１１更新予告②<BR>
				<tr><td bgcolor=green>
					０４／１１更新予告①<BR>
				<tr><td>
					０４／０４更新予告③<BR>
					０４／０４更新予告②<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０４／１１更新予告①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【ジャングルハント！】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０４／１１更新予告①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【ジャングルハント！】</font><BR>
依頼主：居丈高な貴族<BR>僕らは庶民の生活のため勇気を<BR>出し密林の調査に赴いたのだ。<BR>だがこんな危険な場所とは母上<BR>からも聞いていないぞ！先行し<BR>僕たちの安全を確保したまえ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60027.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>７/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０４／１８更新予告②<BR>
					０４／１８更新予告①<BR>
					０４／１１更新予告④<BR>
					０４／１１更新予告③<BR>
					０４／１１更新予告②<BR>
					０４／１１更新予告①<BR>
				<tr><td bgcolor=green>
					０４／０４更新予告③<BR>
				<tr><td>
					０４／０４更新予告②<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０４／０４更新予告③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回は特典をさらに１つ<BR>追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０４／０４更新予告③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
以下の特典が追加されるのニャ！<BR>
<font color=orange>・称号<BR>　【マガジン】<BR><BR><BR><BR><BR></font>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/b00000.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>７/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０４／１８更新予告②<BR>
					０４／１８更新予告①<BR>
					０４／１１更新予告④<BR>
					０４／１１更新予告③<BR>
					０４／１１更新予告②<BR>
					０４／１１更新予告①<BR>
					０４／０４更新予告③<BR>
				<tr><td bgcolor=green>
					０４／０４更新予告②<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０４／０４更新予告②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
週刊少年マガジン創刊50周年と<BR>少年ライバル発売を記念して、<BR>次回のクエストは<BR><font color=orange>【マガジン　暴虐の轟竜】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０４／０４更新予告②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【マガジン　暴虐の轟竜】</font><BR>
依頼主：火竜の鎧を纏った男<BR>最近は口先ばかりで一流と認め<BR>られるハンターはいやしねぇ。<BR>そこでこの話だ…辺境の闘技場<BR>に轟竜が棲みついたらしい。<BR>倒せたら一流と認めてやるぜ？<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60008.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
