<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?pg_no=4",
		"RB_LINK=DB_INFO.PHP?pg_no=6",
		"MOVE_CHAR=GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					０５／０２更新予告④<BR>
				<tr><td>
					０５／０２更新予告③<BR>
					０５／０２更新予告②<BR>
					０５／０２更新予告①<BR>
					０４／２５更新予告④<BR>
					０４／２５更新予告③<BR>
					０４／２５更新予告②<BR>
					０４／２５更新予告①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０５／０２更新予告④</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回は特典をさらに６つ<BR>追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０５／０２更新予告④</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
以下の特典が追加されるのニャ！<BR>
<font color=orange>・称号<BR>　【書士隊】<BR>　【王立学術院】<BR>　【電撃】<BR>・プーギーの服<BR>　【天使のレオタード】<BR></font>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/b00002.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０５／０２更新予告④<BR>
				<tr><td bgcolor=green>
					０５／０２更新予告③<BR>
				<tr><td>
					０５／０２更新予告②<BR>
					０５／０２更新予告①<BR>
					０４／２５更新予告④<BR>
					０４／２５更新予告③<BR>
					０４／２５更新予告②<BR>
					０４／２５更新予告①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０５／０２更新予告③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回は特典をさらに６つ<BR>追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０５／０２更新予告③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
以下の特典が追加されるのニャ！<BR>
<font color=orange>・さすらいの料理ネコ<BR>　【オレンジ】<BR>・オトモアイルー防具<BR>　【ネコ武者鎧】<BR><BR><BR></font>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/b00001.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０５／０２更新予告④<BR>
					０５／０２更新予告③<BR>
				<tr><td bgcolor=green>
					０５／０２更新予告②<BR>
				<tr><td>
					０５／０２更新予告①<BR>
					０４／２５更新予告④<BR>
					０４／２５更新予告③<BR>
					０４／２５更新予告②<BR>
					０４／２５更新予告①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０５／０２更新予告②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【「マ）王　マオウ再び！】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０５／０２更新予告②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【「マ）王　マオウ再び！】</font><BR>
依頼主：元ハンターの老爺<BR>片角のマオウをご存知か？その<BR>躯は巨大で他の同種とは格の違<BR>う強さらしい…以前倒されたと<BR>聞いていたが、最近再び噂を耳<BR>にした。調べてみてくれんか？<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60004.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０５／０２更新予告④<BR>
					０５／０２更新予告③<BR>
					０５／０２更新予告②<BR>
				<tr><td bgcolor=green>
					０５／０２更新予告①<BR>
				<tr><td>
					０４／２５更新予告④<BR>
					０４／２５更新予告③<BR>
					０４／２５更新予告②<BR>
					０４／２５更新予告①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０５／０２更新予告①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【栄冠を求めて】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０５／０２更新予告①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【栄冠を求めて】</font><BR>
依頼主：若手の闘技場運営者<BR>力こそが全ての闘技場！本日は<BR>ババコンガ、リオレイア、ショ<BR>ウグンギザミと多彩な相手を用<BR>意しました。剥ぎ取れる回復薬<BR>をうまく使ってくださいね！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60025.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０５／０２更新予告④<BR>
					０５／０２更新予告③<BR>
					０５／０２更新予告②<BR>
					０５／０２更新予告①<BR>
				<tr><td bgcolor=green>
					０４／２５更新予告④<BR>
				<tr><td>
					０４／２５更新予告③<BR>
					０４／２５更新予告②<BR>
					０４／２５更新予告①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０４／２５更新予告④</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【チャレンジクエスト　０３】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０４／２５更新予告④</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【チャレンジクエスト　０３】</font><BR>
依頼主：教官<BR>今度水上闘技場で闘技会がある<BR>のだ。貰える金額が良かったの<BR>で参加を申し込んでおいたぞ。<BR>何？うまい話には裏が？…貴様<BR>なら大丈夫だ！…多分。<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/c61003.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０５／０２更新予告④<BR>
					０５／０２更新予告③<BR>
					０５／０２更新予告②<BR>
					０５／０２更新予告①<BR>
					０４／２５更新予告④<BR>
				<tr><td bgcolor=green>
					０４／２５更新予告③<BR>
				<tr><td>
					０４／２５更新予告②<BR>
					０４／２５更新予告①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０４／２５更新予告③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【祖なるもの】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０４／２５更新予告③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【祖なるもの】</font><BR>
依頼主：純白のアイルー<BR>旦那！これから古塔へ行ってみ<BR>ないかニャ？行かないといけな<BR>いようニャ…でも、行ったらト<BR>ンデモないことになるような…<BR>なんだか胸騒ぎがするのニャ…<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60029.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０５／０２更新予告④<BR>
					０５／０２更新予告③<BR>
					０５／０２更新予告②<BR>
					０５／０２更新予告①<BR>
					０４／２５更新予告④<BR>
					０４／２５更新予告③<BR>
				<tr><td bgcolor=green>
					０４／２５更新予告②<BR>
				<tr><td>
					０４／２５更新予告①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０４／２５更新予告②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【二色の双にゃふ・小闘技場】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０４／２５更新予告②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【二色の双にゃふ・小闘技場】</font><BR>
依頼主：白い獣人と黒い獣人<BR>「全国１００万人のアイルー好<BR>きのみんな！待たせたのデス！<BR>ボクらからの挑戦デス！」<BR>「見事クリアできたら特別な<BR>チケットを進呈するで！」<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60033.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=220 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr>
			<td>
				<table width=198 cellspacing=0>
				<tr>
					<td height=34 width=198 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/８</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					０５／０２更新予告④<BR>
					０５／０２更新予告③<BR>
					０５／０２更新予告②<BR>
					０５／０２更新予告①<BR>
					０４／２５更新予告④<BR>
					０４／２５更新予告③<BR>
					０４／２５更新予告②<BR>
				<tr><td bgcolor=green>
					０４／２５更新予告①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=260>
		<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=yellow>０４／２５更新予告①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
次回はクエスト<BR><font color=orange>【大繁殖！眠鳥の乱】</font><BR>を追加予定ニャ！<BR>詳しく知りたかったら<BR>□ボタンを押すのニャ！<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=34 align=center valign=center top colspan=2>
			<font size=2>
			<font color=yellow>０４／２５更新予告①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=16 align=left colspan=2>
次回の内容をちょっとだけ教えちゃうのニャ！
			</td>
	</tr>
	<tr>
		<td width=240 height=120 align=left valign=top center>
			<font size=2>
<font color=orange>【大繁殖！眠鳥の乱】</font><BR>
依頼主：決意に燃える獣人<BR>静かな場所だと聞いて家を買っ<BR>たのにヒプノックだらけだニャ<BR>んて！オイラのマイホームを守<BR>るため、ハンターさんは１頭で<BR>も多く狩るのを手伝うのニャ！<BR>
			</font>
		</td>
		<td width=210 height=129 align=center valign=center>
			<img src=PNG/e60026.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
