<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:7",
		"MOVE_CHAR=GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=GIF/PIG.gif,64,48,1,1,3,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<B>
<img src=GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=GIF/HUKIDASI.gif>
<form action="BONUS/bonus.mib" BDOWNLOAD method=post>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td width=432 height=131 valign=top>
<img src="" width=10 height=10><BR>
特典は全て開放されているニャ！<BR>
						詳細は□ボタンで確認してほしいのニャー。
			</td>
		</tr>
		<tr>
			<td height=46 align=center>
				<img ANIME=10 src=GIF/BDL.gif width=210 height=46 alt="[O] DOWNLOAD"><BR>
				<input type=image src="" name=submit width=0 height=0>
			</td>
		</tr>
		<tr>
			<td align=right height=20>
			</td>
		</tr>
		</table>
	</td>
</tr>
</form>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<a name=002></a>
<img src=GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
				<tr>
					<td align=center>
						<B>１/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<BR></font>
【さすらいの料理ネコ】<BR>この毛並みのアイルーが村を訪れるようになる…かもニャ。<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=00>・赤虎</a><BR>
<a href=#003 qname=01>・オレンジ</a><BR>
<a href=#003 qname=02>・漆黒</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=PNG/bonus03.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<a name=003></a>
<img src=GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
				<tr>
					<td align=center>
						<B>２/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<BR></font>
【オトモアイルー防具】<BR>オトモアイルーの着せ替え用の防具が追加されるニャ。<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=25>・ネコ武者鎧</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=PNG/bonus19.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<a name=004></a>
<img src=GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
				<tr>
					<td align=center>
						<B>３/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<BR></font>
【オトモスキル】<BR>修得できるオトモスキルが追加されるニャ。<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=26>・属性攻撃【龍】</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=PNG/bonus15.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<a name=005></a>
<img src=GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
				<tr>
					<td align=center>
						<B>４/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<BR></font>
【称号】<BR>ギルドカードで使う称号が追加されるニャ。<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#004 qname=03>・ココット</a><BR>
<a href=#004 qname=04>・ジャンボ</a><BR>
<a href=#004 qname=05>・ミナガルデ</a><BR>
<a href=#004 qname=06>・ドンドルマ</a><BR>
			</td>
			<td width=232 height=90 valign=top>
<a href=#009 qname=20>・書士隊</a><BR>
<a href=#009 qname=21>・王立学術院</a><BR>
<a href=#009 qname=23>・古龍観測隊</a><BR>
<a href=#009 qname=22>・シュレイド</a><BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<a name=006></a>
<img src=GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
				<tr>
					<td align=center>
						<B>５/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<BR></font>
【称号】<BR>ギルドカードで使う称号が追加されるニャ。<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#009 qname=17>・マガジン</a><BR>
<a href=#009 qname=15>・電撃</a><BR>
<a href=#009 qname=16>・ジャンプ</a><BR>
<a href=#009 qname=14>・ファミ通</a><BR>
			</td>
			<td width=232 height=90 valign=top>
<a href=#009 qname=18>・狩魂</a><BR>
<a href=#009 qname=19>・歌姫</a><BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<a name=007></a>
<img src=GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
				<tr>
					<td align=center>
						<B>６/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<BR></font>
【プーギーの服】<BR>プーギーの着せ替え用の服が追加されるニャ。<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#002 qname=09>・ファミ通ヒゲ眼鏡</a><BR>
<a href=#002 qname=07>・天使のレオタード</a><BR>
<a href=#002 qname=08>・眠りを誘う白</a><BR>
<a href=#002 qname=13>・マフモフウォーマー</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=PNG/bonus14.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<a name=008></a>
<img src=GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
				<tr>
					<td align=center>
						<B>７/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<BR></font>
【ポッケポイント】<BR>ポッケポイントが３０００ポイント貰えるニャ。<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#005 qname=24>・３０００ポイント入手</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=PNG/bonus11.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<a name=009></a>
<img src=GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
				<tr>
					<td align=center>
						<B>８/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<BR></font>
【農場施設】<BR>トレニャーの船が建造可能になるニャ。<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#006 qname=11>・トレニャーの船</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=PNG/bonus12.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<a name=010></a>
<img src=GIF/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
				<tr>
					<td align=center>
						<B>９/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<BR></font>
【行商ばあちゃんの品揃え】<BR>いつもよりずっと良い品を仕入れてくれる…かもニャ。
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#007 qname=12>・特別な品揃え</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=PNG/bonus13.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
