<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_CMENU.PHP?pg_no=0",
		"RB_LINK=DL_CMENU.PHP?pg_no=0",
		"MOVE_CHAR=GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=GIF/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m61013.mib" DOWNLOAD CSUM=39051 FSIZE=2376 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m61013>モンハンフェスタ　０３</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m61012>モンハンフェスタ　０２</a><BR>
				<a href=#003 qname=m61004>チャレンジクエスト　０４</a><BR>
				<a href=#004 qname=m61003>チャレンジクエスト　０３</a><BR>
				<a href=#005 qname=m61011>モンハンフェスタ　０１</a><BR>
				<a href=#006 qname=m61002>チャレンジクエスト　０２</a><BR>
				<a href=#007 qname=m61001>チャレンジクエスト　０１</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				モンハンフェスタ　０３
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>　報酬金　：</font> ３０００ｚ<br>
				<font color=orangered>　契約金　：</font> ０ｚ<br>
				<font color=orangered>　制限時間：</font> ２０分<br>
				<font color=orangered>　指定地　：</font> 大闘技場<br>
				<font color=orangered>　特殊条件：</font><br>　なし<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_RED2.gif></td>
					<td width=219 height=18 background=GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				モンハンフェスタ　０３
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>すべての大型モンスターの討伐<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>依頼主：</font>妖艶な大会運営者<BR>
					ふふ、大会もいよいよ佳境ね。<BR>続けざまに登場するモンスター<BR>を打ち倒し、勝利の証を手にす<BR>るのはどのハンターかしら。華<BR>麗なテクニックを期待するわ。<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=GIF/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m61012.mib" DOWNLOAD CSUM=34473 FSIZE=2316 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61013>モンハンフェスタ　０３</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m61012>モンハンフェスタ　０２</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m61004>チャレンジクエスト　０４</a><BR>
				<a href=#004 qname=m61003>チャレンジクエスト　０３</a><BR>
				<a href=#005 qname=m61011>モンハンフェスタ　０１</a><BR>
				<a href=#006 qname=m61002>チャレンジクエスト　０２</a><BR>
				<a href=#007 qname=m61001>チャレンジクエスト　０１</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				モンハンフェスタ　０２
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>　報酬金　：</font> ３０００ｚ<br>
				<font color=orangered>　契約金　：</font> ０ｚ<br>
				<font color=orangered>　制限時間：</font> １５分<br>
				<font color=orangered>　指定地　：</font> 大闘技場<br>
				<font color=orangered>　特殊条件：</font><br>　なし<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_RED2.gif></td>
					<td width=219 height=18 background=GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				モンハンフェスタ　０２
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>ティガレックス１頭の討伐<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>依頼主：</font>豪快な大会運営者<BR>
					さぁ、祭りだッ！今回の相手は<BR>轟竜ティガレックス！<BR>知っての通りその力は圧倒的！<BR>だが先へ進むのならば、この壁<BR>を見事、乗り越えてみせろ！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=GIF/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m61004.mib" DOWNLOAD CSUM=46326 FSIZE=6000 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61013>モンハンフェスタ　０３</a><BR>
				<a href=#002 qname=m61012>モンハンフェスタ　０２</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m61004>チャレンジクエスト　０４</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m61003>チャレンジクエスト　０３</a><BR>
				<a href=#005 qname=m61011>モンハンフェスタ　０１</a><BR>
				<a href=#006 qname=m61002>チャレンジクエスト　０２</a><BR>
				<a href=#007 qname=m61001>チャレンジクエスト　０１</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				チャレンジクエスト　０４
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>　報酬金　：</font> ２１０００ｚ<br>
				<font color=orangered>　契約金　：</font> ０ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 旧密林<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_RED2.gif></td>
					<td width=219 height=18 background=GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				チャレンジクエスト　０４
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>すべての大型モンスターの討伐<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>依頼主：</font>教官<BR>
					モンスターの心を知るにはモン<BR>スターになりきるのが一番！<BR>というわけでそんな訓練を用意<BR>してみたぞ。この装備で己の内<BR>に宿る獣の魂を解放するのだ！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=GIF/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m61003.mib" DOWNLOAD CSUM=52374 FSIZE=1976 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61013>モンハンフェスタ　０３</a><BR>
				<a href=#002 qname=m61012>モンハンフェスタ　０２</a><BR>
				<a href=#003 qname=m61004>チャレンジクエスト　０４</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m61003>チャレンジクエスト　０３</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m61011>モンハンフェスタ　０１</a><BR>
				<a href=#006 qname=m61002>チャレンジクエスト　０２</a><BR>
				<a href=#007 qname=m61001>チャレンジクエスト　０１</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				チャレンジクエスト　０３
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>　報酬金　：</font> ６００００ｚ<br>
				<font color=orangered>　契約金　：</font> ０ｚ<br>
				<font color=orangered>　制限時間：</font> ４０分<br>
				<font color=orangered>　指定地　：</font> 水上闘技場<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_RED2.gif></td>
					<td width=219 height=18 background=GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				チャレンジクエスト　０３
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>ガノトトス１頭の討伐<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>依頼主：</font>教官<BR>
					今度水上闘技場で闘技会がある<BR>のだ。貰える金額が良かったの<BR>で参加を申し込んでおいたぞ。<BR>何？うまい話には裏が？…貴様<BR>なら大丈夫だ！…多分。<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=GIF/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m61011.mib" DOWNLOAD CSUM=33691 FSIZE=3372 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61013>モンハンフェスタ　０３</a><BR>
				<a href=#002 qname=m61012>モンハンフェスタ　０２</a><BR>
				<a href=#003 qname=m61004>チャレンジクエスト　０４</a><BR>
				<a href=#004 qname=m61003>チャレンジクエスト　０３</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m61011>モンハンフェスタ　０１</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m61002>チャレンジクエスト　０２</a><BR>
				<a href=#007 qname=m61001>チャレンジクエスト　０１</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				モンハンフェスタ　０１
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>　報酬金　：</font> ２４００ｚ<br>
				<font color=orangered>　契約金　：</font> ０ｚ<br>
				<font color=orangered>　制限時間：</font> １５分<br>
				<font color=orangered>　指定地　：</font> 樹海＜昼＞<br>
				<font color=orangered>　特殊条件：</font><br>　なし<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_RED2.gif></td>
					<td width=219 height=18 background=GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				モンハンフェスタ　０１
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>ナルガクルガ１頭の討伐<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>依頼主：</font>若き大会運営者<BR>
					大会へようこそ！<BR>此度は樹海でのナルガクルガ討<BR>伐を依頼させていただきます。<BR>腕を疑うわけではありませんが<BR>その実力、見せてください！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=GIF/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m61002.mib" DOWNLOAD CSUM=38320 FSIZE=2388 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61013>モンハンフェスタ　０３</a><BR>
				<a href=#002 qname=m61012>モンハンフェスタ　０２</a><BR>
				<a href=#003 qname=m61004>チャレンジクエスト　０４</a><BR>
				<a href=#004 qname=m61003>チャレンジクエスト　０３</a><BR>
				<a href=#005 qname=m61011>モンハンフェスタ　０１</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m61002>チャレンジクエスト　０２</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m61001>チャレンジクエスト　０１</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				チャレンジクエスト　０２
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>　報酬金　：</font> ７５００ｚ<br>
				<font color=orangered>　契約金　：</font> ０ｚ<br>
				<font color=orangered>　制限時間：</font> ２０分<br>
				<font color=orangered>　指定地　：</font> 大闘技場<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ４以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_RED2.gif></td>
					<td width=219 height=18 background=GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				チャレンジクエスト　０２
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>キングチャチャブー２匹の討伐<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★<BR>
					<font color=orangered>依頼主：</font>教官<BR>
					奇面族からの挑戦だ！ハンター<BR>を代表して挑戦を受けたのだが<BR>我輩大事な用があったのを忘れ<BR>ておった。貴様が代わりに行っ<BR>て見事勝利を飾ってくるのだ！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=GIF/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m61001.mib" DOWNLOAD CSUM=39983 FSIZE=5908 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61013>モンハンフェスタ　０３</a><BR>
				<a href=#002 qname=m61012>モンハンフェスタ　０２</a><BR>
				<a href=#003 qname=m61004>チャレンジクエスト　０４</a><BR>
				<a href=#004 qname=m61003>チャレンジクエスト　０３</a><BR>
				<a href=#005 qname=m61011>モンハンフェスタ　０１</a><BR>
				<a href=#006 qname=m61002>チャレンジクエスト　０２</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m61001>チャレンジクエスト　０１</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				チャレンジクエスト　０１
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>　報酬金　：</font> ６０００ｚ<br>
				<font color=orangered>　契約金　：</font> ０ｚ<br>
				<font color=orangered>　制限時間：</font> ４０分<br>
				<font color=orangered>　指定地　：</font> 密林＜夜＞<br>
				<font color=orangered>　特殊条件：</font><br>　なし<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_RED2.gif></td>
					<td width=219 height=18 background=GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				チャレンジクエスト　０１
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>イャンガルルガ１頭の討伐<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★<BR>
					<font color=orangered>依頼主：</font>教官<BR>
					密林にて黒狼鳥イャンガルルガ<BR>が目撃された。我輩思うに、<BR>これは良い訓練になるはず…。<BR>さあ、装備は貸してやるから<BR>ちょっと狩ってこい！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
