<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?pg_no=3",
		"RB_LINK=DL_MENU.PHP?pg_no=5",
		"MOVE_CHAR=GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60033.mib" DOWNLOAD CSUM=65431 FSIZE=1532 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>５/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60033>二色の双にゃふ・小闘技場</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m60026>大繁殖！眠鳥の乱</a><BR>
				<a href=#003 qname=m60001>アメザリカーニバル！</a><BR>
				<a href=#004 qname=m60023>その名は大怪鳥！？</a><BR>
				<a href=#005 qname=m60020>猪突乱撃！</a><BR>
				<a href=#006 qname=m60027>ジャングルハント！</a><BR>
				<a href=#007 qname=m60008>マガジン　暴虐の轟竜</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				二色の双にゃふ・小闘技場
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ４５００ｚ<br>
				<font color=orangered>　契約金　：</font> ４００ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 闘技場<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ４以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_RED2.gif></td>
					<td width=219 height=18 background=GIF/T_RED.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				二色の双にゃふ・小闘技場
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>アイルー２０匹の討伐<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★<BR>
					<font color=orangered>依頼主：</font>白い獣人と黒い獣人<BR>
					「全国１００万人のアイルー好<BR>きのみんな！待たせたのデス！<BR>ボクらからの挑戦デス！」<BR>「見事クリアできたら特別な<BR>チケットを進呈するで！」<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60026.mib" DOWNLOAD CSUM=55110 FSIZE=5612 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>５/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60033>二色の双にゃふ・小闘技場</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60026>大繁殖！眠鳥の乱</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m60001>アメザリカーニバル！</a><BR>
				<a href=#004 qname=m60023>その名は大怪鳥！？</a><BR>
				<a href=#005 qname=m60020>猪突乱撃！</a><BR>
				<a href=#006 qname=m60027>ジャングルハント！</a><BR>
				<a href=#007 qname=m60008>マガジン　暴虐の轟竜</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				大繁殖！眠鳥の乱
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ９０００ｚ<br>
				<font color=orangered>　契約金　：</font> ７５０ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 樹海＜昼＞<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ４以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_WHT2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				大繁殖！眠鳥の乱
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>タイムアップもしくは、<BR>ネコタクチケットの納品<BR><BR>
					<font color=orangered>失敗条件：</font><br>２頭以上を狩猟せずにタイム<BR>アップ、もしくは報奨金ゼロ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★★<BR>
					<font color=orangered>依頼主：</font>決意に燃える獣人<BR>
					静かな場所だと聞いて家を買っ<BR>たのにヒプノックだらけだニャ<BR>んて！オイラのマイホームを守<BR>るため、ハンターさんは１頭で<BR>も多く狩るのを手伝うのニャ！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60001.mib" DOWNLOAD CSUM=60714 FSIZE=1508 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>５/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60033>二色の双にゃふ・小闘技場</a><BR>
				<a href=#002 qname=m60026>大繁殖！眠鳥の乱</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60001>アメザリカーニバル！</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m60023>その名は大怪鳥！？</a><BR>
				<a href=#005 qname=m60020>猪突乱撃！</a><BR>
				<a href=#006 qname=m60027>ジャングルハント！</a><BR>
				<a href=#007 qname=m60008>マガジン　暴虐の轟竜</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				アメザリカーニバル！
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ２７０００ｚ<br>
				<font color=orangered>　契約金　：</font> ２２５０ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 水上闘技場<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_WHT2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				アメザリカーニバル！
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>ダイミョウザザミ亜種１匹と<BR>ショウグンギザミ亜種１匹の<BR>狩猟<BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>依頼主：</font>アメリカザリガニ<BR>
					アメリカザリガニから挑戦状！<BR>舞台は逃げ場無き水上闘技場、<BR>２匹の巨大な甲殻種を相手に勝<BR>利できるか！？クリアできたら<BR>スゴい武具が手に入るかも！？<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60023.mib" DOWNLOAD CSUM=30740 FSIZE=4816 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>５/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60033>二色の双にゃふ・小闘技場</a><BR>
				<a href=#002 qname=m60026>大繁殖！眠鳥の乱</a><BR>
				<a href=#003 qname=m60001>アメザリカーニバル！</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60023>その名は大怪鳥！？</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m60020>猪突乱撃！</a><BR>
				<a href=#006 qname=m60027>ジャングルハント！</a><BR>
				<a href=#007 qname=m60008>マガジン　暴虐の轟竜</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				その名は大怪鳥！？
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ６０００ｚ<br>
				<font color=orangered>　契約金　：</font> ５００ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 森丘＜昼＞<br>
				<font color=orangered>　特殊条件：</font><br>　受注＆参加資格は、<BR>　防具未装備<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_WHT2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				その名は大怪鳥！？
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>イャンクック？２頭の狩猟<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★<BR>
					<font color=orangered>依頼主：</font>食の求道者<BR>
					未知の食材を求めて我はこの地<BR>へ参った。聞けば近辺の丘に幻<BR>ともされる獲物が居るとか…？<BR>我の本懐を遂げんがため…狩人<BR>たちよ、急ぎ狩りへ向かえ！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60020.mib" DOWNLOAD CSUM=58085 FSIZE=1496 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>５/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60033>二色の双にゃふ・小闘技場</a><BR>
				<a href=#002 qname=m60026>大繁殖！眠鳥の乱</a><BR>
				<a href=#003 qname=m60001>アメザリカーニバル！</a><BR>
				<a href=#004 qname=m60023>その名は大怪鳥！？</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60020>猪突乱撃！</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m60027>ジャングルハント！</a><BR>
				<a href=#007 qname=m60008>マガジン　暴虐の轟竜</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				猪突乱撃！
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ８４００ｚ<br>
				<font color=orangered>　契約金　：</font> ７００ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 闘技場<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_RED2.gif></td>
					<td width=219 height=18 background=GIF/T_RED.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				猪突乱撃！
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>ブルファンゴ３０頭の討伐<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★<BR>
					<font color=orangered>依頼主：</font>目つきの怪しい貴婦人<BR>
					アタクシのパーティの余興に参<BR>加してくださるハンターさんを<BR>募集していますの。ウフフフ…<BR>縦横無尽に駆け回る猪の群れ…<BR>あなたは避けきれるかしらッ！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60027.mib" DOWNLOAD CSUM=13534 FSIZE=6308 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>５/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60033>二色の双にゃふ・小闘技場</a><BR>
				<a href=#002 qname=m60026>大繁殖！眠鳥の乱</a><BR>
				<a href=#003 qname=m60001>アメザリカーニバル！</a><BR>
				<a href=#004 qname=m60023>その名は大怪鳥！？</a><BR>
				<a href=#005 qname=m60020>猪突乱撃！</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60027>ジャングルハント！</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m60008>マガジン　暴虐の轟竜</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				ジャングルハント！
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> １４１００ｚ<br>
				<font color=orangered>　契約金　：</font> １２００ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 密林＜昼＞<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ４以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_PNK2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				ジャングルハント！
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>すべての大型モンスターの狩猟<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★★<BR>
					<font color=orangered>依頼主：</font>居丈高な貴族<BR>
					僕らは庶民の生活のため勇気を<BR>出し密林の調査に赴いたのだ。<BR>だがこんな危険な場所とは母上<BR>からも聞いていないぞ！先行し<BR>僕たちの安全を確保したまえ！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60008.mib" DOWNLOAD CSUM=39975 FSIZE=1364 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>５/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60033>二色の双にゃふ・小闘技場</a><BR>
				<a href=#002 qname=m60026>大繁殖！眠鳥の乱</a><BR>
				<a href=#003 qname=m60001>アメザリカーニバル！</a><BR>
				<a href=#004 qname=m60023>その名は大怪鳥！？</a><BR>
				<a href=#005 qname=m60020>猪突乱撃！</a><BR>
				<a href=#006 qname=m60027>ジャングルハント！</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60008>マガジン　暴虐の轟竜</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				マガジン　暴虐の轟竜
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> １５０００ｚ<br>
				<font color=orangered>　契約金　：</font> １２５０ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 大闘技場<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_WHT2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				マガジン　暴虐の轟竜
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>ティガレックス１頭の狩猟<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>依頼主：</font>火竜の鎧を纏った男<BR>
					最近は口先ばかりで一流と認め<BR>られるハンターはいやしねぇ。<BR>そこでこの話だ…辺境の闘技場<BR>に轟竜が棲みついたらしい。<BR>倒せたら一流と認めてやるぜ？<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
