<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?pg_no=4",
		"RB_LINK=DL_MENU.PHP?pg_no=0",
		"MOVE_CHAR=GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60024.mib" DOWNLOAD CSUM=1572 FSIZE=6224 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>６/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60024>砂漠の三怪</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m60013>悪臭を絶て！</a><BR>
				<a href=#003 qname=m60036>ＪＵＭＰ　炎帝の凱旋</a><BR>
					<BR>
					<BR>
					<BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				砂漠の三怪
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> １２３００ｚ<br>
				<font color=orangered>　契約金　：</font> １０５０ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 砂漠＜昼＞<br>
				<font color=orangered>　特殊条件：</font><br>　なし<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_PNK2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				砂漠の三怪
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>すべての大型モンスターの狩猟<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>依頼主：</font>北方から来た薬売り<BR>
					何だよこの砂漠は！１日でモン<BR>スターと３度遭遇するなんて！<BR>運んでいた商品、大量の回復薬<BR>を置いてきちまった…今頃は<BR>モンスターの腹の中かなぁ。<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60013.mib" DOWNLOAD CSUM=23364 FSIZE=4828 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>６/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60024>砂漠の三怪</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60013>悪臭を絶て！</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m60036>ＪＵＭＰ　炎帝の凱旋</a><BR>
					<BR>
					<BR>
					<BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				悪臭を絶て！
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> １８０００ｚ<br>
				<font color=orangered>　契約金　：</font> １５００ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 沼地＜昼＞<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_WHT2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				悪臭を絶て！
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>ババコンガ亜種１頭と<BR>ババコンガ１頭の狩猟<BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★<BR>
					<font color=orangered>依頼主：</font>湖畔の村の主婦<BR>
					聞いとくれよ！うちの村へ流れ<BR>てくる水が急に臭くなっちまっ<BR>たんだ！きっと水源に何かある<BR>に違いないよ…原因を見つけて<BR>バシッと解決してきておくれ！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60036.mib" DOWNLOAD CSUM=1891 FSIZE=1564 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>６/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60024>砂漠の三怪</a><BR>
				<a href=#002 qname=m60013>悪臭を絶て！</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60036>ＪＵＭＰ　炎帝の凱旋</a><BR>
			<tr><td height=78 valign=top>
					<BR>
					<BR>
					<BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				ＪＵＭＰ　炎帝の凱旋
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> １２０００ｚ<br>
				<font color=orangered>　契約金　：</font> １０００ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 街<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ６以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_RED2.gif></td>
					<td width=219 height=18 background=GIF/T_RED.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				ＪＵＭＰ　炎帝の凱旋
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>テオ・テスカトル１体の討伐<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★★★<BR>
					<font color=orangered>依頼主：</font>隻眼黒髭の男<BR>
					街は今、炎王龍によって蹂躙さ<BR>れようとしている。そこでだ…<BR>どうだ、俺にお前が街を救うと<BR>ころを見せてはくれねぇか？<BR>勿論、報酬は期待していいぜ。<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
