<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?pg_no=0",
		"RB_LINK=DL_MENU.PHP?pg_no=2",
		"MOVE_CHAR=GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60014.mib" DOWNLOAD CSUM=62516 FSIZE=1516 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60014>二色の双角・闘技場</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m60022>マグマの海に擁かれて</a><BR>
				<a href=#003 qname=m60007>ＪＵＭＰ　赤き闘技会</a><BR>
				<a href=#004 qname=m60032>白光</a><BR>
				<a href=#005 qname=m60021>ヒプノック大乱闘！</a><BR>
				<a href=#006 qname=m60005>電撃祭Ｇ　イカヅチの山</a><BR>
				<a href=#007 qname=m60003>ファミ通　桜舞う季節</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				二色の双角・闘技場
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ３３０００ｚ<br>
				<font color=orangered>　契約金　：</font> ２７５０ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 大闘技場<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_WHT2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				二色の双角・闘技場
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>ディアブロス亜種１頭と<BR>ディアブロス１頭の狩猟<BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>依頼主：</font>初老の闘技場支配人<BR>
					この仕事とは離れていたんだが<BR>あの時の興奮が忘れられなくて<BR>戻ってきてしまったよ！さぁ、<BR>今回は２頭のディアブロスが君<BR>達の相手だ！頑張ってくれよ！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60022.mib" DOWNLOAD CSUM=24270 FSIZE=5828 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>二色の双角・闘技場</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60022>マグマの海に擁かれて</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m60007>ＪＵＭＰ　赤き闘技会</a><BR>
				<a href=#004 qname=m60032>白光</a><BR>
				<a href=#005 qname=m60021>ヒプノック大乱闘！</a><BR>
				<a href=#006 qname=m60005>電撃祭Ｇ　イカヅチの山</a><BR>
				<a href=#007 qname=m60003>ファミ通　桜舞う季節</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				マグマの海に擁かれて
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> １３５００ｚ<br>
				<font color=orangered>　契約金　：</font> １１５０ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 火山＜夜＞<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_WHT2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				マグマの海に擁かれて
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>ヴォルガノス１頭の狩猟<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>依頼主：</font>浅黒い肌の鉱夫<BR>
					俺っちが一仕事終えて帰ろうと<BR>した時の話さ…火山の奥でマグ<BR>マに浮かぶ巨大な黒い影を見た<BR>んだ！きっとこの火山のヌシに<BR>違いねぇ！調査を頼むぜ！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60007.mib" DOWNLOAD CSUM=28131 FSIZE=1772 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>二色の双角・闘技場</a><BR>
				<a href=#002 qname=m60022>マグマの海に擁かれて</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60007>ＪＵＭＰ　赤き闘技会</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m60032>白光</a><BR>
				<a href=#005 qname=m60021>ヒプノック大乱闘！</a><BR>
				<a href=#006 qname=m60005>電撃祭Ｇ　イカヅチの山</a><BR>
				<a href=#007 qname=m60003>ファミ通　桜舞う季節</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				ＪＵＭＰ　赤き闘技会
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ２９４００ｚ<br>
				<font color=orangered>　契約金　：</font> ２４５０ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 大闘技場<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_PNK2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				ＪＵＭＰ　赤き闘技会
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>すべての大型モンスターの狩猟<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>依頼主：</font>海賊団の副長<BR>
					ウチのボスが誕生日だってんで<BR>祝いに闘技会を開催するんだ。<BR>そんで参加する命知らずを募集<BR>したい。強いヤツは大歓迎！<BR>力の無いヤツは勘弁してくれ！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60032.mib" DOWNLOAD CSUM=3957 FSIZE=3672 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>二色の双角・闘技場</a><BR>
				<a href=#002 qname=m60022>マグマの海に擁かれて</a><BR>
				<a href=#003 qname=m60007>ＪＵＭＰ　赤き闘技会</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60032>白光</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m60021>ヒプノック大乱闘！</a><BR>
				<a href=#006 qname=m60005>電撃祭Ｇ　イカヅチの山</a><BR>
				<a href=#007 qname=m60003>ファミ通　桜舞う季節</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				白光
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ５４０００ｚ<br>
				<font color=orangered>　契約金　：</font> ４５００ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 塔<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ９以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_PPL2.gif></td>
					<td width=219 height=18 background=GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				白光
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>ミラボレアス１体の討伐<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>依頼主：</font>白いドレスの少女<BR>
					うふふ、あなたハンターなんで<BR>しょ？ある場所まで一緒に来て<BR>欲しいの…素敵な所よ。白い光<BR>が綺羅星のように舞い散って…<BR>退屈なんてさせないんだから…<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60021.mib" DOWNLOAD CSUM=46867 FSIZE=1400 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>二色の双角・闘技場</a><BR>
				<a href=#002 qname=m60022>マグマの海に擁かれて</a><BR>
				<a href=#003 qname=m60007>ＪＵＭＰ　赤き闘技会</a><BR>
				<a href=#004 qname=m60032>白光</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60021>ヒプノック大乱闘！</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m60005>電撃祭Ｇ　イカヅチの山</a><BR>
				<a href=#007 qname=m60003>ファミ通　桜舞う季節</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				ヒプノック大乱闘！
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> １５０００ｚ<br>
				<font color=orangered>　契約金　：</font> １２５０ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 大闘技場<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_WHT2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				ヒプノック大乱闘！
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>ヒプノック２頭の狩猟<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★<BR>
					<font color=orangered>依頼主：</font>闘技場の運営者<BR>
					ハンターが己の腕前を披露する<BR>闘技場！２頭のヒプノックが待<BR>つ場内へ足を踏み入れた者は、<BR>深い眠りへ誘われるでしょう！<BR>あなたの実力見せてください！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60005.mib" DOWNLOAD CSUM=30270 FSIZE=5388 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>二色の双角・闘技場</a><BR>
				<a href=#002 qname=m60022>マグマの海に擁かれて</a><BR>
				<a href=#003 qname=m60007>ＪＵＭＰ　赤き闘技会</a><BR>
				<a href=#004 qname=m60032>白光</a><BR>
				<a href=#005 qname=m60021>ヒプノック大乱闘！</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60005>電撃祭Ｇ　イカヅチの山</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m60003>ファミ通　桜舞う季節</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				電撃祭Ｇ　イカヅチの山
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ２２２００ｚ<br>
				<font color=orangered>　契約金　：</font> １８５０ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 雪山＜昼＞<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_PNK2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				電撃祭Ｇ　イカヅチの山
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>すべての大型モンスターの狩猟<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>依頼主：</font>電撃ＰＳ　ポリタン<BR>
					ポリタンからグレートな挑戦！<BR>キミは雪山に現れた電撃を放つ<BR>モンスターに勝利できるか！？<BR>達成できたら豪華チケットが…<BR>だけども相手は１頭じゃない？<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60003.mib" DOWNLOAD CSUM=25790 FSIZE=6432 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>二色の双角・闘技場</a><BR>
				<a href=#002 qname=m60022>マグマの海に擁かれて</a><BR>
				<a href=#003 qname=m60007>ＪＵＭＰ　赤き闘技会</a><BR>
				<a href=#004 qname=m60032>白光</a><BR>
				<a href=#005 qname=m60021>ヒプノック大乱闘！</a><BR>
				<a href=#006 qname=m60005>電撃祭Ｇ　イカヅチの山</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60003>ファミ通　桜舞う季節</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				ファミ通　桜舞う季節
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ２１０００ｚ<br>
				<font color=orangered>　契約金　：</font> １７５０ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 密林＜昼＞<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_PNK2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				ファミ通　桜舞う季節
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>すべての大型モンスターの狩猟<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>依頼主：</font>ファミ通ＭＨＰ攻略班<BR>
					ファミ通からの挑戦状！<BR>密林に現れた桜色のモンスター<BR>たち！キミは全てを狩り勝利を<BR>その手に掴めるか？クリアでき<BR>たら特別なチケットを大進呈！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
