<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?pg_no=1",
		"RB_LINK=DL_MENU.PHP?pg_no=3",
		"MOVE_CHAR=GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60031.mib" DOWNLOAD CSUM=21291 FSIZE=1240 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60031>緋天終焉</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m60035>ハンターズフェスタ！</a><BR>
				<a href=#003 qname=m60009>マガジン　大鳥の陣</a><BR>
				<a href=#004 qname=m60012>砂漠を駆ける獣</a><BR>
				<a href=#005 qname=m60017>激戦！血煙闘技場</a><BR>
				<a href=#006 qname=m60002>ファミ通　吹雪を討つもの</a><BR>
				<a href=#007 qname=m60030>宿命の黒き翼</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				緋天終焉
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ５４０００ｚ<br>
				<font color=orangered>　契約金　：</font> ４５００ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 決戦場<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ９以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_PPL2.gif></td>
					<td width=219 height=18 background=GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				緋天終焉
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>ミラボレアス１体の討伐<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>依頼主：</font>ギルドの重鎮<BR>
					見よ！緋色に染まった空を！<BR>ミラボレアス…かの者の怒りは<BR>天をも焦がす…伝承は真であっ<BR>たか！誰でも良い！この焔の禍<BR>を祓ってくれる者はおらぬか！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60035.mib" DOWNLOAD CSUM=36913 FSIZE=1808 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60031>緋天終焉</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60035>ハンターズフェスタ！</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m60009>マガジン　大鳥の陣</a><BR>
				<a href=#004 qname=m60012>砂漠を駆ける獣</a><BR>
				<a href=#005 qname=m60017>激戦！血煙闘技場</a><BR>
				<a href=#006 qname=m60002>ファミ通　吹雪を討つもの</a><BR>
				<a href=#007 qname=m60030>宿命の黒き翼</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				ハンターズフェスタ！
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ３３０００ｚ<br>
				<font color=orangered>　契約金　：</font> ２７５０ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 大闘技場<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_PNK2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				ハンターズフェスタ！
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>すべての大型モンスターの狩猟<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>依頼主：</font>おかっぱ頭の少女<BR>
					えへへ…ウチな今回のお祭りの<BR>案内人やねん。ええと…コホン<BR>この試練に見事打ち勝てた者に<BR>特別なチケットを授ける！と。<BR>みんな、絶対挑戦しにきてな！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60009.mib" DOWNLOAD CSUM=58543 FSIZE=1984 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60031>緋天終焉</a><BR>
				<a href=#002 qname=m60035>ハンターズフェスタ！</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60009>マガジン　大鳥の陣</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m60012>砂漠を駆ける獣</a><BR>
				<a href=#005 qname=m60017>激戦！血煙闘技場</a><BR>
				<a href=#006 qname=m60002>ファミ通　吹雪を討つもの</a><BR>
				<a href=#007 qname=m60030>宿命の黒き翼</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				マガジン　大鳥の陣
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ３７５００ｚ<br>
				<font color=orangered>　契約金　：</font> ３１５０ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 大闘技場<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_PNK2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				マガジン　大鳥の陣
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>すべての大型モンスターの狩猟<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>依頼主：</font>眼光鋭い東方の戦士<BR>
					ハンターなる者の力を見る為に<BR>遠く東方より参りました。<BR>舞台はこちらで用意します。<BR>力を示す度量のある方は、是非<BR>闘技場までいらしてください。<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60012.mib" DOWNLOAD CSUM=43131 FSIZE=4992 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60031>緋天終焉</a><BR>
				<a href=#002 qname=m60035>ハンターズフェスタ！</a><BR>
				<a href=#003 qname=m60009>マガジン　大鳥の陣</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60012>砂漠を駆ける獣</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m60017>激戦！血煙闘技場</a><BR>
				<a href=#006 qname=m60002>ファミ通　吹雪を討つもの</a><BR>
				<a href=#007 qname=m60030>宿命の黒き翼</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				砂漠を駆ける獣
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ２４０００ｚ<br>
				<font color=orangered>　契約金　：</font> ２０００ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 砂漠＜昼＞<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_WHT2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				砂漠を駆ける獣
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>ドドブランゴ亜種２頭の狩猟<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>依頼主：</font>傷だらけの獣人<BR>
					オイラは亡くなったご主人と約<BR>束したのニャ！この手紙は必ず<BR>届けるって！あと少しなのニャ<BR>でも道はモンスターだらけで…<BR>お願いニャ…助けてニャ…<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60017.mib" DOWNLOAD CSUM=62346 FSIZE=1972 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60031>緋天終焉</a><BR>
				<a href=#002 qname=m60035>ハンターズフェスタ！</a><BR>
				<a href=#003 qname=m60009>マガジン　大鳥の陣</a><BR>
				<a href=#004 qname=m60012>砂漠を駆ける獣</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60017>激戦！血煙闘技場</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m60002>ファミ通　吹雪を討つもの</a><BR>
				<a href=#007 qname=m60030>宿命の黒き翼</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				激戦！血煙闘技場
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ３９０００ｚ<br>
				<font color=orangered>　契約金　：</font> ３２５０ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 水上闘技場<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ７以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_PNK2.gif></td>
					<td width=219 height=18 background=GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				激戦！血煙闘技場
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>すべての大型モンスターの狩猟<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>依頼主：</font>生真面目な女騎士<BR>
					これは私の趣味ではないのだが<BR>キミたちの力が見たいという方<BR>がいてな。その実力、見せては<BR>もらえまいか？報酬に関しては<BR>無論期待してくれていいぞ。<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60002.mib" DOWNLOAD CSUM=48929 FSIZE=4072 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60031>緋天終焉</a><BR>
				<a href=#002 qname=m60035>ハンターズフェスタ！</a><BR>
				<a href=#003 qname=m60009>マガジン　大鳥の陣</a><BR>
				<a href=#004 qname=m60012>砂漠を駆ける獣</a><BR>
				<a href=#005 qname=m60017>激戦！血煙闘技場</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60002>ファミ通　吹雪を討つもの</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m60030>宿命の黒き翼</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				ファミ通　吹雪を討つもの
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> １８０００ｚ<br>
				<font color=orangered>　契約金　：</font> １５００ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> 雪山＜夜＞<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ９以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_RED2.gif></td>
					<td width=219 height=18 background=GIF/T_RED.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				ファミ通　吹雪を討つもの
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>クシャルダオラ１体の討伐<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>依頼主：</font>あるガンランス使い<BR>
					あの雪山に僕が長年追い続けた<BR>古龍がいる。あいつの素材で僕<BR>の求めたガンランスが完成する<BR>んだが、…恐ろしく強いんだ！<BR>報酬は弾むよ！手伝ってくれ！<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=208 height=184 border=0 cellspacing=5 background=GIF/LIST.gif>
		<tr><td>
			<table width=198 cellspacing=0>
			<form action="QUEST/m60030.mib" DOWNLOAD CSUM=34418 FSIZE=1272 method=post>
			<tr>
				<td width=198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/６</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60031>緋天終焉</a><BR>
				<a href=#002 qname=m60035>ハンターズフェスタ！</a><BR>
				<a href=#003 qname=m60009>マガジン　大鳥の陣</a><BR>
				<a href=#004 qname=m60012>砂漠を駆ける獣</a><BR>
				<a href=#005 qname=m60017>激戦！血煙闘技場</a><BR>
				<a href=#006 qname=m60002>ファミ通　吹雪を討つもの</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60030>宿命の黒き翼</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=GIF/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				宿命の黒き翼
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>　報酬金　：</font> ５４０００ｚ<br>
				<font color=orangered>　契約金　：</font> ４５００ｚ<br>
				<font color=orangered>　制限時間：</font> ５０分<br>
				<font color=orangered>　指定地　：</font> シュレイド城<br>
				<font color=orangered>　特殊条件：</font><br>　参加資格はＨＲ９以上<BR>　<BR>　
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=GIF/T_PPL2.gif></td>
					<td width=219 height=18 background=GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				宿命の黒き翼
			</td>
			<td>
				<font color=orangered>クエストＬＶ：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>成功条件：</font><br>ミラボレアス１体の討伐<BR><BR><BR>
					<font color=orangered>失敗条件：</font><br>報酬金ゼロ<BR>タイムアップ<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>依頼主：</font>老獪なギルドマスター<BR>
					古代の城跡で黒い翼の龍の姿を<BR>見たと連絡があってな。調査隊<BR>は消息不明…こりゃ嫌な予感が<BR>するわい。誰か次の調査へ行っ<BR>てくれる者は…おらんかの？<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/BUTTON4.gif></td></tr></table>
</body>
</html>
