<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=OFF",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:1",
		"MOVE_CHAR=GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=GIF/ro-dos.gif,256,145,4,1,2,30,-82,100",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<B>
<img src=GIF/LOGO1.gif width=200 height=50 alt="Top"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=476 height=197 cellspacing=0 2 cellpadding=0 border=0>
<tr>
	<td width=15>
	</td>
	<td width=200 210>
	<table width=200 210 cellspacing=0 cellpadding=0>
		<form action="DL_SELECT.PHP" method=get><tr><td>
		 <input type=image ANIME=20 src="GIF/DOWNLOAD.gif"    name=submit width=186 height=68 alt="Quest">
		</td></tr></form>
		<form action="DL_BONUS.PHP" method=get><tr><td>
		 <input type=image ANIME=20 src="GIF/BONUS.gif"       name=submit width=186 height=64 alt="Bonus">
		</td></tr></form>
		<form action="DB_INFO.PHP" method=get><tr><td>
		 <input type=image ANIME=20 src="GIF/INFORMATION.gif" name=submit width=186 height=65 alt="Information"></a>
		 <input type=hidden name=pg_no value=0>
		</td></tr></form>
	</table>
	</td>
	<td width=260>
	<table width=258 height=194 border=0 cellspacing=10 cellpadding=0 background=GIF/KANBAN.gif>
		<tr>
			<td align=center>
				<font color=orange><B>最新更新情報 </B></font><br>
			</td>
		</tr>
		<tr>
			<td valign=top><B>
≪１２／１９≫<BR>特典を１つ<BR>追加したのニャ！<BR><BR><BR><BR><BR>
			</B></td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0 bgcolor=black><tr><td width=480 height=25 background=GIF/BUTTON1.gif></td></tr></table>
</body>
</html>
