<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=5",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=5&pg_no=3",
		"RB_LINK=DB_INFO.PHP?lang=5&pg_no=5",
		"MOVE_CHAR=../MHP2GUSA/GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					4/9 Informazioni agg. ②<BR>
				<tr><td>
					4/9 Informazioni agg. ①<BR>
					28/8 Informazioni agg. ②<BR>
					28/8 Informazioni agg. ①<BR>
					21/8 Informazioni agg.<BR>
					14/8 Informazioni agg.<BR>
					7/8 Informazioni agg.<BR>
					31/7 Informazioni agg. ③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>4/9 Informazioni agg. ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Le ali nere del destino</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>4/9 Informazioni agg. ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Le ali nere del destino--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Scaltro maest. Gilda<BR>Abbiamo saputo che un drago <BR>dalle ali nere è stato visto<BR>presso le rovine di un<BR>antico castello. Gli uomini<BR>della nostra spedizione  <BR>sono scomparsi e temo il  <BR>peggio. Chi ci va?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60030.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					4/9 Informazioni agg. ②<BR>
				<tr><td bgcolor=green>
					4/9 Informazioni agg. ①<BR>
				<tr><td>
					28/8 Informazioni agg. ②<BR>
					28/8 Informazioni agg. ①<BR>
					21/8 Informazioni agg.<BR>
					14/8 Informazioni agg.<BR>
					7/8 Informazioni agg.<BR>
					31/7 Informazioni agg. ③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>4/9 Informazioni agg. ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Caccia nella giungla!</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>4/9 Informazioni agg. ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Caccia nella giungla!--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Nobile prepotente<BR>Per il bene dei nostri <BR>cittadini, abbiamo scelto di<BR>essere coraggiosi e<BR>di ispezionare la foresta.<BR>Non sapevamo che fosse<BR>luogo tanto pericoloso!<BR>Ti chiedo di proteggerci!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60027.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					4/9 Informazioni agg. ②<BR>
					4/9 Informazioni agg. ①<BR>
				<tr><td bgcolor=green>
					28/8 Informazioni agg. ②<BR>
				<tr><td>
					28/8 Informazioni agg. ①<BR>
					21/8 Informazioni agg.<BR>
					14/8 Informazioni agg.<BR>
					7/8 Informazioni agg.<BR>
					31/7 Informazioni agg. ③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>28/8 Informazioni agg. ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include 1 nuovi<BR>elementi bonus, miao!<BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>28/8 Informazioni agg. ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
I seguenti elementi bonus verranno aggiunti.
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
<font color=orange>Titolo:<BR>　Predone<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br></font>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/b00000.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					4/9 Informazioni agg. ②<BR>
					4/9 Informazioni agg. ①<BR>
					28/8 Informazioni agg. ②<BR>
				<tr><td bgcolor=green>
					28/8 Informazioni agg. ①<BR>
				<tr><td>
					21/8 Informazioni agg.<BR>
					14/8 Informazioni agg.<BR>
					7/8 Informazioni agg.<BR>
					31/7 Informazioni agg. ③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>28/8 Informazioni agg. ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Tigre del deserto</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>28/8 Informazioni agg. ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Tigre del deserto--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Curiosa fanciulla<BR>Wow! Sembra che ci sia un<BR>mostro tigrato che si aggira<BR>dall'altra parte! Andiamo,<BR>cerchiamo di avvistarlo!<BR>Se è una bestia violenta, ci<BR>sarai tu a proteggermi, no?<BR>　　　　　　　　　　　　　　<br>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60037.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					4/9 Informazioni agg. ②<BR>
					4/9 Informazioni agg. ①<BR>
					28/8 Informazioni agg. ②<BR>
					28/8 Informazioni agg. ①<BR>
				<tr><td bgcolor=green>
					21/8 Informazioni agg.<BR>
				<tr><td>
					14/8 Informazioni agg.<BR>
					7/8 Informazioni agg.<BR>
					31/7 Informazioni agg. ③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>21/8 Informazioni agg.</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Monster Hunter Fiesta 2</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>21/8 Informazioni agg.</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Monster Hunter Fiesta 2--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Promotore caloroso<BR>È il momento delle sfide! Il<BR>tuo avversario è il possente<BR>Tigrex! Come sai, la sua<BR>forza lascia ben poche vie<BR>di scampo, ma per avanzare, <BR>devi superare questo muro!<BR>　　　　　　　　　　　　　　<br>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/f00002.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					4/9 Informazioni agg. ②<BR>
					4/9 Informazioni agg. ①<BR>
					28/8 Informazioni agg. ②<BR>
					28/8 Informazioni agg. ①<BR>
					21/8 Informazioni agg.<BR>
				<tr><td bgcolor=green>
					14/8 Informazioni agg.<BR>
				<tr><td>
					7/8 Informazioni agg.<BR>
					31/7 Informazioni agg. ③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>14/8 Informazioni agg.</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Missione Sfida 4</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>14/8 Informazioni agg.</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Missione Sfida 4--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Istruttore<BR>Diventa un'unica cosa con<BR>i mostri imparando a pensare<BR>come loro: così potrai<BR>sconfiggerli! A ciò serve<BR>questo addestramento. Usa<BR>l'equipaggiamento, entra  <BR>nelle loro teste bestiali!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/c61004.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					4/9 Informazioni agg. ②<BR>
					4/9 Informazioni agg. ①<BR>
					28/8 Informazioni agg. ②<BR>
					28/8 Informazioni agg. ①<BR>
					21/8 Informazioni agg.<BR>
					14/8 Informazioni agg.<BR>
				<tr><td bgcolor=green>
					7/8 Informazioni agg.<BR>
				<tr><td>
					31/7 Informazioni agg. ③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>7/8 Informazioni agg.</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Festival acquatico</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>7/8 Informazioni agg.</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Festival acquatico--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Impresario soave<BR>Voglio che sia una festa<BR>divertente, e sai cosa  <BR>penso la renderebbe tale?<BR>Esibire qualche cacciatore<BR>di primo piano in azione!<BR>Ho già 4 mostri pronti: su,<BR>un po' di spettacolo!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60028.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					4/9 Informazioni agg. ②<BR>
					4/9 Informazioni agg. ①<BR>
					28/8 Informazioni agg. ②<BR>
					28/8 Informazioni agg. ①<BR>
					21/8 Informazioni agg.<BR>
					14/8 Informazioni agg.<BR>
					7/8 Informazioni agg.<BR>
				<tr><td bgcolor=green>
					31/7 Informazioni agg. ③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>31/7 Informazioni agg. ③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include 6 nuovi<BR>elementi bonus, miao!<BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>31/7 Informazioni agg. ③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
I seguenti elementi bonus verranno aggiunti.
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
<font color=orange>Titolo:<BR>　Topo&nbsp;biblio.<BR>　ImperStudioso<BR>　Elettrico<BR>La moda di Piggie:<BR>　Body&nbsp;dell'angelo<BR>　　　　　　　　　　　　　　<br></font>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/b00002.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
</body>
</html>
