<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=3",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=3&pg_no=0",
		"RB_LINK=DB_INFO.PHP?lang=3&pg_no=2",
		"MOVE_CHAR=../MHP2GUSA/GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					18/12 Info. Mise à jour<BR>
				<tr><td>
					11/12 Info. Mise à jour<BR>
					4/12 Info. Mise à jour<BR>
					27/11 Info. Mise à jour<BR>
					20/11 Info. Mise à jour<BR>
					13/11 Info. Mise à jour<BR>
					6/11 Info. Mise à jour ②<BR>
					6/11 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>18/12 Info. Mise à jour</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Les cornes jumelles - Arène</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>18/12 Info. Mise à jour</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Les cornes jumelles - Arène--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Directeur arène agé<BR>J'avais juré il y a bien<BR>longtemps de ne plus gérer<BR>ce type d'affaires, mais je<BR>n'ai pas pu résister ! Alors<BR>me revoilà ! Vos adversaires<BR>du jour sont deux Diablos !<BR>Bonne chance !<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60014.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Info. Mise à jour<BR>
				<tr><td bgcolor=green>
					11/12 Info. Mise à jour<BR>
				<tr><td>
					4/12 Info. Mise à jour<BR>
					27/11 Info. Mise à jour<BR>
					20/11 Info. Mise à jour<BR>
					13/11 Info. Mise à jour<BR>
					6/11 Info. Mise à jour ②<BR>
					6/11 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>11/12 Info. Mise à jour</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Entouré d'une mer de magma</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>11/12 Info. Mise à jour</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Entouré d'une mer de magma--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Mineur noirci<BR>On se préparait pour notre<BR>journée de travail quand on<BR>a vu une énorme silhouette<BR>sombre tapie sous la surface<BR>de la lave, au fond de la<BR>grotte. Comme un monstre du<BR>Lava Ness ! Allez voir !<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60022.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Info. Mise à jour<BR>
					11/12 Info. Mise à jour<BR>
				<tr><td bgcolor=green>
					4/12 Info. Mise à jour<BR>
				<tr><td>
					27/11 Info. Mise à jour<BR>
					20/11 Info. Mise à jour<BR>
					13/11 Info. Mise à jour<BR>
					6/11 Info. Mise à jour ②<BR>
					6/11 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>4/12 Info. Mise à jour</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Quête défi 10</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>4/12 Info. Mise à jour</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Quête défi 10--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Instructeur<BR>Voici le redouté Rajang<BR>doré ! Il a une puissance<BR>inégalée, mais je crois en<BR>vous. Je pense que vous<BR>arriverez à le battre. Ne<BR>retenez pas vos coups et la<BR>victoire sera à vous !<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/c61010.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Info. Mise à jour<BR>
					11/12 Info. Mise à jour<BR>
					4/12 Info. Mise à jour<BR>
				<tr><td bgcolor=green>
					27/11 Info. Mise à jour<BR>
				<tr><td>
					20/11 Info. Mise à jour<BR>
					13/11 Info. Mise à jour<BR>
					6/11 Info. Mise à jour ②<BR>
					6/11 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>27/11 Info. Mise à jour</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Un halo blanc de lumière</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>27/11 Info. Mise à jour</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Un halo blanc de lumière--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Fille vêtue de blanc<BR>Vous êtes chasseur, hein ?<BR>Hi hi. Ça vous dirait que je<BR>vous emmène... vers un lieu<BR>magnifique où une lumière<BR>blanche danse en scintillant<BR>comme les étoiles... Vous ne<BR>serez pas déçu, vous verrez.<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60032.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Info. Mise à jour<BR>
					11/12 Info. Mise à jour<BR>
					4/12 Info. Mise à jour<BR>
					27/11 Info. Mise à jour<BR>
				<tr><td bgcolor=green>
					20/11 Info. Mise à jour<BR>
				<tr><td>
					13/11 Info. Mise à jour<BR>
					6/11 Info. Mise à jour ②<BR>
					6/11 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>20/11 Info. Mise à jour</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Quête défi 9</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>20/11 Info. Mise à jour</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Quête défi 9--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Instructeur<BR>Aujourd'hui, j'ai une quête<BR>spéciale pour vous ! Votre<BR>cible : une meute de Veloci-<BR>prey dans la Grande arène.<BR>Mais ce n'est rien comparé<BR>aux autres monstres qui vous<BR>attendent !<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/c61009.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Info. Mise à jour<BR>
					11/12 Info. Mise à jour<BR>
					4/12 Info. Mise à jour<BR>
					27/11 Info. Mise à jour<BR>
					20/11 Info. Mise à jour<BR>
				<tr><td bgcolor=green>
					13/11 Info. Mise à jour<BR>
				<tr><td>
					6/11 Info. Mise à jour ②<BR>
					6/11 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>13/11 Info. Mise à jour</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Bagarre Hypnocatrices</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>13/11 Info. Mise à jour</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Bagarre Hypnocatrices--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Directeur de l'arène<BR>Oyez, approchez de l'arène<BR>ultime ! J'ai 2, oui j'ai<BR>bien dit 2, Hypnocatrices<BR>qui vous attendent, prêts<BR>à vous emmener au pays des<BR>rêves ! Préparez-vous à<BR>avoir les paupières lourdes.<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60021.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Info. Mise à jour<BR>
					11/12 Info. Mise à jour<BR>
					4/12 Info. Mise à jour<BR>
					27/11 Info. Mise à jour<BR>
					20/11 Info. Mise à jour<BR>
					13/11 Info. Mise à jour<BR>
				<tr><td bgcolor=green>
					6/11 Info. Mise à jour ②<BR>
				<tr><td>
					6/11 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>6/11 Info. Mise à jour ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise à jour<BR>inclura 3 nouveaux<BR>éléments bonus, miaou !<BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>6/11 Info. Mise à jour ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
Ces éléments bonus seront ajoutés.
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
<font color=orange>Titres:<BR>　Âme&nbsp;chasseur<BR>　Diva<BR>Les&nbsp;objets&nbsp;de&nbsp;Mémé<BR>colporteuse:<BR>　Objets&nbsp;spéciaux<BR>　　　　　　　　　　　　　　<br></font>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/b00005.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Info. Mise à jour<BR>
					11/12 Info. Mise à jour<BR>
					4/12 Info. Mise à jour<BR>
					27/11 Info. Mise à jour<BR>
					20/11 Info. Mise à jour<BR>
					13/11 Info. Mise à jour<BR>
					6/11 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					6/11 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>6/11 Info. Mise à jour ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Quête défi 8</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>6/11 Info. Mise à jour ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Quête défi 8--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Instructeur<BR>Je gère une arène où j'ai<BR>le plaisir de remettre aux<BR>meilleurs combattants des<BR>récompenses tirées de mes<BR>trésors cachés. Vous<BR>pouvez y participer avec<BR>vos amis. Je vous attends !<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/c61008.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
</body>
</html>
