<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=3",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=3&pg_no=5",
		"RB_LINK=DB_INFO.PHP?lang=3&pg_no=1",
		"MOVE_CHAR=../MHP2GUSA/GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					5/4 Info. Mise à jour ②<BR>
				<tr><td>
					5/4 Info. Mise à jour ①<BR>
					2/4 Info. Mise à jour ③<BR>
					2/4 Info. Mise à jour ②<BR>
					2/4 Info. Mise à jour ①<BR>
					25/12 Info. Mise à jour ③<BR>
					25/12 Info. Mise à jour ②<BR>
					25/12 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>5/4 Info. Mise à jour ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Double terreur</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>5/4 Info. Mise à jour ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Double terreur--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Mercenaire pâle<BR>Je n'arrive pas à y croire,<BR>il y avait 2 Rajang se<BR>dans l'arène !<BR>Écoutez, si vous tenez à<BR>la vie, ne vous approchez<BR>pas. C'est compris ?<BR>　　　　　　　　　　　　　　<br>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60038.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					5/4 Info. Mise à jour ①<BR>
				<tr><td>
					2/4 Info. Mise à jour ③<BR>
					2/4 Info. Mise à jour ②<BR>
					2/4 Info. Mise à jour ①<BR>
					25/12 Info. Mise à jour ③<BR>
					25/12 Info. Mise à jour ②<BR>
					25/12 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>5/4 Info. Mise à jour ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Roi des hautes sphères</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>5/4 Info. Mise à jour ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Roi des hautes sphères--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Roi bienveillant<BR>Le puissant et redoutable<BR>Akantor... On a réussi à le<BR>traquer jusqu'ici, mais on<BR>a subi de grosses pertes.<BR>Chasseurs de ces terres !<BR>J'ai besoin de votre aide<BR>plus que jamais !<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60034.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Info. Mise à jour ②<BR>
					5/4 Info. Mise à jour ①<BR>
				<tr><td bgcolor=green>
					2/4 Info. Mise à jour ③<BR>
				<tr><td>
					2/4 Info. Mise à jour ②<BR>
					2/4 Info. Mise à jour ①<BR>
					25/12 Info. Mise à jour ③<BR>
					25/12 Info. Mise à jour ②<BR>
					25/12 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>2/4 Info. Mise à jour ③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Chasse divine générale</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>2/4 Info. Mise à jour ③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Chasse divine générale--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Chevalier rouge<BR>Messire, aurez-vous le<BR>courage de relever ce défi ?<BR>Croyez en votre force et en<BR>celle de vos compagnons, car<BR>la bravoure se révèle au<BR>cœur du danger. Gardez la<BR>foi et n'abandonnez jamais !<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60019.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Info. Mise à jour ②<BR>
					5/4 Info. Mise à jour ①<BR>
					2/4 Info. Mise à jour ③<BR>
				<tr><td bgcolor=green>
					2/4 Info. Mise à jour ②<BR>
				<tr><td>
					2/4 Info. Mise à jour ①<BR>
					25/12 Info. Mise à jour ③<BR>
					25/12 Info. Mise à jour ②<BR>
					25/12 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>2/4 Info. Mise à jour ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Montagne dans le ciel</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>2/4 Info. Mise à jour ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Montagne dans le ciel--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Dame cheveux longs<BR>Un jour, alors que j'étais<BR>enfant, j'ai vu une ombre<BR>géante dans le ciel. Elle<BR>était plus grande que tous<BR>les Wyvern que j'avais vus.<BR>Ai-je rêvé ? Pouvez-vous<BR>vérifier cela pour moi ?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60010.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Info. Mise à jour ②<BR>
					5/4 Info. Mise à jour ①<BR>
					2/4 Info. Mise à jour ③<BR>
					2/4 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					2/4 Info. Mise à jour ①<BR>
				<tr><td>
					25/12 Info. Mise à jour ③<BR>
					25/12 Info. Mise à jour ②<BR>
					25/12 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>2/4 Info. Mise à jour ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Montagne de larmes</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>2/4 Info. Mise à jour ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Montagne de larmes--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Jeune noble<BR>Deux Rajang ont enlevé ma<BR>belle fiancée et se sont<BR>enfuis dans la montagne. Je<BR>sais qu'elle ne veut pas de<BR>moi, mais je ne peux vivre<BR>sans elle ! Je vous en prie,<BR>prêtez-moi votre force !<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60016.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Info. Mise à jour ②<BR>
					5/4 Info. Mise à jour ①<BR>
					2/4 Info. Mise à jour ③<BR>
					2/4 Info. Mise à jour ②<BR>
					2/4 Info. Mise à jour ①<BR>
				<tr><td bgcolor=green>
					25/12 Info. Mise à jour ③<BR>
				<tr><td>
					25/12 Info. Mise à jour ②<BR>
					25/12 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>25/12 Info. Mise à jour ③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise à jour<BR>inclura 1 nouveaux<BR>éléments bonus, miaou !<BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>25/12 Info. Mise à jour ③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
Ces éléments bonus seront ajoutés.
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
<font color=orange>Mode Cochonet:<BR>　Combinaison&nbsp;Mafumofu<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br></font>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/b00011.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Info. Mise à jour ②<BR>
					5/4 Info. Mise à jour ①<BR>
					2/4 Info. Mise à jour ③<BR>
					2/4 Info. Mise à jour ②<BR>
					2/4 Info. Mise à jour ①<BR>
					25/12 Info. Mise à jour ③<BR>
				<tr><td bgcolor=green>
					25/12 Info. Mise à jour ②<BR>
				<tr><td>
					25/12 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>25/12 Info. Mise à jour ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Quatre rois de feu</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>25/12 Info. Mise à jour ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Quatre rois de feu--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Scientifique en blanc<BR>On a découvert que le Volcan<BR>est un vivier où prospèrent<BR>plusieurs variétés de<BR>monstres. Pourriez-vous<BR>aller là-bas et nous ramener<BR>quatre espèces pour nos<BR>recherches, je vous prie ?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60018.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Info. Mise à jour ②<BR>
					5/4 Info. Mise à jour ①<BR>
					2/4 Info. Mise à jour ③<BR>
					2/4 Info. Mise à jour ②<BR>
					2/4 Info. Mise à jour ①<BR>
					25/12 Info. Mise à jour ③<BR>
					25/12 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					25/12 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>25/12 Info. Mise à jour ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>2 falaises ! 2 vents chauds</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>25/12 Info. Mise à jour ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--2 falaises ! 2 vents chauds--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Directeur de l'arène<BR>Oyez, approchez de l'arène<BR>ultime ! J'ai 2, oui, j'ai<BR>bien dit 2, terribles<BR>Gravios noirs dans cette<BR>arène ! Pensez-vous être<BR>capable de vaincre ces deux<BR>bêtes sauvages ?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60015.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
</body>
</html>
