<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=5",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=5&pg_no=5",
		"RB_LINK=DB_INFO.PHP?lang=5&pg_no=1",
		"MOVE_CHAR=../MHP2GUSA/GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					5/4 Informazioni agg. ②<BR>
				<tr><td>
					5/4 Informazioni agg. ①<BR>
					2/4 Informazioni agg. ③<BR>
					2/4 Informazioni agg. ②<BR>
					2/4 Informazioni agg. ①<BR>
					25/12 Informazioni agg. ③<BR>
					25/12 Informazioni agg. ②<BR>
					25/12 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>5/4 Informazioni agg. ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Gemelli del terrore</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>5/4 Informazioni agg. ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Gemelli del terrore--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:MercenarioPallido<BR>Non riesco a credere ai miei<BR>occhi. Era terribile!<BR>C'erano due Rajang seduti<BR>nell'arena...<BR>Ascoltami... Se ci tieni alla<BR>tua pelle non ti avvicinare<BR>all'arena. Capito?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60038.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Informazioni agg. ②<BR>
				<tr><td bgcolor=green>
					5/4 Informazioni agg. ①<BR>
				<tr><td>
					2/4 Informazioni agg. ③<BR>
					2/4 Informazioni agg. ②<BR>
					2/4 Informazioni agg. ①<BR>
					25/12 Informazioni agg. ③<BR>
					25/12 Informazioni agg. ②<BR>
					25/12 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>5/4 Informazioni agg. ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Re delle vette elevate</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>5/4 Informazioni agg. ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Re delle vette elevate--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Benevolo monarca<BR>Il potentissimo Akantor... <BR>Gli abbiamo dato la caccia<BR>fin qui, ma abbiamo subito<BR>gravi danni. Cacciatori <BR>di questa terra! Richiedo il<BR>vostro aiuto immediato!<BR>　　　　　　　　　　　　　　<br>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60034.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Informazioni agg. ②<BR>
					5/4 Informazioni agg. ①<BR>
				<tr><td bgcolor=green>
					2/4 Informazioni agg. ③<BR>
				<tr><td>
					2/4 Informazioni agg. ②<BR>
					2/4 Informazioni agg. ①<BR>
					25/12 Informazioni agg. ③<BR>
					25/12 Informazioni agg. ②<BR>
					25/12 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>2/4 Informazioni agg. ③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Battuta di caccia grossa</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>2/4 Informazioni agg. ③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Battuta di caccia grossa--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Cavaliere in rosso<BR>Udite, udite, chi accetterà<BR>questa sfida? Credi nella<BR>tua forza e in quella dei<BR>tuoi compagni: è nel cuore<BR>del pericolo che viene messo<BR>alla prova l'ardimento. Alti<BR>i cuori e mano alle armi!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60019.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Informazioni agg. ②<BR>
					5/4 Informazioni agg. ①<BR>
					2/4 Informazioni agg. ③<BR>
				<tr><td bgcolor=green>
					2/4 Informazioni agg. ②<BR>
				<tr><td>
					2/4 Informazioni agg. ①<BR>
					25/12 Informazioni agg. ③<BR>
					25/12 Informazioni agg. ②<BR>
					25/12 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>2/4 Informazioni agg. ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Montagna nel cielo</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>2/4 Informazioni agg. ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Montagna nel cielo--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Vecchia capelli lun.<BR>Un tempo, quando ero<BR>bambina, vidi nel cielo <BR>un'ombra gigantesca...<BR>Più grande di tutti i wyvern<BR>mai visti. Fu solo un sogno?<BR>Te la senti di capirci<BR>qualcosa?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60010.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Informazioni agg. ②<BR>
					5/4 Informazioni agg. ①<BR>
					2/4 Informazioni agg. ③<BR>
					2/4 Informazioni agg. ②<BR>
				<tr><td bgcolor=green>
					2/4 Informazioni agg. ①<BR>
				<tr><td>
					25/12 Informazioni agg. ③<BR>
					25/12 Informazioni agg. ②<BR>
					25/12 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>2/4 Informazioni agg. ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Cima Lacrima del Demone</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>2/4 Informazioni agg. ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Cima Lacrima del Demone--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Giovane nobile<BR>Due Rajang hanno rapito la <BR>mia amata ma restia moglie<BR>e sono fuggiti sui monti.<BR>Non mi importa se lei non<BR>mi vuole, ma non posso<BR>vivere senza di lei! Ti<BR>prego, donami la tua forza!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60016.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Informazioni agg. ②<BR>
					5/4 Informazioni agg. ①<BR>
					2/4 Informazioni agg. ③<BR>
					2/4 Informazioni agg. ②<BR>
					2/4 Informazioni agg. ①<BR>
				<tr><td bgcolor=green>
					25/12 Informazioni agg. ③<BR>
				<tr><td>
					25/12 Informazioni agg. ②<BR>
					25/12 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>25/12 Informazioni agg. ③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include 1 nuovi<BR>elementi bonus, miao!<BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>25/12 Informazioni agg. ③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
I seguenti elementi bonus verranno aggiunti.
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
<font color=orange>La moda di Piggie:<BR>　Tuta&nbsp;Mafumofu<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br></font>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/b00011.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Informazioni agg. ②<BR>
					5/4 Informazioni agg. ①<BR>
					2/4 Informazioni agg. ③<BR>
					2/4 Informazioni agg. ②<BR>
					2/4 Informazioni agg. ①<BR>
					25/12 Informazioni agg. ③<BR>
				<tr><td bgcolor=green>
					25/12 Informazioni agg. ②<BR>
				<tr><td>
					25/12 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>25/12 Informazioni agg. ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Quattro re di fuoco</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>25/12 Informazioni agg. ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Quattro re di fuoco--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Scienziato in bianco<BR>Ci hanno confermato che<BR>la zona del Vulcano è un<BR>ricco terreno di pascolo per<BR>numerosi mostri. Vorresti <BR>recarti in quell'area e<BR>cacciare 4 specie <BR>per le nostre ricerche?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60018.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>１/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/4 Informazioni agg. ②<BR>
					5/4 Informazioni agg. ①<BR>
					2/4 Informazioni agg. ③<BR>
					2/4 Informazioni agg. ②<BR>
					2/4 Informazioni agg. ①<BR>
					25/12 Informazioni agg. ③<BR>
					25/12 Informazioni agg. ②<BR>
				<tr><td bgcolor=green>
					25/12 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>25/12 Informazioni agg. ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Venti caldi nel buio</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>25/12 Informazioni agg. ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Venti caldi nel buio--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Manager arena<BR>Venite, venite tutti, <BR>nell'arena per eccellenza! <BR>Ho 2, sì, ben due temibili<BR>Gravios neri proprio qui, in<BR>questa arena! Pensi di<BR>avere ciò che serve per <BR>vincere i due orridi mostri?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60015.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
</body>
</html>
