<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=5",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=5&pg_no=0",
		"RB_LINK=DB_INFO.PHP?lang=5&pg_no=2",
		"MOVE_CHAR=../MHP2GUSA/GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					18/12 Informazioni agg.<BR>
				<tr><td>
					11/12 Informazioni agg.<BR>
					4/12 Informazioni agg.<BR>
					27/11 Informazioni agg.<BR>
					20/11 Informazioni agg.<BR>
					13/11 Informazioni agg.<BR>
					6/11 Informazioni agg. ②<BR>
					6/11 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>18/12 Informazioni agg.</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Doppi Corni gemelli - Arena</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>18/12 Informazioni agg.</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Doppi Corni gemelli - Arena--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Manager arena 1/2età<BR>Avevo giurato di abbandonare<BR>questo lavoro molto tempo<BR>fa, ma non ho resistito,<BR>così eccomi qui, dentro<BR>fino al collo! Questa<BR>volta ti tocca una coppia<BR>di Diablos! Auguri!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60014.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Informazioni agg.<BR>
				<tr><td bgcolor=green>
					11/12 Informazioni agg.<BR>
				<tr><td>
					4/12 Informazioni agg.<BR>
					27/11 Informazioni agg.<BR>
					20/11 Informazioni agg.<BR>
					13/11 Informazioni agg.<BR>
					6/11 Informazioni agg. ②<BR>
					6/11 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>11/12 Informazioni agg.</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Mare di magma</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>11/12 Informazioni agg.</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Mare di magma--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Minatore cinereo<BR>Stavamo per preparare le <BR>nostre cose, quando abbiamo<BR>scorto un'immensa ombra<BR>scura sotto la superficie<BR>della lava sul fondo della<BR>caverna, una specie di <BR>Mostro di Lava! Controlla!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60022.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Informazioni agg.<BR>
					11/12 Informazioni agg.<BR>
				<tr><td bgcolor=green>
					4/12 Informazioni agg.<BR>
				<tr><td>
					27/11 Informazioni agg.<BR>
					20/11 Informazioni agg.<BR>
					13/11 Informazioni agg.<BR>
					6/11 Informazioni agg. ②<BR>
					6/11 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>4/12 Informazioni agg.</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Missione Sfida 10</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>4/12 Informazioni agg.</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Missione Sfida 10--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Istruttore<BR>È il temutissimo Rajang<BR>dorato! È la bestia più <BR>forte che potrai mai <BR>affrontare, ma visto che si<BR>tratta di te, confido che <BR>batterai quel mostro. Non <BR>risparmiarti e vincerai!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/c61010.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Informazioni agg.<BR>
					11/12 Informazioni agg.<BR>
					4/12 Informazioni agg.<BR>
				<tr><td bgcolor=green>
					27/11 Informazioni agg.<BR>
				<tr><td>
					20/11 Informazioni agg.<BR>
					13/11 Informazioni agg.<BR>
					6/11 Informazioni agg. ②<BR>
					6/11 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>27/11 Informazioni agg.</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Un bianco raggio di luce</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>27/11 Informazioni agg.</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Un bianco raggio di luce--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Ragazza in bianco<BR>Sei un cacciatore, giusto?<BR>Ihih. Voglio che tu venga<BR>con me... in un posto<BR>stupendo, dove danza<BR>luce bianca, ardente <BR>come le stelle nel cielo...<BR>Vedrai, non ti annoierai...<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60032.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Informazioni agg.<BR>
					11/12 Informazioni agg.<BR>
					4/12 Informazioni agg.<BR>
					27/11 Informazioni agg.<BR>
				<tr><td bgcolor=green>
					20/11 Informazioni agg.<BR>
				<tr><td>
					13/11 Informazioni agg.<BR>
					6/11 Informazioni agg. ②<BR>
					6/11 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>20/11 Informazioni agg.</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Missione Sfida 9</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>20/11 Informazioni agg.</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Missione Sfida 9--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Istruttore<BR>Ora ho una missione speciale<BR>per te! L'obiettivo: il <BR>branco di Velociprey che ti<BR>aspetta nell'Grande arena. <BR>Ma quelli sono poca cosa<BR>in confronto all'altro<BR>mostro che troverai laggiù!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/c61009.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Informazioni agg.<BR>
					11/12 Informazioni agg.<BR>
					4/12 Informazioni agg.<BR>
					27/11 Informazioni agg.<BR>
					20/11 Informazioni agg.<BR>
				<tr><td bgcolor=green>
					13/11 Informazioni agg.<BR>
				<tr><td>
					6/11 Informazioni agg. ②<BR>
					6/11 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>13/11 Informazioni agg.</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Super-zuffa Hypnocatrice</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>13/11 Informazioni agg.</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Super-zuffa Hypnocatrice--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Manager arena<BR>Venite, venite tutti, <BR>nell'arena per eccellenza! <BR>Ho 2, sì, ben 2 Hypnocatrice<BR>che aspettano là dentro,<BR>pronte a darti il benvenuto!<BR>Saprai restare sveglio con  <BR>quei loro occhi ipnotici?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60021.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Informazioni agg.<BR>
					11/12 Informazioni agg.<BR>
					4/12 Informazioni agg.<BR>
					27/11 Informazioni agg.<BR>
					20/11 Informazioni agg.<BR>
					13/11 Informazioni agg.<BR>
				<tr><td bgcolor=green>
					6/11 Informazioni agg. ②<BR>
				<tr><td>
					6/11 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>6/11 Informazioni agg. ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include 3 nuovi<BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>6/11 Informazioni agg. ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
I seguenti elementi bonus verranno aggiunti.
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
<font color=orange>Titolo:<BR>　Anima&nbsp;caccia<BR>　Diva<BR>Oggetti&nbsp;della<BR>vecchia ambulante:<BR>　Oggetti&nbsp;speciali<BR>　　　　　　　　　　　　　　<br></font>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/b00005.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Informazioni agg.<BR>
					11/12 Informazioni agg.<BR>
					4/12 Informazioni agg.<BR>
					27/11 Informazioni agg.<BR>
					20/11 Informazioni agg.<BR>
					13/11 Informazioni agg.<BR>
					6/11 Informazioni agg. ②<BR>
				<tr><td bgcolor=green>
					6/11 Informazioni agg. ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>6/11 Informazioni agg. ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Missione Sfida 8</font><BR><BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per<BR>maggiori dettagli, miao!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>6/11 Informazioni agg. ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>--Missione Sfida 8--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Istruttore<BR>Dirigo un'arena tutta mia,<BR>dove sarò lieto di premiare<BR>con alcuni dei miei tesori<BR>chiunque ottenga tempi <BR>record. Puoi anche <BR>partecipare con i tuoi <BR>amici. Non farmi aspettare!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/c61008.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
</body>
</html>
