<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=3",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=3&pg_no=1",
		"RB_LINK=DB_INFO.PHP?lang=3&pg_no=3",
		"MOVE_CHAR=../MHP2GUSA/GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					23/10 Info. Mise à jour ②<BR>
				<tr><td>
					23/10 Info. Mise à jour ①<BR>
					16/10 Info. Mise à jour ②<BR>
					16/10 Info. Mise à jour ①<BR>
					9/10 Info. Mise à jour ②<BR>
					9/10 Info. Mise à jour ①<BR>
					2/10 Info. Mise à jour ②<BR>
					2/10 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>23/10 Info. Mise à jour ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Monster Hunter Fiesta 4</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>23/10 Info. Mise à jour ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Monster Hunter Fiesta 4--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Promoteur vertueux<BR>Grâce à la participation de<BR>tous ces chasseurs émérites,<BR>on a réussi à créer cet<BR>événement majeur ! On espère<BR>que tous les chasseurs se<BR>joindront à cette dernière<BR>chasse d'anthologie !<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/f00004.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					23/10 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					23/10 Info. Mise à jour ①<BR>
				<tr><td>
					16/10 Info. Mise à jour ②<BR>
					16/10 Info. Mise à jour ①<BR>
					9/10 Info. Mise à jour ②<BR>
					9/10 Info. Mise à jour ①<BR>
					2/10 Info. Mise à jour ②<BR>
					2/10 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>23/10 Info. Mise à jour ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Fiesta des chasseurs !</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>23/10 Info. Mise à jour ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Fiesta des chasseurs !--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Fille cheveux courts<BR>C-C'est moi qui suis chargée<BR>du festival cette fois, et<BR>euh... *hum* La récompense<BR>en cas de victoire est un<BR>ticket très spécial ! Alors<BR>euh, j'espère que vous serez<BR>nombreux à participer !<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60035.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					23/10 Info. Mise à jour ②<BR>
					23/10 Info. Mise à jour ①<BR>
				<tr><td bgcolor=green>
					16/10 Info. Mise à jour ②<BR>
				<tr><td>
					16/10 Info. Mise à jour ①<BR>
					9/10 Info. Mise à jour ②<BR>
					9/10 Info. Mise à jour ①<BR>
					2/10 Info. Mise à jour ②<BR>
					2/10 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>16/10 Info. Mise à jour ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Cieux écarlates</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>16/10 Info. Mise à jour ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Cieux écarlates--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Poids lourd guilde<BR>Regardez ce ciel écarlate !<BR>La légende est vraie ! Même<BR>le ciel devient rouge sang<BR>quand un Fatalis se met en<BR>colère. Vite, quelqu'un doit<BR>mettre fin à cette rage et<BR>redonner au ciel sa couleur.<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60031.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					23/10 Info. Mise à jour ②<BR>
					23/10 Info. Mise à jour ①<BR>
					16/10 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					16/10 Info. Mise à jour ①<BR>
				<tr><td>
					9/10 Info. Mise à jour ②<BR>
					9/10 Info. Mise à jour ①<BR>
					2/10 Info. Mise à jour ②<BR>
					2/10 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>16/10 Info. Mise à jour ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Monster Hunter Fiesta 3</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>16/10 Info. Mise à jour ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Monster Hunter Fiesta 3--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Promotrice volupt.<BR>Nous voici arrivés à la<BR>meilleure partie de ces<BR>compétitions. Je me demande<BR>qui sera le grand gagnant<BR>et remportera le trophée !<BR>En tout cas, j'ai hâte de<BR>voir votre talent à l'œuvre.<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/f00003.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					23/10 Info. Mise à jour ②<BR>
					23/10 Info. Mise à jour ①<BR>
					16/10 Info. Mise à jour ②<BR>
					16/10 Info. Mise à jour ①<BR>
				<tr><td bgcolor=green>
					9/10 Info. Mise à jour ②<BR>
				<tr><td>
					9/10 Info. Mise à jour ①<BR>
					2/10 Info. Mise à jour ②<BR>
					2/10 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>9/10 Info. Mise à jour ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Quête défi 7</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>9/10 Info. Mise à jour ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Quête défi 7--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Instructeur<BR>Affrontez 2 Nargacuga de<BR>suite ! Gare à leur rapidité<BR>et à leur queue super puis-<BR>sante, un seul coup suffit.<BR>Restez calme et concentré.<BR>Vous finirez par les avoir.<BR>　　　　　　　　　　　　　　<br>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/c61007.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					23/10 Info. Mise à jour ②<BR>
					23/10 Info. Mise à jour ①<BR>
					16/10 Info. Mise à jour ②<BR>
					16/10 Info. Mise à jour ①<BR>
					9/10 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					9/10 Info. Mise à jour ①<BR>
				<tr><td>
					2/10 Info. Mise à jour ②<BR>
					2/10 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>9/10 Info. Mise à jour ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>2 murs ? Des vents maléf.</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>9/10 Info. Mise à jour ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--2 murs ? Des vents maléf.--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Directeur suspect<BR>Oyez, approchez de l'arène<BR>ultime ! Mes 2 monstres sont<BR>parmi les plus forts et les<BR>plus terrifiants du monde !<BR>Lancez-vous ! Venez vous<BR>mesurer à eux et démontrer<BR>votre courage au combat.<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60011.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					23/10 Info. Mise à jour ②<BR>
					23/10 Info. Mise à jour ①<BR>
					16/10 Info. Mise à jour ②<BR>
					16/10 Info. Mise à jour ①<BR>
					9/10 Info. Mise à jour ②<BR>
					9/10 Info. Mise à jour ①<BR>
				<tr><td bgcolor=green>
					2/10 Info. Mise à jour ②<BR>
				<tr><td>
					2/10 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>2/10 Info. Mise à jour ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Bêtes des dunes</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>2/10 Info. Mise à jour ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Bêtes des dunes--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Créatures blessées<BR>Miaou, on a promis à notre<BR>maître qu'on livrerait cette<BR>lettre à sa destination !<BR>On y est presque arrivé,<BR>mais on a rencontré ces<BR>monstres sur notre chemin...<BR>Aidez-nous, je vous en prie.<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60012.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>３/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					23/10 Info. Mise à jour ②<BR>
					23/10 Info. Mise à jour ①<BR>
					16/10 Info. Mise à jour ②<BR>
					16/10 Info. Mise à jour ①<BR>
					9/10 Info. Mise à jour ②<BR>
					9/10 Info. Mise à jour ①<BR>
					2/10 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					2/10 Info. Mise à jour ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>2/10 Info. Mise à jour ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Les lauriers, je vous prie.</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>2/10 Info. Mise à jour ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Les lauriers, je vous prie.--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Jeune directeur arène<BR>Envie de frimer ? Venez dans<BR>mon arène ! Au menu du jour,<BR>il y a un Congalala, un<BR>Rathian, un Ceanataur S. et<BR>d'autres monstres ! Utilisez<BR>bien les quelques potions<BR>que vous pourrez trouver !<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60025.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
</body>
</html>
