<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=3",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=3&pg_no=4",
		"RB_LINK=DB_INFO.PHP?lang=3&pg_no=0",
		"MOVE_CHAR=../MHP2GUSA/GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					31/7 Info. Mise à jour ②<BR>
				<tr><td>
					31/7 Info. Mise à jour ①<BR>
					24/7 Info. Mise à jour<BR>
					17/7 Info. Mise à jour<BR>
					10/7 Info. Mise à jour<BR>
					3/7 Info. Mise à jour ②<BR>
					3/7 Info. Mise à jour ①<BR>
					Nouveau !<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>31/7 Info. Mise à jour ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise à jour<BR>inclura 6 nouveaux<BR>éléments bonus, miaou !<BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>31/7 Info. Mise à jour ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
Ces éléments bonus seront ajoutés.
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
<font color=orange>Chef Felyne errant:<BR>　Orange<BR>Armure compagnon Felyne:<BR>　Samurai&nbsp;Felyne<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br></font>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/b00001.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					31/7 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					31/7 Info. Mise à jour ①<BR>
				<tr><td>
					24/7 Info. Mise à jour<BR>
					17/7 Info. Mise à jour<BR>
					10/7 Info. Mise à jour<BR>
					3/7 Info. Mise à jour ②<BR>
					3/7 Info. Mise à jour ①<BR>
					Nouveau !<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>31/7 Info. Mise à jour ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Quête défi 3</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>31/7 Info. Mise à jour ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Quête défi 3--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Instructeur<BR>Cette fois, ça se passe dans<BR>l'Arène inondée. La prime <BR>est très intéressante, alors<BR>ça ne coûte rien d'essayer.<BR>Quoi ? Les clauses ? Bah,<BR>ça ira ! Vous allez gagner !<BR>Enfin, peut-être... Ah ah !<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/c61003.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					31/7 Info. Mise à jour ②<BR>
					31/7 Info. Mise à jour ①<BR>
				<tr><td bgcolor=green>
					24/7 Info. Mise à jour<BR>
				<tr><td>
					17/7 Info. Mise à jour<BR>
					10/7 Info. Mise à jour<BR>
					3/7 Info. Mise à jour ②<BR>
					3/7 Info. Mise à jour ①<BR>
					Nouveau !<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>24/7 Info. Mise à jour</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Quête défi 2</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>24/7 Info. Mise à jour</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Quête défi 2--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Instructeur<BR>Oh oh ! Un défi lancé par les<BR>Shakalaka ! Normalement, je<BR>m'en charge moi-même, mais<BR>je viens de me souvenir que<BR>j'ai un truc super important<BR>à faire. Alors allez-y à ma<BR>place et ramenez le trophée.<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/c61002.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					31/7 Info. Mise à jour ②<BR>
					31/7 Info. Mise à jour ①<BR>
					24/7 Info. Mise à jour<BR>
				<tr><td bgcolor=green>
					17/7 Info. Mise à jour<BR>
				<tr><td>
					10/7 Info. Mise à jour<BR>
					3/7 Info. Mise à jour ②<BR>
					3/7 Info. Mise à jour ①<BR>
					Nouveau !<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>17/7 Info. Mise à jour</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Monster Hunter Fiesta 1</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>17/7 Info. Mise à jour</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Monster Hunter Fiesta 1--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Jeune promoteur<BR>Bienvenue dans la compéti-<BR>tion ! Pour ce défi, on<BR>demande aux participants de<BR>tuer un Nargacuga de la<BR>Grande forêt. Ayez confiance<BR>en vous et montrez-nous<BR>votre vraie force !<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/f00001.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					31/7 Info. Mise à jour ②<BR>
					31/7 Info. Mise à jour ①<BR>
					24/7 Info. Mise à jour<BR>
					17/7 Info. Mise à jour<BR>
				<tr><td bgcolor=green>
					10/7 Info. Mise à jour<BR>
				<tr><td>
					3/7 Info. Mise à jour ②<BR>
					3/7 Info. Mise à jour ①<BR>
					Nouveau !<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>10/7 Info. Mise à jour</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>2 coul. félines - Pt. arène</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>10/7 Info. Mise à jour</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--2 coul. félines - Pt. arène--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Créatures Ying-Yang<BR>Avis au million de fans des<BR>créatures Felyne :<BR>Notre défi spécial est enfin<BR>arrivé ! Si vous réussissez<BR>à terminer cette épreuve,<BR>vous recevrez un ticket très<BR>spécial !<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60033.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					31/7 Info. Mise à jour ②<BR>
					31/7 Info. Mise à jour ①<BR>
					24/7 Info. Mise à jour<BR>
					17/7 Info. Mise à jour<BR>
					10/7 Info. Mise à jour<BR>
				<tr><td bgcolor=green>
					3/7 Info. Mise à jour ②<BR>
				<tr><td>
					3/7 Info. Mise à jour ①<BR>
					Nouveau !<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>3/7 Info. Mise à jour ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise à jour<BR>inclura 1 nouveaux<BR>éléments bonus, miaou !<BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>3/7 Info. Mise à jour ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
Ces éléments bonus seront ajoutés.
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
<font color=orange>Titres:<BR>　Génial<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br></font>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/b00000.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					31/7 Info. Mise à jour ②<BR>
					31/7 Info. Mise à jour ①<BR>
					24/7 Info. Mise à jour<BR>
					17/7 Info. Mise à jour<BR>
					10/7 Info. Mise à jour<BR>
					3/7 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					3/7 Info. Mise à jour ①<BR>
				<tr><td>
					Nouveau !<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>3/7 Info. Mise à jour ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Triumvirat des sables</font><BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>3/7 Info. Mise à jour ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>--Triumvirat des sables--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Client:Pharmacien du nord<BR>Saleté de désert ! C'est la<BR>3ème fois aujourd'hui que je<BR>dois abandonner tous mes<BR>produits sur place. Toutes<BR>ces super potions... Si ça<BR>se trouve, elles sont dans<BR>l'estomac d'un monstre.<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60024.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>６/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					31/7 Info. Mise à jour ②<BR>
					31/7 Info. Mise à jour ①<BR>
					24/7 Info. Mise à jour<BR>
					17/7 Info. Mise à jour<BR>
					10/7 Info. Mise à jour<BR>
					3/7 Info. Mise à jour ②<BR>
					3/7 Info. Mise à jour ①<BR>
				<tr><td bgcolor=green>
					Nouveau !<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>Nouveau !</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La page de téléchargement est<BR>maintenant ouverte !<BR><BR>Appuyer sur la touche <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td width=450 height=34 align=center valign=bottom colspan=2>
			<font size=2>
			<font color=yellow>Nouveau !</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td width=450 height=143 align=left valign=center>
			<B><font size=2>
La page de téléchargement est<BR>maintenant ouverte !<BR>Nous ajouterons régulièrement des quêtes et<BR>des éléments bonus. <BR>Mettez-vous tous à télécharger, nya !<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>
			</font></B>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
</body>
</html>
