<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=2",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=2&pg_no=3",
		"RB_LINK=DB_INFO.PHP?lang=2&pg_no=5",
		"MOVE_CHAR=../MHP2GUSA/GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					4/9 Update-Informationen②<BR>
				<tr><td>
					4/9 Update-Informationen①<BR>
					28/8 Update-Informationen②<BR>
					28/8 Update-Informationen①<BR>
					21/8 Update-Informationen<BR>
					14/8 Update-Informationen<BR>
					7/8 Update-Informationen<BR>
					31/7 Update-Informationen③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>4/9 Update-Informationen②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Schwarze Schicksalsschwingen</font><BR><BR>Drücke die <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>4/9 Update-Informationen②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>--Schwarze Schicksalsschwingen--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Klient:ListigerGildenmeistr<BR>Man sagt, ein Drache mit <BR>schwarzen Schwingen wurde in<BR>den alten Schlossruinen ge-<BR>sehen. Unsere Expedition ist<BR>verschollen - ich befürchte <BR>das Schlimmste. Will denn <BR>niemand nachsehen?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60030.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					4/9 Update-Informationen②<BR>
				<tr><td bgcolor=green>
					4/9 Update-Informationen①<BR>
				<tr><td>
					28/8 Update-Informationen②<BR>
					28/8 Update-Informationen①<BR>
					21/8 Update-Informationen<BR>
					14/8 Update-Informationen<BR>
					7/8 Update-Informationen<BR>
					31/7 Update-Informationen③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>4/9 Update-Informationen①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Dschungelhatz!</font><BR><BR>Drücke die <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>4/9 Update-Informationen①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>--Dschungelhatz!--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Klient:Herrischer Adliger<BR>Zum Wohle unserer untertä-<BR>nigen Untertanen haben wir<BR>mutig den Wald erforscht.<BR>Doch selbst unsere liebe<BR>Mutter warnte uns nicht vor<BR>solch' Schrecken! Ich will,<BR>dass Ihr uns beschützet!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60027.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					4/9 Update-Informationen②<BR>
					4/9 Update-Informationen①<BR>
				<tr><td bgcolor=green>
					28/8 Update-Informationen②<BR>
				<tr><td>
					28/8 Update-Informationen①<BR>
					21/8 Update-Informationen<BR>
					14/8 Update-Informationen<BR>
					7/8 Update-Informationen<BR>
					31/7 Update-Informationen③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>28/8 Update-Informationen②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Das nächste Update<BR>wird 1 Bonusobjekte<BR>enthalten! *schnurr*<BR><BR>Drücke die <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>28/8 Update-Informationen②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
Die Bonusobjekte werden hinzugefügt.
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
<font color=orange>Titel:<BR>　Plünderer<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br></font>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/b00000.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					4/9 Update-Informationen②<BR>
					4/9 Update-Informationen①<BR>
					28/8 Update-Informationen②<BR>
				<tr><td bgcolor=green>
					28/8 Update-Informationen①<BR>
				<tr><td>
					21/8 Update-Informationen<BR>
					14/8 Update-Informationen<BR>
					7/8 Update-Informationen<BR>
					31/7 Update-Informationen③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>28/8 Update-Informationen①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Tiger der Wüste</font><BR><BR>Drücke die <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>28/8 Update-Informationen①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>--Tiger der Wüste--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Klient:Sehr neugierige Magd<BR>Wow! Angeblich treibt sich <BR>ein gestreiftes Monster auf <BR>der anderen Seite herum! <BR>Schnell, vielleicht sehen <BR>wir es! Wenn es gefährlich <BR>wird, beschützt du mich <BR>doch, nicht wahr?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60037.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					4/9 Update-Informationen②<BR>
					4/9 Update-Informationen①<BR>
					28/8 Update-Informationen②<BR>
					28/8 Update-Informationen①<BR>
				<tr><td bgcolor=green>
					21/8 Update-Informationen<BR>
				<tr><td>
					14/8 Update-Informationen<BR>
					7/8 Update-Informationen<BR>
					31/7 Update-Informationen③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>21/8 Update-Informationen</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Monsterjäger-Fiesta 2</font><BR><BR>Drücke die <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>21/8 Update-Informationen</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>--Monsterjäger-Fiesta 2--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Klient:Herzlicher Promoter<BR>Partyzeit! Dein Gegner ist <BR>der mächtige Tigrex! Seine <BR>Stärke ist erdrückend, aber <BR>um weiterzukommen, ist<BR>dieser Sieg quasi<BR>unerlässlich!<BR>　　　　　　　　　　　　　　<br>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/f00002.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					4/9 Update-Informationen②<BR>
					4/9 Update-Informationen①<BR>
					28/8 Update-Informationen②<BR>
					28/8 Update-Informationen①<BR>
					21/8 Update-Informationen<BR>
				<tr><td bgcolor=green>
					14/8 Update-Informationen<BR>
				<tr><td>
					7/8 Update-Informationen<BR>
					31/7 Update-Informationen③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>14/8 Update-Informationen</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Challenge-Quest 4</font><BR><BR>Drücke die <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>14/8 Update-Informationen</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>--Challenge-Quest 4--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Klient:Ausbilder<BR>Werde eins mit den Monstern <BR>und denke wie sie. So <BR>schlägst du sie! Dazu dient <BR>dieses Training. Nimm diese <BR>Ausrüstung und dringe in <BR>die Köpfe der Biester <BR>ein!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/c61004.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					4/9 Update-Informationen②<BR>
					4/9 Update-Informationen①<BR>
					28/8 Update-Informationen②<BR>
					28/8 Update-Informationen①<BR>
					21/8 Update-Informationen<BR>
					14/8 Update-Informationen<BR>
				<tr><td bgcolor=green>
					7/8 Update-Informationen<BR>
				<tr><td>
					31/7 Update-Informationen③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>7/8 Update-Informationen</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Wasserfest</font><BR><BR>Drücke die <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>7/8 Update-Informationen</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>--Wasserfest--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Klient:Charmanter Produzent<BR>Ich will eine spaßige Feier!<BR>Und was könnte besser sein, <BR>als den Gästen zu zeigen, <BR>wie erstklassige Jäger<BR>Monster zur Srecke bringen?<BR>Ich habe 4 Monster besorgt,<BR>also lassen wir es krachen!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60028.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>５/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					4/9 Update-Informationen②<BR>
					4/9 Update-Informationen①<BR>
					28/8 Update-Informationen②<BR>
					28/8 Update-Informationen①<BR>
					21/8 Update-Informationen<BR>
					14/8 Update-Informationen<BR>
					7/8 Update-Informationen<BR>
				<tr><td bgcolor=green>
					31/7 Update-Informationen③<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>31/7 Update-Informationen③</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
Das nächste Update<BR>wird 6 Bonusobjekte<BR>enthalten! *schnurr*<BR><BR>Drücke die <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>31/7 Update-Informationen③</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
Die Bonusobjekte werden hinzugefügt.
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
<font color=orange>Titel:<BR>　Bücherwurm<BR>　Kais.&nbsp;Schüler<BR>　Elektrisch<BR>Speckie-Mode:<BR>　Engelaufzug<BR>　　　　　　　　　　　　　　<br></font>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/b00002.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
</body>
</html>
