<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=4",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=4&pg_no=0",
		"RB_LINK=DB_INFO.PHP?lang=4&pg_no=2",
		"MOVE_CHAR=../MHP2GUSA/GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					18/12 Info actualización<BR>
				<tr><td>
					11/12 Info actualización<BR>
					4/12 Info actualización<BR>
					27/11 Info actualización<BR>
					20/11 Info actualización<BR>
					13/11 Info actualización<BR>
					6/11 Info actualización ②<BR>
					6/11 Info actualización ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>18/12 Info actualización</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Doble cornamenta - Arena</font><BR><BR>Pulsa el botón <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>18/12 Info actualización</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>--Doble cornamenta - Arena--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Jefe arena 1/2 edad<BR>Renuncié a este negocio<BR>hace mucho tiempo, pero no<BR>podría abandonarlo, así que<BR>aquí estoy, ¡otra vez liado!<BR>¡Tus oponentes esta vez son<BR>un par de Diablos! ¡Buena<BR>suerte!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60014.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Info actualización<BR>
				<tr><td bgcolor=green>
					11/12 Info actualización<BR>
				<tr><td>
					4/12 Info actualización<BR>
					27/11 Info actualización<BR>
					20/11 Info actualización<BR>
					13/11 Info actualización<BR>
					6/11 Info actualización ②<BR>
					6/11 Info actualización ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>11/12 Info actualización</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Rodeado en un mar de magma</font><BR><BR>Pulsa el botón <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>11/12 Info actualización</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>--Rodeado en un mar de magma--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Minero pálido<BR>Íbamos a dar por acabada la<BR>jornada cuando vimos una<BR>sombra enorme y oscura<BR>acechando bajo el magma al<BR>fondo de la cueva, como un<BR>Nessie de la Lava. ¡Ten<BR>cuidado!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60022.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Info actualización<BR>
					11/12 Info actualización<BR>
				<tr><td bgcolor=green>
					4/12 Info actualización<BR>
				<tr><td>
					27/11 Info actualización<BR>
					20/11 Info actualización<BR>
					13/11 Info actualización<BR>
					6/11 Info actualización ②<BR>
					6/11 Info actualización ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>4/12 Info actualización</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Misión Desafío 10</font><BR><BR>Pulsa el botón <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>4/12 Info actualización</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>--Misión Desafío 10--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Instructor<BR>¡Es el temido Rajang dorado!<BR>Es el más fuerte que verás<BR>jamás pero, tratándose de<BR>ti, confío en que lo <BR>vencerás. ¡No te guardes<BR>nada y la victoria<BR>será tuya!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/c61010.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Info actualización<BR>
					11/12 Info actualización<BR>
					4/12 Info actualización<BR>
				<tr><td bgcolor=green>
					27/11 Info actualización<BR>
				<tr><td>
					20/11 Info actualización<BR>
					13/11 Info actualización<BR>
					6/11 Info actualización ②<BR>
					6/11 Info actualización ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>27/11 Info actualización</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Un rayo de luz blanca</font><BR><BR>Pulsa el botón <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>27/11 Info actualización</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>--Un rayo de luz blanca--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Chica de blanco<BR>Eres cazador, ¿no? Quiero<BR>que vengas conmigo... a<BR>un lugar maravilloso, donde<BR>la luz baila como estrellas<BR>en el cielo... Te juro que<BR>no te aburrirás...<BR>　　　　　　　　　　　　　　<br>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60032.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Info actualización<BR>
					11/12 Info actualización<BR>
					4/12 Info actualización<BR>
					27/11 Info actualización<BR>
				<tr><td bgcolor=green>
					20/11 Info actualización<BR>
				<tr><td>
					13/11 Info actualización<BR>
					6/11 Info actualización ②<BR>
					6/11 Info actualización ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>20/11 Info actualización</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Misión Desafío 9</font><BR><BR>Pulsa el botón <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>20/11 Info actualización</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>--Misión Desafío 9--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Instructor<BR>Hoy tengo para ti una<BR>aventura especial: un<BR>grupo de Velociprey en<BR>la Gran arena. Pero,<BR>¡cuidado! ¡No son nada<BR>al lado del otro<BR>monstruo que te espera!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/c61009.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Info actualización<BR>
					11/12 Info actualización<BR>
					4/12 Info actualización<BR>
					27/11 Info actualización<BR>
					20/11 Info actualización<BR>
				<tr><td bgcolor=green>
					13/11 Info actualización<BR>
				<tr><td>
					6/11 Info actualización ②<BR>
					6/11 Info actualización ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>13/11 Info actualización</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Superpelea Hypnocatrice</font><BR><BR>Pulsa el botón <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>13/11 Info actualización</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>--Superpelea Hypnocatrice--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Jefe arena<BR>¡Todos están invitados a la<BR>pelea definitiva! ¡Tengo 2,<BR>cuéntalos, 2 Hypnocatrice<BR>esperando, listos para<BR>ponerte a soñar. ¿Eres<BR>capaz de vencer 2<BR>párpados somnolientos?<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/e60021.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Info actualización<BR>
					11/12 Info actualización<BR>
					4/12 Info actualización<BR>
					27/11 Info actualización<BR>
					20/11 Info actualización<BR>
					13/11 Info actualización<BR>
				<tr><td bgcolor=green>
					6/11 Info actualización ②<BR>
				<tr><td>
					6/11 Info actualización ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>6/11 Info actualización ②</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La próxima actualización<BR>tiene previsto incluir 3<BR>nuevos Elementos extra.<BR><BR>Pulsa el botón <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>6/11 Info actualización ②</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
Los siguientes elementos extra serán añadidos.
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
<font color=orange>Título:<BR>　Alma&nbsp;cazador<BR>　Diva<BR>Objetos&nbsp;de&nbsp;la&nbsp;vendedora<BR>ambulante anciana:<BR>　Objetos&nbsp;especiales<BR>　　　　　　　　　　　　　　<br></font>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/b00005.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr>
			<td>
				<table width=224 208 198 cellspacing=0>
				<tr>
					<td width=224 208 198 height=34 align=center valign=center>
						<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
						<tr>
							<td align=center>
								<B><font color=white>２/６</font></B>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					18/12 Info actualización<BR>
					11/12 Info actualización<BR>
					4/12 Info actualización<BR>
					27/11 Info actualización<BR>
					20/11 Info actualización<BR>
					13/11 Info actualización<BR>
					6/11 Info actualización ②<BR>
				<tr><td bgcolor=green>
					6/11 Info actualización ①<BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	<td width=256 260>
		<table width=246 256 258 height=194 border=0 cellspacing=7 0 10 cellpadding=0 background=../MHP2GUSA/GIF/KANBAN_S.gif>
		<tr>
			<td align=center>
				<font color=yellow>6/11 Info actualización ①</font><br>
			</td>
		</tr>
		<tr>
			<td valign=top>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Misión Desafío 8</font><BR><BR>Pulsa el botón <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table cellspacing=0 cellpadding width=479 468 height=197 195 background=../MHP2GUSA/GIF/HUKIDASI.gif>
		<tr>
			<td width=479 468 align=center>
	<table width=459 450 height=177 cellspacing=0 cellpadding=0>
	<tr>
		<td height=20 30 34 align=center valign=center top colspan=2>
			<font size=2>
				<img src="" width=5 height=5><BR>
			<font color=yellow>6/11 Info actualización ①</font><br>
			</font>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>--Misión Desafío 8--</font>
			</td>
	</tr>
	<tr>
		<td width=259 240 height=104 120 align=left valign=top center>
			<font size=2>
Cliente:Instructor<BR>Aquí regento mi arena<BR>propia, y estaré feliz de <BR>repartir premios de mi<BR>tesoro a cualquiera que<BR>destaque por sus tiempos.<BR>Puedes venir con amigos.<BR>¡No me hagas esperar!<BR>
			</font>
		</td>
		<td width=200 210 height=129 align=center valign=center>
			<img src=../MHP2GUSA/PNG/c61008.png width=200 height=96><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
</body>
</html>
