<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=2",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:7",
		"MOVE_CHAR=../MHP2GUSA/GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=../MHP2GUSA/GIF/PIG.gif,64,48,1,1,3,10,480,050",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<img src=../MHP2GUSA/GIF/DE/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<form action="BONUS/bonus.mib" BDOWNLOAD method=post>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td width=432 height=131 valign=top>
<img src="" width=10 height=10><BR>
Alle Bonusobjekte wurden veröffentlicht, miau!<BR>Drücke die <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16>-Taste für mehr Details.<BR><BR><BR><BR><BR><BR>
			</td>
		</tr>
		<tr>
			<td height=46 align=center>
				<img ANIME=10 src=../MHP2GUSA/GIF/DE/BDL.gif width=210 height=46 alt="[O] DOWNLOAD"><BR>
				<input type=image src="" name=submit width=0 height=0>
			</td>
		</tr>
		<tr>
			<td align=right height=20>
			</td>
		</tr>
		</table>
	</td>
</tr>
</form>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<a name=002></a>
<img src=../MHP2GUSA/GIF/DE/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>１/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Noch nicht heruntergeladene Objekte sind gelb,miau!<BR></font>
-Wandernder Felyne-Koch-<BR>Es scheint, als sei eine farbige Felyne in der<BR>Stadt angekommen. *schnurr*<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=00>・RoterTiger</a><BR>
<a href=#003 qname=01>・Orange</a><BR>
<a href=#003 qname=02>・Pechschwrz</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=../MHP2GUSA/PNG/bonus03.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<a name=003></a>
<img src=../MHP2GUSA/GIF/DE/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>２/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Noch nicht heruntergeladene Objekte sind gelb,miau!<BR></font>
-Felyne-Kameraden-Rüstungen-<BR>Es wurden neue Felyne-Kameraden-Rüstungen<BR>hinzugefügt! *schnurr*<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=25>・Felyne-Samurai</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=../MHP2GUSA/PNG/bonus19.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<a name=004></a>
<img src=../MHP2GUSA/GIF/DE/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>３/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Noch nicht heruntergeladene Objekte sind gelb,miau!<BR></font>
-Kameradenfähigkeiten-<BR>Es wurden neue Kameradenfähigkeiten hinzugefügt!<BR>*schnurr*<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=26>・Elementangr. Drache</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=../MHP2GUSA/PNG/bonus15.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<a name=005></a>
<img src=../MHP2GUSA/GIF/DE/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>４/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Noch nicht heruntergeladene Objekte sind gelb,miau!<BR></font>
-Titels-<BR>Es wurden neue Titel für deine Gildenkarte<BR>hinzugefügt! *schnurr*<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=03>・Kokoto</a><BR>
<a href=#003 qname=04>・Jumbo</a><BR>
<a href=#003 qname=05>・Minnegard</a><BR>
<a href=#003 qname=06>・Dondruma</a><BR>
			</td>
			<td width=232 height=90 valign=top>
<a href=#003 qname=20>・Bücherwurm</a><BR>
<a href=#003 qname=21>・Kais. Schüler</a><BR>
<a href=#003 qname=23>・DrachÄltKönig</a><BR>
<a href=#003 qname=22>・Schrade</a><BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<a name=006></a>
<img src=../MHP2GUSA/GIF/DE/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>５/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Noch nicht heruntergeladene Objekte sind gelb,miau!<BR></font>
-Titels-<BR>Es wurden neue Titel für deine Gildenkarte<BR>hinzugefügt! *schnurr*<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=17>・Bienenknie</a><BR>
<a href=#003 qname=15>・Elektrisch</a><BR>
<a href=#003 qname=16>・Plünderer</a><BR>
<a href=#003 qname=14>・Berühmt</a><BR>
			</td>
			<td width=232 height=90 valign=top>
<a href=#003 qname=18>・Jägerseele</a><BR>
<a href=#003 qname=19>・Diva</a><BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<a name=007></a>
<img src=../MHP2GUSA/GIF/DE/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>６/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Noch nicht heruntergeladene Objekte sind gelb,miau!<BR></font>
-Speckie-Mode-<BR>Es wurde neue Kleidung für Speckie hinzugefügt,<BR>miau!<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=07>・Engelaufzug</a><BR>
<a href=#003 qname=08>・Schlafschwein weiß</a><BR>
<a href=#003 qname=13>・Mafumofu-Overall</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=../MHP2GUSA/PNG/bonus14.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<a name=008></a>
<img src=../MHP2GUSA/GIF/DE/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>７/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Noch nicht heruntergeladene Objekte sind gelb,miau!<BR></font>
-Pokke-Punkte-<BR>Du kannst 3000 Pokke-Punkte bekommen. *schnurr*<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=24>・3000 Pokke-Punkte</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=../MHP2GUSA/PNG/bonus11.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<a name=009></a>
<img src=../MHP2GUSA/GIF/DE/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>８/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Noch nicht heruntergeladene Objekte sind gelb,miau!<BR></font>
-Farmausstattung-<BR>Du kannast Trenyas Boot zur Pokke-Farm hinzu-<BR>fügen. *schnurr*<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=11>・Trenyas Boot</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=../MHP2GUSA/PNG/bonus12.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<a name=010></a>
<img src=../MHP2GUSA/GIF/DE/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>９/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Noch nicht heruntergeladene Objekte sind gelb,miau!<BR></font>
-Hausierer-Omi-Objekte-<BR>Die Hausierer-Omi hat einige Objekte bekommen,<BR>die sogar noch besser als sonst sind!<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=12>・Spezialobjekte</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=../MHP2GUSA/PNG/bonus13.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
</body>
</html>
