<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=5",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:7",
		"MOVE_CHAR=../MHP2GUSA/GIF/NEKO_NEW.gif,122,62,3,,16,,348,143",
		"MOVE_CHAR=../MHP2GUSA/GIF/PIG.gif,64,48,1,1,3,10,480,050",
		"MOVE_CHAR=../MHP2GUSA/GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<img src=../MHP2GUSA/GIF/IT/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<form action="BONUS/bonus.mib" BDOWNLOAD method=post>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td width=432 height=131 valign=top>
<img src="" width=10 height=10><BR>
Tutti gli elementi bonus sono stati<BR>resi disponibili, miao!<BR>Premi il tasto <img src=../MHP2GUSA/GIF/B_REC.gif width=16 height=16> per maggiori dettagli.<BR><BR><BR><BR><BR>
			</td>
		</tr>
		<tr>
			<td height=46 align=center>
				<img ANIME=10 src=../MHP2GUSA/GIF/IT/BDL.gif width=210 height=46 alt="[O] DOWNLOAD"><BR>
				<input type=image src="" name=submit width=0 height=0>
			</td>
		</tr>
		<tr>
			<td align=right height=20>
			</td>
		</tr>
		</table>
	</td>
</tr>
</form>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<a name=002></a>
<img src=../MHP2GUSA/GIF/IT/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>１/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Elementi in giallo non ancora scaricati, miao!<BR></font>
- Il cuoco vagabondo Felyne -<BR>Sembra un Felyne colorato che ha vagato<BR>per il villaggio, nya.<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=00>・Rss. Tigre</a><BR>
<a href=#003 qname=01>・Arancione</a><BR>
<a href=#003 qname=02>・Ebano</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=../MHP2GUSA/PNG/bonus03.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<a name=003></a>
<img src=../MHP2GUSA/GIF/IT/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>２/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Elementi in giallo non ancora scaricati, miao!<BR></font>
- Armatura compagno Felyne -<BR>È stata aggiunta una nuova armatura per i compagni<BR>Felyne, miao!<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=25>・Samurai Felyne</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=../MHP2GUSA/PNG/bonus19.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<a name=004></a>
<img src=../MHP2GUSA/GIF/IT/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>３/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Elementi in giallo non ancora scaricati, miao!<BR></font>
- Abilità compagno -<BR>Sono state aggiunte nuove Abilità compagno<BR>da apprendere, miao!<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=26>・Attacco elem. Drago</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=../MHP2GUSA/PNG/bonus15.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<a name=005></a>
<img src=../MHP2GUSA/GIF/IT/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>４/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Elementi in giallo non ancora scaricati, miao!<BR></font>
-Titolo-<BR>Sono stati aggiunti nuovi Titoli per la<BR>tua tessera della Gilda, nya!<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=03>・Kokoto</a><BR>
<a href=#003 qname=04>・Jumbo</a><BR>
<a href=#003 qname=05>・Minegarde</a><BR>
<a href=#003 qname=06>・Dondruma</a><BR>
			</td>
			<td width=232 height=90 valign=top>
<a href=#003 qname=20>・Topo biblio.</a><BR>
<a href=#003 qname=21>・ImperStudioso</a><BR>
<a href=#003 qname=23>・Re Drago Anz.</a><BR>
<a href=#003 qname=22>・Schrade</a><BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<a name=006></a>
<img src=../MHP2GUSA/GIF/IT/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>５/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Elementi in giallo non ancora scaricati, miao!<BR></font>
-Titolo-<BR>Sono stati aggiunti nuovi Titoli per la<BR>tua tessera della Gilda, nya!<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=17>・Eccellente</a><BR>
<a href=#003 qname=15>・Elettrico</a><BR>
<a href=#003 qname=16>・Predone</a><BR>
<a href=#003 qname=14>・Famoso</a><BR>
			</td>
			<td width=232 height=90 valign=top>
<a href=#003 qname=18>・Anima caccia.</a><BR>
<a href=#003 qname=19>・Diva</a><BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<a name=007></a>
<img src=../MHP2GUSA/GIF/IT/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>６/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Elementi in giallo non ancora scaricati, miao!<BR></font>
- Moda di Piggie -<BR>Sono stati aggiunti nuovi indumenti <BR>per Piggie, nya!<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=07>・Body dell'angelo</a><BR>
<a href=#003 qname=08>・Bianco maiale</a><BR>
<a href=#003 qname=13>・Tuta Mafumofu</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=../MHP2GUSA/PNG/bonus14.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<a name=008></a>
<img src=../MHP2GUSA/GIF/IT/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>７/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Elementi in giallo non ancora scaricati, miao!<BR></font>
- Punti Pokke -<BR>Puoi ottenere 3000 Punti Pokke, nya.<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=24>・3000 Punti Pokke</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=../MHP2GUSA/PNG/bonus11.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<a name=009></a>
<img src=../MHP2GUSA/GIF/IT/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>８/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Elementi in giallo non ancora scaricati, miao!<BR></font>
- Equipaggiamento per la fattoria -<BR>Puoi aggiungere la barca di Trenya alla<BR>fattoria Pokke, nya.<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=11>・Barca di Trenya</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=../MHP2GUSA/PNG/bonus12.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<a name=010></a>
<img src=../MHP2GUSA/GIF/IT/LOGO13.gif width=200 height=50 alt="Bonus"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=479 height=197 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/HUKIDASI.gif>
<tr>
	<td width=479 align=center valign=top>
		<table width=432 height=197 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
				<tr>
					<td align=center>
						<B>９/９</B>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>Elementi in giallo non ancora scaricati, miao!<BR></font>
- Oggetti della vecchia ambulante -<BR>La vecchia ambulante ha recuperato qualche<BR>oggetto migliore del solito, nya!<BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#003 qname=12>・Oggetti speciali</a><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=../MHP2GUSA/PNG/bonus13.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
</body>
</html>
