<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=4",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_CMENU.PHP?lang=4&pg_no=1",
		"RB_LINK=DL_CMENU.PHP?lang=4&pg_no=1",
		"MOVE_CHAR=../MHP2GUSA/GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=../MHP2GUSA/GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61010.mib" DOWNLOAD CSUM=61231 FSIZE=3052 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m61010>Misión Desafío 10</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m61009>Misión Desafío 9</a><BR>
				<a href=#003 qname=m61008>Misión Desafío 8</a><BR>
				<a href=#004 qname=m61014>Fiesta Monster Hunter 4</a><BR>
				<a href=#005 qname=m61013>Fiesta Monster Hunter 3</a><BR>
				<a href=#006 qname=m61007>Misión Desafío 7</a><BR>
				<a href=#007 qname=m61006>Misión Desafío 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Misión Desafío 10
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>24000z<br>
				<font color=orangered>&nbsp;Contrato :</font>0z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Gran arena<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 9 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Misión Desafío 10
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Mata al Rajang<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Cliente：</font>Instructor<BR>
					¡Es el temido Rajang dorado!<BR>Es el más fuerte que verás<BR>jamás pero, tratándose de<BR>ti, confío en que lo <BR>vencerás. ¡No te guardes<BR>nada y la victoria<BR>será tuya!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61009.mib" DOWNLOAD CSUM=37868 FSIZE=3404 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Misión Desafío 10</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m61009>Misión Desafío 9</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m61008>Misión Desafío 8</a><BR>
				<a href=#004 qname=m61014>Fiesta Monster Hunter 4</a><BR>
				<a href=#005 qname=m61013>Fiesta Monster Hunter 3</a><BR>
				<a href=#006 qname=m61007>Misión Desafío 7</a><BR>
				<a href=#007 qname=m61006>Misión Desafío 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Misión Desafío 9
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>12000z<br>
				<font color=orangered>&nbsp;Contrato :</font>0z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>40 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Gran arena<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 7 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Misión Desafío 9
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Mata 50 Velociprey<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>Cliente：</font>Instructor<BR>
					Hoy tengo para ti una<BR>aventura especial: un<BR>grupo de Velociprey en<BR>la Gran arena. Pero,<BR>¡cuidado! ¡No son nada<BR>al lado del otro<BR>monstruo que te espera!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61008.mib" DOWNLOAD CSUM=10597 FSIZE=3684 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Misión Desafío 10</a><BR>
				<a href=#002 qname=m61009>Misión Desafío 9</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m61008>Misión Desafío 8</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m61014>Fiesta Monster Hunter 4</a><BR>
				<a href=#005 qname=m61013>Fiesta Monster Hunter 3</a><BR>
				<a href=#006 qname=m61007>Misión Desafío 7</a><BR>
				<a href=#007 qname=m61006>Misión Desafío 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Misión Desafío 8
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>27000z<br>
				<font color=orangered>&nbsp;Contrato :</font>0z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Arena acuática<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 7 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Misión Desafío 8
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Mata todos los monstruos<BR>grandes<BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Cliente：</font>Instructor<BR>
					Aquí regento mi arena<BR>propia, y estaré feliz de <BR>repartir premios de mi<BR>tesoro a cualquiera que<BR>destaque por sus tiempos.<BR>Puedes venir con amigos.<BR>¡No me hagas esperar!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61014.mib" DOWNLOAD CSUM=17488 FSIZE=3184 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Misión Desafío 10</a><BR>
				<a href=#002 qname=m61009>Misión Desafío 9</a><BR>
				<a href=#003 qname=m61008>Misión Desafío 8</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m61014>Fiesta Monster Hunter 4</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m61013>Fiesta Monster Hunter 3</a><BR>
				<a href=#006 qname=m61007>Misión Desafío 7</a><BR>
				<a href=#007 qname=m61006>Misión Desafío 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Fiesta Monster Hunter 4
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>4500z<br>
				<font color=orangered>&nbsp;Contrato :</font>0z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>20 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Gran arena<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;No<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Fiesta Monster Hunter 4
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Mata al Rajang<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Cliente：</font>Promotor virtuoso<BR>
					¡Gracias a la partici-<BR>pación de todos hemos<BR>llegado hasta aquí!<BR>¡Esperamos que todos<BR>los cazadores se unan<BR>en una última cacería y<BR>demuestren su fuerza!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61013.mib" DOWNLOAD CSUM=26138 FSIZE=3804 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Misión Desafío 10</a><BR>
				<a href=#002 qname=m61009>Misión Desafío 9</a><BR>
				<a href=#003 qname=m61008>Misión Desafío 8</a><BR>
				<a href=#004 qname=m61014>Fiesta Monster Hunter 4</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m61013>Fiesta Monster Hunter 3</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m61007>Misión Desafío 7</a><BR>
				<a href=#007 qname=m61006>Misión Desafío 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Fiesta Monster Hunter 3
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>3000z<br>
				<font color=orangered>&nbsp;Contrato :</font>0z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>20 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Gran arena<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;No<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Fiesta Monster Hunter 3
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Mata todos los monstruos<BR>grandes<BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Cliente：</font>Promotora voluptuosa<BR>
					Parece que hemos llegado<BR>a lo mejor de estas<BR>competiciones. ¡Me pregunto<BR>quién quedará en pie y se<BR>llevará el premio a casa.<BR>Estoy impaciente por ver<BR>tu magnífica técnica.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61007.mib" DOWNLOAD CSUM=11993 FSIZE=3132 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Misión Desafío 10</a><BR>
				<a href=#002 qname=m61009>Misión Desafío 9</a><BR>
				<a href=#003 qname=m61008>Misión Desafío 8</a><BR>
				<a href=#004 qname=m61014>Fiesta Monster Hunter 4</a><BR>
				<a href=#005 qname=m61013>Fiesta Monster Hunter 3</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m61007>Misión Desafío 7</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m61006>Misión Desafío 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Misión Desafío 7
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>24000z<br>
				<font color=orangered>&nbsp;Contrato :</font>0z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Gran arena<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 7 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Misión Desafío 7
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Mata a 2 Nargacuga<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>Cliente：</font>Instructor<BR>
					¡Lucha con 2 Nargacugas a<BR>la vez! ¡Cuidado con su<BR>velocidad y sus colas<BR>superfuertes! ¡Un latigazo<BR>es letal! Mantén la calma<BR>y piensa bien las cosas.<BR>No tardarán en caer.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61006.mib" DOWNLOAD CSUM=5097 FSIZE=7764 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Misión Desafío 10</a><BR>
				<a href=#002 qname=m61009>Misión Desafío 9</a><BR>
				<a href=#003 qname=m61008>Misión Desafío 8</a><BR>
				<a href=#004 qname=m61014>Fiesta Monster Hunter 4</a><BR>
				<a href=#005 qname=m61013>Fiesta Monster Hunter 3</a><BR>
				<a href=#006 qname=m61007>Misión Desafío 7</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m61006>Misión Desafío 6</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Misión Desafío 6
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>7500z<br>
				<font color=orangered>&nbsp;Contrato :</font>0z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>30 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Vieja jungla<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 4 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Misión Desafío 6
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Mata la Vespoid reina<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★<BR>
					<font color=orangered>Cliente：</font>Instructor<BR>
					Me han pedido que haga algo<BR>con los enormes bichos que<BR>han aparecido en la Vieja<BR>Jungla. Es sólo una idea,<BR>pero quizá quieras ir a por<BR>la jefa. ¡Vete zumbando a<BR>por la reina!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
</body>
</html>
