<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=3",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_CMENU.PHP?lang=3&pg_no=0",
		"RB_LINK=DL_CMENU.PHP?lang=3&pg_no=0",
		"MOVE_CHAR=../MHP2GUSA/GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=../MHP2GUSA/GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61005.mib" DOWNLOAD CSUM=25603 FSIZE=3816 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m61005>Quête défi 5</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m61012>Monster Hunter Fiesta 2</a><BR>
				<a href=#003 qname=m61004>Quête défi 4</a><BR>
				<a href=#004 qname=m61003>Quête défi 3</a><BR>
				<a href=#005 qname=m61002>Quête défi 2</a><BR>
				<a href=#006 qname=m61011>Monster Hunter Fiesta 1</a><BR>
				<a href=#007 qname=m61001>Quête défi 1</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/FR/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Quête défi 5
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Prime　:</font>4800z<br>
				<font color=orangered>&nbsp;Contrat:</font>0z<br>
				<font color=orangered>&nbsp;Temps　:</font>20 min.<br>
				<font color=orangered>&nbsp;Zone 　:</font>Grande arène<br>
				<font color=orangered>&nbsp;Conditions spéciales:</font><br>&nbsp;&nbsp;Aucune<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/FR/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Quête défi 5
			</td>
			<td>
				<font color=orangered>Niv. quête：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condition succès:</font><br>Tuer 2 Bulldrome<BR><BR><BR>
					<font color=orangered>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★<BR>
					<font color=orangered>Client：</font>Instructeur<BR>
					Combattre le ventre vide est<BR>la pire chose qu'un chasseur<BR>puisse faire. Pour maîtriser<BR>la chasse, il faut maîtriser<BR>ses repas ! Je vais faire de<BR>vous le roi de la cuisine.<BR>Ou plutôt, le maître du BBQ.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61012.mib" DOWNLOAD CSUM=45650 FSIZE=3420 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61005>Quête défi 5</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m61012>Monster Hunter Fiesta 2</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m61004>Quête défi 4</a><BR>
				<a href=#004 qname=m61003>Quête défi 3</a><BR>
				<a href=#005 qname=m61002>Quête défi 2</a><BR>
				<a href=#006 qname=m61011>Monster Hunter Fiesta 1</a><BR>
				<a href=#007 qname=m61001>Quête défi 1</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/FR/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Monster Hunter Fiesta 2
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Prime　:</font>3000z<br>
				<font color=orangered>&nbsp;Contrat:</font>0z<br>
				<font color=orangered>&nbsp;Temps　:</font>15 min.<br>
				<font color=orangered>&nbsp;Zone 　:</font>Grande arène<br>
				<font color=orangered>&nbsp;Conditions spéciales:</font><br>&nbsp;&nbsp;Aucune<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/FR/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Monster Hunter Fiesta 2
			</td>
			<td>
				<font color=orangered>Niv. quête：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condition succès:</font><br>Tuer le Tigrex<BR><BR><BR>
					<font color=orangered>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>Client：</font>Promoteur chaleureux<BR>
					C'est l'heure du festival !<BR>Votre adversaire du jour est<BR>le puissant Tigrex. Sa force<BR>peut vous broyer, alors si<BR>vous voulez passer à l'étape<BR>suivante, essayez de ne pas<BR>vous faire attraper !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61004.mib" DOWNLOAD CSUM=12064 FSIZE=7340 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61005>Quête défi 5</a><BR>
				<a href=#002 qname=m61012>Monster Hunter Fiesta 2</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m61004>Quête défi 4</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m61003>Quête défi 3</a><BR>
				<a href=#005 qname=m61002>Quête défi 2</a><BR>
				<a href=#006 qname=m61011>Monster Hunter Fiesta 1</a><BR>
				<a href=#007 qname=m61001>Quête défi 1</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/FR/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Quête défi 4
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Prime　:</font>21000z<br>
				<font color=orangered>&nbsp;Contrat:</font>0z<br>
				<font color=orangered>&nbsp;Temps　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone 　:</font>Vieille jungle<br>
				<font color=orangered>&nbsp;Conditions spéciales:</font><br>&nbsp;&nbsp;Un Rang de plus de 7 est<BR>　requis pour cette quête.<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/FR/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Quête défi 4
			</td>
			<td>
				<font color=orangered>Niv. quête：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condition succès:</font><br>Tuer tous les gros<BR>monstres<BR><BR>
					<font color=orangered>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Client：</font>Instructeur<BR>
					Pour lire dans les pensées<BR>des monstres et les battre,<BR>vous devez ne faire qu'un<BR>avec eux. Voilà à quoi sert<BR>cet entraînement. Utilisez<BR>cet équipement et rentrez<BR>dans la tête de ces bêtes !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61003.mib" DOWNLOAD CSUM=6176 FSIZE=3140 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61005>Quête défi 5</a><BR>
				<a href=#002 qname=m61012>Monster Hunter Fiesta 2</a><BR>
				<a href=#003 qname=m61004>Quête défi 4</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m61003>Quête défi 3</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m61002>Quête défi 2</a><BR>
				<a href=#006 qname=m61011>Monster Hunter Fiesta 1</a><BR>
				<a href=#007 qname=m61001>Quête défi 1</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/FR/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Quête défi 3
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Prime　:</font>60000z<br>
				<font color=orangered>&nbsp;Contrat:</font>0z<br>
				<font color=orangered>&nbsp;Temps　:</font>40 min.<br>
				<font color=orangered>&nbsp;Zone 　:</font>Arène inondée<br>
				<font color=orangered>&nbsp;Conditions spéciales:</font><br>&nbsp;&nbsp;Un Rang de plus de 7 est<BR>　requis pour cette quête.<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/FR/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Quête défi 3
			</td>
			<td>
				<font color=orangered>Niv. quête：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condition succès:</font><br>Tuer le Plesioth<BR><BR><BR>
					<font color=orangered>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>Client：</font>Instructeur<BR>
					Cette fois, ça se passe dans<BR>l'Arène inondée. La prime <BR>est très intéressante, alors<BR>ça ne coûte rien d'essayer.<BR>Quoi ? Les clauses ? Bah,<BR>ça ira ! Vous allez gagner !<BR>Enfin, peut-être... Ah ah !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61002.mib" DOWNLOAD CSUM=386 FSIZE=3600 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61005>Quête défi 5</a><BR>
				<a href=#002 qname=m61012>Monster Hunter Fiesta 2</a><BR>
				<a href=#003 qname=m61004>Quête défi 4</a><BR>
				<a href=#004 qname=m61003>Quête défi 3</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m61002>Quête défi 2</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m61011>Monster Hunter Fiesta 1</a><BR>
				<a href=#007 qname=m61001>Quête défi 1</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/FR/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Quête défi 2
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Prime　:</font>7500z<br>
				<font color=orangered>&nbsp;Contrat:</font>0z<br>
				<font color=orangered>&nbsp;Temps　:</font>20 min.<br>
				<font color=orangered>&nbsp;Zone 　:</font>Grande arène<br>
				<font color=orangered>&nbsp;Conditions spéciales:</font><br>&nbsp;&nbsp;Un Rang de plus de 4 est<BR>　requis pour cette quête.<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/FR/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Quête défi 2
			</td>
			<td>
				<font color=orangered>Niv. quête：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condition succès:</font><br>Tuer 2 Rois Shakalaka<BR><BR><BR>
					<font color=orangered>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★<BR>
					<font color=orangered>Client：</font>Instructeur<BR>
					Oh oh ! Un défi lancé par les<BR>Shakalaka ! Normalement, je<BR>m'en charge moi-même, mais<BR>je viens de me souvenir que<BR>j'ai un truc super important<BR>à faire. Alors allez-y à ma<BR>place et ramenez le trophée.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61011.mib" DOWNLOAD CSUM=53259 FSIZE=4552 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61005>Quête défi 5</a><BR>
				<a href=#002 qname=m61012>Monster Hunter Fiesta 2</a><BR>
				<a href=#003 qname=m61004>Quête défi 4</a><BR>
				<a href=#004 qname=m61003>Quête défi 3</a><BR>
				<a href=#005 qname=m61002>Quête défi 2</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m61011>Monster Hunter Fiesta 1</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m61001>Quête défi 1</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/FR/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Monster Hunter Fiesta 1
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Prime　:</font>2400z<br>
				<font color=orangered>&nbsp;Contrat:</font>0z<br>
				<font color=orangered>&nbsp;Temps　:</font>15 min.<br>
				<font color=orangered>&nbsp;Zone 　:</font>Grande forêt(Jour)<br>
				<font color=orangered>&nbsp;Conditions spéciales:</font><br>&nbsp;&nbsp;Aucune<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/FR/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Monster Hunter Fiesta 1
			</td>
			<td>
				<font color=orangered>Niv. quête：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condition succès:</font><br>Tuer le Nargacuga<BR><BR><BR>
					<font color=orangered>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>Client：</font>Jeune promoteur<BR>
					Bienvenue dans la compéti-<BR>tion ! Pour ce défi, on<BR>demande aux participants de<BR>tuer un Nargacuga de la<BR>Grande forêt. Ayez confiance<BR>en vous et montrez-nous<BR>votre vraie force !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61001.mib" DOWNLOAD CSUM=50690 FSIZE=7104 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61005>Quête défi 5</a><BR>
				<a href=#002 qname=m61012>Monster Hunter Fiesta 2</a><BR>
				<a href=#003 qname=m61004>Quête défi 4</a><BR>
				<a href=#004 qname=m61003>Quête défi 3</a><BR>
				<a href=#005 qname=m61002>Quête défi 2</a><BR>
				<a href=#006 qname=m61011>Monster Hunter Fiesta 1</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m61001>Quête défi 1</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/FR/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Quête défi 1
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Prime　:</font>6000z<br>
				<font color=orangered>&nbsp;Contrat:</font>0z<br>
				<font color=orangered>&nbsp;Temps　:</font>40 min.<br>
				<font color=orangered>&nbsp;Zone 　:</font>Jungle(nuit)<br>
				<font color=orangered>&nbsp;Conditions spéciales:</font><br>&nbsp;&nbsp;Aucune<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/FR/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Quête défi 1
			</td>
			<td>
				<font color=orangered>Niv. quête：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condition succès:</font><br>Tuer le Yian Garuga<BR><BR><BR>
					<font color=orangered>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★<BR>
					<font color=orangered>Client：</font>Instructeur<BR>
					Un Yian Garuga a été repéré<BR>dans la jungle et en tant<BR>qu'instructeur, je pense que<BR>c'est une bonne occasion<BR>d'entraînement. Je vais vous<BR>prêter de l'équipement.<BR>Préparez-vous au combat !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/FR/BUTTON4.gif></td></tr></table>
</body>
</html>
