<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=2",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_CMENU.PHP?lang=2&pg_no=1",
		"RB_LINK=DL_CMENU.PHP?lang=2&pg_no=1",
		"MOVE_CHAR=../MHP2GUSA/GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=../MHP2GUSA/GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61010.mib" DOWNLOAD CSUM=61231 FSIZE=3052 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m61010>Challenge-Quest 10</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m61009>Challenge-Quest 9</a><BR>
				<a href=#003 qname=m61008>Challenge-Quest 8</a><BR>
				<a href=#004 qname=m61014>Monsterjäger-Fiesta 4</a><BR>
				<a href=#005 qname=m61013>Monsterjäger-Fiesta 3</a><BR>
				<a href=#006 qname=m61007>Challenge-Quest 7</a><BR>
				<a href=#007 qname=m61006>Challenge-Quest 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Challenge-Quest 10
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>24000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>0z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Große Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  9 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Challenge-Quest 10
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Den Rajang töten<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Klient：</font>Ausbilder<BR>
					Der gefürchtete goldene <BR>Rajang! Der Stärkste der <BR>Starken, aber du packst <BR>das schon! <BR>Halte nichts zurück und <BR>der Sieg wird dir gehören!<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61009.mib" DOWNLOAD CSUM=37868 FSIZE=3404 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Challenge-Quest 10</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m61009>Challenge-Quest 9</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m61008>Challenge-Quest 8</a><BR>
				<a href=#004 qname=m61014>Monsterjäger-Fiesta 4</a><BR>
				<a href=#005 qname=m61013>Monsterjäger-Fiesta 3</a><BR>
				<a href=#006 qname=m61007>Challenge-Quest 7</a><BR>
				<a href=#007 qname=m61006>Challenge-Quest 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Challenge-Quest 9
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>12000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>0z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>40 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Große Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  7 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Challenge-Quest 9
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>50 Velocipreys töten<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>Klient：</font>Ausbilder<BR>
					Heute habe ich eine<BR>besondere Aufgabe für dich:<BR>Das Rudel Velocipreys,<BR>das in der großen Arena<BR>wartet. Aber sie sind klein<BR>im Vergleich zu dem anderen<BR>Monster, das dort lauert!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61008.mib" DOWNLOAD CSUM=10597 FSIZE=3684 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Challenge-Quest 10</a><BR>
				<a href=#002 qname=m61009>Challenge-Quest 9</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m61008>Challenge-Quest 8</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m61014>Monsterjäger-Fiesta 4</a><BR>
				<a href=#005 qname=m61013>Monsterjäger-Fiesta 3</a><BR>
				<a href=#006 qname=m61007>Challenge-Quest 7</a><BR>
				<a href=#007 qname=m61006>Challenge-Quest 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Challenge-Quest 8
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>27000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>0z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Burggraben-Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  7 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Challenge-Quest 8
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Alle großen Monster töten<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Klient：</font>Ausbilder<BR>
					Ich führe meine eigene Arena<BR>und gebe für herausragende <BR>Zeiten Preise aus meinem <BR>eigenen Schatz. Du kannst <BR>sogar mit deinen Freunden <BR>kommen. <BR>Lass mich nicht warten!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61014.mib" DOWNLOAD CSUM=17488 FSIZE=3184 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Challenge-Quest 10</a><BR>
				<a href=#002 qname=m61009>Challenge-Quest 9</a><BR>
				<a href=#003 qname=m61008>Challenge-Quest 8</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m61014>Monsterjäger-Fiesta 4</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m61013>Monsterjäger-Fiesta 3</a><BR>
				<a href=#006 qname=m61007>Challenge-Quest 7</a><BR>
				<a href=#007 qname=m61006>Challenge-Quest 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Monsterjäger-Fiesta 4
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>4500z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>0z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>20 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Große Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nein<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Monsterjäger-Fiesta 4
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Den Rajang töten<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Klient：</font>TugendhafterPromoter<BR>
					Dank der Teilnahme so vieler<BR>starker Jäger konnten wir <BR>diese Phase, das Finale, <BR>erreichen! Wir hoffen, dass <BR>alle Jäger an der letzten <BR>Jagd als Zeichen wahrer <BR>Macht teilnehmen werden!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61013.mib" DOWNLOAD CSUM=26138 FSIZE=3804 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Challenge-Quest 10</a><BR>
				<a href=#002 qname=m61009>Challenge-Quest 9</a><BR>
				<a href=#003 qname=m61008>Challenge-Quest 8</a><BR>
				<a href=#004 qname=m61014>Monsterjäger-Fiesta 4</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m61013>Monsterjäger-Fiesta 3</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m61007>Challenge-Quest 7</a><BR>
				<a href=#007 qname=m61006>Challenge-Quest 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Monsterjäger-Fiesta 3
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>3000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>0z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>20 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Große Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nein<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Monsterjäger-Fiesta 3
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Alle großen Monster töten<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Klient：</font>Sinnlicher Promoter<BR>
					Wir haben den besten Teil <BR>der Wettbewerbe erreicht. <BR>Wer wird am Ende wohl siegen<BR>und den Beweis nach Hause <BR>tragen? Ich freue mich auf <BR>eine Demonstration deiner <BR>großartigen Technik.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61007.mib" DOWNLOAD CSUM=11993 FSIZE=3132 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Challenge-Quest 10</a><BR>
				<a href=#002 qname=m61009>Challenge-Quest 9</a><BR>
				<a href=#003 qname=m61008>Challenge-Quest 8</a><BR>
				<a href=#004 qname=m61014>Monsterjäger-Fiesta 4</a><BR>
				<a href=#005 qname=m61013>Monsterjäger-Fiesta 3</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m61007>Challenge-Quest 7</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m61006>Challenge-Quest 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Challenge-Quest 7
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>24000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>0z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Große Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  7 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Challenge-Quest 7
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>2 Nargacugas töten<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>Klient：</font>Ausbilder<BR>
					Bekämpfe 2 Nargacugas! Sie <BR>sind schnell und haben über-<BR>aus starke Schwänze. Sei <BR>auf der Hut! Ein Schlag und <BR>du bist Geschichte! Bleib <BR>cool und plane voraus. <BR>Sie werden schon fallen.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61006.mib" DOWNLOAD CSUM=5097 FSIZE=7764 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Challenge-Quest 10</a><BR>
				<a href=#002 qname=m61009>Challenge-Quest 9</a><BR>
				<a href=#003 qname=m61008>Challenge-Quest 8</a><BR>
				<a href=#004 qname=m61014>Monsterjäger-Fiesta 4</a><BR>
				<a href=#005 qname=m61013>Monsterjäger-Fiesta 3</a><BR>
				<a href=#006 qname=m61007>Challenge-Quest 7</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m61006>Challenge-Quest 6</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Challenge-Quest 6
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>7500z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>0z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>30 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Alter Dschungel<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  4 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Challenge-Quest 6
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Die Vespoid-Königin töten<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★<BR>
					<font color=orangered>Klient：</font>Ausbilder<BR>
					Man hat mich gebeten, etwas <BR>gegen die riesigen Käfer im <BR>Alten Dschungel zu unter-<BR>nehmen. Wie wär's, wenn du <BR>dich um die Anführerin <BR>kümmerst? Schnapp dir die <BR>Königin!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
</body>
</html>
