<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=5",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_CMENU.PHP?lang=5&pg_no=1",
		"RB_LINK=DL_CMENU.PHP?lang=5&pg_no=1",
		"MOVE_CHAR=../MHP2GUSA/GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=../MHP2GUSA/GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61010.mib" DOWNLOAD CSUM=61231 FSIZE=3052 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m61010>Missione Sfida 10</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m61009>Missione Sfida 9</a><BR>
				<a href=#003 qname=m61008>Missione Sfida 8</a><BR>
				<a href=#004 qname=m61014>Monster Hunter Fiesta 4</a><BR>
				<a href=#005 qname=m61013>Monster Hunter Fiesta 3</a><BR>
				<a href=#006 qname=m61007>Missione Sfida 7</a><BR>
				<a href=#007 qname=m61006>Missione Sfida 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/IT/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Missione Sfida 10
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Premio 　:</font>24000z<br>
				<font color=orangered>&nbsp;Contratto:</font>0z<br>
				<font color=orangered>&nbsp;Tempo　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Grande arena<br>
				<font color=orangered>&nbsp;Condizioni speciali:</font><br>&nbsp;&nbsp;Solo GC 9 o superiore<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/IT/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Missione Sfida 10
			</td>
			<td>
				<font color=orangered>Liv. miss.：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condizioni vittoria:</font><br>Uccidi il Rajang<BR><BR><BR>
					<font color=orangered>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Cliente：</font>Istruttore<BR>
					È il temutissimo Rajang<BR>dorato! È la bestia più <BR>forte che potrai mai <BR>affrontare, ma visto che si<BR>tratta di te, confido che <BR>batterai quel mostro. Non <BR>risparmiarti e vincerai!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61009.mib" DOWNLOAD CSUM=37868 FSIZE=3404 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Missione Sfida 10</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m61009>Missione Sfida 9</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m61008>Missione Sfida 8</a><BR>
				<a href=#004 qname=m61014>Monster Hunter Fiesta 4</a><BR>
				<a href=#005 qname=m61013>Monster Hunter Fiesta 3</a><BR>
				<a href=#006 qname=m61007>Missione Sfida 7</a><BR>
				<a href=#007 qname=m61006>Missione Sfida 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/IT/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Missione Sfida 9
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Premio 　:</font>12000z<br>
				<font color=orangered>&nbsp;Contratto:</font>0z<br>
				<font color=orangered>&nbsp;Tempo　　:</font>40 min.<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Grande arena<br>
				<font color=orangered>&nbsp;Condizioni speciali:</font><br>&nbsp;&nbsp;Solo GC 7 o superiore<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/IT/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Missione Sfida 9
			</td>
			<td>
				<font color=orangered>Liv. miss.：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condizioni vittoria:</font><br>Uccidi 50 Velociprey<BR><BR><BR>
					<font color=orangered>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>Cliente：</font>Istruttore<BR>
					Ora ho una missione speciale<BR>per te! L'obiettivo: il <BR>branco di Velociprey che ti<BR>aspetta nell'Grande arena. <BR>Ma quelli sono poca cosa<BR>in confronto all'altro<BR>mostro che troverai laggiù!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61008.mib" DOWNLOAD CSUM=10597 FSIZE=3684 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Missione Sfida 10</a><BR>
				<a href=#002 qname=m61009>Missione Sfida 9</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m61008>Missione Sfida 8</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m61014>Monster Hunter Fiesta 4</a><BR>
				<a href=#005 qname=m61013>Monster Hunter Fiesta 3</a><BR>
				<a href=#006 qname=m61007>Missione Sfida 7</a><BR>
				<a href=#007 qname=m61006>Missione Sfida 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/IT/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Missione Sfida 8
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Premio 　:</font>27000z<br>
				<font color=orangered>&nbsp;Contratto:</font>0z<br>
				<font color=orangered>&nbsp;Tempo　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Arena del fosso<br>
				<font color=orangered>&nbsp;Condizioni speciali:</font><br>&nbsp;&nbsp;Solo GC 7 o superiore<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/IT/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Missione Sfida 8
			</td>
			<td>
				<font color=orangered>Liv. miss.：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condizioni vittoria:</font><br>Uccidi tutti i mostri<BR>di grandi dimensioni<BR><BR>
					<font color=orangered>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Cliente：</font>Istruttore<BR>
					Dirigo un'arena tutta mia,<BR>dove sarò lieto di premiare<BR>con alcuni dei miei tesori<BR>chiunque ottenga tempi <BR>record. Puoi anche <BR>partecipare con i tuoi <BR>amici. Non farmi aspettare!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61014.mib" DOWNLOAD CSUM=17488 FSIZE=3184 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Missione Sfida 10</a><BR>
				<a href=#002 qname=m61009>Missione Sfida 9</a><BR>
				<a href=#003 qname=m61008>Missione Sfida 8</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m61014>Monster Hunter Fiesta 4</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m61013>Monster Hunter Fiesta 3</a><BR>
				<a href=#006 qname=m61007>Missione Sfida 7</a><BR>
				<a href=#007 qname=m61006>Missione Sfida 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/IT/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Monster Hunter Fiesta 4
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Premio 　:</font>4500z<br>
				<font color=orangered>&nbsp;Contratto:</font>0z<br>
				<font color=orangered>&nbsp;Tempo　　:</font>20 min.<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Grande arena<br>
				<font color=orangered>&nbsp;Condizioni speciali:</font><br>&nbsp;&nbsp;No<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/IT/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Monster Hunter Fiesta 4
			</td>
			<td>
				<font color=orangered>Liv. miss.：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condizioni vittoria:</font><br>Uccidi il Rajang<BR><BR><BR>
					<font color=orangered>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Cliente：</font>Promotore virtuoso<BR>
					Grazie alla partecipazione <BR>di tanti forti cacciatori,<BR>abbiamo raggiunto la fase <BR>finale della sfida! Ci<BR>auguriamo che tutti costoro <BR>dimostrino la loro vera<BR>potenza in un'ultima caccia!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61013.mib" DOWNLOAD CSUM=26138 FSIZE=3804 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Missione Sfida 10</a><BR>
				<a href=#002 qname=m61009>Missione Sfida 9</a><BR>
				<a href=#003 qname=m61008>Missione Sfida 8</a><BR>
				<a href=#004 qname=m61014>Monster Hunter Fiesta 4</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m61013>Monster Hunter Fiesta 3</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m61007>Missione Sfida 7</a><BR>
				<a href=#007 qname=m61006>Missione Sfida 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/IT/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Monster Hunter Fiesta 3
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Premio 　:</font>3000z<br>
				<font color=orangered>&nbsp;Contratto:</font>0z<br>
				<font color=orangered>&nbsp;Tempo　　:</font>20 min.<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Grande arena<br>
				<font color=orangered>&nbsp;Condizioni speciali:</font><br>&nbsp;&nbsp;No<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/IT/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Monster Hunter Fiesta 3
			</td>
			<td>
				<font color=orangered>Liv. miss.：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condizioni vittoria:</font><br>Uccidi tutti i mostri<BR>di grandi dimensioni<BR><BR>
					<font color=orangered>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Cliente：</font>Promot. voluttuoso<BR>
					Sembra che siamo giunti alla<BR>parte migliore di queste<BR>competizioni. Mi chiedo chi<BR>rimarrà in piedi fino alla <BR>fine e tornerà a casa sulle<BR>proprie gambe. Aspetto di<BR>ammirare la tua tecnica.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61007.mib" DOWNLOAD CSUM=11993 FSIZE=3132 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Missione Sfida 10</a><BR>
				<a href=#002 qname=m61009>Missione Sfida 9</a><BR>
				<a href=#003 qname=m61008>Missione Sfida 8</a><BR>
				<a href=#004 qname=m61014>Monster Hunter Fiesta 4</a><BR>
				<a href=#005 qname=m61013>Monster Hunter Fiesta 3</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m61007>Missione Sfida 7</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m61006>Missione Sfida 6</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/IT/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Missione Sfida 7
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Premio 　:</font>24000z<br>
				<font color=orangered>&nbsp;Contratto:</font>0z<br>
				<font color=orangered>&nbsp;Tempo　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Grande arena<br>
				<font color=orangered>&nbsp;Condizioni speciali:</font><br>&nbsp;&nbsp;Solo GC 7 o superiore<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/IT/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Missione Sfida 7
			</td>
			<td>
				<font color=orangered>Liv. miss.：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condizioni vittoria:</font><br>Uccidi 2 Nargacuga<BR><BR><BR>
					<font color=orangered>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★<BR>
					<font color=orangered>Cliente：</font>Istruttore<BR>
					Lotta corpo a corpo con 2<BR>Nargacuga! Fai attenzione<BR>all'incredibile velocità e<BR>alle code super-potenti! <BR>Un solo colpo e addio! <BR>Sangue freddo, rifletti <BR>prima di agire: ce la farai.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m61006.mib" DOWNLOAD CSUM=5097 FSIZE=7764 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/２</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m61010>Missione Sfida 10</a><BR>
				<a href=#002 qname=m61009>Missione Sfida 9</a><BR>
				<a href=#003 qname=m61008>Missione Sfida 8</a><BR>
				<a href=#004 qname=m61014>Monster Hunter Fiesta 4</a><BR>
				<a href=#005 qname=m61013>Monster Hunter Fiesta 3</a><BR>
				<a href=#006 qname=m61007>Missione Sfida 7</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m61006>Missione Sfida 6</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/IT/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Missione Sfida 6
			</td>
		</tr>
		<tr>
			<td height=120 valign=top>
				<font color=orangered>&nbsp;Premio 　:</font>7500z<br>
				<font color=orangered>&nbsp;Contratto:</font>0z<br>
				<font color=orangered>&nbsp;Tempo　　:</font>30 min.<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Giungla antica<br>
				<font color=orangered>&nbsp;Condizioni speciali:</font><br>&nbsp;&nbsp;Solo GC 4 o superiore<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/IT/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Missione Sfida 6
			</td>
			<td>
				<font color=orangered>Liv. miss.：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condizioni vittoria:</font><br>Uccidi il Vespoid regina<BR><BR><BR>
					<font color=orangered>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★<BR>
					<font color=orangered>Cliente：</font>Istruttore<BR>
					Ho ricevuto una richiesta di<BR>intervento per via di quegli<BR>enormi insetti sbucati<BR>nella Giungla antica. <BR>Forse potresti guidare tu la<BR>missione. Punta dritto<BR>sulla Regina!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
</body>
</html>
