<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=2",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=2&pg_no=1",
		"RB_LINK=DL_MENU.PHP?lang=2&pg_no=3",
		"MOVE_CHAR=../MHP2GUSA/GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=../MHP2GUSA/GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60012.mib" DOWNLOAD CSUM=17793 FSIZE=6272 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60012>Monster der Dünen</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m60025>Lorbeer, bitte.</a><BR>
				<a href=#003 qname=m60029>Der große Kerl</a><BR>
				<a href=#004 qname=m60017>Arena aus Blut und Tränen</a><BR>
				<a href=#005 qname=m60023>Der Name lautet Mega Kut-Ku?</a><BR>
				<a href=#006 qname=m60020>Schweine-Panikparty!</a><BR>
				<a href=#007 qname=m60030>Schwarze Schicksalsschwingen</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Monster der Dünen
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>24000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>2000z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Wüste(Tag)<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  7 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Monster der Dünen
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>2 Kupfer-Blangongas erjagen<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>Klient：</font>Verwundete Kreaturen<BR>
					Wir haben unserem Meister <BR>ein Versprechen gegeben. <BR>*miau* Wir müssen diesen <BR>Brief überbringen. Wir <BR>waren fast dort, aber dort <BR>gibt es so viele Monster. <BR>Bitte helft uns ... *miau*<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60025.mib" DOWNLOAD CSUM=4576 FSIZE=3136 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Monster der Dünen</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60025>Lorbeer, bitte.</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m60029>Der große Kerl</a><BR>
				<a href=#004 qname=m60017>Arena aus Blut und Tränen</a><BR>
				<a href=#005 qname=m60023>Der Name lautet Mega Kut-Ku?</a><BR>
				<a href=#006 qname=m60020>Schweine-Panikparty!</a><BR>
				<a href=#007 qname=m60030>Schwarze Schicksalsschwingen</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Lorbeer, bitte.
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>12000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>1000z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Große Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nein<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_PNK2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Lorbeer, bitte.
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Alle großen Monster erjagen<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Klient：</font>Junger Arena-Manager<BR>
					Du willst angeben? Dann ab <BR>in die Arena! Heute servie-<BR>ren wir Congalala, Rathian, <BR>Shogun Ceanataur und vieles <BR>mehr! Nutze die wenigen <BR>Tränke, die du findest, mit <BR>Umsicht!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60029.mib" DOWNLOAD CSUM=14869 FSIZE=4804 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Monster der Dünen</a><BR>
				<a href=#002 qname=m60025>Lorbeer, bitte.</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60029>Der große Kerl</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m60017>Arena aus Blut und Tränen</a><BR>
				<a href=#005 qname=m60023>Der Name lautet Mega Kut-Ku?</a><BR>
				<a href=#006 qname=m60020>Schweine-Panikparty!</a><BR>
				<a href=#007 qname=m60030>Schwarze Schicksalsschwingen</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Der große Kerl
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>36000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>3000z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Turm<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  6 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_PPL2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Der große Kerl
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Den Fatalis töten<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★★★<BR>
					<font color=orangered>Klient：</font>Reine, weiße Felyne<BR>
					Meister! Willst du den alten<BR>Turm besuchen? Das darfst du<BR>dir nicht entgehen lassen, <BR>miau! Es ist unglaublich! <BR>Aber ich habe schon ein <BR>schlechtes Gefühl ...<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60017.mib" DOWNLOAD CSUM=37796 FSIZE=3360 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Monster der Dünen</a><BR>
				<a href=#002 qname=m60025>Lorbeer, bitte.</a><BR>
				<a href=#003 qname=m60029>Der große Kerl</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60017>Arena aus Blut und Tränen</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m60023>Der Name lautet Mega Kut-Ku?</a><BR>
				<a href=#006 qname=m60020>Schweine-Panikparty!</a><BR>
				<a href=#007 qname=m60030>Schwarze Schicksalsschwingen</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Arena aus Blut und Tränen
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>39000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>3250z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Burggraben-Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  7 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_PNK2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Arena aus Blut und Tränen
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Alle großen Monster erjagen<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>Klient：</font>Ernste Rittersfrau<BR>
					Das ist zwar nicht meine <BR>Art, aber es gibt jemanden,<BR>der Stärke testen möchte.<BR>Beweise deine wahre Kraft.<BR>Selbstverständlich wirst<BR>du für deinen Aufwand <BR>entlohnt werden.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60023.mib" DOWNLOAD CSUM=54531 FSIZE=6144 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Monster der Dünen</a><BR>
				<a href=#002 qname=m60025>Lorbeer, bitte.</a><BR>
				<a href=#003 qname=m60029>Der große Kerl</a><BR>
				<a href=#004 qname=m60017>Arena aus Blut und Tränen</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60023>Der Name lautet Mega Kut-Ku?</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m60020>Schweine-Panikparty!</a><BR>
				<a href=#007 qname=m60030>Schwarze Schicksalsschwingen</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Der Name lautet Mega Kut-Ku?
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>6000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>500z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Wald&Hügel(Tag)<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Keine Rüstung angelegt.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Der Name lautet Mega Kut-Ku?
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>2 Yian Kut-Kus erjagen (?)<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★<BR>
					<font color=orangered>Klient：</font>Liebhaber von Essen<BR>
					Ich bin auf der Suche nach <BR>einem unvergleichlichen Ge-<BR>schmackserlebnis. Hier soll <BR>ein legendäres Wesen auf <BR>einem Hügel leben. Helft mir<BR>bei der Erfüllung meines <BR>Lebenstraums. Auf zur Jagd!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60020.mib" DOWNLOAD CSUM=25038 FSIZE=2796 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Monster der Dünen</a><BR>
				<a href=#002 qname=m60025>Lorbeer, bitte.</a><BR>
				<a href=#003 qname=m60029>Der große Kerl</a><BR>
				<a href=#004 qname=m60017>Arena aus Blut und Tränen</a><BR>
				<a href=#005 qname=m60023>Der Name lautet Mega Kut-Ku?</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60020>Schweine-Panikparty!</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m60030>Schwarze Schicksalsschwingen</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Schweine-Panikparty!
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>8400z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>700z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  7 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Schweine-Panikparty!
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>30 Bullfangos töten<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★<BR>
					<font color=orangered>Klient：</font>ZeigefrVerdächtiDame<BR>
					Ich suche noch Jäger als <BR>Attraktion für mein Fest. <BR>Hee, hee, hee... Es wird<BR>ein prächtiges Büffet frei-<BR>laufender Schweinchen sein,<BR>wenn du so willst. Ob du<BR>wohl schneller bist?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60030.mib" DOWNLOAD CSUM=64928 FSIZE=2524 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Monster der Dünen</a><BR>
				<a href=#002 qname=m60025>Lorbeer, bitte.</a><BR>
				<a href=#003 qname=m60029>Der große Kerl</a><BR>
				<a href=#004 qname=m60017>Arena aus Blut und Tränen</a><BR>
				<a href=#005 qname=m60023>Der Name lautet Mega Kut-Ku?</a><BR>
				<a href=#006 qname=m60020>Schweine-Panikparty!</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60030>Schwarze Schicksalsschwingen</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Schwarze Schicksalsschwingen
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>54000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>4500z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>SchlsSchrade<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  9 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_PPL2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Schwarze Schicksalsschwingen
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Den Fatalis töten<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Klient：</font>ListigerGildenmeistr<BR>
					Man sagt, ein Drache mit <BR>schwarzen Schwingen wurde in<BR>den alten Schlossruinen ge-<BR>sehen. Unsere Expedition ist<BR>verschollen - ich befürchte <BR>das Schlimmste. Will denn <BR>niemand nachsehen?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
</body>
</html>
