<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=5",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=5&pg_no=1",
		"RB_LINK=DL_MENU.PHP?lang=5&pg_no=3",
		"MOVE_CHAR=../MHP2GUSA/GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=../MHP2GUSA/GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60012.mib" DOWNLOAD CSUM=17793 FSIZE=6272 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60012>Bestie delle dune</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m60025>Gloria e onore, prego.</a><BR>
				<a href=#003 qname=m60029>Viaggi e presagi</a><BR>
				<a href=#004 qname=m60017>Arena di sangue e lacrime</a><BR>
				<a href=#005 qname=m60023>Si chiama "Mega Kut-Ku"!?</a><BR>
				<a href=#006 qname=m60020>Mandria selvaggia in festa!</a><BR>
				<a href=#007 qname=m60030>Le ali nere del destino</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/IT/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Bestie delle dune
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Premio 　:</font>24000z<br>
				<font color=orangered>&nbsp;Contratto:</font>2000z<br>
				<font color=orangered>&nbsp;Tempo　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Deserto(giorno)<br>
				<font color=orangered>&nbsp;Condizioni speciali:</font><br>&nbsp;&nbsp;Solo GC 7 o superiore<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/IT/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Bestie delle dune
			</td>
			<td>
				<font color=orangered>Liv. miss.：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condizioni vittoria:</font><br>Caccia 2 Blangonga ramati<BR><BR><BR>
					<font color=orangered>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>Cliente：</font>Creature ferite<BR>
					Abbiamo fatto una promessa<BR>al nostro padrone, miao! <BR>Dobbiamo solo recapitare<BR>questa lettera! Ci eravamo<BR>così vicini, ma poi quei <BR>mostri là fuori... Ti<BR>prego... Aiutaci... Miao...<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60025.mib" DOWNLOAD CSUM=4576 FSIZE=3136 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Bestie delle dune</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60025>Gloria e onore, prego.</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m60029>Viaggi e presagi</a><BR>
				<a href=#004 qname=m60017>Arena di sangue e lacrime</a><BR>
				<a href=#005 qname=m60023>Si chiama "Mega Kut-Ku"!?</a><BR>
				<a href=#006 qname=m60020>Mandria selvaggia in festa!</a><BR>
				<a href=#007 qname=m60030>Le ali nere del destino</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/IT/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Gloria e onore, prego.
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Premio 　:</font>12000z<br>
				<font color=orangered>&nbsp;Contratto:</font>1000z<br>
				<font color=orangered>&nbsp;Tempo　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Grande arena<br>
				<font color=orangered>&nbsp;Condizioni speciali:</font><br>&nbsp;&nbsp;No<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/IT/T_PNK2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Gloria e onore, prego.
			</td>
			<td>
				<font color=orangered>Liv. miss.：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condizioni vittoria:</font><br>Caccia tutti i mostri<BR>di grandi dimensioni<BR><BR>
					<font color=orangered>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Cliente：</font>Giov. manager arena<BR>
					Vuoi esibirti? Bene, l'arena<BR>è perfetta per te! Oggi <BR>il menu offre Congalala, <BR>Rathian, Shogun Ceanataur e<BR>molto altro ancora! Usa<BR>bene le poche Pozioni<BR>che trovi!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60029.mib" DOWNLOAD CSUM=14869 FSIZE=4804 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Bestie delle dune</a><BR>
				<a href=#002 qname=m60025>Gloria e onore, prego.</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60029>Viaggi e presagi</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m60017>Arena di sangue e lacrime</a><BR>
				<a href=#005 qname=m60023>Si chiama "Mega Kut-Ku"!?</a><BR>
				<a href=#006 qname=m60020>Mandria selvaggia in festa!</a><BR>
				<a href=#007 qname=m60030>Le ali nere del destino</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/IT/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Viaggi e presagi
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Premio 　:</font>36000z<br>
				<font color=orangered>&nbsp;Contratto:</font>3000z<br>
				<font color=orangered>&nbsp;Tempo　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Torre<br>
				<font color=orangered>&nbsp;Condizioni speciali:</font><br>&nbsp;&nbsp;Solo GC 6 o superiore<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/IT/T_PPL2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Viaggi e presagi
			</td>
			<td>
				<font color=orangered>Liv. miss.：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condizioni vittoria:</font><br>Uccidi il Fatalis<BR><BR><BR>
					<font color=orangered>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★★★<BR>
					<font color=orangered>Cliente：</font>Felyne bianco neve<BR>
					Padrone! Vuoi controllare<BR>la Torre antica? Non puoi<BR>permetterti di perdere<BR>l'occasione, miao... Se ci <BR>vai, vedrai qualcosa di <BR>incredibile... Anche se non<BR>ho buoni presentimenti...<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60017.mib" DOWNLOAD CSUM=37796 FSIZE=3360 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Bestie delle dune</a><BR>
				<a href=#002 qname=m60025>Gloria e onore, prego.</a><BR>
				<a href=#003 qname=m60029>Viaggi e presagi</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60017>Arena di sangue e lacrime</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m60023>Si chiama "Mega Kut-Ku"!?</a><BR>
				<a href=#006 qname=m60020>Mandria selvaggia in festa!</a><BR>
				<a href=#007 qname=m60030>Le ali nere del destino</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/IT/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Arena di sangue e lacrime
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Premio 　:</font>39000z<br>
				<font color=orangered>&nbsp;Contratto:</font>3250z<br>
				<font color=orangered>&nbsp;Tempo　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Arena del fosso<br>
				<font color=orangered>&nbsp;Condizioni speciali:</font><br>&nbsp;&nbsp;Solo GC 7 o superiore<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/IT/T_PNK2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Arena di sangue e lacrime
			</td>
			<td>
				<font color=orangered>Liv. miss.：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condizioni vittoria:</font><br>Caccia tutti i mostri<BR>di grandi dimensioni<BR><BR>
					<font color=orangered>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>Cliente：</font>Seria dama a cavallo<BR>
					Benché di solito non sia<BR>mio costume, c'è qualcuno<BR>che vuole mettere alla<BR>prova la tua forza. Puoi<BR>mostrami il tuo vero<BR>potere? Aspettati una<BR>ricompensa per il disturbo.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60023.mib" DOWNLOAD CSUM=54531 FSIZE=6144 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Bestie delle dune</a><BR>
				<a href=#002 qname=m60025>Gloria e onore, prego.</a><BR>
				<a href=#003 qname=m60029>Viaggi e presagi</a><BR>
				<a href=#004 qname=m60017>Arena di sangue e lacrime</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60023>Si chiama "Mega Kut-Ku"!?</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m60020>Mandria selvaggia in festa!</a><BR>
				<a href=#007 qname=m60030>Le ali nere del destino</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/IT/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Si chiama "Mega Kut-Ku"!?
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Premio 　:</font>6000z<br>
				<font color=orangered>&nbsp;Contratto:</font>500z<br>
				<font color=orangered>&nbsp;Tempo　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Foresta e coll.(g)<br>
				<font color=orangered>&nbsp;Condizioni speciali:</font><br>&nbsp;&nbsp;Avviare missione o unirsi:<BR>　nessun’armatura equipagg.<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/IT/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Si chiama "Mega Kut-Ku"!?
			</td>
			<td>
				<font color=orangered>Liv. miss.：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condizioni vittoria:</font><br>Caccia 2 Yian Kut-Ku (?)<BR><BR><BR>
					<font color=orangered>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★<BR>
					<font color=orangered>Cliente：</font>Buongustaio<BR>
					Sono giunto qui in cerca di<BR>un cibo non ancora gustato<BR>da papille umane. Ho sentito<BR>che là, su quella collina, <BR>vive una mitica creatura.<BR>Aiutami a soddisfare la mia<BR>ambizione! Forza, a caccia!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60020.mib" DOWNLOAD CSUM=25038 FSIZE=2796 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Bestie delle dune</a><BR>
				<a href=#002 qname=m60025>Gloria e onore, prego.</a><BR>
				<a href=#003 qname=m60029>Viaggi e presagi</a><BR>
				<a href=#004 qname=m60017>Arena di sangue e lacrime</a><BR>
				<a href=#005 qname=m60023>Si chiama "Mega Kut-Ku"!?</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60020>Mandria selvaggia in festa!</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m60030>Le ali nere del destino</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/IT/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Mandria selvaggia in festa!
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Premio 　:</font>8400z<br>
				<font color=orangered>&nbsp;Contratto:</font>700z<br>
				<font color=orangered>&nbsp;Tempo　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Arena<br>
				<font color=orangered>&nbsp;Condizioni speciali:</font><br>&nbsp;&nbsp;Solo GC 7 o superiore<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/IT/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Mandria selvaggia in festa!
			</td>
			<td>
				<font color=orangered>Liv. miss.：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condizioni vittoria:</font><br>Uccidi 30 Bullfango<BR><BR><BR>
					<font color=orangered>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★<BR>
					<font color=orangered>Cliente：</font>Dama sospetta<BR>
					Vorrei movimentare la<BR>mia festa, perciò recluto<BR>cacciatori. Eh eh eh...<BR>È un vero e proprio buffet<BR>di cinghiali che vagano<BR>liberi... Chissà se riesci <BR>a superarli in velocità...<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60030.mib" DOWNLOAD CSUM=64928 FSIZE=2524 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Bestie delle dune</a><BR>
				<a href=#002 qname=m60025>Gloria e onore, prego.</a><BR>
				<a href=#003 qname=m60029>Viaggi e presagi</a><BR>
				<a href=#004 qname=m60017>Arena di sangue e lacrime</a><BR>
				<a href=#005 qname=m60023>Si chiama "Mega Kut-Ku"!?</a><BR>
				<a href=#006 qname=m60020>Mandria selvaggia in festa!</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60030>Le ali nere del destino</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/IT/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Le ali nere del destino
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Premio 　:</font>54000z<br>
				<font color=orangered>&nbsp;Contratto:</font>4500z<br>
				<font color=orangered>&nbsp;Tempo　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Castello Schrade<br>
				<font color=orangered>&nbsp;Condizioni speciali:</font><br>&nbsp;&nbsp;Solo GC 9 o superiore<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/IT/T_PPL2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Le ali nere del destino
			</td>
			<td>
				<font color=orangered>Liv. miss.：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Condizioni vittoria:</font><br>Uccidi il Fatalis<BR><BR><BR>
					<font color=orangered>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Cliente：</font>Scaltro maest. Gilda<BR>
					Abbiamo saputo che un drago <BR>dalle ali nere è stato visto<BR>presso le rovine di un<BR>antico castello. Gli uomini<BR>della nostra spedizione  <BR>sono scomparsi e temo il  <BR>peggio. Chi ci va?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON4.gif></td></tr></table>
</body>
</html>
