<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=4",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=4&pg_no=3",
		"RB_LINK=DL_MENU.PHP?lang=4&pg_no=1",
		"MOVE_CHAR=../MHP2GUSA/GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=../MHP2GUSA/GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60038.mib" DOWNLOAD CSUM=60310 FSIZE=2520 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60038>Terror doble</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m60034>Rey de altura</a><BR>
				<a href=#003 qname=m60019>Cacería divina para todos</a><BR>
				<a href=#004 qname=m60010>Montaña en el cielo</a><BR>
				<a href=#005 qname=m60016>La lágrima del demonio</a><BR>
				<a href=#006 qname=m60018>Cuatro reyes de fuego</a><BR>
				<a href=#007 qname=m60015>¡Dos abismos! Viento cálido</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Terror doble
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>42000z<br>
				<font color=orangered>&nbsp;Contrato :</font>3500z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Gran arena<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 7 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Terror doble
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Caza 2 Rajang<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Cliente：</font>Mercenario pálido<BR>
					¡No puedo creer lo que vi!<BR>Fue horrible. Allí estaban,<BR>2 Rajang esperando en la<BR>arena...<BR>Escucha, si das algún valor<BR>a tu vida, ¡no te acerques<BR>allí! ¿De acuerdo?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60034.mib" DOWNLOAD CSUM=30781 FSIZE=2332 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60038>Terror doble</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60034>Rey de altura</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m60019>Cacería divina para todos</a><BR>
				<a href=#004 qname=m60010>Montaña en el cielo</a><BR>
				<a href=#005 qname=m60016>La lágrima del demonio</a><BR>
				<a href=#006 qname=m60018>Cuatro reyes de fuego</a><BR>
				<a href=#007 qname=m60015>¡Dos abismos! Viento cálido</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Rey de altura
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>60000z<br>
				<font color=orangered>&nbsp;Contrato :</font>5000z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Campo Batalla<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 9 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Rey de altura
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Mata al Akantor<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Cliente：</font>Monarca benevolente<BR>
					El profundamente poderoso<BR>Akantor...<BR>Lo hemos perseguido, pero<BR>sufriendo muchos daños.<BR>¡Cazadores de esta tierra!<BR>¡Os pido vuestra ayuda<BR>inmediata!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60019.mib" DOWNLOAD CSUM=8338 FSIZE=3596 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60038>Terror doble</a><BR>
				<a href=#002 qname=m60034>Rey de altura</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60019>Cacería divina para todos</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m60010>Montaña en el cielo</a><BR>
				<a href=#005 qname=m60016>La lágrima del demonio</a><BR>
				<a href=#006 qname=m60018>Cuatro reyes de fuego</a><BR>
				<a href=#007 qname=m60015>¡Dos abismos! Viento cálido</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Cacería divina para todos
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>60000z<br>
				<font color=orangered>&nbsp;Contrato :</font>5000z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Gran arena<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 9 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_PNK2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Cacería divina para todos
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Caza todos los monstruos<BR>grandes<BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Cliente：</font>Caballero de rojo<BR>
					¡Oh tú que vas a someterte<BR>a esta prueba! Cree en<BR>tu fuerza y en la de<BR>los tuyos porque es en el<BR>peligro donde se prueba la<BR>fortaleza. ¡Lucha hasta el<BR>fin sin perder la esperanza!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60010.mib" DOWNLOAD CSUM=18506 FSIZE=4772 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60038>Terror doble</a><BR>
				<a href=#002 qname=m60034>Rey de altura</a><BR>
				<a href=#003 qname=m60019>Cacería divina para todos</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60010>Montaña en el cielo</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m60016>La lágrima del demonio</a><BR>
				<a href=#006 qname=m60018>Cuatro reyes de fuego</a><BR>
				<a href=#007 qname=m60015>¡Dos abismos! Viento cálido</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Montaña en el cielo
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>30000z<br>
				<font color=orangered>&nbsp;Contrato :</font>2500z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Torre<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 9 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Montaña en el cielo
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Mata al Yama Tsukami<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Cliente：</font>Anciana pelo largo<BR>
					Una vez, siendo una niña, vi<BR>una sombra gigante en el<BR>cielo. Era lo más grande que<BR>había visto. ¿Fue un sueño?<BR>¿Serías tan amable de com-<BR>probarlo por mí, majete?<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60016.mib" DOWNLOAD CSUM=35192 FSIZE=5384 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60038>Terror doble</a><BR>
				<a href=#002 qname=m60034>Rey de altura</a><BR>
				<a href=#003 qname=m60019>Cacería divina para todos</a><BR>
				<a href=#004 qname=m60010>Montaña en el cielo</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60016>La lágrima del demonio</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m60018>Cuatro reyes de fuego</a><BR>
				<a href=#007 qname=m60015>¡Dos abismos! Viento cálido</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				La lágrima del demonio
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>30000z<br>
				<font color=orangered>&nbsp;Contrato :</font>2500z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Mont. Nevadas(D)<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 7 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				La lágrima del demonio
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Caza 2 Rajang<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Cliente：</font>Joven noble<BR>
					Dos Rajang raptaron a mi<BR>adorable novia y escaparon a<BR>las montañas. No me importa<BR>que no me quiera, pero no<BR>puedo vivir sin ella. ¡Por<BR>favor, préstame tu fuerza!<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60018.mib" DOWNLOAD CSUM=21719 FSIZE=7952 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60038>Terror doble</a><BR>
				<a href=#002 qname=m60034>Rey de altura</a><BR>
				<a href=#003 qname=m60019>Cacería divina para todos</a><BR>
				<a href=#004 qname=m60010>Montaña en el cielo</a><BR>
				<a href=#005 qname=m60016>La lágrima del demonio</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60018>Cuatro reyes de fuego</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m60015>¡Dos abismos! Viento cálido</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Cuatro reyes de fuego
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>42000z<br>
				<font color=orangered>&nbsp;Contrato :</font>3500z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Volcán(D)<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 7 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_PNK2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Cuatro reyes de fuego
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Caza todos los monstruos<BR>grandes<BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Cliente：</font>Científico de blanco<BR>
					Hemos confirmado que la<BR>zona volcánica es adecuada<BR>para la alimentación de una<BR>gran variedad de monstruos.<BR>¿Tendrías la bondad de ir<BR>allí y cazar 4 especies para<BR>nuestra investigación?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60015.mib" DOWNLOAD CSUM=17420 FSIZE=2700 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>１/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60038>Terror doble</a><BR>
				<a href=#002 qname=m60034>Rey de altura</a><BR>
				<a href=#003 qname=m60019>Cacería divina para todos</a><BR>
				<a href=#004 qname=m60010>Montaña en el cielo</a><BR>
				<a href=#005 qname=m60016>La lágrima del demonio</a><BR>
				<a href=#006 qname=m60018>Cuatro reyes de fuego</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60015>¡Dos abismos! Viento cálido</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				¡Dos abismos! Viento cálido
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>36000z<br>
				<font color=orangered>&nbsp;Contrato :</font>3000z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Gran arena<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 7 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				¡Dos abismos! Viento cálido
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Caza 2 Gravios negros<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Cliente：</font>Jefe arena<BR>
					¡Todos están invitados a la<BR>pelea definitiva! ¡Tengo 2,<BR>cuéntenlos, 2 horribles<BR>Gravios negros aquí, en esta<BR>arena! ¿Crees que tienes lo<BR>que hay que tener para<BR>vencer a estas bestias?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
</body>
</html>
