<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=2",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=2&pg_no=0",
		"RB_LINK=DL_MENU.PHP?lang=2&pg_no=2",
		"MOVE_CHAR=../MHP2GUSA/GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=../MHP2GUSA/GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60014.mib" DOWNLOAD CSUM=33440 FSIZE=2824 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60014>Zwei Zwillingshörner - Arena</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m60022>In einem Meer aus Magma</a><BR>
				<a href=#003 qname=m60032>Ein weißer Lichtstrahl</a><BR>
				<a href=#004 qname=m60021>Super-Hypnocatrice-Kampf</a><BR>
				<a href=#005 qname=m60035>Jäger-Fiesta!</a><BR>
				<a href=#006 qname=m60031>Scharlachroter Himmel</a><BR>
				<a href=#007 qname=m60011>Zwei Mauern - dunkle Winde</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Zwei Zwillingshörner - Arena
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>33000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>2750z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Große Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  7 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Zwei Zwillingshörner - Arena
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Den schwarzen Diablos <BR>und den Diablos erjagen<BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Klient：</font>Mitt40-Arena-Manager<BR>
					Ich habe diesen Beruf schon <BR>vor langer Zeit aufgegeben, <BR>aber er hat mich nicht<BR>losgelassen. Also mache<BR>ich weiter! Dein aktueller <BR>Gegner ist ein Diablos-Paar.<BR>Viel Glück!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60022.mib" DOWNLOAD CSUM=49185 FSIZE=7040 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>Zwei Zwillingshörner - Arena</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60022>In einem Meer aus Magma</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m60032>Ein weißer Lichtstrahl</a><BR>
				<a href=#004 qname=m60021>Super-Hypnocatrice-Kampf</a><BR>
				<a href=#005 qname=m60035>Jäger-Fiesta!</a><BR>
				<a href=#006 qname=m60031>Scharlachroter Himmel</a><BR>
				<a href=#007 qname=m60011>Zwei Mauern - dunkle Winde</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				In einem Meer aus Magma
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>13500z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>1150z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Vulkan(Nacht)<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  7 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				In einem Meer aus Magma
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Den Lavasioth erjagen<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>Klient：</font>Aschefarben.Bergmann<BR>
					Wir wollten gerade zusammen-<BR>packen, als wir einen <BR>großen, finsteren Schatten <BR>unter der Lava hinten in der<BR>Höhle entdeckten - <BR>vielleicht das Monster von <BR>Lava Ness. Sieh nach!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60032.mib" DOWNLOAD CSUM=32467 FSIZE=4904 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>Zwei Zwillingshörner - Arena</a><BR>
				<a href=#002 qname=m60022>In einem Meer aus Magma</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60032>Ein weißer Lichtstrahl</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m60021>Super-Hypnocatrice-Kampf</a><BR>
				<a href=#005 qname=m60035>Jäger-Fiesta!</a><BR>
				<a href=#006 qname=m60031>Scharlachroter Himmel</a><BR>
				<a href=#007 qname=m60011>Zwei Mauern - dunkle Winde</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Ein weißer Lichtstrahl
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>54000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>4500z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Turm<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  9 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_PPL2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Ein weißer Lichtstrahl
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Den Fatalis töten<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Klient：</font>WeißgekleidetMädchen<BR>
					Du bist doch ein Jäger? <BR>Tja... Bitte komm mit mir <BR>an einen wunderbaren Ort, <BR>an dem weiße Lichter tanzen <BR>und funkeln wie die Sterne <BR>am Himmel. Du wirst dich <BR>keinesfalls langweilen!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60021.mib" DOWNLOAD CSUM=11820 FSIZE=2660 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>Zwei Zwillingshörner - Arena</a><BR>
				<a href=#002 qname=m60022>In einem Meer aus Magma</a><BR>
				<a href=#003 qname=m60032>Ein weißer Lichtstrahl</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60021>Super-Hypnocatrice-Kampf</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m60035>Jäger-Fiesta!</a><BR>
				<a href=#006 qname=m60031>Scharlachroter Himmel</a><BR>
				<a href=#007 qname=m60011>Zwei Mauern - dunkle Winde</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Super-Hypnocatrice-Kampf
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>15000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>1250z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Große Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  7 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Super-Hypnocatrice-Kampf
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>2 Hypnocatricen erjagen<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★<BR>
					<font color=orangered>Klient：</font>Arena-Manager<BR>
					Kommt, kommt alle zur <BR>ultimativen Arena! Ich biete<BR>2, ja 2, Hypnocatricen, die <BR>da drin warten, um euch ins <BR>Traumland zu schicken! <BR>Könnt ihr eure schlaffen <BR>Lider offen halten?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60035.mib" DOWNLOAD CSUM=8800 FSIZE=3128 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>Zwei Zwillingshörner - Arena</a><BR>
				<a href=#002 qname=m60022>In einem Meer aus Magma</a><BR>
				<a href=#003 qname=m60032>Ein weißer Lichtstrahl</a><BR>
				<a href=#004 qname=m60021>Super-Hypnocatrice-Kampf</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60035>Jäger-Fiesta!</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m60031>Scharlachroter Himmel</a><BR>
				<a href=#007 qname=m60011>Zwei Mauern - dunkle Winde</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Jäger-Fiesta!
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>33000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>2750z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Große Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  7 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_PNK2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Jäger-Fiesta!
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Alle großen Monster erjagen<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Klient：</font>Kurzhaariges Mädchen<BR>
					I-Ich bin für die Fest-<BR>leitung verantwortlich. <BR>Und... *räusper* Die Be-<BR>lohnung für den Sieg ist ein<BR>ganz besonderer Pass! Ich <BR>hoffe also, dass du es auch <BR>versuchst.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60031.mib" DOWNLOAD CSUM=42611 FSIZE=2436 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>Zwei Zwillingshörner - Arena</a><BR>
				<a href=#002 qname=m60022>In einem Meer aus Magma</a><BR>
				<a href=#003 qname=m60032>Ein weißer Lichtstrahl</a><BR>
				<a href=#004 qname=m60021>Super-Hypnocatrice-Kampf</a><BR>
				<a href=#005 qname=m60035>Jäger-Fiesta!</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60031>Scharlachroter Himmel</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m60011>Zwei Mauern - dunkle Winde</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Scharlachroter Himmel
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>54000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>4500z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Schlachtfeld<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  9 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_PPL2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Scharlachroter Himmel
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Den Fatalis töten<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Klient：</font>Gildenschwergewicht<BR>
					Sieh den feuerroten Himmel <BR>an! Es ist wahr: Der Zorn <BR>des Fatalis färbt den Himmel<BR>rot wie Blut. Wer wird uns <BR>helfen, den Zorn zu stillen <BR>und dem Himmel seine rich-<BR>tige Farbe wiederzugeben?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60011.mib" DOWNLOAD CSUM=18412 FSIZE=2704 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>Zwei Zwillingshörner - Arena</a><BR>
				<a href=#002 qname=m60022>In einem Meer aus Magma</a><BR>
				<a href=#003 qname=m60032>Ein weißer Lichtstrahl</a><BR>
				<a href=#004 qname=m60021>Super-Hypnocatrice-Kampf</a><BR>
				<a href=#005 qname=m60035>Jäger-Fiesta!</a><BR>
				<a href=#006 qname=m60031>Scharlachroter Himmel</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60011>Zwei Mauern - dunkle Winde</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Zwei Mauern - dunkle Winde
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>26100z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>2200z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Burggraben-Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  7 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Zwei Mauern - dunkle Winde
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>2 Terra Shogun Ceanatauren<BR>erjagen<BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>Klient：</font>Verdächtiger Manager<BR>
					Kommt, kommt in die <BR>ultimative Arena! Ich <BR>besitze 2 der stärksten und <BR>gefährlichsten Monster, die <BR>das Land je gesehen hat! <BR>Kommt näher! Beweist eure <BR>Tapferkeit!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
</body>
</html>
