<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=2",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=2&pg_no=2",
		"RB_LINK=DL_MENU.PHP?lang=2&pg_no=0",
		"MOVE_CHAR=../MHP2GUSA/GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=../MHP2GUSA/GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60027.mib" DOWNLOAD CSUM=54524 FSIZE=7664 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>４/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60027>Dschungelhatz!</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m60037>Tiger der Wüste</a><BR>
				<a href=#003 qname=m60028>Wasserfest</a><BR>
				<a href=#004 qname=m60033>2 Farben Miau - Kleine Arena</a><BR>
				<a href=#005 qname=m60024>Triumvirat des Sandes</a><BR>
				<a href=#006 qname=m60026>Babyschwemme - Schlaftreff</a><BR>
				<a href=#007 qname=m60013>Weg mit der Panik!</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Dschungelhatz!
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>14100z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>1200z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Dschungel(Tag)<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  4 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_PNK2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Dschungelhatz!
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Alle großen Monster erjagen<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★★<BR>
					<font color=orangered>Klient：</font>Herrischer Adliger<BR>
					Zum Wohle unserer untertä-<BR>nigen Untertanen haben wir<BR>mutig den Wald erforscht.<BR>Doch selbst unsere liebe<BR>Mutter warnte uns nicht vor<BR>solch' Schrecken! Ich will,<BR>dass Ihr uns beschützet!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60037.mib" DOWNLOAD CSUM=39899 FSIZE=7532 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>４/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60027>Dschungelhatz!</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60037>Tiger der Wüste</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m60028>Wasserfest</a><BR>
				<a href=#004 qname=m60033>2 Farben Miau - Kleine Arena</a><BR>
				<a href=#005 qname=m60024>Triumvirat des Sandes</a><BR>
				<a href=#006 qname=m60026>Babyschwemme - Schlaftreff</a><BR>
				<a href=#007 qname=m60013>Weg mit der Panik!</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Tiger der Wüste
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>14100z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>1200z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Alte Wüste<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  7 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Tiger der Wüste
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Den Tigrex erjagen<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Klient：</font>Sehr neugierige Magd<BR>
					Wow! Angeblich treibt sich <BR>ein gestreiftes Monster auf <BR>der anderen Seite herum! <BR>Schnell, vielleicht sehen <BR>wir es! Wenn es gefährlich <BR>wird, beschützt du mich <BR>doch, nicht wahr?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60028.mib" DOWNLOAD CSUM=29746 FSIZE=3336 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>４/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60027>Dschungelhatz!</a><BR>
				<a href=#002 qname=m60037>Tiger der Wüste</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60028>Wasserfest</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m60033>2 Farben Miau - Kleine Arena</a><BR>
				<a href=#005 qname=m60024>Triumvirat des Sandes</a><BR>
				<a href=#006 qname=m60026>Babyschwemme - Schlaftreff</a><BR>
				<a href=#007 qname=m60013>Weg mit der Panik!</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Wasserfest
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>24000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>2000z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Burggraben-Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  4 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_PNK2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Wasserfest
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Alle großen Monster erjagen<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★★★<BR>
					<font color=orangered>Klient：</font>Charmanter Produzent<BR>
					Ich will eine spaßige Feier!<BR>Und was könnte besser sein, <BR>als den Gästen zu zeigen, <BR>wie erstklassige Jäger<BR>Monster zur Srecke bringen?<BR>Ich habe 4 Monster besorgt,<BR>also lassen wir es krachen!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60033.mib" DOWNLOAD CSUM=18767 FSIZE=2700 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>４/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60027>Dschungelhatz!</a><BR>
				<a href=#002 qname=m60037>Tiger der Wüste</a><BR>
				<a href=#003 qname=m60028>Wasserfest</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60033>2 Farben Miau - Kleine Arena</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m60024>Triumvirat des Sandes</a><BR>
				<a href=#006 qname=m60026>Babyschwemme - Schlaftreff</a><BR>
				<a href=#007 qname=m60013>Weg mit der Panik!</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				2 Farben Miau - Kleine Arena
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>4500z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>400z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Arena<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  4 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				2 Farben Miau - Kleine Arena
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>20 Felynes besiegen<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★<BR>
					<font color=orangered>Klient：</font>Ying-Yang-Kreaturen<BR>
					An die eine Million Felyne-<BR>Fans da draußen: Hier kommt <BR>eine ganz besondere <BR>Herausforderung! Wer sie <BR>meistert, erhält zur <BR>Belohnung einen ganz <BR>besonderen Pass!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60024.mib" DOWNLOAD CSUM=48755 FSIZE=7604 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>４/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60027>Dschungelhatz!</a><BR>
				<a href=#002 qname=m60037>Tiger der Wüste</a><BR>
				<a href=#003 qname=m60028>Wasserfest</a><BR>
				<a href=#004 qname=m60033>2 Farben Miau - Kleine Arena</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60024>Triumvirat des Sandes</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m60026>Babyschwemme - Schlaftreff</a><BR>
				<a href=#007 qname=m60013>Weg mit der Panik!</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Triumvirat des Sandes
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>12300z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>1050z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Wüste(Tag)<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nein<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_PNK2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Triumvirat des Sandes
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Alle großen Monster erjagen<BR><BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Klient：</font>NordmedizinVerkäufer<BR>
					Was ist bloß los mit dieser <BR>Wüste? Das ist heute schon <BR>das 3. Mal! Ich musste all <BR>meine Waren zurücklassen. <BR>Die ganzen großen Tränke! <BR>Ob ein Monster sie gefressen<BR>hat?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60026.mib" DOWNLOAD CSUM=58434 FSIZE=7128 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>４/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60027>Dschungelhatz!</a><BR>
				<a href=#002 qname=m60037>Tiger der Wüste</a><BR>
				<a href=#003 qname=m60028>Wasserfest</a><BR>
				<a href=#004 qname=m60033>2 Farben Miau - Kleine Arena</a><BR>
				<a href=#005 qname=m60024>Triumvirat des Sandes</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60026>Babyschwemme - Schlaftreff</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m60013>Weg mit der Panik!</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Babyschwemme - Schlaftreff
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>9000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>750z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Großer Wald(Tag)<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  4 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Babyschwemme - Schlaftreff
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Bis zum Zeitablauf überleben<BR>oder den Tatzenpass abgeben<BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0 oder Zeit vor <BR>Erjagen von 2 abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★★<BR>
					<font color=orangered>Klient：</font>EntschlosseneKreatur<BR>
					Ich dachte, ich kaufe mir <BR>ein Haus in einer fried-<BR>lichen Gegend, aber überall <BR>gibt es Hypnocatricen, <BR>miau. Bitte schütze mein <BR>Haus, indem du mindestens <BR>zwei davon erlegst!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60013.mib" DOWNLOAD CSUM=10403 FSIZE=6164 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>４/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60027>Dschungelhatz!</a><BR>
				<a href=#002 qname=m60037>Tiger der Wüste</a><BR>
				<a href=#003 qname=m60028>Wasserfest</a><BR>
				<a href=#004 qname=m60033>2 Farben Miau - Kleine Arena</a><BR>
				<a href=#005 qname=m60024>Triumvirat des Sandes</a><BR>
				<a href=#006 qname=m60026>Babyschwemme - Schlaftreff</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60013>Weg mit der Panik!</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/DE/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Weg mit der Panik!
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Belohnung:</font>18000z<br>
				<font color=orangered>&nbsp;Gebühr 　:</font>1500z<br>
				<font color=orangered>&nbsp;Zeit 　　:</font>50 min<br>
				<font color=orangered>&nbsp;Zone 　　:</font>Sumpf(Tag)<br>
				<font color=orangered>&nbsp;Sonderbedingungen:</font><br>&nbsp;&nbsp;Nur JR  7 oder höher.<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/DE/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Weg mit der Panik!
			</td>
			<td>
				<font color=orangered>Quest-Stufe：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Zielbedingung(en):</font><br>Den Smaragd-Congalala <BR>und den Congalala erjagen<BR><BR>
					<font color=orangered>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★<BR>
					<font color=orangered>Klient：</font>Hausfrau am See<BR>
					Hört mich an, bitte! Seit <BR>Kurzem stinkt das Wasser <BR>meines Dorfes wie Abwasser! <BR>Bestimmt ist die Quelle <BR>verunreinigt. Bitte findet <BR>die Ursache und behebt das <BR>Problem.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/DE/BUTTON4.gif></td></tr></table>
</body>
</html>
