<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=4",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=4&pg_no=1",
		"RB_LINK=DL_MENU.PHP?lang=4&pg_no=3",
		"MOVE_CHAR=../MHP2GUSA/GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=../MHP2GUSA/GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60012.mib" DOWNLOAD CSUM=17793 FSIZE=6272 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60012>Bestias de las dunas</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m60025>Laurel, por favor.</a><BR>
				<a href=#003 qname=m60029>El pez gordo</a><BR>
				<a href=#004 qname=m60017>Arena de sangre y lágrimas</a><BR>
				<a href=#005 qname=m60023>¿¡Se llama "Mega Kut-Ku"!?</a><BR>
				<a href=#006 qname=m60020>¡Fiesta del pánico porcino!</a><BR>
				<a href=#007 qname=m60030>Las negras alas del destino</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Bestias de las dunas
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>24000z<br>
				<font color=orangered>&nbsp;Contrato :</font>2000z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Desierto(D)<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 7 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Bestias de las dunas
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Caza 2 Blangonga cobre<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>Cliente：</font>Criaturas heridas<BR>
					Hicimos una promesa a<BR>nuestro maestro, ¡miau!<BR>Tenemos que llevar esta<BR>carta a su destino.<BR>Estábamos muy cerca, pero<BR>hay monstruos por ahí...<BR>Por favor, ayúdanos... Miau<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60025.mib" DOWNLOAD CSUM=4576 FSIZE=3136 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Bestias de las dunas</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60025>Laurel, por favor.</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m60029>El pez gordo</a><BR>
				<a href=#004 qname=m60017>Arena de sangre y lágrimas</a><BR>
				<a href=#005 qname=m60023>¿¡Se llama "Mega Kut-Ku"!?</a><BR>
				<a href=#006 qname=m60020>¡Fiesta del pánico porcino!</a><BR>
				<a href=#007 qname=m60030>Las negras alas del destino</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Laurel, por favor.
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>12000z<br>
				<font color=orangered>&nbsp;Contrato :</font>1000z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Gran arena<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;No<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_PNK2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Laurel, por favor.
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Caza todos los monstruos<BR>grandes<BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★<BR>
					<font color=orangered>Cliente：</font>Jefe arena joven<BR>
					¿Quieres destacar? ¡Pues la<BR>arena es perfecta para ti!<BR>Hoy tenemos en el menú un<BR>Congalala, un Rathian, un<BR>Shogun Ceanataur y muchas<BR>otras cosas. ¡Usa bien las<BR>pociones que encontraste!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60029.mib" DOWNLOAD CSUM=14869 FSIZE=4804 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Bestias de las dunas</a><BR>
				<a href=#002 qname=m60025>Laurel, por favor.</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60029>El pez gordo</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m60017>Arena de sangre y lágrimas</a><BR>
				<a href=#005 qname=m60023>¿¡Se llama "Mega Kut-Ku"!?</a><BR>
				<a href=#006 qname=m60020>¡Fiesta del pánico porcino!</a><BR>
				<a href=#007 qname=m60030>Las negras alas del destino</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				El pez gordo
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>36000z<br>
				<font color=orangered>&nbsp;Contrato :</font>3000z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Torre<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 6 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_PPL2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				El pez gordo
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Mata al Fatalis<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★★★★★★<BR>
					<font color=orangered>Cliente：</font>Felyne blanco puro<BR>
					¡Maestro! ¿Vas a explorar la<BR>vieja Torre? No te la puedes<BR>perder, miau... Si vas,<BR>verás algo increíble...<BR>Aunque tengo un mal<BR>presentimiento... <BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60017.mib" DOWNLOAD CSUM=37796 FSIZE=3360 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Bestias de las dunas</a><BR>
				<a href=#002 qname=m60025>Laurel, por favor.</a><BR>
				<a href=#003 qname=m60029>El pez gordo</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60017>Arena de sangre y lágrimas</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m60023>¿¡Se llama "Mega Kut-Ku"!?</a><BR>
				<a href=#006 qname=m60020>¡Fiesta del pánico porcino!</a><BR>
				<a href=#007 qname=m60030>Las negras alas del destino</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Arena de sangre y lágrimas
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>39000z<br>
				<font color=orangered>&nbsp;Contrato :</font>3250z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Arena acuática<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 7 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_PNK2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Arena de sangre y lágrimas
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Caza todos los monstruos<BR>grandes<BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>Cliente：</font>Caballero serio<BR>
					No suelo hacerlo así pero hay<BR>alguien que quiere probar tu<BR>fuerza. ¿Puedes mostrarme<BR>tu auténtico poder? Espera<BR>una recompensa por<BR>tus esfuerzos.<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60023.mib" DOWNLOAD CSUM=54531 FSIZE=6144 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Bestias de las dunas</a><BR>
				<a href=#002 qname=m60025>Laurel, por favor.</a><BR>
				<a href=#003 qname=m60029>El pez gordo</a><BR>
				<a href=#004 qname=m60017>Arena de sangre y lágrimas</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60023>¿¡Se llama "Mega Kut-Ku"!?</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m60020>¡Fiesta del pánico porcino!</a><BR>
				<a href=#007 qname=m60030>Las negras alas del destino</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				¿¡Se llama "Mega Kut-Ku"!?
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>6000z<br>
				<font color=orangered>&nbsp;Contrato :</font>500z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Bosque y colinas(D)<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Iniciando y comprb. reqs.<BR>　misión. Armadura fuera.<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				¿¡Se llama "Mega Kut-Ku"!?
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Caza 2 Yian Kut-Ku (?)<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					★★★<BR>
					<font color=orangered>Cliente：</font>Experto en comida<BR>
					Llegué aquí buscando una<BR>comida nunca probada por los<BR>mortales. He oído que en la<BR>montaña cercana vive una<BR>criatura legendaria.<BR>¡Ayúdame a satisfacer mi<BR>ambición! ¡A cazar!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60020.mib" DOWNLOAD CSUM=25038 FSIZE=2796 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Bestias de las dunas</a><BR>
				<a href=#002 qname=m60025>Laurel, por favor.</a><BR>
				<a href=#003 qname=m60029>El pez gordo</a><BR>
				<a href=#004 qname=m60017>Arena de sangre y lágrimas</a><BR>
				<a href=#005 qname=m60023>¿¡Se llama "Mega Kut-Ku"!?</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60020>¡Fiesta del pánico porcino!</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m60030>Las negras alas del destino</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_RED2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				¡Fiesta del pánico porcino!
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>8400z<br>
				<font color=orangered>&nbsp;Contrato :</font>700z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Arena<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 7 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_RED2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_RED.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				¡Fiesta del pánico porcino!
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Mata 30 Bullfango<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★<BR>
					<font color=orangered>Cliente：</font>Dama exuberante<BR>
					Estoy contratando cazadores<BR>para divertir a los míos,<BR>ji, ji ji... Hay toda una<BR>colección de cerditos<BR>sueltos. Me pregunto<BR>si serás capaz de<BR>atraparlos...<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60030.mib" DOWNLOAD CSUM=64928 FSIZE=2524 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>３/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60012>Bestias de las dunas</a><BR>
				<a href=#002 qname=m60025>Laurel, por favor.</a><BR>
				<a href=#003 qname=m60029>El pez gordo</a><BR>
				<a href=#004 qname=m60017>Arena de sangre y lágrimas</a><BR>
				<a href=#005 qname=m60023>¿¡Se llama "Mega Kut-Ku"!?</a><BR>
				<a href=#006 qname=m60020>¡Fiesta del pánico porcino!</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60030>Las negras alas del destino</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/ES/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Las negras alas del destino
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Recompen.:</font>54000z<br>
				<font color=orangered>&nbsp;Contrato :</font>4500z<br>
				<font color=orangered>&nbsp;Tiempo 　:</font>50 min<br>
				<font color=orangered>&nbsp;Zona 　　:</font>Cast.Schrade<br>
				<font color=orangered>&nbsp;Condiciones especiales:</font><br>&nbsp;&nbsp;Sólo RC 9 o superior<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/ES/T_PPL2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Las negras alas del destino
			</td>
			<td>
				<font color=orangered>Nv. misión：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Cond. éxito:</font><br>Mata al Fatalis<BR><BR><BR>
					<font color=orangered>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Cliente：</font>Maest. astuto Gremio<BR>
					Nos han informado de que<BR>se ha visto un dragón de<BR>alas negras en las ruinas de<BR>la Torre. Nuestra<BR>expedición ha desaparecido<BR>y me temo lo peor. ¿No irá<BR>nadie a echar un vistazo?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/ES/BUTTON4.gif></td></tr></table>
</body>
</html>
