<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=1",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=1&pg_no=0",
		"RB_LINK=DL_MENU.PHP?lang=1&pg_no=2",
		"MOVE_CHAR=../MHP2GUSA/GIF/chacha.gif,42,65,2,1,4,20,480,030",
		"MOVE_CHAR=../MHP2GUSA/GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=black link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img src=../MHP2GUSA/GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60014.mib" DOWNLOAD CSUM=33440 FSIZE=2824 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60014>Dual Twin Horns - Arena</a><BR>
			<tr><td height=110 valign=top>
				<a href=#002 qname=m60022>Surrounded in a Sea of Magma</a><BR>
				<a href=#003 qname=m60032>A White Beam of Light</a><BR>
				<a href=#004 qname=m60021>Super Hypnocatrice Brawl</a><BR>
				<a href=#005 qname=m60035>Hunter's Fiesta!</a><BR>
				<a href=#006 qname=m60031>Scarlet Skies</a><BR>
				<a href=#007 qname=m60011>Two Walls? Dark Winds</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/EN/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Dual Twin Horns - Arena
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>33000z<br>
				<font color=orangered>&nbsp;Contract:</font>2750z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Great Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=../MHP2GUSA/GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/EN/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Dual Twin Horns - Arena
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt the Black Diablos<BR>and the Diablos<BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Client：</font>Mid-Age Arena Manag<BR>
					I had sworn off this<BR>business a long time ago,<BR>but I couldn't leave it<BR>behind, so here I am, back<BR>in the thick of it! Your<BR>opponent this time is a pair<BR>of Diablos! Good luck!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img src=../MHP2GUSA/GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60022.mib" DOWNLOAD CSUM=49185 FSIZE=7040 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>Dual Twin Horns - Arena</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60022>Surrounded in a Sea of Magma</a><BR>
			<tr><td height=94 valign=top>
				<a href=#003 qname=m60032>A White Beam of Light</a><BR>
				<a href=#004 qname=m60021>Super Hypnocatrice Brawl</a><BR>
				<a href=#005 qname=m60035>Hunter's Fiesta!</a><BR>
				<a href=#006 qname=m60031>Scarlet Skies</a><BR>
				<a href=#007 qname=m60011>Two Walls? Dark Winds</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/EN/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Surrounded in a Sea of Magma
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>13500z<br>
				<font color=orangered>&nbsp;Contract:</font>1150z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Volcano(Night)<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=../MHP2GUSA/GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/EN/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Surrounded in a Sea of Magma
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt the Lavasioth<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>Client：</font>Ashen Miner<BR>
					We were just about to pack<BR>up for the day when we spied<BR>a huge, dark shadow lurking<BR>under the surface of the<BR>lava at the back of the cave<BR>like some sort of Lava<BR>Ness Monster! Check it out!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img src=../MHP2GUSA/GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60032.mib" DOWNLOAD CSUM=32467 FSIZE=4904 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>Dual Twin Horns - Arena</a><BR>
				<a href=#002 qname=m60022>Surrounded in a Sea of Magma</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60032>A White Beam of Light</a><BR>
			<tr><td height=78 valign=top>
				<a href=#004 qname=m60021>Super Hypnocatrice Brawl</a><BR>
				<a href=#005 qname=m60035>Hunter's Fiesta!</a><BR>
				<a href=#006 qname=m60031>Scarlet Skies</a><BR>
				<a href=#007 qname=m60011>Two Walls? Dark Winds</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/EN/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				A White Beam of Light
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>54000z<br>
				<font color=orangered>&nbsp;Contract:</font>4500z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Tower<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 9 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=../MHP2GUSA/GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/EN/T_PPL2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				A White Beam of Light
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Slay the Fatalis<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Client：</font>White-Dressed Girl<BR>
					You're a hunter, right? Tee<BR>hee. I want you to come with<BR>me... to a wonderful place;<BR>a place where white light<BR>dances about, twinkling like<BR>the stars in the sky... I<BR>swear you won't be bored...<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img src=../MHP2GUSA/GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60021.mib" DOWNLOAD CSUM=11820 FSIZE=2660 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>Dual Twin Horns - Arena</a><BR>
				<a href=#002 qname=m60022>Surrounded in a Sea of Magma</a><BR>
				<a href=#003 qname=m60032>A White Beam of Light</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60021>Super Hypnocatrice Brawl</a><BR>
			<tr><td height=62 valign=top>
				<a href=#005 qname=m60035>Hunter's Fiesta!</a><BR>
				<a href=#006 qname=m60031>Scarlet Skies</a><BR>
				<a href=#007 qname=m60011>Two Walls? Dark Winds</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/EN/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Super Hypnocatrice Brawl
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>15000z<br>
				<font color=orangered>&nbsp;Contract:</font>1250z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Great Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=../MHP2GUSA/GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/EN/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Super Hypnocatrice Brawl
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt 2 Hypnocatrices<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★<BR>
					<font color=orangered>Client：</font>Arena Manager<BR>
					Come one, come all, to the<BR>ultimate arena! I've got 2,<BR>yes, count 'em, 2<BR>Hypnocatrices waiting just<BR>inside, ready to lull you<BR>off to Lala-land! Can you<BR>fight off 2 droopy eyelids?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img src=../MHP2GUSA/GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60035.mib" DOWNLOAD CSUM=8800 FSIZE=3128 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>Dual Twin Horns - Arena</a><BR>
				<a href=#002 qname=m60022>Surrounded in a Sea of Magma</a><BR>
				<a href=#003 qname=m60032>A White Beam of Light</a><BR>
				<a href=#004 qname=m60021>Super Hypnocatrice Brawl</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60035>Hunter's Fiesta!</a><BR>
			<tr><td height=46 valign=top>
				<a href=#006 qname=m60031>Scarlet Skies</a><BR>
				<a href=#007 qname=m60011>Two Walls? Dark Winds</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/EN/T_PNK2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Hunter's Fiesta!
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>33000z<br>
				<font color=orangered>&nbsp;Contract:</font>2750z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Great Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=../MHP2GUSA/GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/EN/T_PNK2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Hunter's Fiesta!
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt all of the Large<BR>Monsters<BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Client：</font>Short-Haired Girl<BR>
					I... I'm the one in charge<BR>of the festival this time,<BR>and, um... *ahem* The reward<BR>for skillfully winning this<BR>challenge is a very special<BR>ticket! So, um, I hope you<BR>will all give it a try!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img src=../MHP2GUSA/GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60031.mib" DOWNLOAD CSUM=42611 FSIZE=2436 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>Dual Twin Horns - Arena</a><BR>
				<a href=#002 qname=m60022>Surrounded in a Sea of Magma</a><BR>
				<a href=#003 qname=m60032>A White Beam of Light</a><BR>
				<a href=#004 qname=m60021>Super Hypnocatrice Brawl</a><BR>
				<a href=#005 qname=m60035>Hunter's Fiesta!</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60031>Scarlet Skies</a><BR>
			<tr><td height=30 valign=top>
				<a href=#007 qname=m60011>Two Walls? Dark Winds</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/EN/T_PPL2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Scarlet Skies
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>54000z<br>
				<font color=orangered>&nbsp;Contract:</font>4500z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Battleground<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 9 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=../MHP2GUSA/GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/EN/T_PPL2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_PPL.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Scarlet Skies
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Slay the Fatalis<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★★<BR>
					<font color=orangered>Client：</font>Guild Heavyweight<BR>
					Look at that fiery scarlet<BR>sky! The legends are true!<BR>The wrath of a Fatalis turns<BR>even the sky blood red.<BR>Please, someone, anyone!<BR>Quell the rage and return<BR>the sky to its normal color!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img src=../MHP2GUSA/GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=476 height=197 cellspacing=0>
<tr>
	<td width=224 align=center>
		<table width=224 208 height=184 border=0 cellspacing=5 background=../MHP2GUSA/GIF/LIST_W.gif>
		<tr><td>
			<table width=224 198 cellspacing=0>
			<form action="QUEST/m60011.mib" DOWNLOAD CSUM=18412 FSIZE=2704 method=post>
			<tr>
				<td width=224 198 height=38 align=center valign=center>
					<table width=129 height=17 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/LR.gif>
					<tr>
						<td align=center>
							<B><font color=white>２/４</font></B>
						</td>
					</tr>
					</table>
				</td>
			</tr>
			<tr><td>
				<a href=#001 qname=m60014>Dual Twin Horns - Arena</a><BR>
				<a href=#002 qname=m60022>Surrounded in a Sea of Magma</a><BR>
				<a href=#003 qname=m60032>A White Beam of Light</a><BR>
				<a href=#004 qname=m60021>Super Hypnocatrice Brawl</a><BR>
				<a href=#005 qname=m60035>Hunter's Fiesta!</a><BR>
				<a href=#006 qname=m60031>Scarlet Skies</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60011>Two Walls? Dark Winds</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=247>
		<table width=247 height=195 cellspacing=0 cellpadding=2 background=../MHP2GUSA/GIF/QBOARD.gif>
		<tr>
			<td width=243 height=26 align=center valign=bottom>
				<table width=219 height=18 cellspacing=0 cellpadding=0 background=../MHP2GUSA/GIF/EN/T_WHT2.gif>
				<tr>
					<td height=18>
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height=30 align=center valign=top>
				Two Walls? Dark Winds
			</td>
		</tr>
		<tr>
			<td height=123 valign=top>
				<font color=orangered>&nbsp;Reward　:</font>26100z<br>
				<font color=orangered>&nbsp;Contract:</font>2200z<br>
				<font color=orangered>&nbsp;Time　　:</font>50 min.<br>
				<font color=orangered>&nbsp;Zone　　:</font>Moat Arena<br>
				<font color=orangered>&nbsp;Special Conditions:</font><br>&nbsp;&nbsp;HR 7 Or Above Only<BR>　<BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/EN/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=../MHP2GUSA/GIF/EN/LOGO11.gif width=200 height=50 alt="Event"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2G"><br>
<table width=480 height=197 cellspacing=0>
<tr>
	<td>
		<table width=480 height=196 cellspacing=0 background=../MHP2GUSA/GIF/QBOARD2.gif>
		<tr>
			<td colspan=3 width=480 height=27 align=center valign=bottom>
				<table width=438 height=18 cellspacing=0 cellpadding=0 ><tr>
					<td width=219 height=18 background=../MHP2GUSA/GIF/EN/T_WHT2.gif></td>
					<td width=219 height=18 background=../MHP2GUSA/GIF/T_WHT.gif></td>
					</td>
				</tr></table>
			</td>
		</tr>
		<tr>
			<td colspan=2 align=center>
				Two Walls? Dark Winds
			</td>
			<td>
				<font color=orangered>Quest Level：</font>
			</td>
		</tr>
		<tr>
			<TD width=8></TD>
			<td width=227 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD>
					<font color=orangered>Goal Condition:</font><br>Hunt 2 Terra S.Ceanataurs<BR><BR><BR>
					<font color=orangered>Fail Condition:</font><br>Reward Zero<BR>Time Over<BR>
				</TABLE>
			</td>
			<td width=242 valign=top>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=234 align=left>
					Ｇ★★<BR>
					<font color=orangered>Client：</font>Suspicious Manager<BR>
					Come one, come all, to the<BR>ultimate arena! I've got 2<BR>of the hardest, strongest,<BR>and most terrifying monsters<BR>around! Step on up! Prove<BR>you've got the right stuff!<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/EN/BUTTON4.gif></td></tr></table>
</body>
</html>
