<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=5",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:6",
		"MOVE_CHAR=../MHP2GUSA/GIF/ro-dos.gif,256,145,4,1,2,30,-82,100",
		"MOVE_CHAR=../MHP2GUSA/GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=../MHP2GUSA/GIF/BG.gif>
<basefont size=2>
<B>
<img src=../MHP2GUSA/GIF/IT/LOGO10.gif width=200 height=50 alt="Quest"><img src=../MHP2GUSA/GIF/LOGO2.gif width=280 height=50 alt="MHP2ndG"><br>
<table width=480 height=197 cellspacing=0 cellpadding=0 border=0>
<tr>
		<form action="DL_MENU.PHP" method=get>
	<td width=240 height=196 align=center valign=center>
		 <input type=hidden name=lang value=5>
		 <input type=hidden name=pg_no value=0>
		 <input ANIME=1 type=image src="../MHP2GUSA/GIF/IT/SELECT1.gif" name=submit width=190 height=160 alt="Event">
	</td>
		</form>
		<form action="DL_CMENU.PHP" method=get>
	<td width=240 height=196 align=center valign=center>
		 <input type=hidden name=lang value=5>
		 <input type=hidden name=pg_no value=0>
		 <input ANIME=1 type=image src="../MHP2GUSA/GIF/IT/SELECT2.gif" name=submit width=190 height=160 alt="Challenge">
	</td>
		</form>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=../MHP2GUSA/GIF/IT/BUTTON2.gif></td></tr></table>
</body>
</html>
