<?php header('Content-Type: charset=Shift_JIS'); 
?>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=Shift-JIS">
<!--
<GAME-STYLE>
	"MOUSE=OFF",
	"SCROLL=OFF",
	"TITLE=OFF",
	"BACK=ON:DL_TOP.PHP",
	"FORWARD=OFF",
	"CANCEL=OFF",
	"RELOAD=OFF",
	"CHOICE_MV=OFF",
	"LINK_U=OFF",
	"FRONT_LABEL=ON:1",
</GAME-STYLE>
-->
<body background=PNG/BG.PNG text=white link=white vlink=white bgcolor=black>

<basefont size=2>
<B>

<!--
<img src=PNG/LOGO1.PNG width=240 height=50><img src=PNG/LOGO2.PNG width=240 height=50><br>
-->
!!!Under construction!!!
</body>
</html>