<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?pg_no=12",
		"RB_LINK=DB_INFO.PHP?pg_no=0",
		"MOVE_CHAR=fpic://51.gif,57,71,7,,20,,403,137",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=fpic://03.gif>
<basefont size=1>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							14/14
						</table>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>１２／０３更新予告②<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>１２／０３更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>オープン！！<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>１２／０３更新予告②</font><br>
				</center>
<BR>
次回は特典をさらに２つ<img height=16><BR>追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 01 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>１２／０３更新予告②</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>・農場施設</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
<font color=orange>　【特注よろず焼き機】<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR></font>
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/bonus51.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							14/14
						</table>
				<tr><td>
					<img width=14 height=16 17>１２／０３更新予告②<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>１２／０３更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>オープン！！<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>１２／０３更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【ファミ通・怒濤の突進祭り！】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 02 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>１２／０３更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【ファミ通・怒濤の突進祭り！】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：ファミ通編集部<img height=16><BR>突進といえばブルファンゴ！<img height=16><BR>新鋭リノプロスも侮れない！<img height=16><BR>もうそんな連中は怖くないぜ、と<img height=16><BR>鼻で笑った貴方！　初心に戻って<img height=16><BR>裸一貫で挑んでみませんか？<img height=16><BR>勝者には生産用チケットを進呈！
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/e60014.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							14/14
						</table>
				<tr><td>
					<img width=14 height=16 17>１２／０３更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／０３更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>オープン！！<BR>
<img height=1><BR>
				<tr><td>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>オープン！！</font><br>
				</center>
<BR>
ダウンロードページを<img height=16><BR>オープンしたのニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 03 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td width=450 height=34 align=center valign=bottom colspan=2>
			<font color=yellow>オープン！！</font><br>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=450 height=143 align=left valign=center>
ダウンロードページをオープンしたのニャ！<img height=16><BR>いろんなクエストや、特典をドンドン追加していくから<img height=16><BR>みんなバンバン！ダウンロードしていってほしいニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
</body>
</html>
