<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?pg_no=2",
		"RB_LINK=DB_INFO.PHP?pg_no=4",
		"MOVE_CHAR=fpic://51.gif,57,71,7,,20,,403,137",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=fpic://03.gif>
<basefont size=1>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							4/14
						</table>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０８／１９更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>０８／１２更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１２更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１０更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１０更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／０５更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／０５更新予告①<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０８／１９更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【塵雪の乱気流】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 01 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０８／１９更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【塵雪の乱気流】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：酔狂な気象学者<img height=16><BR>竜巻を起こす氷牙竜と風牙竜。<img height=16><BR>この二頭の力が合わさったとき、<img height=16><BR>どんな化学反応を起こすのか。<img height=16><BR>…深い、深いわ、たいへん興味<img height=16><BR>深いわ！！　実験に協力して<img height=16><BR>くれるハンターを募集中よ！
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/e60041.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							4/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０８／１９更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０８／１２更新予告②<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>０８／１２更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１０更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１０更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／０５更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／０５更新予告①<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０８／１２更新予告②</font><br>
				</center>
<BR>
次回は特典をさらに１つ<img height=16><BR>追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 02 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０８／１２更新予告②</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　以下の特典が追加されるのニャ！<img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
<font color=orange>・プーギーの服<img height=16><BR>　【純真クレナイ】<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR></font>
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/bonus23.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							4/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０８／１９更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１２更新予告②<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０８／１２更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>０８／１０更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１０更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／０５更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／０５更新予告①<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０８／１２更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【激走！　白兎獣と狩人】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 03 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０８／１２更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【激走！　白兎獣と狩人】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：凍土最速ソリ乗り<img height=16><BR>最速商人参上！　夜露四苦ッ！<img height=16><BR>ソリの速さが自慢だゼ！<img height=16><BR>…だが、俺は奴に敗れちまった。<img height=16><BR>だれか俺の仇を討ってくれ！<img height=16><BR>かわいいウサギさんに見えるが<img height=16><BR>見た目に騙されるなよ！！
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/e60036.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							4/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０８／１９更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１２更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１２更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０８／１０更新予告②<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>０８／１０更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／０５更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／０５更新予告①<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０８／１０更新予告②</font><br>
				</center>
<BR>
次回は特典をさらに１つ<img height=16><BR>追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 04 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０８／１０更新予告②</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　以下の特典が追加されるのニャ！<img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
<font color=orange>・称号<img height=16><BR>　【ぽかぽか】<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR></font>
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/bonus00.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							4/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０８／１９更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１２更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１２更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１０更新予告②<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０８／１０更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>０８／０５更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／０５更新予告①<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０８／１０更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【アイルー村からオトモへ】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 05 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０８／１０更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【アイルー村からオトモへ】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：ぽかぽか大使アイルー<img height=16><BR>ニャニャニャーーン！！<img height=16><BR>アイルー村で大人気の服を、<img height=16><BR>プレゼントしにきたニャ！<img height=16><BR>ただし！　タダであげるわけには<img height=16><BR>いかないニャよ。ボクらの挑戦に<img height=16><BR>勝ってからニャ。さぁ来いニャ！
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/e60027.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							4/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０８／１９更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１２更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１２更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１０更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１０更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０８／０５更新予告②<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>０８／０５更新予告①<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０８／０５更新予告②</font><br>
				</center>
<BR>
次回は特典をさらに１つ<img height=16><BR>追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 06 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０８／０５更新予告②</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　以下の特典が追加されるのニャ！<img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
<font color=orange>・称号<img height=16><BR>　【モンハン】<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR></font>
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/bonus00.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							4/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０８／１９更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１２更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１２更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１０更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／１０更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０８／０５更新予告②<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０８／０５更新予告①<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０８／０５更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【覇王降臨】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 07 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０８／０５更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【覇王降臨】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：人望厚い国王<img height=16><BR>火山の奥地にある溶岩峡谷に覇王<img height=16><BR>と呼ばれる飛竜がおるのだが、<img height=16><BR>今にもそこから動きだそうと<img height=16><BR>しておる。もし我が国を通る<img height=16><BR>ことにでもなったら…。狩人よ！<img height=16><BR>その力、余に貸してくれ！
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/e60032.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
</body>
</html>
