<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?pg_no=10",
		"RB_LINK=DB_INFO.PHP?pg_no=12",
		"MOVE_CHAR=fpic://51.gif,57,71,7,,20,,403,137",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=fpic://03.gif>
<basefont size=1>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							12/14
						</table>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０１／１４更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>０１／０７更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０１／０７更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／３１更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／３１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／２７更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／２４更新予告②<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０１／１４更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【犬夜叉・大妖の牙を求めて】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 01 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０１／１４更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【犬夜叉・大妖の牙を求めて】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：少年サンデー編集部<img height=16><BR>もっとも過酷な狩り場の１つ、<img height=16><BR>凍土での大連続狩猟！<img height=16><BR>これを達成したハンターには、<img height=16><BR>少年サンデー編集部より、強力な<img height=16><BR>太刀の素材≪伝説の妖怪≫の牙を<img height=16><BR>差し上げます！
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/e60004.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							12/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０１／１４更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０１／０７更新予告②<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>０１／０７更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／３１更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／３１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／２７更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／２４更新予告②<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０１／０７更新予告②</font><br>
				</center>
<BR>
次回は特典をさらに２つ<img height=16><BR>追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 02 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０１／０７更新予告②</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　以下の特典が追加されるのニャ！<img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
<font color=orange>・称号<img height=16><BR>　【電撃】<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR></font>
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/bonus00.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							12/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０１／１４更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０１／０７更新予告②<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０１／０７更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>１２／３１更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／３１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／２７更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／２４更新予告②<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０１／０７更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【電撃・ダブルライジング！】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 03 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０１／０７更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【電撃・ダブルライジング！】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：電撃の編集部<img height=16><BR>電撃編集部の今回の依頼は…、<img height=16><BR>場所は孤島！<img height=16><BR>相手はかの雷狼竜、しかも２頭！<img height=16><BR>このクエストを成功させた方には<img height=16><BR>エレクトリカルな音色を奏でる<img height=16><BR>狩猟笛が作れるチケットを進呈！
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/e60018.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							12/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０１／１４更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０１／０７更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０１／０７更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>１２／３１更新予告②<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>１２／３１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／２７更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／２４更新予告②<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>１２／３１更新予告②</font><br>
				</center>
<BR>
次回は特典をさらに１つ<img height=16><BR>追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 04 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>１２／３１更新予告②</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　以下の特典が追加されるのニャ！<img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
<font color=orange>・称号<img height=16><BR>　【バキ】<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR></font>
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/bonus00.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							12/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０１／１４更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０１／０７更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０１／０７更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／３１更新予告②<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>１２／３１更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>１２／２７更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／２４更新予告②<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>１２／３１更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【範馬刃牙・鬼の遺伝子】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 05 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>１２／３１更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【範馬刃牙・鬼の遺伝子】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：徳川家十三代目当主<img height=16><BR>狩人として生まれたからには、<img height=16><BR>誰だって一度は地上最強を志す！<img height=16><BR>さあ強者よ、裸がっぷり四ツ、<img height=16><BR>己が強さを見せつけてくれいッ！<img height=16><BR>見事勝ち得た者には≪証≫を<img height=16><BR>進呈しようではないかッ！
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/e60002.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							12/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０１／１４更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０１／０７更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０１／０７更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／３１更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／３１更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>１２／２７更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>１２／２４更新予告②<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>１２／２７更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【ユニクロ・究極素材の追求】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 06 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>１２／２７更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【ユニクロ・究極素材の追求】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：こだわりの匠<img height=16><BR>格好良いデザインの装備を<img height=16><BR>ハンターさんのために考えたよ！<img height=16><BR>こだわりの素材を使用している<img height=16><BR>ので、手に入り難いのが困りもの<img height=16><BR>なんだ。良い装備のために、<img height=16><BR>協力してくれないかい？
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/e60022.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							12/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０１／１４更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０１／０７更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０１／０７更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／３１更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／３１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／２７更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>１２／２４更新予告②<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>１２／２４更新予告②</font><br>
				</center>
<BR>
次回は特典をさらに２つ<img height=16><BR>追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 07 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>１２／２４更新予告②</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　以下の特典が追加されるのニャ！<img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
<font color=orange>・温泉ドリンク<img height=16><BR>　【ユクモミルクコーヒー】<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR></font>
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/bonus31.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
</body>
</html>
