<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?pg_no=7",
		"RB_LINK=DB_INFO.PHP?pg_no=9",
		"MOVE_CHAR=fpic://51.gif,57,71,7,,20,,403,137",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=fpic://03.gif>
<basefont size=1>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							9/14
						</table>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０３／１８更新予告②<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>０３／１８更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１４更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１１更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／０４更新予告④<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／０４更新予告③<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０３／１８更新予告②</font><br>
				</center>
<BR>
次回は特典をさらに１つ<img height=16><BR>追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 01 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０３／１８更新予告②</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　以下の特典が追加されるのニャ！<img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
<font color=orange>・称号<img height=16><BR>　【ミナガルデ】<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR></font>
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/bonus00.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							9/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０３／１８更新予告②<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０３／１８更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>０３／１４更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１１更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／０４更新予告④<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／０４更新予告③<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０３／１８更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【ＪＵＭＰ・小兵の狂乱】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 02 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０３／１８更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【ＪＵＭＰ・小兵の狂乱】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：隻眼黒髭の男<img height=16><BR>火山の一角でえらく小さい紅彩鳥<img height=16><BR>が目撃された。小さいだけでも<img height=16><BR>不思議なのにさらに紅彩鳥の<img height=16><BR>周りで爆音が響いてたそうだ。<img height=16><BR>原因を解明してくれたら特別な<img height=16><BR>チケットを贈呈するぜ！
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/e60011.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							9/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０３／１８更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１８更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０３／１４更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>０３／１１更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／０４更新予告④<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／０４更新予告③<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０３／１４更新予告①</font><br>
				</center>
<BR>
次回はオトモアイルーを<img height=16><BR>追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 03 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０３／１４更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　以下のオトモアイルーが追加されるのニャ！<img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
<font color=orange>・オトモアイルー<img height=16><BR>　【SEAMOさんのコシーモ】<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR></font>
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/bto_seamo.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							9/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０３／１８更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１８更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１４更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０３／１１更新予告②<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>０３／１１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／０４更新予告④<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／０４更新予告③<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０３／１１更新予告②</font><br>
				</center>
<BR>
次回は特典をさらに１つ<img height=16><BR>追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 04 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０３／１１更新予告②</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　以下の特典が追加されるのニャ！<img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
<font color=orange>・温泉ドリンク<img height=16><BR>　【ユクモひやしあめ】<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR></font>
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/bonus31.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							9/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０３／１８更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１８更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１４更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１１更新予告②<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０３／１１更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>０３／０４更新予告④<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／０４更新予告③<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０３／１１更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【武装戦線・男たちの勝負！】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 05 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０３／１１更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【武装戦線・男たちの勝負！】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：武装戦線七代目ヘッド<img height=16><BR>武闘派モンスター２頭の狩猟。<img height=16><BR>一筋縄じゃいかねぇこの依頼、<img height=16><BR>見事ものにすることができれば、<img height=16><BR>お前を≪男≫と認めてやる。<img height=16><BR>武装のドクロを背負う資格が<img height=16><BR>あるか、見させてもらうぜ。
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/e60001.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							9/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０３／１８更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１８更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１４更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１１更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１１更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０３／０４更新予告④<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>０３／０４更新予告③<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０３／０４更新予告④</font><br>
				</center>
<BR>
次回はオトモアイルーを<img height=16><BR>追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 06 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０３／０４更新予告④</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　以下のオトモアイルーが追加されるのニャ！<img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
<font color=orange>・オトモアイルー<img height=16><BR>　【ピエール瀧さんのピエルー】<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR></font>
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/bto_taki.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							9/14
						</table>
				<tr><td>
					<img width=14 height=16 17>０３／１８更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１８更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１４更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１１更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／１１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>０３／０４更新予告④<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>０３／０４更新予告③<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>０３／０４更新予告③</font><br>
				</center>
<BR>
次回は特典をさらに２つ<img height=16><BR>追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 07 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>０３／０４更新予告③</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　以下の特典が追加されるのニャ！<img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
<font color=orange>・称号<img height=16><BR>　【ジャンボ】<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR></font>
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/bonus00.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
</body>
</html>
