<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?pg_no=13",
		"RB_LINK=DB_INFO.PHP?pg_no=1",
		"MOVE_CHAR=fpic://51.gif,57,71,7,,20,,403,137",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=fpic://03.gif>
<basefont size=1>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							1/14
						</table>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>１２／０９更新予告②<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>１２／０９更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／０２更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／２５更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／１８更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／１１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／０４更新予告①<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>１２／０９更新予告②</font><br>
				</center>
<BR>
次回は特典をさらに１つ<img height=16><BR>追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 01 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>１２／０９更新予告②</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　以下の特典が追加されるのニャ！<img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
<font color=orange>・プーギーの服<img height=16><BR>　【ブンブンビー】<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR></font>
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/bonus24.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							1/14
						</table>
				<tr><td>
					<img width=14 height=16 17>１２／０９更新予告②<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>１２／０９更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>１２／０２更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／２５更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／１８更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／１１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／０４更新予告①<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>１２／０９更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【最強への挑戦】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 02 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>１２／０９更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【最強への挑戦】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：謎の赤衣の男<img height=16><BR>もはやなにも言うことはない。<img height=16><BR>最強の称号を手に入れるには、<img height=16><BR>この闘技場から無事に生還<img height=16><BR>すればいいのだ。ハンター<img height=16><BR>諸君。さあ、挑戦するがよい。<img height=16><BR>そして乗り越えてみせよ！
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/e60050.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							1/14
						</table>
				<tr><td>
					<img width=14 height=16 17>１２／０９更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／０９更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>１２／０２更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>１１／２５更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／１８更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／１１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／０４更新予告①<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>１２／０２更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【チャレンジクエスト　０６】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 03 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>１２／０２更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【チャレンジクエスト　０６】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：教官<img height=16><BR>おっと、まだ準備中なのだが…<img height=16><BR>うむ…まあ、問題はあるまい、<img height=16><BR>サービスだ！　１頭は準備できて<img height=16><BR>いるから、先に始めておくのだ。<img height=16><BR>準備が終わり次第、もう１頭も<img height=16><BR>投入してやろう。我輩優しすぎ！
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/c61010.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							1/14
						</table>
				<tr><td>
					<img width=14 height=16 17>１２／０９更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／０９更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／０２更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>１１／２５更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>１１／１８更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／１１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／０４更新予告①<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>１１／２５更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【チャレンジクエスト　０３】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 04 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>１１／２５更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【チャレンジクエスト　０３】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：教官<img height=16><BR>闘技場に現れた紅彩鳥を討伐<img height=16><BR>せよ！　もちろんこやつは、他の<img height=16><BR>モンスターを呼び寄せるぞ、準備<img height=16><BR>は十分にしておけ！　無論、どん<img height=16><BR>な相手が来ようと、紅彩鳥さえ<img height=16><BR>倒せば、クエストは成功だ！
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/c61007.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							1/14
						</table>
				<tr><td>
					<img width=14 height=16 17>１２／０９更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／０９更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／０２更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／２５更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>１１／１８更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>１１／１１更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／０４更新予告①<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>１１／１８更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【チャレンジクエスト　１０】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 05 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>１１／１８更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【チャレンジクエスト　１０】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：教官<img height=16><BR>今回は、２頭同時に相手してもら<img height=16><BR>うぞ！　こういう場合は、片方を<img height=16><BR>集中的に狙うのが定石だが、さて<img height=16><BR>どちらを先に狙うべきか…？<img height=16><BR>それは貴様が考えろ！　相手の<img height=16><BR>攻撃を利用するのも手だぞ！！
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/c61014.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							1/14
						</table>
				<tr><td>
					<img width=14 height=16 17>１２／０９更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／０９更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／０２更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／２５更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／１８更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>１１／１１更新予告①<BR>
<img height=1><BR>
				<tr><td>
					<img width=14 height=16 17>１１／０４更新予告①<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>１１／１１更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【チャレンジクエスト　０９】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 06 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>１１／１１更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【チャレンジクエスト　０９】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：教官<img height=16><BR>轟竜ティガレックスに、尾槌竜<img height=16><BR>ドボルベルク！　どちらも小細工<img height=16><BR>なしに手強いモンスターだ！<img height=16><BR>貴様も小細工は抜き、正面から<img height=16><BR>立ち向かえ！　何？　なんか<img height=16><BR>スースーする？　気のせいだ！
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/c61013.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<table width=480 height=250 cellspacing=0>
<tr>
	<td width=230>
	<table width=230 cellspacing=0>
	<tr>
		<td>
			<img src=fpic://55.gif width=93 height=47 alt="Information"><br>
		</td>
	</tr>
	<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr>
			<td align=center>
				<table width=212 cellspacing=0>
				<tr><td width=212 height=15 align=center>
						<table width=92 cellspacing=0 background=fpic://42.gif>
						<tr><td height=15 align=center valign=bottom>
							1/14
						</table>
				<tr><td>
					<img width=14 height=16 17>１２／０９更新予告②<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／０９更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１２／０２更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／２５更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／１８更新予告①<BR>
<img height=1><BR>
					<img width=14 height=16 17>１１／１１更新予告①<BR>
<img height=1><BR>
				<tr><td bgcolor=green>
					<img width=14 height=16 17>１１／０４更新予告①<BR>
<img height=1><BR>
				</table>
			</td>
		</tr>
		</table>
	</td>
	</tr>
	</table>
	</td>
	<td width=250 height=250 valign=middle>
		<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 background=fpic://40.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=170></td>
			<td width=235 valign=top>
				<center>
					<font color=yellow>１１／０４更新予告①</font><br>
				</center>
<BR>
次回はクエスト<img height=16><BR><font color=orange>【未曾有の脅威】</font><img height=16><BR>を追加予定ニャ！<img height=16><BR>詳しく知りたかったら<img height=16><BR><img src=fpic://61.gif width=14 height=14>ボタンを押すのニャ！<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://10.gif width=480 height=22></td></tr></table>
<!--####### 07 2/2 #######-->
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://55.gif width=93 height=47 alt="Information">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td width=479 align=center>
	<table width=450 height=180 cellspacing=0 cellpadding=0>
	<tr>
		<td height=30 align=center valign=center top colspan=3>
			<font color=yellow>１１／０４更新予告①</font><br>
		</td>
	</tr>
	<tr>
		<td height=32 align=left colspan=3>
次回の内容をちょっとだけ教えちゃうのニャ！<img height=16><BR>
　<font color=orange>【未曾有の脅威】</font><img height=16>
		</td>
	</tr>
	<tr>
		<td width=14></td>
		<td width=224 height=120 align=left valign=top center>
依頼主：火の国の姫<img height=16><BR>数々の危機を乗り越え、火の山と<img height=16><BR>共に歩んできた我ら火の民にも<img height=16><BR>覚悟の時が来た。だが、どんな<img height=16><BR>苦難が訪れようとも我々は運命に<img height=16><BR>など屈しない！　明日を切り開く<img height=16><BR>ため、お主の力を貸して欲しい。
		</td>
		<td width=212 height=129 align=left valign=top>
			<img height=2><BR>
			<img src=PNG/e60048.png width=200 height=90><BR>
		</td>
	</tr>
	</table>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://10.gif width=480 height=22></td></tr></table>
</body>
</html>
