<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:7",
		"MOVE_CHAR=fpic://51.gif,57,71,7,,20,,403,137",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=fpic://03.gif>
<basefont size=1>
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://54.gif width=93 height=47 alt="Bonus">
	</td>
</tr>
<form action="BONUS/bonus.mib" BDOWNLOAD method=post>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td align=right height=20>
			</td>
		</tr>
		<tr>
			<td width=432 height=121 valign=top>
特典は全て開放されているニャ！<img height=16><BR>
						詳細は<img src=fpic://61.gif width=14 height=14>ボタンで確認してほしいのニャー。<img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR><img height=16><BR>
			</td>
		</tr>
		<tr>
			<td height=21 align=center>
				<img ANIME=10 src=fpic://04.gif width=214 height=21 alt="[O] DOWNLOAD"><BR>
				<input type=image src="" name=submit width=0 height=0>
			</td>
		</tr>
		<tr>
			<td align=right height=27>
			</td>
		</tr>
		</table>
	</td>
</tr>
</form>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://09.gif width=480 height=22></td></tr></table>
<a name=002></a>
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://54.gif width=93 height=47 alt="Bonus">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=92 height=15 11 cellspacing=0 cellpadding=0 background=fpic://42.gif>
				<tr>
					<td height=15 align=center valign=bottom >
						１/８
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<img height=16><BR></font>
【称号】<img height=16><BR>ギルドカードで使う称号が追加されるニャ。<img height=16><BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#00 qname=00>・ココット</a><img height=16><BR>
<a href=#01 qname=01>・ジャンボ</a><img height=16><BR>
<a href=#02 qname=02>・ミナガルデ</a><img height=16><BR>
<a href=#03 qname=03>・ドンドルマ</a><img height=16><BR>
			</td>
			<td width=232 height=90 valign=top>
<a href=#04 qname=04>・書士隊</a><img height=16><BR>
<a href=#05 qname=05>・王立学術院</a><img height=16><BR>
<a href=#06 qname=06>・古龍観測隊</a><img height=16><BR>
<a href=#07 qname=07>・シュレイド</a><img height=16><BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://09.gif width=480 height=22></td></tr></table>
<a name=003></a>
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://54.gif width=93 height=47 alt="Bonus">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=92 height=15 11 cellspacing=0 cellpadding=0 background=fpic://42.gif>
				<tr>
					<td height=15 align=center valign=bottom >
						２/８
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<img height=16><BR></font>
【称号】<img height=16><BR>ギルドカードで使う称号が追加されるニャ。<img height=16><BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#08 qname=08>・狩魂</a><img height=16><BR>
<a href=#09 qname=09>・歌姫</a><img height=16><BR>
<a href=#12 qname=12>・モガ</a><img height=16><BR>
<a href=#13 qname=13>・ロックラック</a><img height=16><BR>
			</td>
			<td width=232 height=90 valign=top>
<a href=#14 qname=14>・モンハン</a><img height=16><BR>
<a href=#11 qname=11>・ぽかぽか</a><img height=16><BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://09.gif width=480 height=22></td></tr></table>
<a name=004></a>
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://54.gif width=93 height=47 alt="Bonus">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=92 height=15 11 cellspacing=0 cellpadding=0 background=fpic://42.gif>
				<tr>
					<td height=15 align=center valign=bottom >
						３/８
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<img height=16><BR></font>
【称号】<img height=16><BR>ギルドカードで使う称号が追加されるニャ。<img height=16><BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#19 qname=19>・サンデー</a><img height=16><BR>
<a href=#17 qname=17>・ファミ通</a><img height=16><BR>
<a href=#16 qname=16>・ジャンプ</a><img height=16><BR>
<a href=#15 qname=15>・マガジン</a><img height=16><BR>
			</td>
			<td width=232 height=90 valign=top>
<a href=#20 qname=20>・バキ</a><img height=16><BR>
<a href=#18 qname=18>・電撃</a><img height=16><BR>
<a href=#21 qname=21>・クローズ</a><img height=16><BR>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://09.gif width=480 height=22></td></tr></table>
<a name=005></a>
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://54.gif width=93 height=47 alt="Bonus">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=92 height=15 11 cellspacing=0 cellpadding=0 background=fpic://42.gif>
				<tr>
					<td height=15 align=center valign=bottom >
						４/８
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<img height=16><BR></font>
【プーギーの服】<img height=16><BR>プーギーの着せ替え用の服が追加されるニャ。<img height=16><BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#25 qname=25>・ブンブンビー</a><img height=16><BR>
<a href=#22 qname=22>・ブラックハニー</a><img height=16><BR>
<a href=#24 qname=24>・純真クレナイ</a><img height=16><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=PNG/bonus24.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://09.gif width=480 height=22></td></tr></table>
<a name=006></a>
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://54.gif width=93 height=47 alt="Bonus">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=92 height=15 11 cellspacing=0 cellpadding=0 background=fpic://42.gif>
				<tr>
					<td height=15 align=center valign=bottom >
						５/８
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<img height=16><BR></font>
【温泉ドリンク】<img height=16><BR>温泉ドリンクが追加されるニャ。<img height=16><BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#27 qname=27>・ユクモラムネ</a><img height=16><BR>
<a href=#26 qname=26>・ユクモミルクコーヒー</a><img height=16><BR>
<a href=#29 qname=29>・本日のオススメ！</a><img height=16><BR>
<a href=#28 qname=28>・ユクモひやしあめ</a><img height=16><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=PNG/bonus31.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://09.gif width=480 height=22></td></tr></table>
<a name=007></a>
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://54.gif width=93 height=47 alt="Bonus">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=92 height=15 11 cellspacing=0 cellpadding=0 background=fpic://42.gif>
				<tr>
					<td height=15 align=center valign=bottom >
						６/８
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<img height=16><BR></font>
【ユクモポイント】<img height=16><BR>ユクモポイントが３０００ポイント貰えるニャ。<img height=16><BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#33 qname=33>・３０００ポイント入手</a><img height=16><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=PNG/bonus41.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://09.gif width=480 height=22></td></tr></table>
<a name=008></a>
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://54.gif width=93 height=47 alt="Bonus">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=92 height=15 11 cellspacing=0 cellpadding=0 background=fpic://42.gif>
				<tr>
					<td height=15 align=center valign=bottom >
						７/８
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<img height=16><BR></font>
【農場施設】<img height=16><BR>特注よろず焼き機が設置可能になるニャ。<img height=16><BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#34 qname=34>・特注よろず焼き機</a><img height=16><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=PNG/bonus51.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://09.gif width=480 height=22></td></tr></table>
<a name=009></a>
<table width=480 cellspacing=0 cellpadding=0><tr><td height=250 valign=top>
<table width=480 height=239 cellspacing=0 cellpadding=0 background=fpic://05.gif>
<tr>
	<td height=47>
		<img src=fpic://54.gif width=93 height=47 alt="Bonus">
	</td>
</tr>
<tr>
	<td width=480 align=center valign=top>
		<table width=432 height=192 cellspacing=0 cellpadding=0>
		<tr>
			<td colspan=2 width=432 height=25 align=center valign=bottom>
				<table width=92 height=15 11 cellspacing=0 cellpadding=0 background=fpic://42.gif>
				<tr>
					<td height=15 align=center valign=bottom >
						８/８
					</td>
				</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan=2 width=432 height=55 valign=top>
<font color=orange>まだ獲得していない特典は黄色で表示されるニャ！<img height=16><BR></font>
【行商人の品揃え】<img height=16><BR>いつもよりずっと良い品を仕入れてくれる…かもニャ。<img height=16><BR>
			</td>
		</tr>
		<tr>
			<td width=200 height=90 valign=top>
<a href=#35 qname=35>・特別な品揃え</a><img height=16><BR>
			</td>
			<td width=232 align=center valign=top>
				<img src=PNG/bonus61.png width=200 height=90>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://09.gif width=480 height=22></td></tr></table>
</body>
</html>
