<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_CMENU.PHP?pg_no=0",
		"RB_LINK=DL_CMENU.PHP?pg_no=0",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=#393025 link=white vlink=white bgcolor=brown background=fpic://03.gif>
<basefont size=1>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m61008.mib" DOWNLOAD CSUM=33979 FSIZE=2400 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>2/2</font>
				</table>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#001 qname=m61008>チャレンジクエスト　０４</a><BR><img height=1><BR>
			<tr><td height=102 valign=top>
				<img width=14 height=16><a href=#002 qname=m61009>チャレンジクエスト　０５</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m61010>チャレンジクエスト　０６</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m61011>チャレンジクエスト　０７</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m61012>チャレンジクエスト　０８</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m61013>チャレンジクエスト　０９</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m61014>チャレンジクエスト　１０</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=GIF/CQ_kunren.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>チャレンジクエスト　０４</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>６０００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>３０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>参加資格</font><br>
						<img height=16>なし<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 01 2/2 #######-->
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=GIF/CQ_kunren_L.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom>
				チャレンジクエスト　０４
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>すべての大型モンスターの討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=GIF/kunren_R.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>教官<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>我輩だ。教官だ！<BR>チャレンジクエストが大連続狩猟<BR>形式の場合、気持ちの切替が重要<BR>になる！　テンポが違う相手に、<BR>対応していけるか！？　ヌハハ、<BR>貴様の地力が試されるぞ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m61009.mib" DOWNLOAD CSUM=24379 FSIZE=2276 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>2/2</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m61008>チャレンジクエスト　０４</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#002 qname=m61009>チャレンジクエスト　０５</a><BR><img height=1><BR>
			<tr><td height=85 valign=top>
				<img width=14 height=16><a href=#003 qname=m61010>チャレンジクエスト　０６</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m61011>チャレンジクエスト　０７</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m61012>チャレンジクエスト　０８</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m61013>チャレンジクエスト　０９</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m61014>チャレンジクエスト　１０</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=GIF/CQ_kunren.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>チャレンジクエスト　０５</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>６０００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>３０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>参加資格</font><br>
						<img height=16>なし<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 02 2/2 #######-->
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=GIF/CQ_kunren_L.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom>
				チャレンジクエスト　０５
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ナルガクルガ亜種１頭の討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=GIF/kunren_R.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>教官<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>鋭い動きで、死角から襲い来る<BR>緑迅竜！　闘技場のような視界が<BR>ひらけた場所であっても、その<BR>脅威は揺るがない！…だが我輩が<BR>選んだナイス装備ならサクサク<BR>回避可能のはず！　華麗に舞え！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m61010.mib" DOWNLOAD CSUM=33775 FSIZE=2352 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>2/2</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m61008>チャレンジクエスト　０４</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m61009>チャレンジクエスト　０５</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#003 qname=m61010>チャレンジクエスト　０６</a><BR><img height=1><BR>
			<tr><td height=68 valign=top>
				<img width=14 height=16><a href=#004 qname=m61011>チャレンジクエスト　０７</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m61012>チャレンジクエスト　０８</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m61013>チャレンジクエスト　０９</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m61014>チャレンジクエスト　１０</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=GIF/CQ_kunren.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>チャレンジクエスト　０６</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>７５００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>３０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>参加資格</font><br>
						<img height=16>ＨＲ６以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 03 2/2 #######-->
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=GIF/CQ_kunren_L.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom>
				チャレンジクエスト　０６
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>アオアシラ１頭と<BR>ジンオウガ１頭の討伐<BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=GIF/kunren_R.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>教官<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>おっと、まだ準備中なのだが…<BR>うむ…まあ、問題はあるまい、<BR>サービスだ！　１頭は準備できて<BR>いるから、先に始めておくのだ。<BR>準備が終わり次第、もう１頭も<BR>投入してやろう。我輩優しすぎ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m61011.mib" DOWNLOAD CSUM=50322 FSIZE=2476 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>2/2</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m61008>チャレンジクエスト　０４</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m61009>チャレンジクエスト　０５</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m61010>チャレンジクエスト　０６</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#004 qname=m61011>チャレンジクエスト　０７</a><BR><img height=1><BR>
			<tr><td height=51 valign=top>
				<img width=14 height=16><a href=#005 qname=m61012>チャレンジクエスト　０８</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m61013>チャレンジクエスト　０９</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m61014>チャレンジクエスト　１０</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=GIF/CQ_kunren.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>チャレンジクエスト　０７</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>４８００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>３０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>参加資格</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 04 2/2 #######-->
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=GIF/CQ_kunren_L.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom>
				チャレンジクエスト　０７
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ドスジャギィ１頭の討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=GIF/kunren_R.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>教官<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>ハンターたる者、アイテムを使い<BR>こなして、初めて一流といえる！<BR>今回は我輩がたくさんアイテムを<BR>用意しておいたぞ！　どの順番で<BR>使えば一番効果的になるのかを<BR>考えてハンティングを行うのだ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m61012.mib" DOWNLOAD CSUM=31159 FSIZE=2288 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>2/2</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m61008>チャレンジクエスト　０４</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m61009>チャレンジクエスト　０５</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m61010>チャレンジクエスト　０６</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m61011>チャレンジクエスト　０７</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#005 qname=m61012>チャレンジクエスト　０８</a><BR><img height=1><BR>
			<tr><td height=34 valign=top>
				<img width=14 height=16><a href=#006 qname=m61013>チャレンジクエスト　０９</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m61014>チャレンジクエスト　１０</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=GIF/CQ_kunren.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>チャレンジクエスト　０８</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>７５００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>３０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>参加資格</font><br>
						<img height=16>ＨＲ６以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 05 2/2 #######-->
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=GIF/CQ_kunren_L.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom>
				チャレンジクエスト　０８
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>アグナコトル亜種１頭の討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=GIF/kunren_R.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>教官<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>一流のハンターならば、たとえ<BR>空腹になっても、華麗に立ち回れ<BR>なければいかん！　今回はそんな<BR>クエストだ。相手はアグナコトル<BR>亜種！　ガード可能な装備は無い<BR>ぞ。必死に避け、全力で攻めろ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m61013.mib" DOWNLOAD CSUM=43673 FSIZE=2412 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>2/2</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m61008>チャレンジクエスト　０４</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m61009>チャレンジクエスト　０５</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m61010>チャレンジクエスト　０６</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m61011>チャレンジクエスト　０７</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m61012>チャレンジクエスト　０８</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#006 qname=m61013>チャレンジクエスト　０９</a><BR><img height=1><BR>
			<tr><td height=17 valign=top>
				<img width=14 height=16><a href=#007 qname=m61014>チャレンジクエスト　１０</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=GIF/CQ_kunren.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>チャレンジクエスト　０９</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>９０００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>３０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>参加資格</font><br>
						<img height=16>ＨＲ６以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 06 2/2 #######-->
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=GIF/CQ_kunren_L.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom>
				チャレンジクエスト　０９
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>すべての大型モンスターの討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=GIF/kunren_R.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>教官<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>轟竜ティガレックスに、尾槌竜<BR>ドボルベルク！　どちらも小細工<BR>なしに手強いモンスターだ！<BR>貴様も小細工は抜き、正面から<BR>立ち向かえ！　何？　なんか<BR>スースーする？　気のせいだ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m61014.mib" DOWNLOAD CSUM=26900 FSIZE=2776 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>2/2</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m61008>チャレンジクエスト　０４</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m61009>チャレンジクエスト　０５</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m61010>チャレンジクエスト　０６</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m61011>チャレンジクエスト　０７</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m61012>チャレンジクエスト　０８</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m61013>チャレンジクエスト　０９</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#007 qname=m61014>チャレンジクエスト　１０</a><BR><img height=1><BR>
			<tr><td height=0 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=GIF/CQ_kunren.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>チャレンジクエスト　１０</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>９０００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>３０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>参加資格</font><br>
						<img height=16>ＨＲ６以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 07 2/2 #######-->
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=GIF/CQ_kunren_L.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom>
				チャレンジクエスト　１０
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ティガレックス亜種１頭と<BR>ウラガンキン亜種１頭の討伐<BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=GIF/kunren_R.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>教官<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>今回は、２頭同時に相手してもら<BR>うぞ！　こういう場合は、片方を<BR>集中的に狙うのが定石だが、さて<BR>どちらを先に狙うべきか…？<BR>それは貴様が考えろ！　相手の<BR>攻撃を利用するのも手だぞ！！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
</body>
</html>
