<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_CMENU.PHP?pg_no=1",
		"RB_LINK=DL_CMENU.PHP?pg_no=1",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=#393025 link=white vlink=white bgcolor=brown background=fpic://03.gif>
<basefont size=1>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m61001.mib" DOWNLOAD CSUM=25301 FSIZE=2252 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>1/2</font>
				</table>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#001 qname=m61001>モンハンフェスタ　０１</a><BR><img height=1><BR>
			<tr><td height=102 valign=top>
				<img width=14 height=16><a href=#002 qname=m61002>モンハンフェスタ　０２</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m61003>モンハンフェスタ　０３</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m61004>モンハンフェスタ　０４</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m61005>チャレンジクエスト　０１</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m61006>チャレンジクエスト　０２</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m61007>チャレンジクエスト　０３</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=GIF/CQ_kunren.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>モンハンフェスタ　０１</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>６３００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>参加資格</font><br>
						<img height=16>なし<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 01 2/2 #######-->
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=GIF/CQ_kunren_L.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom>
				モンハンフェスタ　０１
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ジンオウガ１頭の討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=GIF/kunren_R.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>若き大会運営者<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>モンハンフェスタへようこそ！<BR>ご存じの通り、こちらでは、<BR>如何に早いタイムで、クエストを<BR>達成するかが問われます。<BR>ジンオウガは手強い相手ですが、<BR>くれぐれもお気をつけて！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m61002.mib" DOWNLOAD CSUM=23248 FSIZE=2276 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>1/2</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m61001>モンハンフェスタ　０１</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#002 qname=m61002>モンハンフェスタ　０２</a><BR><img height=1><BR>
			<tr><td height=85 valign=top>
				<img width=14 height=16><a href=#003 qname=m61003>モンハンフェスタ　０３</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m61004>モンハンフェスタ　０４</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m61005>チャレンジクエスト　０１</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m61006>チャレンジクエスト　０２</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m61007>チャレンジクエスト　０３</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=GIF/CQ_kunren.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>モンハンフェスタ　０２</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>６３００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>参加資格</font><br>
						<img height=16>なし<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 02 2/2 #######-->
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=GIF/CQ_kunren_L.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom>
				モンハンフェスタ　０２
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ティガレックス亜種１頭の討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=GIF/kunren_R.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>豪快な大会運営者<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>諸君、ようこそ決勝の舞台へ！<BR>諸君らの挑戦を歓迎するぞ！<BR>今回挑んでもらう相手は、<BR>ティガレックス亜種だ！<BR>恐るべき咆哮と突進をもつ黒轟竜<BR>を、見事乗り越えてみせろ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m61003.mib" DOWNLOAD CSUM=21023 FSIZE=2256 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>1/2</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m61001>モンハンフェスタ　０１</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m61002>モンハンフェスタ　０２</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#003 qname=m61003>モンハンフェスタ　０３</a><BR><img height=1><BR>
			<tr><td height=68 valign=top>
				<img width=14 height=16><a href=#004 qname=m61004>モンハンフェスタ　０４</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m61005>チャレンジクエスト　０１</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m61006>チャレンジクエスト　０２</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m61007>チャレンジクエスト　０３</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=GIF/CQ_kunren.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>モンハンフェスタ　０３</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>９０００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>参加資格</font><br>
						<img height=16>なし<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 03 2/2 #######-->
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=GIF/CQ_kunren_L.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom>
				モンハンフェスタ　０３
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>イビルジョー１頭の討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=GIF/kunren_R.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>妖艶な大会運営者<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>ふふ、大会もいよいよ佳境ね。<BR>今回貴方が挑むのは、恐暴竜<BR>イビルジョー。あの大きな口に<BR>噛まれたらと思うとゾクゾクする<BR>わ…。貴方の素敵な立ち回りを<BR>期待しているわ。<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m61004.mib" DOWNLOAD CSUM=12573 FSIZE=2672 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>1/2</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m61001>モンハンフェスタ　０１</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m61002>モンハンフェスタ　０２</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m61003>モンハンフェスタ　０３</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#004 qname=m61004>モンハンフェスタ　０４</a><BR><img height=1><BR>
			<tr><td height=51 valign=top>
				<img width=14 height=16><a href=#005 qname=m61005>チャレンジクエスト　０１</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m61006>チャレンジクエスト　０２</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m61007>チャレンジクエスト　０３</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=GIF/CQ_kunren.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>モンハンフェスタ　０４</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>９０００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>参加資格</font><br>
						<img height=16>なし<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 04 2/2 #######-->
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=GIF/CQ_kunren_L.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom>
				モンハンフェスタ　０４
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>すべての大型モンスターの討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=GIF/kunren_R.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>高潔な大会運営者<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>数多の狩人が腕を競い、鎬を<BR>削った今大会もいよいよこれで<BR>フィナーレです！<BR>全ての狩人が注目するこの一戦、<BR>存分に力を発揮してください。<BR><BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m61005.mib" DOWNLOAD CSUM=63080 FSIZE=2528 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>1/2</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m61001>モンハンフェスタ　０１</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m61002>モンハンフェスタ　０２</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m61003>モンハンフェスタ　０３</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m61004>モンハンフェスタ　０４</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#005 qname=m61005>チャレンジクエスト　０１</a><BR><img height=1><BR>
			<tr><td height=34 valign=top>
				<img width=14 height=16><a href=#006 qname=m61006>チャレンジクエスト　０２</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m61007>チャレンジクエスト　０３</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=GIF/CQ_kunren.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>チャレンジクエスト　０１</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>１８００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>３０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>参加資格</font><br>
						<img height=16>なし<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 05 2/2 #######-->
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=GIF/CQ_kunren_L.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom>
				チャレンジクエスト　０１
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ドスフロギィ１頭の討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=GIF/kunren_R.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>教官<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>我輩だ。教官だ！<BR>今回貴様に挑んでもらうのは、<BR>ドスフロギィとその子分共だ！<BR>いかに毒霧をかわして立ち回るか<BR>がポイントだ！…ぬ？　なめて<BR>かかると痛い目を見るぞ！！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m61006.mib" DOWNLOAD CSUM=42823 FSIZE=2412 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>1/2</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m61001>モンハンフェスタ　０１</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m61002>モンハンフェスタ　０２</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m61003>モンハンフェスタ　０３</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m61004>モンハンフェスタ　０４</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m61005>チャレンジクエスト　０１</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#006 qname=m61006>チャレンジクエスト　０２</a><BR><img height=1><BR>
			<tr><td height=17 valign=top>
				<img width=14 height=16><a href=#007 qname=m61007>チャレンジクエスト　０３</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=GIF/CQ_kunren.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>チャレンジクエスト　０２</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>１８００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>３０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>参加資格</font><br>
						<img height=16>なし<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 06 2/2 #######-->
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=GIF/CQ_kunren_L.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom>
				チャレンジクエスト　０２
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>すべての大型モンスターの討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=GIF/kunren_R.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>教官<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>クエスト達成までの時間を競う、<BR>チャレンジクエストのお時間だ！<BR>今回のお相手は、牙獣種２連続！<BR>効率よく立ち回るという意識を身<BR>につけるには、格好の相手だな！<BR>よく考えて行動する癖をつけろ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m61007.mib" DOWNLOAD CSUM=30608 FSIZE=2316 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>1/2</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m61001>モンハンフェスタ　０１</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m61002>モンハンフェスタ　０２</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m61003>モンハンフェスタ　０３</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m61004>モンハンフェスタ　０４</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m61005>チャレンジクエスト　０１</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m61006>チャレンジクエスト　０２</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#007 qname=m61007>チャレンジクエスト　０３</a><BR><img height=1><BR>
			<tr><td height=0 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=GIF/CQ_kunren.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>チャレンジクエスト　０３</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>６０００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>３０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>参加資格</font><br>
						<img height=16>ＨＲ５以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 07 2/2 #######-->
<img ANIME=130 src=fpic://53.gif width=231 height=47 alt="Challenge"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=GIF/CQ_kunren_L.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom>
				チャレンジクエスト　０３
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>クルペッコ亜種１頭の討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=GIF/kunren_R.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>教官<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>闘技場に現れた紅彩鳥を討伐<BR>せよ！　もちろんこやつは、他の<BR>モンスターを呼び寄せるぞ、準備<BR>は十分にしておけ！　無論、どん<BR>な相手が来ようと、紅彩鳥さえ<BR>倒せば、クエストは成功だ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
</body>
</html>
