<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?pg_no=3",
		"RB_LINK=DL_MENU.PHP?pg_no=5",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=#393025 link=white vlink=white bgcolor=brown background=fpic://03.gif>
<basefont size=1>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60025.mib" DOWNLOAD CSUM=45942 FSIZE=1352 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>5/8</font>
				</table>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#001 qname=m60025>恐暴の宴</a><BR><img height=1><BR>
			<tr><td height=102 valign=top>
				<img width=14 height=16><a href=#002 qname=m60029>孤島のたまご祭り！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60017>ファミ通・峯山龍、討伐祭り</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60019>電撃の双舞踏</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60028>モンハン部・特選クエスト！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60011>ＪＵＭＰ・小兵の狂乱</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60001>武装戦線・男たちの勝負！</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://32.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>恐暴の宴</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>１９２００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>１６００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 01 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://33.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				恐暴の宴
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>イビルジョー２頭の狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>闘技場の主<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>邪なる捕食者、貪欲の象徴、地を<BR>食らう者、恐暴竜イビルジョー！<BR>我らが闘技場に、この史上最凶の<BR>モンスターが２頭もやってきた！<BR>果たしてどんなハンターが、立ち<BR>向かうのか？　刮目して見よ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60029.mib" DOWNLOAD CSUM=51121 FSIZE=7104 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>5/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60025>恐暴の宴</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#002 qname=m60029>孤島のたまご祭り！</a><BR><img height=1><BR>
			<tr><td height=85 valign=top>
				<img width=14 height=16><a href=#003 qname=m60017>ファミ通・峯山龍、討伐祭り</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60019>電撃の双舞踏</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60028>モンハン部・特選クエスト！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60011>ＪＵＭＰ・小兵の狂乱</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60001>武装戦線・男たちの勝負！</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://30.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>孤島のたまご祭り！</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>４８００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>４００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>孤島&lt;昼&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>なし<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 02 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://31.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				孤島のたまご祭り！
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>竜の卵３個の納品<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://46.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>食道楽を究めた貴婦人<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>グルメの基本は、なんと言っても<BR>竜の卵ざますわね！　パーティー<BR>を開くために、いつもより多めに<BR>調達をお願いするわ。<BR>竜の巣は、海沿いと高台の２ヵ所<BR>にあるらしいわよ。<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60017.mib" DOWNLOAD CSUM=17750 FSIZE=1696 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>5/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60025>恐暴の宴</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60029>孤島のたまご祭り！</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#003 qname=m60017>ファミ通・峯山龍、討伐祭り</a><BR><img height=1><BR>
			<tr><td height=68 valign=top>
				<img width=14 height=16><a href=#004 qname=m60019>電撃の双舞踏</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60028>モンハン部・特選クエスト！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60011>ＪＵＭＰ・小兵の狂乱</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60001>武装戦線・男たちの勝負！</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://34.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>ファミ通・峯山龍、討伐祭り</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>１０２００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>８５０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>３０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>大砂漠<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ３以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 03 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://35.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				ファミ通・峯山龍、討伐祭り
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ジエン・モーランの討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ、タイムアップ<BR>撃龍船の耐久度ゼロ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://57.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>ファミ通編集部<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>祭りだと聞いて来た編集部。<BR>まさか祭りが峯山龍の討伐作戦<BR>の事とはつゆしらず…。<BR>祭りを大成功させたあかつきには<BR>素敵なオトモ武具が作れる<BR>チケットを進呈します！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60019.mib" DOWNLOAD CSUM=35476 FSIZE=1328 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>5/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60025>恐暴の宴</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60029>孤島のたまご祭り！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60017>ファミ通・峯山龍、討伐祭り</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#004 qname=m60019>電撃の双舞踏</a><BR><img height=1><BR>
			<tr><td height=51 valign=top>
				<img width=14 height=16><a href=#005 qname=m60028>モンハン部・特選クエスト！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60011>ＪＵＭＰ・小兵の狂乱</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60001>武装戦線・男たちの勝負！</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://32.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>電撃の双舞踏</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>１３２００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>１１００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 04 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://33.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				電撃の双舞踏
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ギギネブラ亜種２頭の狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>電撃の編集部<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>電撃の編集部からの挑戦状！<BR>電気を操る怪竜。それも２頭を<BR>前にキミは勝利できるか！？<BR>もしクリアできたらシビれる<BR>ような武器が作れるチケットを<BR>プレゼントするよ。<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60028.mib" DOWNLOAD CSUM=16210 FSIZE=4764 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>5/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60025>恐暴の宴</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60029>孤島のたまご祭り！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60017>ファミ通・峯山龍、討伐祭り</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60019>電撃の双舞踏</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#005 qname=m60028>モンハン部・特選クエスト！</a><BR><img height=1><BR>
			<tr><td height=34 valign=top>
				<img width=14 height=16><a href=#006 qname=m60011>ＪＵＭＰ・小兵の狂乱</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60001>武装戦線・男たちの勝負！</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://32.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>モンハン部・特選クエスト！</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>７２００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>６００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>孤島&lt;夜&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 05 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://33.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				モンハン部・特選クエスト！
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>クルペッコ１頭の狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>モンハン部サポーター<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>やぁ、みんな。狩りしてる？<BR>今日も楽しくクエストへ出発だ！<BR>さてさて今回のモンスターは…<BR>何とちっちゃいクルペッコだ！<BR>見事倒したら、すてきな防具が<BR>君のものだ。早速行ってみよう！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60011.mib" DOWNLOAD CSUM=1262 FSIZE=4648 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>5/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60025>恐暴の宴</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60029>孤島のたまご祭り！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60017>ファミ通・峯山龍、討伐祭り</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60019>電撃の双舞踏</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60028>モンハン部・特選クエスト！</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#006 qname=m60011>ＪＵＭＰ・小兵の狂乱</a><BR><img height=1><BR>
			<tr><td height=17 valign=top>
				<img width=14 height=16><a href=#007 qname=m60001>武装戦線・男たちの勝負！</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://32.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>ＪＵＭＰ・小兵の狂乱</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>８４００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>７００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>火山&lt;夜&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 06 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://33.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				ＪＵＭＰ・小兵の狂乱
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>クルペッコ亜種１頭の狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>隻眼黒髭の男<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>火山の一角でえらく小さい紅彩鳥<BR>が目撃された。小さいだけでも<BR>不思議なのにさらに紅彩鳥の<BR>周りで爆音が響いてたそうだ。<BR>原因を解明してくれたら特別な<BR>チケットを贈呈するぜ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60001.mib" DOWNLOAD CSUM=6817 FSIZE=4668 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>5/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60025>恐暴の宴</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60029>孤島のたまご祭り！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60017>ファミ通・峯山龍、討伐祭り</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60019>電撃の双舞踏</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60028>モンハン部・特選クエスト！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60011>ＪＵＭＰ・小兵の狂乱</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#007 qname=m60001>武装戦線・男たちの勝負！</a><BR><img height=1><BR>
			<tr><td height=0 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://32.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>武装戦線・男たちの勝負！</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>７２００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>６００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>砂原&lt;夜&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>なし<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 07 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://33.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				武装戦線・男たちの勝負！
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ボルボロス２頭の狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>武装戦線七代目ヘッド<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>武闘派モンスター２頭の狩猟。<BR>一筋縄じゃいかねぇこの依頼、<BR>見事ものにすることができれば、<BR>お前を≪男≫と認めてやる。<BR>武装のドクロを背負う資格が<BR>あるか、見させてもらうぜ。<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
</body>
</html>
