<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?pg_no=0",
		"RB_LINK=DL_MENU.PHP?pg_no=2",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=#393025 link=white vlink=white bgcolor=brown background=fpic://03.gif>
<basefont size=1>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60051.mib" DOWNLOAD CSUM=31386 FSIZE=1752 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>2/8</font>
				</table>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#001 qname=m60051>狩人の矜持</a><BR><img height=1><BR>
			<tr><td height=102 valign=top>
				<img width=14 height=16><a href=#002 qname=m60040>氷泥武闘曲</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60033>崩竜激震</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60045>水没林のフロントライン</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60041>塵雪の乱気流</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60036>激走！　白兎獣と狩人</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60027>アイルー村からオトモへ</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://28.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>狩人の矜持</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>３００００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>２５００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 01 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://29.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				狩人の矜持
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>すべての大型モンスターの狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>騎士を従えた少女<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>この地方にとびきり優秀な<BR>ハンターがいるって聞いたけど<BR>あなたのことね？　その実力を<BR>見込んで、前人未踏のクエストを<BR>紹介してあげる。狩人たる誇り、<BR>歴史に刻んでごらんなさい。<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60040.mib" DOWNLOAD CSUM=46257 FSIZE=1404 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>2/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60051>狩人の矜持</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#002 qname=m60040>氷泥武闘曲</a><BR><img height=1><BR>
			<tr><td height=85 valign=top>
				<img width=14 height=16><a href=#003 qname=m60033>崩竜激震</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60045>水没林のフロントライン</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60041>塵雪の乱気流</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60036>激走！　白兎獣と狩人</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60027>アイルー村からオトモへ</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://32.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>氷泥武闘曲</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>１０８００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>９００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 02 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://33.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				氷泥武闘曲
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ボルボロス１頭と<BR>ボルボロス亜種１頭の狩猟<BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>孤高の作曲家<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>通常種と亜種が互いの誇りを<BR>かけて頭部を打ち付けあう際の<BR>鳴動。氷と泥が激しく舞い踊り、<BR>生命の音色を奏でる…そこに君の<BR>熱きビートを重ね、私の楽曲に<BR>最後の音を添えてくれたまえ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60033.mib" DOWNLOAD CSUM=23829 FSIZE=1232 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>2/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60051>狩人の矜持</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60040>氷泥武闘曲</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#003 qname=m60033>崩竜激震</a><BR><img height=1><BR>
			<tr><td height=68 valign=top>
				<img width=14 height=16><a href=#004 qname=m60045>水没林のフロントライン</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60041>塵雪の乱気流</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60036>激走！　白兎獣と狩人</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60027>アイルー村からオトモへ</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://34.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>崩竜激震</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>４０８００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>３４００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>極圏<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ６以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 03 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://35.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				崩竜激震
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ウカムルバスの討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://57.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>心優しき領主<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>ここ最近、極圏の最深部で地響き<BR>が収まる日がなくて助けて<BR>欲しいと陳情がありました。<BR>村人達は白き神がこの世を崩しに<BR>来たのだと怯えています。どうか<BR>彼らを助けてあげてください。<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60045.mib" DOWNLOAD CSUM=4175 FSIZE=5228 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>2/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60051>狩人の矜持</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60040>氷泥武闘曲</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60033>崩竜激震</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#004 qname=m60045>水没林のフロントライン</a><BR><img height=1><BR>
			<tr><td height=51 valign=top>
				<img width=14 height=16><a href=#005 qname=m60041>塵雪の乱気流</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60036>激走！　白兎獣と狩人</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60027>アイルー村からオトモへ</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://28.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>水没林のフロントライン</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>３００００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>２５００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>水没林&lt;昼&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 04 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://29.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				水没林のフロントライン
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>すべての大型モンスターの狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>水没林の警備隊員<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>大変だ！　水没林にモンスター達<BR>が現れた…いや大群と言った方が<BR>良いかもしれない。前線で警備隊<BR>が応戦しているが、数が多すぎて<BR>耐えきれそうにない！　頼む、<BR>水没林の安全を守ってくれ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60041.mib" DOWNLOAD CSUM=42823 FSIZE=1400 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>2/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60051>狩人の矜持</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60040>氷泥武闘曲</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60033>崩竜激震</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60045>水没林のフロントライン</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#005 qname=m60041>塵雪の乱気流</a><BR><img height=1><BR>
			<tr><td height=34 valign=top>
				<img width=14 height=16><a href=#006 qname=m60036>激走！　白兎獣と狩人</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60027>アイルー村からオトモへ</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://32.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>塵雪の乱気流</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>１４４００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>１２００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 05 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://33.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				塵雪の乱気流
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ベリオロス１頭と<BR>ベリオロス亜種１頭の狩猟<BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>酔狂な気象学者<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>竜巻を起こす氷牙竜と風牙竜。<BR>この二頭の力が合わさったとき、<BR>どんな化学反応を起こすのか。<BR>…深い、深いわ、たいへん興味<BR>深いわ！！　実験に協力して<BR>くれるハンターを募集中よ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60036.mib" DOWNLOAD CSUM=30919 FSIZE=4356 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>2/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60051>狩人の矜持</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60040>氷泥武闘曲</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60033>崩竜激震</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60045>水没林のフロントライン</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60041>塵雪の乱気流</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#006 qname=m60036>激走！　白兎獣と狩人</a><BR><img height=1><BR>
			<tr><td height=17 valign=top>
				<img width=14 height=16><a href=#007 qname=m60027>アイルー村からオトモへ</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://32.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>激走！　白兎獣と狩人</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>８４００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>７００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>凍土&lt;昼&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 06 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://33.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				激走！　白兎獣と狩人
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ウルクスス１頭の狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>凍土最速ソリ乗り<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>最速商人参上！　夜露四苦ッ！<BR>ソリの速さが自慢だゼ！<BR>…だが、俺は奴に敗れちまった。<BR>だれか俺の仇を討ってくれ！<BR>かわいいウサギさんに見えるが<BR>見た目に騙されるなよ！！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60027.mib" DOWNLOAD CSUM=17926 FSIZE=1656 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>2/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60051>狩人の矜持</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60040>氷泥武闘曲</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60033>崩竜激震</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60045>水没林のフロントライン</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60041>塵雪の乱気流</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60036>激走！　白兎獣と狩人</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#007 qname=m60027>アイルー村からオトモへ</a><BR><img height=1><BR>
			<tr><td height=0 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://36.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>アイルー村からオトモへ</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>３６００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>３００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>小闘技場<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>なし<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 07 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://37.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				アイルー村からオトモへ
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>アイルー２０匹の討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://58.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>ぽかぽか大使アイルー<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>ニャニャニャーーン！！<BR>アイルー村で大人気の服を、<BR>プレゼントしにきたニャ！<BR>ただし！　タダであげるわけには<BR>いかないニャよ。ボクらの挑戦に<BR>勝ってからニャ。さぁ来いニャ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
</body>
</html>
