<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?pg_no=4",
		"RB_LINK=DL_MENU.PHP?pg_no=6",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=#393025 link=white vlink=white bgcolor=brown background=fpic://03.gif>
<basefont size=1>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60005.mib" DOWNLOAD CSUM=63012 FSIZE=1532 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>6/8</font>
				</table>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#001 qname=m60005>ＹＡＩＢＡ・風神と雷神</a><BR><img height=1><BR>
			<tr><td height=102 valign=top>
				<img width=14 height=16><a href=#002 qname=m60037>巨大熊、山中を破壊す</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60015>ファミ通・状態異常を克服せよ</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60008>マガジン・水没林調査班！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60003>クローズ・鈴蘭最強への証明</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60012>ＪＵＭＰ・２つの赤き凶弾</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60020>ＭＧＳ・ハンターイーター作戦</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://28.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>ＹＡＩＢＡ・風神と雷神</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>１９２００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>１６００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 01 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://29.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				ＹＡＩＢＡ・風神と雷神
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>すべての大型モンスターの狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>眼光鋭い小柄な老人<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>強いと評判の風竜と雷竜。見事<BR>討ち果たさんと勢い勇んで来たが<BR>急に腰痛が…おヌシちょちょいと<BR>ワシに代わり倒してくるのじゃ。<BR>うまくいったら、秘蔵の奥義書を<BR>やろうではないか。<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60037.mib" DOWNLOAD CSUM=47210 FSIZE=4524 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>6/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60005>ＹＡＩＢＡ・風神と雷神</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#002 qname=m60037>巨大熊、山中を破壊す</a><BR><img height=1><BR>
			<tr><td height=85 valign=top>
				<img width=14 height=16><a href=#003 qname=m60015>ファミ通・状態異常を克服せよ</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60008>マガジン・水没林調査班！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60003>クローズ・鈴蘭最強への証明</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60012>ＪＵＭＰ・２つの赤き凶弾</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60020>ＭＧＳ・ハンターイーター作戦</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://32.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>巨大熊、山中を破壊す</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>７８００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>６５０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>渓流&lt;昼&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 02 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://33.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				巨大熊、山中を破壊す
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>アオアシラ１頭の狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>巨漢の警備兵<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>ウス！　俺は見たであります！<BR>巨大で青いアシラさんが、森の中<BR>で暴れまくっていやがりました。<BR>見るからに凶暴な振る舞いに<BR>近づくのは無理であります。<BR>代わりに頼むであります！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60015.mib" DOWNLOAD CSUM=40996 FSIZE=4924 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>6/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60005>ＹＡＩＢＡ・風神と雷神</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60037>巨大熊、山中を破壊す</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#003 qname=m60015>ファミ通・状態異常を克服せよ</a><BR><img height=1><BR>
			<tr><td height=68 valign=top>
				<img width=14 height=16><a href=#004 qname=m60008>マガジン・水没林調査班！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60003>クローズ・鈴蘭最強への証明</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60012>ＪＵＭＰ・２つの赤き凶弾</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60020>ＭＧＳ・ハンターイーター作戦</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://28.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>ファミ通・状態異常を克服せよ</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>９６００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>８００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>火山&lt;夜&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ガンランス限定<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 03 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://29.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				ファミ通・状態異常を克服せよ
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>すべての大型モンスターの狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>ファミ通編集部<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>麻痺！　毒！　睡眠！　我々を<BR>悩ませる状態異常を克服するため<BR>火山の大連続狩猟に挑め！<BR>ただし武器は、ガンランス限定！<BR>その代わり、勝者には、黄金の銃<BR>槍が生産できるチケットを進呈！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60008.mib" DOWNLOAD CSUM=52426 FSIZE=4568 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>6/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60005>ＹＡＩＢＡ・風神と雷神</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60037>巨大熊、山中を破壊す</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60015>ファミ通・状態異常を克服せよ</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#004 qname=m60008>マガジン・水没林調査班！</a><BR><img height=1><BR>
			<tr><td height=51 valign=top>
				<img width=14 height=16><a href=#005 qname=m60003>クローズ・鈴蘭最強への証明</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60012>ＪＵＭＰ・２つの赤き凶弾</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60020>ＭＧＳ・ハンターイーター作戦</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://32.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>マガジン・水没林調査班！</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>１６８００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>１４００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>水没林&lt;昼&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 04 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://33.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				マガジン・水没林調査班！
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>イビルジョー１頭と<BR>ナルガクルガ１頭の狩猟<BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>知的な眼鏡の男<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>みんな！　この文献を見てくれ…<BR>『水没林で黒き疾風と暴食の王が<BR>出会うとき、大いなる絶望が<BR>刻まれる…』つまり、そのとき<BR>この地上の文明は滅亡する！<BR>「…な、なんだってー！？」<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60003.mib" DOWNLOAD CSUM=27217 FSIZE=1732 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>6/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60005>ＹＡＩＢＡ・風神と雷神</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60037>巨大熊、山中を破壊す</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60015>ファミ通・状態異常を克服せよ</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60008>マガジン・水没林調査班！</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#005 qname=m60003>クローズ・鈴蘭最強への証明</a><BR><img height=1><BR>
			<tr><td height=34 valign=top>
				<img width=14 height=16><a href=#006 qname=m60012>ＪＵＭＰ・２つの赤き凶弾</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60020>ＭＧＳ・ハンターイーター作戦</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://28.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>クローズ・鈴蘭最強への証明</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>２１６００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>１８００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>闘技場<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 05 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://29.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				クローズ・鈴蘭最強への証明
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>すべての大型モンスターの狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>金髪グラサンの男<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>これだけの強敵の連続狩猟。<BR>ムチャといえばそうなんだが…。<BR>このクエストをこなしてしまう<BR>ハンターがいるのであれば、<BR>ここにある鈴蘭最強の証を<BR>受け継ぐべきじゃねーのかな。<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60012.mib" DOWNLOAD CSUM=5582 FSIZE=4620 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>6/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60005>ＹＡＩＢＡ・風神と雷神</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60037>巨大熊、山中を破壊す</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60015>ファミ通・状態異常を克服せよ</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60008>マガジン・水没林調査班！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60003>クローズ・鈴蘭最強への証明</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#006 qname=m60012>ＪＵＭＰ・２つの赤き凶弾</a><BR><img height=1><BR>
			<tr><td height=17 valign=top>
				<img width=14 height=16><a href=#007 qname=m60020>ＭＧＳ・ハンターイーター作戦</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://32.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>ＪＵＭＰ・２つの赤き凶弾</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>７２００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>６００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>砂原&lt;昼&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>なし<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 06 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://33.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				ＪＵＭＰ・２つの赤き凶弾
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ラングロトラ２頭の狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>隻眼黒髭の男<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>砂原に２つの赤い物体が落ちた。<BR>調査に行った俺の部下が、戻って<BR>こねえんだ。そこで、お前の出番<BR>という訳だ。報酬は…オトモが<BR>いっぱしの海賊になれるような<BR>とっておきを準備しとくぜ。<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60020.mib" DOWNLOAD CSUM=30004 FSIZE=4916 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>6/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60005>ＹＡＩＢＡ・風神と雷神</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60037>巨大熊、山中を破壊す</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60015>ファミ通・状態異常を克服せよ</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60008>マガジン・水没林調査班！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60003>クローズ・鈴蘭最強への証明</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60012>ＪＵＭＰ・２つの赤き凶弾</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#007 qname=m60020>ＭＧＳ・ハンターイーター作戦</a><BR><img height=1><BR>
			<tr><td height=0 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://32.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>ＭＧＳ・ハンターイーター作戦</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>８４００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>７００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>砂原&lt;昼&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 07 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://33.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				ＭＧＳ・ハンターイーター作戦
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ハプルボッカ１頭の狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>ヘルメットのアイルー<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>ハンターの旦那達！　オイラは<BR>とある場所ですごい素材を手に入<BR>れてきたのニャ！　これがあれば<BR>伝説の傭兵そっくりの装備が作れ<BR>るかもしれないニャ！　全ては<BR>このクエストの成否次第だニャ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
</body>
</html>
