<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?pg_no=6",
		"RB_LINK=DL_MENU.PHP?pg_no=0",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=#393025 link=white vlink=white bgcolor=brown background=fpic://03.gif>
<basefont size=1>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60009.mib" DOWNLOAD CSUM=59545 FSIZE=4036 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>8/8</font>
				</table>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#001 qname=m60009>ＪＵＭＰ・赤熱の双腕</a><BR><img height=1><BR>
			<tr><td height=102 valign=top>
				<img width=14 height=16><a href=#002 qname=m60014>ファミ通・怒濤の突進祭り！</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60006>名探偵コナン・連続狩猟事件！</a><BR><img height=1><BR>
					<BR>
					<BR>
					<BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://32.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>ＪＵＭＰ・赤熱の双腕</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>９６００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>８００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>火山&lt;夜&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>なし<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 01 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://33.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				ＪＵＭＰ・赤熱の双腕
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>リオレウス１頭と<BR>アグナコトル１頭の狩猟<BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>隻眼黒髭の男<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>天より来たる炎を降らせし竜と<BR>地より現れし炎をまといし竜。<BR>この二頭を同時に狩ることが<BR>できれば、お主を我が海賊団の<BR>一員と認め、この特別な財宝を<BR>授けよう。期待しているぞ。<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60014.mib" DOWNLOAD CSUM=13536 FSIZE=1640 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>8/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60009>ＪＵＭＰ・赤熱の双腕</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#002 qname=m60014>ファミ通・怒濤の突進祭り！</a><BR><img height=1><BR>
			<tr><td height=85 valign=top>
				<img width=14 height=16><a href=#003 qname=m60006>名探偵コナン・連続狩猟事件！</a><BR><img height=1><BR>
					<BR>
					<BR>
					<BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://36.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>ファミ通・怒濤の突進祭り！</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>３６００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>３００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>小闘技場<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>防具・護石未装備<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 02 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://37.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				ファミ通・怒濤の突進祭り！
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ブルファンゴ２０頭の討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://58.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>ファミ通編集部<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>突進といえばブルファンゴ！<BR>新鋭リノプロスも侮れない！<BR>もうそんな連中は怖くないぜ、と<BR>鼻で笑った貴方！　初心に戻って<BR>裸一貫で挑んでみませんか？<BR>勝者には生産用チケットを進呈！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60006.mib" DOWNLOAD CSUM=14084 FSIZE=1624 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>8/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60009>ＪＵＭＰ・赤熱の双腕</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60014>ファミ通・怒濤の突進祭り！</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#003 qname=m60006>名探偵コナン・連続狩猟事件！</a><BR><img height=1><BR>
			<tr><td height=68 valign=top>
					<BR>
					<BR>
					<BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://28.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>名探偵コナン・連続狩猟事件！</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>７２００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>６００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>小闘技場<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>なし<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 03 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://29.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				名探偵コナン・連続狩猟事件！
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>すべての大型モンスターの狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>発明家と名乗る老人<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>助けてくれ！　この先の闘技場で<BR>暴れとるヤツらがおるんじゃ。<BR>ワシの小さな友人達も閉じ込めら<BR>れておる。ここで頼りになるのは<BR>ハンターだと聞く、解決できれば<BR>ワシの物なら何でも進呈しよう！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
</body>
</html>
