<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?pg_no=1",
		"RB_LINK=DL_MENU.PHP?pg_no=3",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=#393025 link=white vlink=white bgcolor=brown background=fpic://03.gif>
<basefont size=1>
<!-- ########  01  1/2 ######## -->
<a name=001></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60032.mib" DOWNLOAD CSUM=24775 FSIZE=1224 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>3/8</font>
				</table>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#001 qname=m60032>覇王降臨</a><BR><img height=1><BR>
			<tr><td height=102 valign=top>
				<img width=14 height=16><a href=#002 qname=m60044>集え！　砂原の最終決戦</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60042>ガーグァと卵と渓流と</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60052>吠える稲妻、轟く激震</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60034>嵐龍天翔</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60023>水没林に集いしものたち</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60043>渓流の一番長い日</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://34.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>覇王降臨</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>４０８００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>３４００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>溶岩峡谷<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ６以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 01 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://35.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				覇王降臨
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>アカムトルムの討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://57.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>人望厚い国王<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>火山の奥地にある溶岩峡谷に覇王<BR>と呼ばれる飛竜がおるのだが、<BR>今にもそこから動きだそうと<BR>しておる。もし我が国を通る<BR>ことにでもなったら…。狩人よ！<BR>その力、余に貸してくれ！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=002></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60044.mib" DOWNLOAD CSUM=133 FSIZE=5168 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>3/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60032>覇王降臨</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#002 qname=m60044>集え！　砂原の最終決戦</a><BR><img height=1><BR>
			<tr><td height=85 valign=top>
				<img width=14 height=16><a href=#003 qname=m60042>ガーグァと卵と渓流と</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60052>吠える稲妻、轟く激震</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60034>嵐龍天翔</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60023>水没林に集いしものたち</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60043>渓流の一番長い日</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://28.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>集え！　砂原の最終決戦</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>３００００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>２５００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>砂原&lt;夜&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 02 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://29.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				集え！　砂原の最終決戦
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>すべての大型モンスターの狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>年若い将軍<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>かつての私であれば、この任務で<BR>命を落としていただろう。<BR>だが、今は違う。私と…君たち<BR>ギルドのハンターがいるのだ。<BR>恐れるものなどこの先にはない。<BR>さあ、進軍を開始しよう！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=003></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60042.mib" DOWNLOAD CSUM=10776 FSIZE=4704 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>3/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60032>覇王降臨</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60044>集え！　砂原の最終決戦</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#003 qname=m60042>ガーグァと卵と渓流と</a><BR><img height=1><BR>
			<tr><td height=68 valign=top>
				<img width=14 height=16><a href=#004 qname=m60052>吠える稲妻、轟く激震</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60034>嵐龍天翔</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60023>水没林に集いしものたち</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60043>渓流の一番長い日</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://30.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>ガーグァと卵と渓流と</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>７２００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>６００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>渓流&lt;夜&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 03 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://31.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				ガーグァと卵と渓流と
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ガーグァの卵１０個納品<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://46.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>卵好きのお姉さん<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>ガーグァの卵は天然モノに限る！<BR>私の美食魂にかけて、これだけは<BR>譲れないの。さらに言わせてもら<BR>うなら、渓流産の卵しか口にした<BR>くないわ。ああ、待ちきれない！<BR>はやく卵を持ってきて！<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=004></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60052.mib" DOWNLOAD CSUM=59844 FSIZE=4564 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>3/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60032>覇王降臨</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60044>集え！　砂原の最終決戦</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60042>ガーグァと卵と渓流と</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#004 qname=m60052>吠える稲妻、轟く激震</a><BR><img height=1><BR>
			<tr><td height=51 valign=top>
				<img width=14 height=16><a href=#005 qname=m60034>嵐龍天翔</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60023>水没林に集いしものたち</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60043>渓流の一番長い日</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://32.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>吠える稲妻、轟く激震</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>１５０００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>１２５０ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>渓流&lt;昼&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 04 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://33.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				吠える稲妻、轟く激震
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>ジンオウガ１頭と<BR>ドボルベルク１頭の狩猟<BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>山菜採りの老人<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>渓流でのんびり山菜採りをして<BR>おったら、突然の雷鳴と地震が<BR>あってたまげたわい。突然の天変<BR>地異に驚いて、採取道具を忘れて<BR>きてしもうた。ハンターさん、<BR>取りに行ってもらえんか？<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=005></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60034.mib" DOWNLOAD CSUM=28515 FSIZE=1240 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>3/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60032>覇王降臨</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60044>集え！　砂原の最終決戦</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60042>ガーグァと卵と渓流と</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60052>吠える稲妻、轟く激震</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#005 qname=m60034>嵐龍天翔</a><BR><img height=1><BR>
			<tr><td height=34 valign=top>
				<img width=14 height=16><a href=#006 qname=m60023>水没林に集いしものたち</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#007 qname=m60043>渓流の一番長い日</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://34.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>嵐龍天翔</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>３８４００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>３２００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>霊峰<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ６以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 05 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://35.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				嵐龍天翔
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>アマツマガツチの討伐<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://57.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>謎の赤衣の男<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>終焉の鐘は鳴らされた！<BR>厄災の龍と恐れられる伝説の<BR>龍アマツマガツチ。その暴風を<BR>前にハンター達はどこまで<BR>立ち向かえるのか！　人の希望と<BR>可能性を見せてくれたまえ。<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  06  1/2 ######## -->
<a name=006></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60023.mib" DOWNLOAD CSUM=32597 FSIZE=4816 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>3/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60032>覇王降臨</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60044>集え！　砂原の最終決戦</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60042>ガーグァと卵と渓流と</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60052>吠える稲妻、轟く激震</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60034>嵐龍天翔</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#006 qname=m60023>水没林に集いしものたち</a><BR><img height=1><BR>
			<tr><td height=17 valign=top>
				<img width=14 height=16><a href=#007 qname=m60043>渓流の一番長い日</a><BR><img height=1><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://28.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>水没林に集いしものたち</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>１８０００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>１５００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>水没林&lt;夜&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 06 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://29.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				水没林に集いしものたち
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>すべての大型モンスターの狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>交易船の船長<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>今度、重大な取引があるのに<BR>水没林にモンスターが集まって<BR>船が出航できないゼヨ。<BR>もし水没林を解放してくれたら、<BR>珍しい交易品をプレゼントする<BR>ので、どうか助けてくれゼヨ。<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
<!-- ########  07  1/2 ######## -->
<a name=007></a>
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 height=203 cellspacing=0>
<tr>
	<td width=230 height=203 align=center>
		<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
		<tr><td align=center>
			<table width=212 cellspacing=0>
			<form action="QUEST/m60043.mib" DOWNLOAD CSUM=25280 FSIZE=4908 method=post>
			<tr><td width=212 height=15 align=center>
				<table width=92 cellspacing=0 background=fpic://42.gif>
				<tr><td height=15 align=center valign=bottom>
					<font color=white>3/8</font>
				</table>
			<tr><td>
				<img width=14 height=16><a href=#001 qname=m60032>覇王降臨</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#002 qname=m60044>集え！　砂原の最終決戦</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#003 qname=m60042>ガーグァと卵と渓流と</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#004 qname=m60052>吠える稲妻、轟く激震</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#005 qname=m60034>嵐龍天翔</a><BR><img height=1><BR>
				<img width=14 height=16><a href=#006 qname=m60023>水没林に集いしものたち</a><BR><img height=1><BR>
			<tr><td bgcolor=green>
				<img width=14 height=16><a href=#007 qname=m60043>渓流の一番長い日</a><BR><img height=1><BR>
			<tr><td height=0 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
			</form>
			</table>
		</td></tr>
		</table>
	</td>
	<td width=250>
		<table width=248 height=197 cellspacing=0 cellpadding=0 background=fpic://28.gif>
		<tr>
			<td width=248 height=44 align=center valign=bottom colspan=3><img width=10>渓流の一番長い日</td>
		</tr>
		<tr>
			<td width=38></td>
			<td width=182>
				<table width=182 cellspacing=0>
				<tr>
					<td height=123 valign=top>
						<img height=21><font color=#1D3C8D>報酬金　 </font>３００００ｚ<br>
						<img height=16><font color=#1D3C8D>契約金　 </font>２５００ｚ<br>
						<img height=16><font color=#1D3C8D>制限時間 </font>５０分<br>
						<img height=16><font color=#1D3C8D>指定地　 </font>渓流&lt;夜&gt;<br>
						<img height=16><font color=#1D3C8D>受注・参加条件</font><br>
						<img height=16>ＨＲ４以上<BR><BR>
					</td>
				<tr>
				</table>
			</td>
			<td width=21></td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://08.gif width=480 height=22></td></tr></table>
<!--####### 07 2/2 #######-->
<img ANIME=129 src=fpic://53.gif width=231 height=47 alt="Event"><br>
<table width=480 cellspacing=0>
<tr>
	<td width=5></td>
	<td width=475 height=203 align=center>
	<table width=472 height=197 cellpadding=0 cellspacing=0 border=0>
	<tr>
	<td width=236 height=197 background=fpic://29.gif>
		<TABLE width=233 cellspacing=0 cellpadding=0>
		<tr>
			<td width=22></td>
			<td height=44 align=center valign=bottom >
				渓流の一番長い日
			</td>
			<td width=4></td>
		</tr>
		<tr>
			<td width=22 height=153 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　成功条件</font><br>
				<img height=16>すべての大型モンスターの狩猟<BR><BR><BR>
				<img height=16><font color=#1D3C8D>　失敗条件</font><br>
				<img height=16>報酬金ゼロ<BR>タイムアップ<BR>
			</TD>
			<td width=4></td>
		</tr>
		</TABLE>
	</td>
	<td width=236 background=fpic://50.gif>
		<TABLE cellspacing=0 cellpadding=0>
		<tr>
			<td height=45 align=center valign=bottom colspan=3>
				<font color=#1D3C8D>クエストＬＶ</font><font color=#AB001C>★★★★★★★★</font><BR>
			</td>
		</tr>
		<tr>
			<td width=10 height=152 ></td>
			<TD width=210 valign=top>
				<img height=20><font color=#1D3C8D>　依頼主　</font>ユクモ村の村長<BR>
				<img height=16><font color=#1D3C8D>　依頼内容</font><BR>
				<img height=16>感じませんか、このピリピリと<BR>張り詰めた空気…渓流に何か荒々<BR>しい気が漂っています。わたくし<BR>不安で堪りませんの…、ハンター<BR>様、是非渓流に赴いて、この気を<BR>鎮めていただけませんか。<BR>
			</TD>
			<td width=16></td>
		</tr>
		</TABLE>
	</td>
	</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=130 src=fpic://08.gif width=480 height=22></td></tr></table>
</body>
</html>
