<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:8",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=fpic://03.gif>
<basefont size=1>
<!-- ########  01  1/2 ######## -->
<a name=01></a>
<table width=480 height=250 cellspacing=0 border=0>
<tr>
<td width=233>
<table width=233 cellspacing=0>
<tr><td><img src=fpic://56.gif width=185 height=47 alt="Otomo">
<tr><td width=233 height=203 align=center>
<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
<tr><td align=center>
<table width=212 cellspacing=0>
<form action="OTOMO/o00011.dlo" ODOWNLOAD CSUM=23753 FSIZE=192 method=post>
<tr><td width=212 height=15 align=center>
<table width=92 cellspacing=0 background=fpic://42.gif>
<tr><td height=15 align=center valign=bottom>
1/1
</table>
<tr><td bgcolor=green>
<img width=14 height=16><a href=#01 qname=o00011>SEAMOさんのコシーモ</a><BR><img height=1><BR>
<tr><td height=102 valign=top>
<img width=14 height=16><a href=#02 qname=o00003>ハギーのハギとこルー</a><BR><img height=1><BR>
<img width=14 height=16><a href=#03 qname=o00006>ピエール瀧さんのピエルー</a><BR><img height=1><BR>
<img width=14 height=16><a href=#04 qname=o00010>後藤真希さんのｍａｋｉ</a><BR><img height=1><BR>
<img width=14 height=16><a href=#05 qname=o00005>井上聡さんのｕｅ．</a><BR><img height=1><BR>
<BR>
<BR>
<input type=image src="" name=submit width=0 height=0>
</form>
</table>
</td></tr></table>
</td></tr></table>
</td>
<td width=247 height=250 align=center>
<table width=230 height=236 cellspacing=0 cellpadding=0 background=fpic://59.png>
<tr>
<td width=10></td>
<td width=220>
<img height=15><font color=#DFB842>SEAMOさんのコシーモ</font><br>
<img height=27>　　コシーモ　　<img width=10><img src=fpic://49.gif width=89 height=18><br>
<img height=21><font color=#4682D8>ＬＶ　　　　</font><img width=21>　２０<br>
<img height=16><font color=#4682D8>初代旦那さん</font> ＳＥＡＭＯ<br>
<img height=16><font color=#4682D8>毛並み　　　</font> 白<br>
<img height=16><font color=#4682D8>なつき度　　</font> <img ANIME=132 src=fpic://39.gif width=73 height=13 12><br>
<img height=20><font color=#4682D8>攻撃力　　　</font><img width=21>184<br>
<img height=16><font color=#4682D8>防御力　　　</font><img width=21>190<br>
<img height=16><font color=#4682D8>攻撃方法　　</font> ブーメランのみ<br>
<img height=16><font color=#4682D8>標的傾向　　</font> 大型優先<br>
<img height=16><font color=#4682D8>性格　　　　</font> こざかしい<br>
<img height=16><font color=#4682D8>コメント</font><br>
<img height=17 width=7>毒関係はまかせてほしいなり！<br>
</td>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://11.gif width=480 height=22></td></tr></table>
<!####### 01 2/2 #######-->
<table width=480 height=250 cellspacing=0 border=0>
<tr>
<td width=233>
<table width=233 cellspacing=0>
<tr><td><img src=fpic://56.gif width=185 height=47 alt="Otomo">
<tr><td width=233 height=203 align=center>
<table width=226 219 height=139 border=0 cellspacing=0 background=fpic://41.gif>
<tr><td align=center>
<table width=212 205 cellspacing=0>
<form action="OTOMO/o00011.dlo" ODOWNLOAD CSUM=23753 FSIZE=192 method=post>
<tr><td width=212 height=15 align=center>
<table width=92 cellspacing=0 background=fpic://42.gif>
<tr><td height=15 align=center valign=bottom>
1/1
</table>
<tr><td bgcolor=green>
<img width=14 height=16><a href=#01 qname=o00011>SEAMOさんのコシーモ</a><BR><img height=1><BR>
<tr><td height=102 valign=top>
<img width=14 height=16><a href=#02 qname=o00003>ハギーのハギとこルー</a><BR><img height=1><BR>
<img width=14 height=16><a href=#03 qname=o00006>ピエール瀧さんのピエルー</a><BR><img height=1><BR>
<img width=14 height=16><a href=#04 qname=o00010>後藤真希さんのｍａｋｉ</a><BR><img height=1><BR>
<img width=14 height=16><a href=#05 qname=o00005>井上聡さんのｕｅ．</a><BR><img height=1><BR>
<BR>
<BR>
<input type=image src="" name=submit width=0 height=0>
</form>
</table>
</td></tr></table>
</td></tr></table>
</td>
<td width=247 height=250 align=center>
<table width=230 height=236 cellspacing=0 cellpadding=0 background=fpic://60.png>
<tr>
<td width=10></td>
<td width=220>
<img height=15><font color=#DFB842>SEAMOさんのコシーモ</font><br>
<img height=27>　　コシーモ　　<img width=10><img src=fpic://49.gif width=89 height=18><br>
<img height=21 23><font color=#4682D8>能力ボーナス</font><br>
</td>
<tr>
<td colspan=2 height=26 align=center><table cellspacing=0><tr><td width=216 height=18 align=center valign=center background=fpic://47.gif>なし</table></td>
<tr>
<td width=10></td>
<td>
<img height=16 14><font color=#4682D8>発動スキル　　　　スキルレベル</font><br>
<img height=20 18>状態異常攻撃【毒】　　<img ANIME=130 src=fpic://48.gif width=48 height=11><br>
<img height=20 18>状態異常攻撃強化の術　<img ANIME=129 src=fpic://48.gif width=48 height=11><br>
<img height=20 18>解毒・消臭笛の術　　　<img ANIME=133 src=fpic://48.gif width=48 height=11><br>
</td>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://11.gif width=480 height=22></td></tr></table>
<!-- ########  02  1/2 ######## -->
<a name=02></a>
<table width=480 height=250 cellspacing=0 border=0>
<tr>
<td width=233>
<table width=233 cellspacing=0>
<tr><td><img src=fpic://56.gif width=185 height=47 alt="Otomo">
<tr><td width=233 height=203 align=center>
<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
<tr><td align=center>
<table width=212 cellspacing=0>
<form action="OTOMO/o00003.dlo" ODOWNLOAD CSUM=24861 FSIZE=192 method=post>
<tr><td width=212 height=15 align=center>
<table width=92 cellspacing=0 background=fpic://42.gif>
<tr><td height=15 align=center valign=bottom>
1/1
</table>
<tr><td>
<img width=14 height=16><a href=#01 qname=o00011>SEAMOさんのコシーモ</a><BR><img height=1><BR>
<tr><td bgcolor=green>
<img width=14 height=16><a href=#02 qname=o00003>ハギーのハギとこルー</a><BR><img height=1><BR>
<tr><td height=85 valign=top>
<img width=14 height=16><a href=#03 qname=o00006>ピエール瀧さんのピエルー</a><BR><img height=1><BR>
<img width=14 height=16><a href=#04 qname=o00010>後藤真希さんのｍａｋｉ</a><BR><img height=1><BR>
<img width=14 height=16><a href=#05 qname=o00005>井上聡さんのｕｅ．</a><BR><img height=1><BR>
<BR>
<BR>
<input type=image src="" name=submit width=0 height=0>
</form>
</table>
</td></tr></table>
</td></tr></table>
</td>
<td width=247 height=250 align=center>
<table width=230 height=236 cellspacing=0 cellpadding=0 background=fpic://59.png>
<tr>
<td width=10></td>
<td width=220>
<img height=15><font color=#DFB842>ハギーのハギとこルー</font><br>
<img height=27>　　ハギとこルー<img width=10><img src=fpic://49.gif width=89 height=18><br>
<img height=21><font color=#4682D8>ＬＶ　　　　</font><img width=21>　１<br>
<img height=16><font color=#4682D8>初代旦那さん</font> ハギー<br>
<img height=16><font color=#4682D8>毛並み　　　</font> メラルー<br>
<img height=16><font color=#4682D8>なつき度　　</font><br>
<img height=20><font color=#4682D8>攻撃力　　　</font><img width=21> 34<br>
<img height=16><font color=#4682D8>防御力　　　</font><img width=21> 21<br>
<img height=16><font color=#4682D8>攻撃方法　　</font> 爆弾のみ<br>
<img height=16><font color=#4682D8>標的傾向　　</font> 大型一筋<br>
<img height=16><font color=#4682D8>性格　　　　</font> こざかしい<br>
<img height=16><font color=#4682D8>コメント</font><br>
<img height=17 width=7>ハギーのとこトンやってみよう<br>
</td>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://11.gif width=480 height=22></td></tr></table>
<!####### 02 2/2 #######-->
<table width=480 height=250 cellspacing=0 border=0>
<tr>
<td width=233>
<table width=233 cellspacing=0>
<tr><td><img src=fpic://56.gif width=185 height=47 alt="Otomo">
<tr><td width=233 height=203 align=center>
<table width=226 219 height=139 border=0 cellspacing=0 background=fpic://41.gif>
<tr><td align=center>
<table width=212 205 cellspacing=0>
<form action="OTOMO/o00003.dlo" ODOWNLOAD CSUM=24861 FSIZE=192 method=post>
<tr><td width=212 height=15 align=center>
<table width=92 cellspacing=0 background=fpic://42.gif>
<tr><td height=15 align=center valign=bottom>
1/1
</table>
<tr><td>
<img width=14 height=16><a href=#01 qname=o00011>SEAMOさんのコシーモ</a><BR><img height=1><BR>
<tr><td bgcolor=green>
<img width=14 height=16><a href=#02 qname=o00003>ハギーのハギとこルー</a><BR><img height=1><BR>
<tr><td height=85 valign=top>
<img width=14 height=16><a href=#03 qname=o00006>ピエール瀧さんのピエルー</a><BR><img height=1><BR>
<img width=14 height=16><a href=#04 qname=o00010>後藤真希さんのｍａｋｉ</a><BR><img height=1><BR>
<img width=14 height=16><a href=#05 qname=o00005>井上聡さんのｕｅ．</a><BR><img height=1><BR>
<BR>
<BR>
<input type=image src="" name=submit width=0 height=0>
</form>
</table>
</td></tr></table>
</td></tr></table>
</td>
<td width=247 height=250 align=center>
<table width=230 height=236 cellspacing=0 cellpadding=0 background=fpic://60.png>
<tr>
<td width=10></td>
<td width=220>
<img height=15><font color=#DFB842>ハギーのハギとこルー</font><br>
<img height=27>　　ハギとこルー<img width=10><img src=fpic://49.gif width=89 height=18><br>
<img height=21 23><font color=#4682D8>能力ボーナス</font><br>
</td>
<tr>
<td colspan=2 height=26 align=center><table cellspacing=0><tr><td width=216 height=18 align=center valign=center background=fpic://47.gif>特別：雷耐性上昇　体力減少</table></td>
<tr>
<td width=10></td>
<td>
<img height=16 14><font color=#4682D8>発動スキル　　　　スキルレベル</font><br>
</td>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://11.gif width=480 height=22></td></tr></table>
<!-- ########  03  1/2 ######## -->
<a name=03></a>
<table width=480 height=250 cellspacing=0 border=0>
<tr>
<td width=233>
<table width=233 cellspacing=0>
<tr><td><img src=fpic://56.gif width=185 height=47 alt="Otomo">
<tr><td width=233 height=203 align=center>
<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
<tr><td align=center>
<table width=212 cellspacing=0>
<form action="OTOMO/o00006.dlo" ODOWNLOAD CSUM=23074 FSIZE=192 method=post>
<tr><td width=212 height=15 align=center>
<table width=92 cellspacing=0 background=fpic://42.gif>
<tr><td height=15 align=center valign=bottom>
1/1
</table>
<tr><td>
<img width=14 height=16><a href=#01 qname=o00011>SEAMOさんのコシーモ</a><BR><img height=1><BR>
<img width=14 height=16><a href=#02 qname=o00003>ハギーのハギとこルー</a><BR><img height=1><BR>
<tr><td bgcolor=green>
<img width=14 height=16><a href=#03 qname=o00006>ピエール瀧さんのピエルー</a><BR><img height=1><BR>
<tr><td height=68 valign=top>
<img width=14 height=16><a href=#04 qname=o00010>後藤真希さんのｍａｋｉ</a><BR><img height=1><BR>
<img width=14 height=16><a href=#05 qname=o00005>井上聡さんのｕｅ．</a><BR><img height=1><BR>
<BR>
<BR>
<input type=image src="" name=submit width=0 height=0>
</form>
</table>
</td></tr></table>
</td></tr></table>
</td>
<td width=247 height=250 align=center>
<table width=230 height=236 cellspacing=0 cellpadding=0 background=fpic://59.png>
<tr>
<td width=10></td>
<td width=220>
<img height=15><font color=#DFB842>ピエール瀧さんのピエルー</font><br>
<img height=27>　　ピエルー　　<img width=10><img src=fpic://49.gif width=89 height=18><br>
<img height=21><font color=#4682D8>ＬＶ　　　　</font><img width=21>　２０<br>
<img height=16><font color=#4682D8>初代旦那さん</font> ピエールたき<br>
<img height=16><font color=#4682D8>毛並み　　　</font> ハッカ<br>
<img height=16><font color=#4682D8>なつき度　　</font> <img ANIME=132 src=fpic://39.gif width=73 height=13 12><br>
<img height=20><font color=#4682D8>攻撃力　　　</font><img width=21>327<br>
<img height=16><font color=#4682D8>防御力　　　</font><img width=21>197<br>
<img height=16><font color=#4682D8>攻撃方法　　</font> 近接のみ<br>
<img height=16><font color=#4682D8>標的傾向　　</font> バランス<br>
<img height=16><font color=#4682D8>性格　　　　</font> チャンス派<br>
<img height=16><font color=#4682D8>コメント</font><br>
<img height=17 width=7>ハロにちわ～。連れてって～！<br>
</td>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://11.gif width=480 height=22></td></tr></table>
<!####### 03 2/2 #######-->
<table width=480 height=250 cellspacing=0 border=0>
<tr>
<td width=233>
<table width=233 cellspacing=0>
<tr><td><img src=fpic://56.gif width=185 height=47 alt="Otomo">
<tr><td width=233 height=203 align=center>
<table width=226 219 height=139 border=0 cellspacing=0 background=fpic://41.gif>
<tr><td align=center>
<table width=212 205 cellspacing=0>
<form action="OTOMO/o00006.dlo" ODOWNLOAD CSUM=23074 FSIZE=192 method=post>
<tr><td width=212 height=15 align=center>
<table width=92 cellspacing=0 background=fpic://42.gif>
<tr><td height=15 align=center valign=bottom>
1/1
</table>
<tr><td>
<img width=14 height=16><a href=#01 qname=o00011>SEAMOさんのコシーモ</a><BR><img height=1><BR>
<img width=14 height=16><a href=#02 qname=o00003>ハギーのハギとこルー</a><BR><img height=1><BR>
<tr><td bgcolor=green>
<img width=14 height=16><a href=#03 qname=o00006>ピエール瀧さんのピエルー</a><BR><img height=1><BR>
<tr><td height=68 valign=top>
<img width=14 height=16><a href=#04 qname=o00010>後藤真希さんのｍａｋｉ</a><BR><img height=1><BR>
<img width=14 height=16><a href=#05 qname=o00005>井上聡さんのｕｅ．</a><BR><img height=1><BR>
<BR>
<BR>
<input type=image src="" name=submit width=0 height=0>
</form>
</table>
</td></tr></table>
</td></tr></table>
</td>
<td width=247 height=250 align=center>
<table width=230 height=236 cellspacing=0 cellpadding=0 background=fpic://60.png>
<tr>
<td width=10></td>
<td width=220>
<img height=15><font color=#DFB842>ピエール瀧さんのピエルー</font><br>
<img height=27>　　ピエルー　　<img width=10><img src=fpic://49.gif width=89 height=18><br>
<img height=21 23><font color=#4682D8>能力ボーナス</font><br>
</td>
<tr>
<td colspan=2 height=26 align=center><table cellspacing=0><tr><td width=216 height=18 align=center valign=center background=fpic://47.gif>なし</table></td>
<tr>
<td width=10></td>
<td>
<img height=16 14><font color=#4682D8>発動スキル　　　　スキルレベル</font><br>
<img height=20 18>ぶんどり強化の術　　　<img ANIME=129 src=fpic://48.gif width=48 height=11><br>
<img height=20 18>シビレ罠の術　　　　　<img ANIME=130 src=fpic://48.gif width=48 height=11><br>
<img height=20 18>会心攻撃強化の術　　　<img ANIME=128 src=fpic://48.gif width=48 height=11><br>
</td>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://11.gif width=480 height=22></td></tr></table>
<!-- ########  04  1/2 ######## -->
<a name=04></a>
<table width=480 height=250 cellspacing=0 border=0>
<tr>
<td width=233>
<table width=233 cellspacing=0>
<tr><td><img src=fpic://56.gif width=185 height=47 alt="Otomo">
<tr><td width=233 height=203 align=center>
<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
<tr><td align=center>
<table width=212 cellspacing=0>
<form action="OTOMO/o00010.dlo" ODOWNLOAD CSUM=22845 FSIZE=192 method=post>
<tr><td width=212 height=15 align=center>
<table width=92 cellspacing=0 background=fpic://42.gif>
<tr><td height=15 align=center valign=bottom>
1/1
</table>
<tr><td>
<img width=14 height=16><a href=#01 qname=o00011>SEAMOさんのコシーモ</a><BR><img height=1><BR>
<img width=14 height=16><a href=#02 qname=o00003>ハギーのハギとこルー</a><BR><img height=1><BR>
<img width=14 height=16><a href=#03 qname=o00006>ピエール瀧さんのピエルー</a><BR><img height=1><BR>
<tr><td bgcolor=green>
<img width=14 height=16><a href=#04 qname=o00010>後藤真希さんのｍａｋｉ</a><BR><img height=1><BR>
<tr><td height=51 valign=top>
<img width=14 height=16><a href=#05 qname=o00005>井上聡さんのｕｅ．</a><BR><img height=1><BR>
<BR>
<BR>
<input type=image src="" name=submit width=0 height=0>
</form>
</table>
</td></tr></table>
</td></tr></table>
</td>
<td width=247 height=250 align=center>
<table width=230 height=236 cellspacing=0 cellpadding=0 background=fpic://59.png>
<tr>
<td width=10></td>
<td width=220>
<img height=15><font color=#DFB842>後藤真希さんのｍａｋｉ</font><br>
<img height=27>　　ｍａｋｉ　　<img width=10><img src=fpic://49.gif width=89 height=18><br>
<img height=21><font color=#4682D8>ＬＶ　　　　</font><img width=21>　１４<br>
<img height=16><font color=#4682D8>初代旦那さん</font> ＭＡＫＩ<br>
<img height=16><font color=#4682D8>毛並み　　　</font> 白<br>
<img height=16><font color=#4682D8>なつき度　　</font> <img ANIME=131 src=fpic://39.gif width=73 height=13 12><br>
<img height=20><font color=#4682D8>攻撃力　　　</font><img width=21>147<br>
<img height=16><font color=#4682D8>防御力　　　</font><img width=21>122<br>
<img height=16><font color=#4682D8>攻撃方法　　</font> 爆弾のみ<br>
<img height=16><font color=#4682D8>標的傾向　　</font> 小型優先<br>
<img height=16><font color=#4682D8>性格　　　　</font> 勇敢<br>
<img height=16><font color=#4682D8>コメント</font><br>
<img height=17 width=7>可愛がると喜びます！<br>
</td>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://11.gif width=480 height=22></td></tr></table>
<!####### 04 2/2 #######-->
<table width=480 height=250 cellspacing=0 border=0>
<tr>
<td width=233>
<table width=233 cellspacing=0>
<tr><td><img src=fpic://56.gif width=185 height=47 alt="Otomo">
<tr><td width=233 height=203 align=center>
<table width=226 219 height=139 border=0 cellspacing=0 background=fpic://41.gif>
<tr><td align=center>
<table width=212 205 cellspacing=0>
<form action="OTOMO/o00010.dlo" ODOWNLOAD CSUM=22845 FSIZE=192 method=post>
<tr><td width=212 height=15 align=center>
<table width=92 cellspacing=0 background=fpic://42.gif>
<tr><td height=15 align=center valign=bottom>
1/1
</table>
<tr><td>
<img width=14 height=16><a href=#01 qname=o00011>SEAMOさんのコシーモ</a><BR><img height=1><BR>
<img width=14 height=16><a href=#02 qname=o00003>ハギーのハギとこルー</a><BR><img height=1><BR>
<img width=14 height=16><a href=#03 qname=o00006>ピエール瀧さんのピエルー</a><BR><img height=1><BR>
<tr><td bgcolor=green>
<img width=14 height=16><a href=#04 qname=o00010>後藤真希さんのｍａｋｉ</a><BR><img height=1><BR>
<tr><td height=51 valign=top>
<img width=14 height=16><a href=#05 qname=o00005>井上聡さんのｕｅ．</a><BR><img height=1><BR>
<BR>
<BR>
<input type=image src="" name=submit width=0 height=0>
</form>
</table>
</td></tr></table>
</td></tr></table>
</td>
<td width=247 height=250 align=center>
<table width=230 height=236 cellspacing=0 cellpadding=0 background=fpic://60.png>
<tr>
<td width=10></td>
<td width=220>
<img height=15><font color=#DFB842>後藤真希さんのｍａｋｉ</font><br>
<img height=27>　　ｍａｋｉ　　<img width=10><img src=fpic://49.gif width=89 height=18><br>
<img height=21 23><font color=#4682D8>能力ボーナス</font><br>
</td>
<tr>
<td colspan=2 height=26 align=center><table cellspacing=0><tr><td width=216 height=18 align=center valign=center background=fpic://47.gif>なし</table></td>
<tr>
<td width=10></td>
<td>
<img height=16 14><font color=#4682D8>発動スキル　　　　スキルレベル</font><br>
<img height=20 18>泥・雪だるま早割り術　<img ANIME=138 src=fpic://48.gif width=48 height=11><br>
<img height=20 18>鬼人笛の術　　　　　　<img ANIME=134 src=fpic://48.gif width=48 height=11><br>
<img height=20 18>回復笛の術　　　　　　<img ANIME=134 src=fpic://48.gif width=48 height=11><br>
<img height=20 18>解毒・消臭笛の術　　　<img ANIME=133 src=fpic://48.gif width=48 height=11><br>
</td>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://11.gif width=480 height=22></td></tr></table>
<!-- ########  05  1/2 ######## -->
<a name=05></a>
<table width=480 height=250 cellspacing=0 border=0>
<tr>
<td width=233>
<table width=233 cellspacing=0>
<tr><td><img src=fpic://56.gif width=185 height=47 alt="Otomo">
<tr><td width=233 height=203 align=center>
<table width=226 height=139 border=0 cellspacing=0 background=fpic://41.gif>
<tr><td align=center>
<table width=212 cellspacing=0>
<form action="OTOMO/o00005.dlo" ODOWNLOAD CSUM=26036 FSIZE=192 method=post>
<tr><td width=212 height=15 align=center>
<table width=92 cellspacing=0 background=fpic://42.gif>
<tr><td height=15 align=center valign=bottom>
1/1
</table>
<tr><td>
<img width=14 height=16><a href=#01 qname=o00011>SEAMOさんのコシーモ</a><BR><img height=1><BR>
<img width=14 height=16><a href=#02 qname=o00003>ハギーのハギとこルー</a><BR><img height=1><BR>
<img width=14 height=16><a href=#03 qname=o00006>ピエール瀧さんのピエルー</a><BR><img height=1><BR>
<img width=14 height=16><a href=#04 qname=o00010>後藤真希さんのｍａｋｉ</a><BR><img height=1><BR>
<tr><td bgcolor=green>
<img width=14 height=16><a href=#05 qname=o00005>井上聡さんのｕｅ．</a><BR><img height=1><BR>
<tr><td height=34 valign=top>
<BR>
<BR>
<input type=image src="" name=submit width=0 height=0>
</form>
</table>
</td></tr></table>
</td></tr></table>
</td>
<td width=247 height=250 align=center>
<table width=230 height=236 cellspacing=0 cellpadding=0 background=fpic://59.png>
<tr>
<td width=10></td>
<td width=220>
<img height=15><font color=#DFB842>井上聡さんのｕｅ．</font><br>
<img height=27>　　ｕｅ．　　　<img width=10><img src=fpic://49.gif width=89 height=18><br>
<img height=21><font color=#4682D8>ＬＶ　　　　</font><img width=21>　２０<br>
<img height=16><font color=#4682D8>初代旦那さん</font> ｉｎｏ．<br>
<img height=16><font color=#4682D8>毛並み　　　</font> アイルー<br>
<img height=16><font color=#4682D8>なつき度　　</font> <img ANIME=132 src=fpic://39.gif width=73 height=13 12><br>
<img height=20><font color=#4682D8>攻撃力　　　</font><img width=21>334<br>
<img height=16><font color=#4682D8>防御力　　　</font><img width=21>190<br>
<img height=16><font color=#4682D8>攻撃方法　　</font> ブーメランのみ<br>
<img height=16><font color=#4682D8>標的傾向　　</font> 大型一筋<br>
<img height=16><font color=#4682D8>性格　　　　</font> 勇敢<br>
<img height=16><font color=#4682D8>コメント</font><br>
<img height=17 width=7>ｉｎｏ．は頼りになるニャ！！<br>
</td>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://11.gif width=480 height=22></td></tr></table>
<!####### 05 2/2 #######-->
<table width=480 height=250 cellspacing=0 border=0>
<tr>
<td width=233>
<table width=233 cellspacing=0>
<tr><td><img src=fpic://56.gif width=185 height=47 alt="Otomo">
<tr><td width=233 height=203 align=center>
<table width=226 219 height=139 border=0 cellspacing=0 background=fpic://41.gif>
<tr><td align=center>
<table width=212 205 cellspacing=0>
<form action="OTOMO/o00005.dlo" ODOWNLOAD CSUM=26036 FSIZE=192 method=post>
<tr><td width=212 height=15 align=center>
<table width=92 cellspacing=0 background=fpic://42.gif>
<tr><td height=15 align=center valign=bottom>
1/1
</table>
<tr><td>
<img width=14 height=16><a href=#01 qname=o00011>SEAMOさんのコシーモ</a><BR><img height=1><BR>
<img width=14 height=16><a href=#02 qname=o00003>ハギーのハギとこルー</a><BR><img height=1><BR>
<img width=14 height=16><a href=#03 qname=o00006>ピエール瀧さんのピエルー</a><BR><img height=1><BR>
<img width=14 height=16><a href=#04 qname=o00010>後藤真希さんのｍａｋｉ</a><BR><img height=1><BR>
<tr><td bgcolor=green>
<img width=14 height=16><a href=#05 qname=o00005>井上聡さんのｕｅ．</a><BR><img height=1><BR>
<tr><td height=34 valign=top>
<BR>
<BR>
<input type=image src="" name=submit width=0 height=0>
</form>
</table>
</td></tr></table>
</td></tr></table>
</td>
<td width=247 height=250 align=center>
<table width=230 height=236 cellspacing=0 cellpadding=0 background=fpic://60.png>
<tr>
<td width=10></td>
<td width=220>
<img height=15><font color=#DFB842>井上聡さんのｕｅ．</font><br>
<img height=27>　　ｕｅ．　　　<img width=10><img src=fpic://49.gif width=89 height=18><br>
<img height=21 23><font color=#4682D8>能力ボーナス</font><br>
</td>
<tr>
<td colspan=2 height=26 align=center><table cellspacing=0><tr><td width=216 height=18 align=center valign=center background=fpic://47.gif>なし</table></td>
<tr>
<td width=10></td>
<td>
<img height=16 14><font color=#4682D8>発動スキル　　　　スキルレベル</font><br>
<img height=20 18>状態異常攻撃【麻痺】　<img ANIME=131 src=fpic://48.gif width=48 height=11><br>
<img height=20 18>状態異常攻撃強化の術　<img ANIME=129 src=fpic://48.gif width=48 height=11><br>
</td>
</table>
</td></tr></table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=129 src=fpic://11.gif width=480 height=22></td></tr></table>
</body>
</html>
