<html>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:6",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=fpic://03.gif>
<basefont size=1>
<B>
<img ANIME=128 src=fpic://53.gif width=231 height=47 alt="Quest"><br>
<table width=480 height=203 cellspacing=0 cellpadding=0 border=0>
<tr>
		<form action="DL_MENU.PHP" method=get>
	<td width=240 height=196 align=center valign=center>
		 <input type=hidden name=pg_no value=0>
		 <input ANIME=1 type=image src=fpic://38.gif name=submit width=189 height=161 alt="Event">
	</td>
		</form>
		<form action="DL_CMENU.PHP" method=get>
	<td width=240 height=196 align=center valign=center>
		 <input type=hidden name=pg_no value=0>
		 <input ANIME=1 type=image src=fpic://12.gif name=submit width=189 height=161 alt="Challenge">
	</td>
		</form>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=22><img ANIME=128 src=fpic://08.gif width=480 height=22></td></tr></table>
</body>
</html>
