<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=Shift_JIS'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=OFF",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:1",
		"MOVE_CHAR=fpic://51.gif,57,71,7,,20,,403,137",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,-48,-32",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30, 48,-64",
		"MOVE_CHAR=fpic://44.gif,56,56,6,70,10,30,144,  0",
		"MOVE_CHAR=fpic://43.gif,64,64,6,80,11,30,240,-32",
		"ASSEMBLE_BG=ON",
		"OTOMO_TITLE=002:東京ドームのあとらく",
		"OTOMO_TITLE=003:ハギーのハギとこルー",
		"OTOMO_TITLE=004:三浦春馬さんのペコ",
		"OTOMO_TITLE=005:井上聡さんのｕｅ．",
		"OTOMO_TITLE=006:ピエール瀧さんのピエルー",
		"OTOMO_TITLE=007:NAMJATOWNのナジャヴ",
		"OTOMO_TITLE=008:NAMJATOWNのナジャミー",
		"OTOMO_TITLE=009:NAMJATOWNのもののけたま",
		"OTOMO_TITLE=010:後藤真希さんのｍａｋｉ",
		"OTOMO_TITLE=011:SEAMOさんのコシーモ",
		"OTOMO_TITLE=012:モンハン部のマニャ",
		"OTOMO_TITLE=013:サンリオのピューロ",
		"OTOMO_TITLE=014:信州渋温泉のシブザルー",
		"OTOMO_TITLE=015:USJのユニバー",
		"OTOMO_TITLE=016:KODANSHAのゲイノウブ",
		"OTOMO_TITLE=017:岡田義徳さんの碧玉狩猫",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=fpic://03.gif>
<basefont size=1>
<table width=480 height=250 cellspacing=0 cellpadding=0 border=0>
<tr>
	<td width=224>
	<table width=224 height=250 cellspacing=0 cellpadding=0 border=0>
	<tr>
		<td width=224 colspan=2>
			<img src=fpic://52.gif width=208 height=47 alt="Download Menu"><br>
		</td>
	</tr>
	<tr>
		<td>
		<table width=224 cellspacing=0 cellpadding=0>
			<form action="DL_SELECT.PHP" method=get><tr><td>
			 <input type=image ANIME=20 src=fpic://27.gif name=submit width=224 height=47 alt="Quest">
			</td></tr></form>
			<form action="DL_OTOMO.PHP" method=get><tr><td>
			 <input type=image ANIME=20 src=fpic://26.gif name=submit width=224 height=47 alt="Otomo">
			</td></tr></form>
			<form action="DL_BONUS.PHP" method=get><tr><td>
			 <input type=image ANIME=20 src=fpic://23.gif name=submit width=224 height=47 alt="Bonus">
			</td></tr></form>
			<form action="DB_INFO.PHP" method=get><tr><td>
			 <input type=image ANIME=20 src=fpic://25.gif  name=submit width=224 height=47 alt="Information"></a>
			 <input type=hidden name=pg_no value=0>
			</td></tr></form>
		</table>
		</td>
	</tr>
	</table>
	</td>
	<td width=256 valign=top align=right>
	<table width=250 height=250 border=0 cellspacing=0 cellpadding=0 29 background=fpic://24.gif>
		<tr>
			<td valign=top height=37 colspan=2></td>
		</tr>
		<tr>
			<td width=15 height=143></td>
			<td width=235 valign=top>
				　<font color=#4682d8>最新更新情報</font>　１２／０９<br>
				<BR>
				<img height=16>■クエスト<BR><img height=16>【最強への挑戦】<BR><img height=16>■特典<BR><img height=16>【プーギーの服】<BR><img height=16>を追加したのニャ！
			</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0 ><tr><td width=480 height=22 background=fpic://07.gif></td></tr></table>
</body>
</html>
