<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=3",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=3&pg_no=1",
		"RB_LINK=DB_INFO.PHP?lang=3&pg_no=3",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					26/10 Info. Mise à jour ②<BR>
				<tr><td>
					26/10 Info. Mise à jour ①<BR>
					19/10 Info. Mise à jour ②<BR>
					19/10 Info. Mise à jour ①<BR>
					12/10 Info. Mise à jour ②<BR>
					12/10 Info. Mise à jour ①<BR>
					5/10 Info. Mise à jour ④<BR>
					5/10 Info. Mise à jour ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>26/10 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Quête défi 8</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>26/10 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Quête défi 8】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Instructeur<BR>C'est moi, votre instructeur<BR>estimé. Cette fois il<BR>faudra affronter non pas<BR>un, mais deux Tigrex ! Ils<BR>sont intouchables sous<BR>l'effet de la colère, à<BR>vous de créer l'ouverture. <BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61008.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					26/10 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					26/10 Info. Mise à jour ①<BR>
				<tr><td>
					19/10 Info. Mise à jour ②<BR>
					19/10 Info. Mise à jour ①<BR>
					12/10 Info. Mise à jour ②<BR>
					12/10 Info. Mise à jour ①<BR>
					5/10 Info. Mise à jour ④<BR>
					5/10 Info. Mise à jour ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>26/10 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Piège volcanique !</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>26/10 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Piège volcanique !】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Homme cupide<BR>Je suis venu dans la Cein-<BR>ture volcanique chercher du<BR>minerai rare, mais j'ai un<BR>mauvais pressentiment...<BR>Vous devez le sentir aussi,<BR>comme un danger en<BR>approche. Allez vérifier !<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60006.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					26/10 Info. Mise à jour ②<BR>
					26/10 Info. Mise à jour ①<BR>
				<tr><td bgcolor=green>
					19/10 Info. Mise à jour ②<BR>
				<tr><td>
					19/10 Info. Mise à jour ①<BR>
					12/10 Info. Mise à jour ②<BR>
					12/10 Info. Mise à jour ①<BR>
					5/10 Info. Mise à jour ④<BR>
					5/10 Info. Mise à jour ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>19/10 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Quête défi 7</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>19/10 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Quête défi 7】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Instructeur<BR>C'est moi, votre instructeur<BR>estimé. Il y a toujours un<BR>chemin approprié pour<BR>chaque quête.<BR>Vous devriez être capable<BR>de le trouver à l'heure<BR>qu'il est !<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61007.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					26/10 Info. Mise à jour ②<BR>
					26/10 Info. Mise à jour ①<BR>
					19/10 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					19/10 Info. Mise à jour ①<BR>
				<tr><td>
					12/10 Info. Mise à jour ②<BR>
					12/10 Info. Mise à jour ①<BR>
					5/10 Info. Mise à jour ④<BR>
					5/10 Info. Mise à jour ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>19/10 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>L'ultime bataille</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>19/10 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【L'ultime bataille】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Héros lynien<BR>Voici un défi écrit pour<BR>tous les chasseurs, nya !<BR>Mes amis lyniens et moi<BR>feront souffrir tous ceux<BR>qui pénètrent dans l'arène.<BR>Seuls les plus braves <BR>peuvent nous affronter !<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60003.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					26/10 Info. Mise à jour ②<BR>
					26/10 Info. Mise à jour ①<BR>
					19/10 Info. Mise à jour ②<BR>
					19/10 Info. Mise à jour ①<BR>
				<tr><td bgcolor=green>
					12/10 Info. Mise à jour ②<BR>
				<tr><td>
					12/10 Info. Mise à jour ①<BR>
					5/10 Info. Mise à jour ④<BR>
					5/10 Info. Mise à jour ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>12/10 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Quête défi 6</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>12/10 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Quête défi 6】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Instructeur<BR>C'est moi, votre instructeur<BR>estimé. Le défi du<BR>jour concerne un<BR>Bulldrome ! Ne riez pas !<BR>Vous devriez savoir<BR>que les apparences sont<BR>souvent trompeuses.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61006.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					26/10 Info. Mise à jour ②<BR>
					26/10 Info. Mise à jour ①<BR>
					19/10 Info. Mise à jour ②<BR>
					19/10 Info. Mise à jour ①<BR>
					12/10 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					12/10 Info. Mise à jour ①<BR>
				<tr><td>
					5/10 Info. Mise à jour ④<BR>
					5/10 Info. Mise à jour ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>12/10 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Concert lumière & poison</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>12/10 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Concert lumière & poison】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Directeur de l'arène<BR>L'Arène ! L'endroit où mon-<BR>trer au monde vos talents !<BR>Préparez-vous à affronter<BR>non pas un mais deux<BR>mangeurs d'hommes volants,<BR>des Gypceros ! Montrez-nous<BR>votre force !<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60021.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					26/10 Info. Mise à jour ②<BR>
					26/10 Info. Mise à jour ①<BR>
					19/10 Info. Mise à jour ②<BR>
					19/10 Info. Mise à jour ①<BR>
					12/10 Info. Mise à jour ②<BR>
					12/10 Info. Mise à jour ①<BR>
				<tr><td bgcolor=green>
					5/10 Info. Mise à jour ④<BR>
				<tr><td>
					5/10 Info. Mise à jour ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>5/10 Info. Mise à jour ④</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise à jour<BR>inclura 2 nouveaux<BR>éléments bonus, miaou !<BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>5/10 Info. Mise à jour ④</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
Ces éléments bonus seront ajoutés.
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
<font color=orange>Chef Felyne errant:<BR>&nbsp;&nbsp;Orange<BR>Titre:<BR>&nbsp;&nbsp;Jumbo<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br></font>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/b00001.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					26/10 Info. Mise à jour ②<BR>
					26/10 Info. Mise à jour ①<BR>
					19/10 Info. Mise à jour ②<BR>
					19/10 Info. Mise à jour ①<BR>
					12/10 Info. Mise à jour ②<BR>
					12/10 Info. Mise à jour ①<BR>
					5/10 Info. Mise à jour ④<BR>
				<tr><td bgcolor=green>
					5/10 Info. Mise à jour ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>5/10 Info. Mise à jour ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Quête défi 5</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>5/10 Info. Mise à jour ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Quête défi 5】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Instructeur<BR>C'est moi, votre instructeur<BR>estimé. L'entraînement<BR>du jour concerne deux<BR>Ceanataur Shogun, mais il<BR>suffit d'en tuer un pour<BR>compléter la quête. Montrez-<BR>vous à la hauteur !<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61005.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
</body>
</html>
