<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=3",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=3&pg_no=4",
		"RB_LINK=DB_INFO.PHP?lang=3&pg_no=1",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					28/12 Info. Mise à jour<BR>
				<tr><td>
					21/12 Info. Mise à jour<BR>
					14/12 Info. Mise à jour<BR>
					7/12 Info. Mise à jour<BR>
					30/11 Info. Mise à jour ③<BR>
					30/11 Info. Mise à jour ②<BR>
					30/11 Info. Mise à jour ①<BR>
					23/11 Info. Mise à jour<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>28/12 Info. Mise à jour</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Furie sur terre et en l'air</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>28/12 Info. Mise à jour</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Furie sur terre et en l'air】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Chef Village Kokoto<BR>Cela faisait longtemps, mes<BR>amis... Voici mon défi pour<BR>vous ! Vaincre deux Wyvern<BR>Rathalos et Rathian géants.<BR>Avez-vous le niveau<BR>nécessaire pour les<BR>vaincre ?<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60022.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					28/12 Info. Mise à jour<BR>
				<tr><td bgcolor=green>
					21/12 Info. Mise à jour<BR>
				<tr><td>
					14/12 Info. Mise à jour<BR>
					7/12 Info. Mise à jour<BR>
					30/11 Info. Mise à jour ③<BR>
					30/11 Info. Mise à jour ②<BR>
					30/11 Info. Mise à jour ①<BR>
					23/11 Info. Mise à jour<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>21/12 Info. Mise à jour</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Le visiteur d'acier</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>21/12 Info. Mise à jour</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Le visiteur d'acier】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Maître de Guilde<BR>Alerte ! Alerte ! Un Kusha-<BR>la Daora marron approche<BR>de la ville ! Tous les<BR>chasseurs doivent venir ici<BR>le plus vite possible !<BR>Nous avons besoin de vous<BR>pour sauver la ville.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60025.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					28/12 Info. Mise à jour<BR>
					21/12 Info. Mise à jour<BR>
				<tr><td bgcolor=green>
					14/12 Info. Mise à jour<BR>
				<tr><td>
					7/12 Info. Mise à jour<BR>
					30/11 Info. Mise à jour ③<BR>
					30/11 Info. Mise à jour ②<BR>
					30/11 Info. Mise à jour ①<BR>
					23/11 Info. Mise à jour<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>14/12 Info. Mise à jour</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Le dieu doré du tonnerre</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>14/12 Info. Mise à jour</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Le dieu doré du tonnerre】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Directeur de l'arène<BR>C'est absolument terrible !<BR>Un énorme monstre noir<BR>s'est emparé de mon arène !<BR>Nous ne pouvons rien faire<BR>tant qu'il est là !<BR>Débarrassez-nous vite<BR>de lui !<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60019.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					28/12 Info. Mise à jour<BR>
					21/12 Info. Mise à jour<BR>
					14/12 Info. Mise à jour<BR>
				<tr><td bgcolor=green>
					7/12 Info. Mise à jour<BR>
				<tr><td>
					30/11 Info. Mise à jour ③<BR>
					30/11 Info. Mise à jour ②<BR>
					30/11 Info. Mise à jour ①<BR>
					23/11 Info. Mise à jour<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>7/12 Info. Mise à jour</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>L'antre du Remobra</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>7/12 Info. Mise à jour</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【L'antre du Remobra】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Directeur de l'arène<BR>L'Arène ! L'endroit où mon-<BR>trer au monde vos talents !<BR>Cette fois vos adversaires<BR>sont des Remobra volants !<BR>Il faudra du courage pour<BR>survivre à leur poison qui<BR>envahit l'arène !<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60018.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					28/12 Info. Mise à jour<BR>
					21/12 Info. Mise à jour<BR>
					14/12 Info. Mise à jour<BR>
					7/12 Info. Mise à jour<BR>
				<tr><td bgcolor=green>
					30/11 Info. Mise à jour ③<BR>
				<tr><td>
					30/11 Info. Mise à jour ②<BR>
					30/11 Info. Mise à jour ①<BR>
					23/11 Info. Mise à jour<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>30/11 Info. Mise à jour ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise à jour<BR>inclura 2 nouveaux<BR>éléments bonus, miaou !<BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>30/11 Info. Mise à jour ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
Ces éléments bonus seront ajoutés.
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
<font color=orange>Titre:<BR>&nbsp;&nbsp;Dondruma<BR>Les&nbsp;objets&nbsp;de&nbsp;Mémé<BR>colporteuse<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br></font>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/b00003.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					28/12 Info. Mise à jour<BR>
					21/12 Info. Mise à jour<BR>
					14/12 Info. Mise à jour<BR>
					7/12 Info. Mise à jour<BR>
					30/11 Info. Mise à jour ③<BR>
				<tr><td bgcolor=green>
					30/11 Info. Mise à jour ②<BR>
				<tr><td>
					30/11 Info. Mise à jour ①<BR>
					23/11 Info. Mise à jour<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>30/11 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Dragon ancestral</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>30/11 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Dragon ancestral】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :L'homme écarlate<BR>Hé hé hé... L'heure est<BR>venue. Voici votre invita-<BR>tion. Mettez vos plus beaux<BR>vêtements et portez votre<BR>meilleure arme, car il est<BR>temps de danser avec le<BR>roi du désastre.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60017.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					28/12 Info. Mise à jour<BR>
					21/12 Info. Mise à jour<BR>
					14/12 Info. Mise à jour<BR>
					7/12 Info. Mise à jour<BR>
					30/11 Info. Mise à jour ③<BR>
					30/11 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					30/11 Info. Mise à jour ①<BR>
				<tr><td>
					23/11 Info. Mise à jour<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>30/11 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Scarface</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>30/11 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Scarface】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Combattant blessé<BR>J'ai pourchassé le Wyvern<BR>blessé dans la jungle, mais<BR>étant moi-même touché j'ai<BR>vite atteint mes limites.<BR>Vengez mon honneur et<BR>chassez-le à ma place !<BR>　　　　　　　　　　　　　　<br>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60010.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					28/12 Info. Mise à jour<BR>
					21/12 Info. Mise à jour<BR>
					14/12 Info. Mise à jour<BR>
					7/12 Info. Mise à jour<BR>
					30/11 Info. Mise à jour ③<BR>
					30/11 Info. Mise à jour ②<BR>
					30/11 Info. Mise à jour ①<BR>
				<tr><td bgcolor=green>
					23/11 Info. Mise à jour<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>23/11 Info. Mise à jour</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Le vent des ténèbres</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>23/11 Info. Mise à jour</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Le vent des ténèbres】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Directeur de l'arène<BR>L'Arène ! L'endroit où mon-<BR>trer au monde vos talents !<BR>Cette fois nous avons lâché<BR>pas un mais deux terribles<BR>Gravios noirs ! Êtes-vous<BR>à la hauteur du défi ?<BR>　　　　　　　　　　　　　　<br>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60012.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
</body>
</html>
