<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=1",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=1&pg_no=2",
		"RB_LINK=DB_INFO.PHP?lang=1&pg_no=4",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					10/5 Update Information ②<BR>
				<tr><td>
					10/5 Update Information ①<BR>
					9/28 Update Information ②<BR>
					9/28 Update Information ①<BR>
					9/21 Update Information ②<BR>
					9/21 Update Information ①<BR>
					9/14 Update Information ②<BR>
					9/14 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>10/5 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>The Legend of Schrade</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>10/5 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【The Legend of Schrade】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Guild Master<BR>The black dragon Fatalis,<BR>referred to in Schradian<BR>legend, has been confirmed<BR>to exist! Left to roam free,<BR>countries will fall to its<BR>might. We need your help to<BR>end its reign of terror!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60015.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					10/5 Update Information ②<BR>
				<tr><td bgcolor=green>
					10/5 Update Information ①<BR>
				<tr><td>
					9/28 Update Information ②<BR>
					9/28 Update Information ①<BR>
					9/21 Update Information ②<BR>
					9/21 Update Information ①<BR>
					9/14 Update Information ②<BR>
					9/14 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>10/5 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Tempest of Yian Kut-Ku</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>10/5 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Tempest of Yian Kut-Ku】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Hunter's Guild<BR>We've just received a report<BR>from the jungle village that<BR>they are being plagued by<BR>multiple Yian Kut-Ku! Make<BR>haste towards the area and<BR>get the situation under<BR>control!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60009.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					10/5 Update Information ②<BR>
					10/5 Update Information ①<BR>
				<tr><td bgcolor=green>
					9/28 Update Information ②<BR>
				<tr><td>
					9/28 Update Information ①<BR>
					9/21 Update Information ②<BR>
					9/21 Update Information ①<BR>
					9/14 Update Information ②<BR>
					9/14 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>9/28 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Challenge Quest 4</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>9/28 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Challenge Quest 4】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Instructor<BR>It is I, your esteemed<BR>instructor. Now you shall<BR>challenge a Blangonga. To<BR>defeat the beast quickly,<BR>you must concentrate your<BR>attacks. Create an opening<BR>and then strike ferociously.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61004.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					10/5 Update Information ②<BR>
					10/5 Update Information ①<BR>
					9/28 Update Information ②<BR>
				<tr><td bgcolor=green>
					9/28 Update Information ①<BR>
				<tr><td>
					9/21 Update Information ②<BR>
					9/21 Update Information ①<BR>
					9/14 Update Information ②<BR>
					9/14 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>9/28 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Late Night Egg Thief</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>9/28 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Late Night Egg Thief】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:The Lady Gourmet<BR>As an absolute fanatic of<BR>egg dishes, I can say<BR>without hesitation that the<BR>tastiest of all eggs are<BR>Wyvern Eggs. Satisfy my<BR>hunger for this treat and<BR>bring me 3 Wyvern Eggs!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60002.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					10/5 Update Information ②<BR>
					10/5 Update Information ①<BR>
					9/28 Update Information ②<BR>
					9/28 Update Information ①<BR>
				<tr><td bgcolor=green>
					9/21 Update Information ②<BR>
				<tr><td>
					9/21 Update Information ①<BR>
					9/14 Update Information ②<BR>
					9/14 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>9/21 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Challenge Quest 3</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>9/21 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Challenge Quest 3】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Instructor<BR>It is I, your esteemed<BR>instructor. Your next<BR>challenge is in the rainy<BR>Jungle. A landslide has<BR>blocked the path and Barrel<BR>Bombs won't work in this<BR>rain, so use something else!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61003.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					10/5 Update Information ②<BR>
					10/5 Update Information ①<BR>
					9/28 Update Information ②<BR>
					9/28 Update Information ①<BR>
					9/21 Update Information ②<BR>
				<tr><td bgcolor=green>
					9/21 Update Information ①<BR>
				<tr><td>
					9/14 Update Information ②<BR>
					9/14 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>9/21 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Swarms Upon Swarms</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>9/21 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Swarms Upon Swarms】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Annoyed Maiden<BR>Lately, the area around the<BR>village has been very noisy,<BR>and it's all because of that<BR>swarm of bugs! They are so<BR>loud, I can't sleep at<BR>night! You're a hunter<BR>right? Then do something!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60024.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					10/5 Update Information ②<BR>
					10/5 Update Information ①<BR>
					9/28 Update Information ②<BR>
					9/28 Update Information ①<BR>
					9/21 Update Information ②<BR>
					9/21 Update Information ①<BR>
				<tr><td bgcolor=green>
					9/14 Update Information ②<BR>
				<tr><td>
					9/14 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>9/14 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Challenge Quest 2</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>9/14 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Challenge Quest 2】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Instructor<BR>It is I, your esteemed<BR>instructor. Today's practice<BR>is against two Daimyo<BR>Hermitaurs, but you only<BR>have to slay one to clear<BR>the Quest. Use Paintballs<BR>and focus your attacks!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61002.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					10/5 Update Information ②<BR>
					10/5 Update Information ①<BR>
					9/28 Update Information ②<BR>
					9/28 Update Information ①<BR>
					9/21 Update Information ②<BR>
					9/21 Update Information ①<BR>
					9/14 Update Information ②<BR>
				<tr><td bgcolor=green>
					9/14 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>9/14 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Monkeys and Crabs!</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>9/14 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Monkeys and Crabs!】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Arena Manager<BR>The Arena! A place to show<BR>your skills to the world! In<BR>this event, your opponent is<BR>a Blangonga; however, we've<BR>also released Ceanataurs and<BR>Hermitaurs! Beware the crabs<BR>and bring down the beast!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60014.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
</body>
</html>
