<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=4",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=4&pg_no=0",
		"RB_LINK=DB_INFO.PHP?lang=4&pg_no=2",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					16/11 Info actualización ②<BR>
				<tr><td>
					16/11 Info actualización ①<BR>
					9/11 Info actualización ②<BR>
					9/11 Info actualización ①<BR>
					2/11 Info actualización ④<BR>
					2/11 Info actualización ③<BR>
					2/11 Info actualización ②<BR>
					2/11 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>16/11 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Misión de desafío 11</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>16/11 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Misión de desafío 11】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Ausbilder<BR>Soy tu querido instructor.<BR>El primer golpe contra<BR>un enemigo que duerme<BR>hace un daño tremendo<BR>Empieza por colocarle una<BR>bomba y te alzarás<BR>victorioso de un plumazo.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61011.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Info actualización ②<BR>
				<tr><td bgcolor=green>
					16/11 Info actualización ①<BR>
				<tr><td>
					9/11 Info actualización ②<BR>
					9/11 Info actualización ①<BR>
					2/11 Info actualización ④<BR>
					2/11 Info actualización ③<BR>
					2/11 Info actualización ②<BR>
					2/11 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>16/11 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Espada fuerte, escudo fuerte</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>16/11 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Espada fuerte, escudo fuerte】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Jefe de la arena<BR>¡La arena! ¡Un lugar para<BR>mostrar tus habilidades!<BR>¡Para este evento, hemos<BR>sacado al ring a 2 enemigos<BR>con forma de cangrejo!<BR>¡Que venga todo el que esté<BR>listo para luchar!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60008.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Info actualización ②<BR>
					16/11 Info actualización ①<BR>
				<tr><td bgcolor=green>
					9/11 Info actualización ②<BR>
				<tr><td>
					9/11 Info actualización ①<BR>
					2/11 Info actualización ④<BR>
					2/11 Info actualización ③<BR>
					2/11 Info actualización ②<BR>
					2/11 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>9/11 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Misión de desafío 10</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>9/11 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Misión de desafío 10】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Ausbilder<BR>En mi calidad de querido <BR>instructor, debo informarte<BR>de que los Wyverns de fuego<BR>macho y hembra se comportan<BR>de forma muy distinta.<BR>Usa todas tus herramientas<BR>y habilidades de cazador.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61010.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Info actualización ②<BR>
					16/11 Info actualización ①<BR>
					9/11 Info actualización ②<BR>
				<tr><td bgcolor=green>
					9/11 Info actualización ①<BR>
				<tr><td>
					2/11 Info actualización ④<BR>
					2/11 Info actualización ③<BR>
					2/11 Info actualización ②<BR>
					2/11 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>9/11 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>El misterioso Kut-Ku</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>9/11 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【El misterioso Kut-Ku】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Gremio de cazadores<BR>Hemos recibido una señal de<BR>socorro del pueblo de la<BR>jungla. Ha aparecido un<BR>extraño rebaño de Kut-Ku que<BR>se ha desbocado por todo el<BR>campo. ¡Ve a esa zona y pon<BR>todo bajo control!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60023.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Info actualización ②<BR>
					16/11 Info actualización ①<BR>
					9/11 Info actualización ②<BR>
					9/11 Info actualización ①<BR>
				<tr><td bgcolor=green>
					2/11 Info actualización ④<BR>
				<tr><td>
					2/11 Info actualización ③<BR>
					2/11 Info actualización ②<BR>
					2/11 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>2/11 Info actualización ④</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir 3<BR>nuevos Elementos extra.<BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>2/11 Info actualización ④</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
Los siguientes elementos extra serán añadidos.
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
<font color=orange>Modas Piggie:<BR>&nbsp;&nbsp;El&nbsp;cerdo&nbsp;durmiente<BR>El chef Felyne ambulante:<BR>&nbsp;&nbsp;N&nbsp;azabache<BR>Título:<BR>&nbsp;&nbsp;Minegarde<BR>　　　　　　　　　　　　　　<br></font>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/b00002.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Info actualización ②<BR>
					16/11 Info actualización ①<BR>
					9/11 Info actualización ②<BR>
					9/11 Info actualización ①<BR>
					2/11 Info actualización ④<BR>
				<tr><td bgcolor=green>
					2/11 Info actualización ③<BR>
				<tr><td>
					2/11 Info actualización ②<BR>
					2/11 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>2/11 Info actualización ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Misión de desafío 9</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>2/11 Info actualización ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Misión de desafío 9】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Ausbilder<BR>Soy tu querido instructor.<BR>Pasemos ahora al Yian<BR>Garuga. Es una bestia muy<BR>capaz. Para estar a su<BR>altura debes esmerarte.<BR>Tal vez debas pulir tu<BR>estilo con el Arco.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61009.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Info actualización ②<BR>
					16/11 Info actualización ①<BR>
					9/11 Info actualización ②<BR>
					9/11 Info actualización ①<BR>
					2/11 Info actualización ④<BR>
					2/11 Info actualización ③<BR>
				<tr><td bgcolor=green>
					2/11 Info actualización ②<BR>
				<tr><td>
					2/11 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>2/11 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>El desastre carmesí</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>2/11 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【El desastre carmesí】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Director del Gremio<BR>Fatalis... Su ira puede<BR>hacer temblar la tierra y<BR>abrasar el cielo. Su maldad<BR>no tiene fin... ¡Cazadores!<BR>¡Hay que hacer algo! Id en<BR>busca de su rugido y acabad<BR>con la muerte púrpura.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60016.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Info actualización ②<BR>
					16/11 Info actualización ①<BR>
					9/11 Info actualización ②<BR>
					9/11 Info actualización ①<BR>
					2/11 Info actualización ④<BR>
					2/11 Info actualización ③<BR>
					2/11 Info actualización ②<BR>
				<tr><td bgcolor=green>
					2/11 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>2/11 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>La estación verde</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>2/11 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【La estación verde】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Doncella expectante<BR>Mi hermano por fin vuelve a<BR>casa después de tanto<BR>tiempo. ¡Pero debes ocuparte<BR>de las Rathian que han visto<BR>en las colinas próximas al<BR>pueblo! ¡Puede que no le<BR>dejen volver a casa!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60007.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
</body>
</html>
