<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=4",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=4&pg_no=1",
		"RB_LINK=DB_INFO.PHP?lang=4&pg_no=3",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					26/10 Info actualización ②<BR>
				<tr><td>
					26/10 Info actualización ①<BR>
					19/10 Info actualización ②<BR>
					19/10 Info actualización ①<BR>
					12/10 Info actualización ②<BR>
					12/10 Info actualización ①<BR>
					5/10 Info actualización ④<BR>
					5/10 Info actualización ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>26/10 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Misión de desafío 8</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>26/10 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Misión de desafío 8】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Ausbilder<BR>Soy tu querido instructor.<BR>¡Hoy te verás las caras<BR>contra dos Tigrex! Cuando<BR>rabian, no hay quien los<BR>toque, pero puedes valerte<BR>de tu habilidad para crear<BR>oportunidades de ataque.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61008.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					26/10 Info actualización ②<BR>
				<tr><td bgcolor=green>
					26/10 Info actualización ①<BR>
				<tr><td>
					19/10 Info actualización ②<BR>
					19/10 Info actualización ①<BR>
					12/10 Info actualización ②<BR>
					12/10 Info actualización ①<BR>
					5/10 Info actualización ④<BR>
					5/10 Info actualización ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>26/10 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>¡Trampa volcánica!</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>26/10 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【¡Trampa volcánica!】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Mercader ávido<BR>Vine a la región volcánica<BR>en busca de valiosos<BR>minerales, pero tengo una<BR>constante sensación de<BR>peligro... ¿Lo notas? Es<BR>como si se acercaran muchas<BR>amenazas. ¡Echa un vistazo!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60006.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					26/10 Info actualización ②<BR>
					26/10 Info actualización ①<BR>
				<tr><td bgcolor=green>
					19/10 Info actualización ②<BR>
				<tr><td>
					19/10 Info actualización ①<BR>
					12/10 Info actualización ②<BR>
					12/10 Info actualización ①<BR>
					5/10 Info actualización ④<BR>
					5/10 Info actualización ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>19/10 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Misión de desafío 7</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>19/10 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Misión de desafío 7】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Ausbilder<BR>Soy tu querido instructor.<BR>Al cazar, siempre hay un<BR>camino que es el más apto<BR>para la misión. ¿Cuál es la<BR>mejor ruta? Ya deberías ser<BR>capaz de decidirlo tú mismo.<BR>　　　　　　　　　　　　　　<br>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61007.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					26/10 Info actualización ②<BR>
					26/10 Info actualización ①<BR>
					19/10 Info actualización ②<BR>
				<tr><td bgcolor=green>
					19/10 Info actualización ①<BR>
				<tr><td>
					12/10 Info actualización ②<BR>
					12/10 Info actualización ①<BR>
					5/10 Info actualización ④<BR>
					5/10 Info actualización ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>19/10 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Madre de todas las batallas</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>19/10 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Madre de todas las batallas】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:El héroe Lynian<BR>¡Esto es un reto por escrito<BR>para todos los cazadores!<BR>¡Mis amigos Lynian y yo<BR>machacamos a todo el que <BR>pise la arena! ¡Hay que ser<BR>valiente para retarnos, nya!<BR>　　　　　　　　　　　　　　<br>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60003.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					26/10 Info actualización ②<BR>
					26/10 Info actualización ①<BR>
					19/10 Info actualización ②<BR>
					19/10 Info actualización ①<BR>
				<tr><td bgcolor=green>
					12/10 Info actualización ②<BR>
				<tr><td>
					12/10 Info actualización ①<BR>
					5/10 Info actualización ④<BR>
					5/10 Info actualización ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>12/10 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Misión de desafío 6</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>12/10 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Misión de desafío 6】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Ausbilder<BR>Soy tu querido instructor.<BR>¡Hoy te verás las caras con<BR>un Bulldrome! ¡No te burles<BR>de esta misión! A estas<BR>alturas ya habrás aprendido<BR>que siempre hay un pez<BR>más grande en el agua.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61006.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					26/10 Info actualización ②<BR>
					26/10 Info actualización ①<BR>
					19/10 Info actualización ②<BR>
					19/10 Info actualización ①<BR>
					12/10 Info actualización ②<BR>
				<tr><td bgcolor=green>
					12/10 Info actualización ①<BR>
				<tr><td>
					5/10 Info actualización ④<BR>
					5/10 Info actualización ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>12/10 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Concierto de luz y veneno</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>12/10 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Concierto de luz y veneno】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Jefe de la arena<BR>¡La arena! ¡Un lugar para<BR>mostrar tus habilidades!<BR>Prepárate para luchar no<BR>con uno, sino dos,<BR>devoradores de humanos:<BR>¡Gypceros! ¡Veamos<BR>tu fuerza!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60021.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					26/10 Info actualización ②<BR>
					26/10 Info actualización ①<BR>
					19/10 Info actualización ②<BR>
					19/10 Info actualización ①<BR>
					12/10 Info actualización ②<BR>
					12/10 Info actualización ①<BR>
				<tr><td bgcolor=green>
					5/10 Info actualización ④<BR>
				<tr><td>
					5/10 Info actualización ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>5/10 Info actualización ④</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir 2<BR>nuevos Elementos extra.<BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>5/10 Info actualización ④</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
Los siguientes elementos extra serán añadidos.
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
<font color=orange>El chef Felyne ambulante:<BR>&nbsp;&nbsp;Naranja<BR>Título:<BR>&nbsp;&nbsp;Jumbo<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br></font>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/b00001.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>３/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					26/10 Info actualización ②<BR>
					26/10 Info actualización ①<BR>
					19/10 Info actualización ②<BR>
					19/10 Info actualización ①<BR>
					12/10 Info actualización ②<BR>
					12/10 Info actualización ①<BR>
					5/10 Info actualización ④<BR>
				<tr><td bgcolor=green>
					5/10 Info actualización ③<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>5/10 Info actualización ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Misión de desafío 5</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>5/10 Info actualización ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Misión de desafío 5】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Ausbilder<BR>Soy tu querido instructor.<BR>Hoy practicaremos contra<BR>dos Shogun Ceanataurs, pero<BR>sólo tienes que matar a uno<BR>para completar la misión.<BR>¡Demuéstrame tus<BR>verdaderas habilidades!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61005.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
</body>
</html>
