<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=5",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=5&pg_no=0",
		"RB_LINK=DB_INFO.PHP?lang=5&pg_no=2",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					16/11 Informazioni agg. ②<BR>
				<tr><td>
					16/11 Informazioni agg. ①<BR>
					9/11 Informazioni agg. ②<BR>
					9/11 Informazioni agg. ①<BR>
					2/11 Informazioni agg. ④<BR>
					2/11 Informazioni agg. ③<BR>
					2/11 Informazioni agg. ②<BR>
					2/11 Informazioni agg. ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>16/11 Informazioni agg. ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Missione Sfida 11</font><BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>16/11 Informazioni agg. ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>【Missione Sfida 11】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Ausbilder<BR>Sono io, il tuo stimato<BR>istruttore. Il primo colpo a<BR>un nemico addormentato crea<BR>tremendi danni. Inizia<BR>l'attacco colpendolo con una<BR>bomba e la vittoria sarà a<BR>portata di mano!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61011.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Informazioni agg. ②<BR>
				<tr><td bgcolor=green>
					16/11 Informazioni agg. ①<BR>
				<tr><td>
					9/11 Informazioni agg. ②<BR>
					9/11 Informazioni agg. ①<BR>
					2/11 Informazioni agg. ④<BR>
					2/11 Informazioni agg. ③<BR>
					2/11 Informazioni agg. ②<BR>
					2/11 Informazioni agg. ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>16/11 Informazioni agg. ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Forte spada, forte scudo</font><BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>16/11 Informazioni agg. ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>【Forte spada, forte scudo】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Gestore dell'arena<BR>L'Arena! Un luogo in cui<BR>mostrare al mondo le tue<BR>capacità! Per questo evento,<BR>abbiamo messo sul ring due<BR>nemici simili a granchi!<BR>Benvenuto a chiunque voglia<BR>mettersi alla prova!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60008.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Informazioni agg. ②<BR>
					16/11 Informazioni agg. ①<BR>
				<tr><td bgcolor=green>
					9/11 Informazioni agg. ②<BR>
				<tr><td>
					9/11 Informazioni agg. ①<BR>
					2/11 Informazioni agg. ④<BR>
					2/11 Informazioni agg. ③<BR>
					2/11 Informazioni agg. ②<BR>
					2/11 Informazioni agg. ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>9/11 Informazioni agg. ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Missione Sfida 10</font><BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>9/11 Informazioni agg. ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>【Missione Sfida 10】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Ausbilder<BR>Come tuo stimato istruttore,<BR>devo dirti che i maschi e le<BR>femmine degli wyvern di<BR>fuoco si comportano in modo<BR>diverso. Per sconfiggerli,<BR>devi usare tutti i mezzi e<BR>tutte le tue capacità.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61010.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Informazioni agg. ②<BR>
					16/11 Informazioni agg. ①<BR>
					9/11 Informazioni agg. ②<BR>
				<tr><td bgcolor=green>
					9/11 Informazioni agg. ①<BR>
				<tr><td>
					2/11 Informazioni agg. ④<BR>
					2/11 Informazioni agg. ③<BR>
					2/11 Informazioni agg. ②<BR>
					2/11 Informazioni agg. ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>9/11 Informazioni agg. ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Il misterioso Kut-Ku</font><BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>9/11 Informazioni agg. ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>【Il misterioso Kut-Ku】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Gilda dei cacciatori<BR>Abbiamo ricevuto una<BR>richiesta di aiuto dal<BR>villaggio della Giungla. È<BR>apparso uno strano branco di<BR>Kut-Ku che corrono<BR>sfrenatamente sui campi. Vai<BR>lì e prendi il controllo!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60023.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Informazioni agg. ②<BR>
					16/11 Informazioni agg. ①<BR>
					9/11 Informazioni agg. ②<BR>
					9/11 Informazioni agg. ①<BR>
				<tr><td bgcolor=green>
					2/11 Informazioni agg. ④<BR>
				<tr><td>
					2/11 Informazioni agg. ③<BR>
					2/11 Informazioni agg. ②<BR>
					2/11 Informazioni agg. ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>2/11 Informazioni agg. ④</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include 3 nuovi<BR>elementi bonus, miao!<BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>2/11 Informazioni agg. ④</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
I seguenti elementi bonus verranno aggiunti.
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
<font color=orange>La moda di Piggie:<BR>&nbsp;&nbsp;Bianco&nbsp;maiale<BR>Il cuoco vagabondo Felyne:<BR>&nbsp;&nbsp;Ebano<BR>Titolo:<BR>&nbsp;&nbsp;Minegarde<BR>　　　　　　　　　　　　　　<br></font>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/b00002.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Informazioni agg. ②<BR>
					16/11 Informazioni agg. ①<BR>
					9/11 Informazioni agg. ②<BR>
					9/11 Informazioni agg. ①<BR>
					2/11 Informazioni agg. ④<BR>
				<tr><td bgcolor=green>
					2/11 Informazioni agg. ③<BR>
				<tr><td>
					2/11 Informazioni agg. ②<BR>
					2/11 Informazioni agg. ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>2/11 Informazioni agg. ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Missione Sfida 9</font><BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>2/11 Informazioni agg. ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>【Missione Sfida 9】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Ausbilder<BR>Sono io, il tuo stimato<BR>istruttore. Il prossimo è<BR>uno Yian Garuga. È sveglio,<BR>quindi non potrai essere<BR>all'altezza se non ti<BR>impegnerai totalmente. Forse<BR>dovresti provare con l'Arco.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61009.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Informazioni agg. ②<BR>
					16/11 Informazioni agg. ①<BR>
					9/11 Informazioni agg. ②<BR>
					9/11 Informazioni agg. ①<BR>
					2/11 Informazioni agg. ④<BR>
					2/11 Informazioni agg. ③<BR>
				<tr><td bgcolor=green>
					2/11 Informazioni agg. ②<BR>
				<tr><td>
					2/11 Informazioni agg. ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>2/11 Informazioni agg. ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Il disastro cremisi</font><BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>2/11 Informazioni agg. ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>【Il disastro cremisi】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Direttore Gilda<BR>Fatalis... La sua ira può<BR>scuotere la terra e ardere i<BR>cieli. È un male senza fine.<BR>Cacciatori! Non indugiate!<BR>Inseguite il suo ruggito e<BR>abbattete la morte cremisi.<BR>　　　　　　　　　　　　　　<br>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60016.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Informazioni agg. ②<BR>
					16/11 Informazioni agg. ①<BR>
					9/11 Informazioni agg. ②<BR>
					9/11 Informazioni agg. ①<BR>
					2/11 Informazioni agg. ④<BR>
					2/11 Informazioni agg. ③<BR>
					2/11 Informazioni agg. ②<BR>
				<tr><td bgcolor=green>
					2/11 Informazioni agg. ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>2/11 Informazioni agg. ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>La stagione del verde</font><BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>2/11 Informazioni agg. ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>【La stagione del verde】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Ragazza in pensiero<BR>Mio fratello sta finalmente<BR>venendo a casa dopo tanto<BR>tempo. Ma tu devi occuparti<BR>delle Rathian sulle colline<BR>del villaggio vicino, in<BR>modo che non gli creino guai<BR>mentre torna a casa!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60007.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
</body>
</html>
