<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=2",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=2&pg_no=2",
		"RB_LINK=DB_INFO.PHP?lang=2&pg_no=4",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					5/10 Update-Informationen②<BR>
				<tr><td>
					5/10 Update-Informationen①<BR>
					28/9 Update-Informationen②<BR>
					28/9 Update-Informationen①<BR>
					21/9 Update-Informationen②<BR>
					21/9 Update-Informationen①<BR>
					14/9 Update-Informationen②<BR>
					14/9 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>5/10 Update-Informationen②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Die Legende von Schrade</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>5/10 Update-Informationen②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Die Legende von Schrade】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Gildenmeister<BR>Der schwarze Drache Fatalis,<BR>der in der Legende von<BR>Schrade erwähnt wird, lebt<BR>wirklich! Er kann ganze<BR>Länder verwüsten. Wir<BR>brauchen deine Hilfe, um<BR>diesen Terror zu beenden!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60015.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Update-Informationen②<BR>
				<tr><td bgcolor=green>
					5/10 Update-Informationen①<BR>
				<tr><td>
					28/9 Update-Informationen②<BR>
					28/9 Update-Informationen①<BR>
					21/9 Update-Informationen②<BR>
					21/9 Update-Informationen①<BR>
					14/9 Update-Informationen②<BR>
					14/9 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>5/10 Update-Informationen①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Yian Kut-Ku-Sturm</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>5/10 Update-Informationen①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Yian Kut-Ku-Sturm】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Jägergilde<BR>Wir haben aus dem<BR>Dschungeldorf gehört, dass<BR>dort mehrere Yian Kut-Kus<BR>ihr Unwesen treiben. Begib<BR>dich dorthin und bring die<BR>Situation unter Kontrolle!<BR>　　　　　　　　　　　　　　<br>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60009.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Update-Informationen②<BR>
					5/10 Update-Informationen①<BR>
				<tr><td bgcolor=green>
					28/9 Update-Informationen②<BR>
				<tr><td>
					28/9 Update-Informationen①<BR>
					21/9 Update-Informationen②<BR>
					21/9 Update-Informationen①<BR>
					14/9 Update-Informationen②<BR>
					14/9 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>28/9 Update-Informationen②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Challenge-Quest 4</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>28/9 Update-Informationen②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Challenge-Quest 4】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Ausbilder<BR>Ich bin's, dein Ausbilder.<BR>Jetzt geht es gegen einen <BR>Blangonga. Um ihn schnell zu<BR>besiegen, musst du konzen-<BR>triert angreifen. Finde eine<BR>Schwäche und greif dann wie<BR>wild an.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61004.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Update-Informationen②<BR>
					5/10 Update-Informationen①<BR>
					28/9 Update-Informationen②<BR>
				<tr><td bgcolor=green>
					28/9 Update-Informationen①<BR>
				<tr><td>
					21/9 Update-Informationen②<BR>
					21/9 Update-Informationen①<BR>
					14/9 Update-Informationen②<BR>
					14/9 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>28/9 Update-Informationen①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Eierdieb in der Nacht</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>28/9 Update-Informationen①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Eierdieb in der Nacht】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Feinschmeckerin<BR>Ich bin verrückt nach Eier-<BR>gerichten und Wyvern-Eier<BR>sind die schmackhaftesten.<BR>Sei doch so gut und bring<BR>mir drei Wyvern-Eier!<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60002.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Update-Informationen②<BR>
					5/10 Update-Informationen①<BR>
					28/9 Update-Informationen②<BR>
					28/9 Update-Informationen①<BR>
				<tr><td bgcolor=green>
					21/9 Update-Informationen②<BR>
				<tr><td>
					21/9 Update-Informationen①<BR>
					14/9 Update-Informationen②<BR>
					14/9 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>21/9 Update-Informationen②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Challenge-Quest 3</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>21/9 Update-Informationen②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Challenge-Quest 3】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Ausbilder<BR>Ich bin's, dein Ausbilder.<BR>Jetzt geht es in den <BR>feuchten Dschungel. Eine <BR>Schlammlawine versperrt den <BR>Weg und Fassbomben gehen bei<BR>Regen nicht. Probier etwas <BR>anderes!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61003.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Update-Informationen②<BR>
					5/10 Update-Informationen①<BR>
					28/9 Update-Informationen②<BR>
					28/9 Update-Informationen①<BR>
					21/9 Update-Informationen②<BR>
				<tr><td bgcolor=green>
					21/9 Update-Informationen①<BR>
				<tr><td>
					14/9 Update-Informationen②<BR>
					14/9 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>21/9 Update-Informationen①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Schwärme über Schwärme</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>21/9 Update-Informationen①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Schwärme über Schwärme】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Erzürnte Magd<BR>Das Gebiet um das Dorf ist<BR>letzthin sehr laut, und das<BR>liegt an dem Insekten-<BR>schwarm. Ich kann nachts<BR>nicht mehr schlafen. Du bist<BR>doch ein Jäger, oder? Dann<BR>tu etwas!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60024.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Update-Informationen②<BR>
					5/10 Update-Informationen①<BR>
					28/9 Update-Informationen②<BR>
					28/9 Update-Informationen①<BR>
					21/9 Update-Informationen②<BR>
					21/9 Update-Informationen①<BR>
				<tr><td bgcolor=green>
					14/9 Update-Informationen②<BR>
				<tr><td>
					14/9 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>14/9 Update-Informationen②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Challenge-Quest 2</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>14/9 Update-Informationen②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Challenge-Quest 2】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Ausbilder<BR>Ich bin's, dein Ausbilder.<BR>Heute geht es gegen zwei <BR>Daimyo Hermitauren, aber du <BR>musst nur einen töten, um <BR>die Quest zu erfüllen. <BR>Benutze Farbbälle und <BR>greife konzentriert an!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61002.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Update-Informationen②<BR>
					5/10 Update-Informationen①<BR>
					28/9 Update-Informationen②<BR>
					28/9 Update-Informationen①<BR>
					21/9 Update-Informationen②<BR>
					21/9 Update-Informationen①<BR>
					14/9 Update-Informationen②<BR>
				<tr><td bgcolor=green>
					14/9 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>14/9 Update-Informationen①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Affen und Krabben</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>14/9 Update-Informationen①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Affen und Krabben】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Arena-Manager<BR>Die Arena! Hier kann man der<BR>Welt sein Können zeigen!<BR>Heute steht ein Blangonga im<BR>Ring. Wir haben aber auch<BR>Ceanatauren und Hermitauren<BR>losgelassen! Achte auf die<BR>Krabben und erleg das Biest!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60014.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
</body>
</html>
