<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=3",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=3&pg_no=2",
		"RB_LINK=DB_INFO.PHP?lang=3&pg_no=4",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					5/10 Info. Mise à jour ②<BR>
				<tr><td>
					5/10 Info. Mise à jour ①<BR>
					28/9 Info. Mise à jour ②<BR>
					28/9 Info. Mise à jour ①<BR>
					21/9 Info. Mise à jour ②<BR>
					21/9 Info. Mise à jour ①<BR>
					14/9 Info. Mise à jour ②<BR>
					14/9 Info. Mise à jour ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>5/10 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>La légende de Schrade</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>5/10 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【La légende de Schrade】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Maître de Guilde<BR>Le dragon noir Fatalis, évo-<BR>qué dans les légendes schra-<BR>diennes, existerait réelle-<BR>ment ! Si on le laisse, des<BR>pays entiers s'écrouleront.<BR>Nous avons besoin de vous<BR>pour achever son règne !<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60015.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					5/10 Info. Mise à jour ①<BR>
				<tr><td>
					28/9 Info. Mise à jour ②<BR>
					28/9 Info. Mise à jour ①<BR>
					21/9 Info. Mise à jour ②<BR>
					21/9 Info. Mise à jour ①<BR>
					14/9 Info. Mise à jour ②<BR>
					14/9 Info. Mise à jour ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>5/10 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Une tempête de Yian Kut-Ku</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>5/10 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Une tempête de Yian Kut-Ku】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Guilde des chasseurs<BR>Nous venons d'apprendre que<BR>le village de la jungle<BR>est infesté par des Yian<BR>Kut-Ku ! Dépêchez-vous d'y<BR>aller et d'y ramener le<BR>calme !<BR>　　　　　　　　　　　　　　<br>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60009.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Info. Mise à jour ②<BR>
					5/10 Info. Mise à jour ①<BR>
				<tr><td bgcolor=green>
					28/9 Info. Mise à jour ②<BR>
				<tr><td>
					28/9 Info. Mise à jour ①<BR>
					21/9 Info. Mise à jour ②<BR>
					21/9 Info. Mise à jour ①<BR>
					14/9 Info. Mise à jour ②<BR>
					14/9 Info. Mise à jour ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>28/9 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Quête défi 4</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>28/9 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Quête défi 4】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Instructeur<BR>C'est moi, votre instructeur<BR>estimé. Vous allez<BR>rencontrer un Blangonga.<BR>Pour vaincre rapidement la<BR>bête, concentrez vos atta-<BR>ques. Créez une ouverture,<BR>puis frappez sauvagement !<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61004.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Info. Mise à jour ②<BR>
					5/10 Info. Mise à jour ①<BR>
					28/9 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					28/9 Info. Mise à jour ①<BR>
				<tr><td>
					21/9 Info. Mise à jour ②<BR>
					21/9 Info. Mise à jour ①<BR>
					14/9 Info. Mise à jour ②<BR>
					14/9 Info. Mise à jour ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>28/9 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Voleur d'œuf nocturne</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>28/9 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Voleur d'œuf nocturne】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :La Dame gourmet<BR>En fanatique des plats aux<BR>œufs, je peux dire sans<BR>hésitation que les œufs<BR>les meilleurs sont ceux des<BR>Wyvern. Satisfaisez ma<BR>faim en m'apportant<BR>3 Œufs de Wyvern.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60002.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Info. Mise à jour ②<BR>
					5/10 Info. Mise à jour ①<BR>
					28/9 Info. Mise à jour ②<BR>
					28/9 Info. Mise à jour ①<BR>
				<tr><td bgcolor=green>
					21/9 Info. Mise à jour ②<BR>
				<tr><td>
					21/9 Info. Mise à jour ①<BR>
					14/9 Info. Mise à jour ②<BR>
					14/9 Info. Mise à jour ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>21/9 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Quête défi 3</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>21/9 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Quête défi 3】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Instructeur<BR>C'est moi, votre instructeur<BR>estimé. Votre prochain<BR>défi a lieu dans la jungle<BR>humide. Un glissement de<BR>terrain a bloqué le passage<BR>et les Bombes baril seront<BR>inefficaces. Réfléchissez !<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61003.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Info. Mise à jour ②<BR>
					5/10 Info. Mise à jour ①<BR>
					28/9 Info. Mise à jour ②<BR>
					28/9 Info. Mise à jour ①<BR>
					21/9 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					21/9 Info. Mise à jour ①<BR>
				<tr><td>
					14/9 Info. Mise à jour ②<BR>
					14/9 Info. Mise à jour ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>21/9 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Nuées après nuées</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>21/9 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Nuées après nuées】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Jeune fille énervée<BR>Le pourtour du village est<BR>devenu très bruyant à cause<BR>d'une nuée d'insectes !<BR>Impossible de dormir !<BR>Vous êtes chasseur,<BR>n'est-ce pas ? Alors faites<BR>quelque chose !<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60024.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Info. Mise à jour ②<BR>
					5/10 Info. Mise à jour ①<BR>
					28/9 Info. Mise à jour ②<BR>
					28/9 Info. Mise à jour ①<BR>
					21/9 Info. Mise à jour ②<BR>
					21/9 Info. Mise à jour ①<BR>
				<tr><td bgcolor=green>
					14/9 Info. Mise à jour ②<BR>
				<tr><td>
					14/9 Info. Mise à jour ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>14/9 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Quête défi 2</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>14/9 Info. Mise à jour ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Quête défi 2】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Instructeur<BR>C'est moi, votre instructeur<BR>estimé. L'entraînement<BR>du jour concerne deux<BR>Hermitaur Daimyo, mais<BR>il suffit d'en tuer un pour<BR>compléter la quête. Pensez<BR>à utiliser les Marqueurs !<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61002.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Info. Mise à jour ②<BR>
					5/10 Info. Mise à jour ①<BR>
					28/9 Info. Mise à jour ②<BR>
					28/9 Info. Mise à jour ①<BR>
					21/9 Info. Mise à jour ②<BR>
					21/9 Info. Mise à jour ①<BR>
					14/9 Info. Mise à jour ②<BR>
				<tr><td bgcolor=green>
					14/9 Info. Mise à jour ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>14/9 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La prochaine mise<BR>à jour inclura la<BR>quête suivante :<BR><font color=orange>Singes et crabes !</font><BR><BR>Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16><BR>pour plus de détails.<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/FR/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>14/9 Info. Mise à jour ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Un aperçu de ce qui vous attend prochainement.<BR>
<font color=orange>【Singes et crabes !】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client :Directeur de l'arène<BR>L'Arène ! L'endroit où mon-<BR>trer au monde vos talents !<BR>Cette fois votre adversaire<BR>est un Blangonga, mais nous<BR>avons aussi lâché des Cea-<BR>nataur et des Hermitaur !<BR>Attention aux crabes !<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60014.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
</body>
</html>
