<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=1",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=1&pg_no=0",
		"RB_LINK=DB_INFO.PHP?lang=1&pg_no=2",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					11/16 Update Information ②<BR>
				<tr><td>
					11/16 Update Information ①<BR>
					11/9 Update Information ②<BR>
					11/9 Update Information ①<BR>
					11/2 Update Information ④<BR>
					11/2 Update Information ③<BR>
					11/2 Update Information ②<BR>
					11/2 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>11/16 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Challenge Quest 11</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>11/16 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Challenge Quest 11】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Instructor<BR>It is I, your esteemed<BR>instructor. The first blow<BR>on a sleeping enemy is<BR>tremendously damaging. Hit<BR>it with a bomb as the first<BR>blow and victory will be at<BR>hand!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61011.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					11/16 Update Information ②<BR>
				<tr><td bgcolor=green>
					11/16 Update Information ①<BR>
				<tr><td>
					11/9 Update Information ②<BR>
					11/9 Update Information ①<BR>
					11/2 Update Information ④<BR>
					11/2 Update Information ③<BR>
					11/2 Update Information ②<BR>
					11/2 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>11/16 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Strong Sword, Strong Shield</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>11/16 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Strong Sword, Strong Shield】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Arena Manager<BR>The Arena! A place to show<BR>your skills to the world!<BR>For this event, we have<BR>released two crab-like<BR>enemies into the arena! All<BR>those ready to test their<BR>skills are welcome!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60008.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					11/16 Update Information ②<BR>
					11/16 Update Information ①<BR>
				<tr><td bgcolor=green>
					11/9 Update Information ②<BR>
				<tr><td>
					11/9 Update Information ①<BR>
					11/2 Update Information ④<BR>
					11/2 Update Information ③<BR>
					11/2 Update Information ②<BR>
					11/2 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>11/9 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Challenge Quest 10</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>11/9 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Challenge Quest 10】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Instructor<BR>As your esteemed instructor<BR>it is my duty to inform you<BR>that male and female fire<BR>wyverns behave quite<BR>differently. You must use<BR>all your tools and skills as<BR>a hunter to defeat them.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61010.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					11/16 Update Information ②<BR>
					11/16 Update Information ①<BR>
					11/9 Update Information ②<BR>
				<tr><td bgcolor=green>
					11/9 Update Information ①<BR>
				<tr><td>
					11/2 Update Information ④<BR>
					11/2 Update Information ③<BR>
					11/2 Update Information ②<BR>
					11/2 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>11/9 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>The Mysterious Kut-Ku</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>11/9 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【The Mysterious Kut-Ku】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Hunter's Guild<BR>We have received a distress<BR>signal from the jungle<BR>village. A strange flock of<BR>Kut-Ku have appeared and are<BR>running amok over the<BR>fields. Head to the area and<BR>bring things under control!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60023.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					11/16 Update Information ②<BR>
					11/16 Update Information ①<BR>
					11/9 Update Information ②<BR>
					11/9 Update Information ①<BR>
				<tr><td bgcolor=green>
					11/2 Update Information ④<BR>
				<tr><td>
					11/2 Update Information ③<BR>
					11/2 Update Information ②<BR>
					11/2 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>11/2 Update Information ④</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update will include<BR>3 new Bonus Items, meow!<BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>11/2 Update Information ④</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
The Bonus Items will be added.
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
<font color=orange>Piggie Fashions:<BR>&nbsp;&nbsp;SleepyPig&nbsp;White<BR>Wandering Chef:<BR>&nbsp;&nbsp;Jet&nbsp;Black<BR>Title:<BR>&nbsp;&nbsp;Minegarde<BR>　　　　　　　　　　　　　　<br></font>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/b00002.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					11/16 Update Information ②<BR>
					11/16 Update Information ①<BR>
					11/9 Update Information ②<BR>
					11/9 Update Information ①<BR>
					11/2 Update Information ④<BR>
				<tr><td bgcolor=green>
					11/2 Update Information ③<BR>
				<tr><td>
					11/2 Update Information ②<BR>
					11/2 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>11/2 Update Information ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Challenge Quest 9</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>11/2 Update Information ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Challenge Quest 9】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Instructor<BR>It is I, your esteemed<BR>instructor. Next up is Yian<BR>Garuga. It is an able beast,<BR>so you can't match wits with<BR>a half-hearted effort.<BR>Perhaps you should try to<BR>polish your archery skills.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61009.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					11/16 Update Information ②<BR>
					11/16 Update Information ①<BR>
					11/9 Update Information ②<BR>
					11/9 Update Information ①<BR>
					11/2 Update Information ④<BR>
					11/2 Update Information ③<BR>
				<tr><td bgcolor=green>
					11/2 Update Information ②<BR>
				<tr><td>
					11/2 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>11/2 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>The Crimson Disaster</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>11/2 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【The Crimson Disaster】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Guild Director<BR>Fatalis... Its anger can<BR>shake the earth and scorch<BR>the heavens. It is an evil<BR>without end... Hunters! Do<BR>not let this go unheard!<BR>Chase its roar and bring<BR>down the crimson death. <BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60016.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					11/16 Update Information ②<BR>
					11/16 Update Information ①<BR>
					11/9 Update Information ②<BR>
					11/9 Update Information ①<BR>
					11/2 Update Information ④<BR>
					11/2 Update Information ③<BR>
					11/2 Update Information ②<BR>
				<tr><td bgcolor=green>
					11/2 Update Information ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>11/2 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>The Season of Green</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>11/2 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【The Season of Green】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Expectant Maiden<BR>My brother is finally coming<BR>home after a long time away.<BR>But you must take care of<BR>the multiple Rathian spotted<BR>in the hills of the nearby<BR>village before they cause<BR>him trouble on his way home!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60007.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
</body>
</html>
