<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=4",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=4&pg_no=2",
		"RB_LINK=DB_INFO.PHP?lang=4&pg_no=4",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					5/10 Info actualización ②<BR>
				<tr><td>
					5/10 Info actualización ①<BR>
					28/9 Info actualización ②<BR>
					28/9 Info actualización ①<BR>
					21/9 Info actualización ②<BR>
					21/9 Info actualización ①<BR>
					14/9 Info actualización ②<BR>
					14/9 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>5/10 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>La leyenda de Schrade</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>5/10 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【La leyenda de Schrade】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Maestro del Gremio<BR>¡Fatalis, el dragón negro<BR>del que habla la leyenda de<BR>Schrade, existe de<BR>verdad! Si no lo atrapamos,<BR>el país caerá en sus<BR>manos. ¡Necesitamos tu<BR>ayuda para acabar con él!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60015.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Info actualización ②<BR>
				<tr><td bgcolor=green>
					5/10 Info actualización ①<BR>
				<tr><td>
					28/9 Info actualización ②<BR>
					28/9 Info actualización ①<BR>
					21/9 Info actualización ②<BR>
					21/9 Info actualización ①<BR>
					14/9 Info actualización ②<BR>
					14/9 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>5/10 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Tempestad de Yian Kut-Ku</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>5/10 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Tempestad de Yian Kut-Ku】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Gremio de cazadores<BR>¡Nos han dicho que en el<BR>pueblo de la jungla hay una<BR>plaga de Yian Kut-Ku!<BR>¡Vete corriendo a esa<BR>zona y pon la<BR>situación bajo<BR>control!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60009.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Info actualización ②<BR>
					5/10 Info actualización ①<BR>
				<tr><td bgcolor=green>
					28/9 Info actualización ②<BR>
				<tr><td>
					28/9 Info actualización ①<BR>
					21/9 Info actualización ②<BR>
					21/9 Info actualización ①<BR>
					14/9 Info actualización ②<BR>
					14/9 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>28/9 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Misión de desafío 4</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>28/9 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Misión de desafío 4】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Ausbilder<BR>Soy tu querido instructor.<BR>Esta vez te enfrentarás<BR>a un Blangonga. Para<BR>derrotar a la bestia con<BR>rapidez, concéntrate en tus<BR>ataques. Busca un hueco y<BR>ataca con ahínco.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61004.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Info actualización ②<BR>
					5/10 Info actualización ①<BR>
					28/9 Info actualización ②<BR>
				<tr><td bgcolor=green>
					28/9 Info actualización ①<BR>
				<tr><td>
					21/9 Info actualización ②<BR>
					21/9 Info actualización ①<BR>
					14/9 Info actualización ②<BR>
					14/9 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>28/9 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Ladrón de huevos nocturno</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>28/9 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Ladrón de huevos nocturno】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:La Señora Gourmet<BR>Como fanática de los huevos,<BR>puedo afirmar sin dudarlo<BR>que los huevos más sabrosos<BR>son los huevos de<BR>Wyvern. ¡Ayúdame a<BR>satisfacer mi capricho y<BR>tráeme 3 Huevos de Wyvern!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60002.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Info actualización ②<BR>
					5/10 Info actualización ①<BR>
					28/9 Info actualización ②<BR>
					28/9 Info actualización ①<BR>
				<tr><td bgcolor=green>
					21/9 Info actualización ②<BR>
				<tr><td>
					21/9 Info actualización ①<BR>
					14/9 Info actualización ②<BR>
					14/9 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>21/9 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Misión de desafío 3</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>21/9 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Misión de desafío 3】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Ausbilder<BR>Soy tu querido instructor.<BR>El siguiente es en la<BR>lluviosa jungla. Un<BR>corrimiento de tierra taponó<BR>el camino y con lluvia no<BR>sirven las Bombas barril.<BR>¡Busca alternativas!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61003.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Info actualización ②<BR>
					5/10 Info actualización ①<BR>
					28/9 Info actualización ②<BR>
					28/9 Info actualización ①<BR>
					21/9 Info actualización ②<BR>
				<tr><td bgcolor=green>
					21/9 Info actualización ①<BR>
				<tr><td>
					14/9 Info actualización ②<BR>
					14/9 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>21/9 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Enjambres de enjambres</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>21/9 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Enjambres de enjambres】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Doncella enojada<BR>Últimamente, los alrededores<BR>del pueblo son muy ruidosos<BR>y la culpa es de ese<BR>enjambre de bichos. ¡Hacen<BR>tanto ruido que no puedo<BR>dormir! Tú eres cazador,<BR>¿no? ¡Pues haz algo!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60024.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Info actualización ②<BR>
					5/10 Info actualización ①<BR>
					28/9 Info actualización ②<BR>
					28/9 Info actualización ①<BR>
					21/9 Info actualización ②<BR>
					21/9 Info actualización ①<BR>
				<tr><td bgcolor=green>
					14/9 Info actualización ②<BR>
				<tr><td>
					14/9 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>14/9 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>Misión de desafío 2</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>14/9 Info actualización ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【Misión de desafío 2】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Ausbilder<BR>Soy tu querido instructor.<BR>Hoy practicaremos contra<BR>dos Daimyo Hermitaurs,<BR>pero sólo tienes que matar<BR>a uno para completar la<BR>misión. Usa Bolas de pintura<BR>y concéntrate.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61002.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>４/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					5/10 Info actualización ②<BR>
					5/10 Info actualización ①<BR>
					28/9 Info actualización ②<BR>
					28/9 Info actualización ①<BR>
					21/9 Info actualización ②<BR>
					21/9 Info actualización ①<BR>
					14/9 Info actualización ②<BR>
				<tr><td bgcolor=green>
					14/9 Info actualización ①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>14/9 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
La próxima actualización<BR>tiene previsto incluir las<BR>siguientes Misiones, nya:<BR><font color=orange>¡Monos y cangrejos!</font><BR><BR>Pulsa el botón <img src=GIF/B_REC.gif width=16 height=16> para<BR>más detalles, ¡miau!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/ES/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>14/9 Info actualización ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Te contaré algo acerca de la próxima descarga.<BR>
<font color=orange>【¡Monos y cangrejos!】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Jefe de la arena<BR>¡La arena! ¡Un lugar para<BR>mostrar tus habilidades! En<BR>este evento, tu oponente es<BR>un Blangonga; también hay<BR>Ceanataurs y Hermitaurs.<BR>Cuidado con los cangrejos <BR>y mata a la bestia.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60014.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
</body>
</html>
