<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=5",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=5&pg_no=4",
		"RB_LINK=DB_INFO.PHP?lang=5&pg_no=1",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					28/12 Informazioni agg.<BR>
				<tr><td>
					21/12 Informazioni agg.<BR>
					14/12 Informazioni agg.<BR>
					7/12 Informazioni agg.<BR>
					30/11 Informazioni agg. ③<BR>
					30/11 Informazioni agg. ②<BR>
					30/11 Informazioni agg. ①<BR>
					23/11 Informazioni agg.<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>28/12 Informazioni agg.</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Ira di cielo e terra</font><BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>28/12 Informazioni agg.</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>【Ira di cielo e terra】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Capovillaggio Kokoto<BR>È passato molto tempo, amici<BR>miei... Ecco la mia sfida<BR>per tutti voi! Battete i 2<BR>wyvern giganti, il Rathalos<BR>e il Rathian. Siete in<BR>grado di sottometterli?<BR>　　　　　　　　　　　　　　<br>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60022.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					28/12 Informazioni agg.<BR>
				<tr><td bgcolor=green>
					21/12 Informazioni agg.<BR>
				<tr><td>
					14/12 Informazioni agg.<BR>
					7/12 Informazioni agg.<BR>
					30/11 Informazioni agg. ③<BR>
					30/11 Informazioni agg. ②<BR>
					30/11 Informazioni agg. ①<BR>
					23/11 Informazioni agg.<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>21/12 Informazioni agg.</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Il visitatore d'acciaio</font><BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>21/12 Informazioni agg.</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>【Il visitatore d'acciaio】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Maestro della Gilda<BR>Emergenza! Un Kushala Daora<BR>marrone si sta avvicinando<BR>alla nostra città! Tutti i<BR>cacciatori validi dovrebbero<BR>precipitarsi qui appena<BR>possibile! Ci serve aiuto<BR>per salvare la città!!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60025.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					28/12 Informazioni agg.<BR>
					21/12 Informazioni agg.<BR>
				<tr><td bgcolor=green>
					14/12 Informazioni agg.<BR>
				<tr><td>
					7/12 Informazioni agg.<BR>
					30/11 Informazioni agg. ③<BR>
					30/11 Informazioni agg. ②<BR>
					30/11 Informazioni agg. ①<BR>
					23/11 Informazioni agg.<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>14/12 Informazioni agg.</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Dio del tuono dorato</font><BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>14/12 Informazioni agg.</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>【Dio del tuono dorato】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Gestore dell'arena<BR>È terribile! Assolutamente<BR>terribile! Un enorme mostro<BR>nero ha occupato la mia<BR>arena! Con quello lì dentro,<BR>non possiamo fare affari!!<BR>Liberacene velocemente! Per<BR>favore!!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60019.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					28/12 Informazioni agg.<BR>
					21/12 Informazioni agg.<BR>
					14/12 Informazioni agg.<BR>
				<tr><td bgcolor=green>
					7/12 Informazioni agg.<BR>
				<tr><td>
					30/11 Informazioni agg. ③<BR>
					30/11 Informazioni agg. ②<BR>
					30/11 Informazioni agg. ①<BR>
					23/11 Informazioni agg.<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>7/12 Informazioni agg.</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Covo di Remobra</font><BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>7/12 Informazioni agg.</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>【Covo di Remobra】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Gestore dell'arena<BR>L'Arena! Un luogo in cui<BR>mostrare al mondo le tue<BR>capacità! I tuoi avversari<BR>per questo evento sono i<BR>Remobra volanti! Con tutto<BR>il loro veleno, ci vorrà<BR>coraggio per sopravvivere.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60018.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					28/12 Informazioni agg.<BR>
					21/12 Informazioni agg.<BR>
					14/12 Informazioni agg.<BR>
					7/12 Informazioni agg.<BR>
				<tr><td bgcolor=green>
					30/11 Informazioni agg. ③<BR>
				<tr><td>
					30/11 Informazioni agg. ②<BR>
					30/11 Informazioni agg. ①<BR>
					23/11 Informazioni agg.<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>30/11 Informazioni agg. ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include 2 nuovi<BR>elementi bonus, miao!<BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>30/11 Informazioni agg. ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
I seguenti elementi bonus verranno aggiunti.
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
<font color=orange>Titolo:<BR>&nbsp;&nbsp;Dondruma<BR>Oggetti&nbsp;della<BR>vecchia&nbsp;ambulante<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br></font>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/b00003.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					28/12 Informazioni agg.<BR>
					21/12 Informazioni agg.<BR>
					14/12 Informazioni agg.<BR>
					7/12 Informazioni agg.<BR>
					30/11 Informazioni agg. ③<BR>
				<tr><td bgcolor=green>
					30/11 Informazioni agg. ②<BR>
				<tr><td>
					30/11 Informazioni agg. ①<BR>
					23/11 Informazioni agg.<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>30/11 Informazioni agg. ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Drago ancestrale</font><BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>30/11 Informazioni agg. ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>【Drago ancestrale】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Uomo mister. scarl.<BR>Eh eh eh... È giunto il<BR>momento. Ecco il tuo invito<BR>al ballo. Indossa il tuo<BR>abito migliore e porta<BR>l'arma più grande, perché è<BR>ora di andare a danzare con<BR>il re del disastro.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60017.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					28/12 Informazioni agg.<BR>
					21/12 Informazioni agg.<BR>
					14/12 Informazioni agg.<BR>
					7/12 Informazioni agg.<BR>
					30/11 Informazioni agg. ③<BR>
					30/11 Informazioni agg. ②<BR>
				<tr><td bgcolor=green>
					30/11 Informazioni agg. ①<BR>
				<tr><td>
					23/11 Informazioni agg.<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>30/11 Informazioni agg. ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Scarface</font><BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>30/11 Informazioni agg. ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>【Scarface】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Combattente ferito<BR>Ho inseguito il wyvern <BR>ferito nella Giungla;<BR>però, essendo ferito<BR>anch'io, ho esaurito le<BR>forze. Vendica il mio<BR>onore e caccialo in mia<BR>vece!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60010.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					28/12 Informazioni agg.<BR>
					21/12 Informazioni agg.<BR>
					14/12 Informazioni agg.<BR>
					7/12 Informazioni agg.<BR>
					30/11 Informazioni agg. ③<BR>
					30/11 Informazioni agg. ②<BR>
					30/11 Informazioni agg. ①<BR>
				<tr><td bgcolor=green>
					23/11 Informazioni agg.<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>23/11 Informazioni agg.</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Il prossimo aggiornamento<BR>include la seguente<BR>Missione, nya:<BR><font color=orange>Il vento caldo e oscuro</font><BR><BR>Premi il tasto <img src=GIF/B_REC.gif width=16 height=16> per <BR>maggiori dettagli, miao!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/IT/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>23/11 Informazioni agg.</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Ecco una sbirciatina al prossimo aggiornamento!<BR>
<font color=orange>【Il vento caldo e oscuro】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Cliente:Gestore dell'arena<BR>L'Arena! Un luogo in cui<BR>mostrare al mondo le tue<BR>capacità! Per questo evento<BR>abbiamo messo nell'arena non<BR>uno, ma due terribili<BR>Gravios neri! Sei<BR>all'altezza di questa sfida?<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60012.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
</body>
</html>
