<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=2",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=2&pg_no=0",
		"RB_LINK=DB_INFO.PHP?lang=2&pg_no=2",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					16/11 Update-Informationen②<BR>
				<tr><td>
					16/11 Update-Informationen①<BR>
					9/11 Update-Informationen②<BR>
					9/11 Update-Informationen①<BR>
					2/11 Update-Informationen④<BR>
					2/11 Update-Informationen③<BR>
					2/11 Update-Informationen②<BR>
					2/11 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>16/11 Update-Informationen②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Challenge-Quest 11</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>16/11 Update-Informationen②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Challenge-Quest 11】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Ausbilder<BR>Ich bin's, dein Ausbilder.<BR>Der erste Schlag gegen ein <BR>schlafendes Monster fügt ihm<BR>großen Schaden zu. Wenn du <BR>es zuerst mit einer Bombe <BR>triffst, ist der Sieg zum <BR>Greifen nahe.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61011.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Update-Informationen②<BR>
				<tr><td bgcolor=green>
					16/11 Update-Informationen①<BR>
				<tr><td>
					9/11 Update-Informationen②<BR>
					9/11 Update-Informationen①<BR>
					2/11 Update-Informationen④<BR>
					2/11 Update-Informationen③<BR>
					2/11 Update-Informationen②<BR>
					2/11 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>16/11 Update-Informationen①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Starkes Schwert und Schild</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>16/11 Update-Informationen①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Starkes Schwert und Schild】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Arena-Manager<BR>Die Arena! Hier kann man der<BR>Welt sein Können zeigen!<BR>Heute haben wir zwei<BR>krabbengleiche Gegner in den<BR>Ring geschickt. Jeder, der<BR>sein Geschick testen möchte,<BR>ist willkommen!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60008.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Update-Informationen②<BR>
					16/11 Update-Informationen①<BR>
				<tr><td bgcolor=green>
					9/11 Update-Informationen②<BR>
				<tr><td>
					9/11 Update-Informationen①<BR>
					2/11 Update-Informationen④<BR>
					2/11 Update-Informationen③<BR>
					2/11 Update-Informationen②<BR>
					2/11 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>9/11 Update-Informationen②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Challenge-Quest 10</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>9/11 Update-Informationen②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Challenge-Quest 10】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Ausbilder<BR>Ich, dein Ausbilder, sage<BR>dir, dass sich männliche und<BR>weibliche Wyvern sehr <BR>unterschiedlich verhalten. <BR>Du musst alle Hilfsmittel <BR>und Fähigkeiten einsetzen, <BR>um sie zu besiegen.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61010.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Update-Informationen②<BR>
					16/11 Update-Informationen①<BR>
					9/11 Update-Informationen②<BR>
				<tr><td bgcolor=green>
					9/11 Update-Informationen①<BR>
				<tr><td>
					2/11 Update-Informationen④<BR>
					2/11 Update-Informationen③<BR>
					2/11 Update-Informationen②<BR>
					2/11 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>9/11 Update-Informationen①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Der geheimnisvolle Kut-Ku</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>9/11 Update-Informationen①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Der geheimnisvolle Kut-Ku】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Jägergilde<BR>Wir haben einen Notruf aus<BR>dem Dschungeldorf erhalten.<BR>Eine Gruppe seltsamer Kut-<BR>Kus ist aufgetaucht und<BR>verwüstet die Felder. Begib<BR>dich dorthin und bringe die<BR>Situation unter Kontrolle!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60023.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Update-Informationen②<BR>
					16/11 Update-Informationen①<BR>
					9/11 Update-Informationen②<BR>
					9/11 Update-Informationen①<BR>
				<tr><td bgcolor=green>
					2/11 Update-Informationen④<BR>
				<tr><td>
					2/11 Update-Informationen③<BR>
					2/11 Update-Informationen②<BR>
					2/11 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>2/11 Update-Informationen④</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update<BR>wird 3 Bonusobjekte<BR>enthalten! *schnurr*<BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>2/11 Update-Informationen④</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
Die Bonusobjekte werden hinzugefügt.
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
<font color=orange>Speckie-Mode:<BR>&nbsp;&nbsp;Schlafschwein&nbsp;weiß<BR>Wandernder Felyne-Koch:<BR>&nbsp;&nbsp;Pechschwrz<BR>Titel:<BR>&nbsp;&nbsp;Minnegard<BR>　　　　　　　　　　　　　　<br></font>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/b00002.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Update-Informationen②<BR>
					16/11 Update-Informationen①<BR>
					9/11 Update-Informationen②<BR>
					9/11 Update-Informationen①<BR>
					2/11 Update-Informationen④<BR>
				<tr><td bgcolor=green>
					2/11 Update-Informationen③<BR>
				<tr><td>
					2/11 Update-Informationen②<BR>
					2/11 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>2/11 Update-Informationen③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Challenge-Quest 9</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>2/11 Update-Informationen③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Challenge-Quest 9】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Ausbilder<BR>Ich bin's, dein Ausbilder.<BR>Jetzt kommt der Yian<BR>Garuga. Er ist sehr stark <BR>und du kannst ihm nicht mit <BR>halbherzigen Angriffen <BR>beikommen. Wie steht es mit <BR>deinen Bogenkünsten?<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/c61009.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Update-Informationen②<BR>
					16/11 Update-Informationen①<BR>
					9/11 Update-Informationen②<BR>
					9/11 Update-Informationen①<BR>
					2/11 Update-Informationen④<BR>
					2/11 Update-Informationen③<BR>
				<tr><td bgcolor=green>
					2/11 Update-Informationen②<BR>
				<tr><td>
					2/11 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>2/11 Update-Informationen②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Die Purpurkatastrophe</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>2/11 Update-Informationen②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Die Purpurkatastrophe】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Gildendirektor<BR>Fatalis ... Sein Zorn kann<BR>die Erde erschüttern und den<BR>Himmel verbrennen. Er ist<BR>die Verkörperung des Bösen.<BR>Jäger! Hört auf uns! Folgt<BR>seinem Gebrüll und erlegt<BR>den purpurnen Tod!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60016.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>２/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					16/11 Update-Informationen②<BR>
					16/11 Update-Informationen①<BR>
					9/11 Update-Informationen②<BR>
					9/11 Update-Informationen①<BR>
					2/11 Update-Informationen④<BR>
					2/11 Update-Informationen③<BR>
					2/11 Update-Informationen②<BR>
				<tr><td bgcolor=green>
					2/11 Update-Informationen①<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>2/11 Update-Informationen①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
Das nächste Update wird die<BR>folgenden Quest enthalten:<BR><font color=orange>Die grüne Saison</font><BR><BR>Drücke die <img src=GIF/B_REC.gif width=16 height=16>-Taste<BR>für mehr Details, miau!<BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/DE/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>2/11 Update-Informationen①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
Hier ein Ausblick auf den nächsten Download!<BR>
<font color=orange>【Die grüne Saison】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Klient:Hoffnungsvolle Magd<BR>Mein Bruder kehrt nach<BR>langer Abwesenheit endlich<BR>heim. Bitte erlege die<BR>Rathian-Brut, die sich auf<BR>den Hügeln beim Dorf<BR>tummelt, bevor sie ihn<BR>überfallen kann!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60007.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
</body>
</html>
