<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=1",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:3",
		"LB_LINK=DB_INFO.PHP?lang=1&pg_no=4",
		"RB_LINK=DB_INFO.PHP?lang=1&pg_no=1",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,0,16,0,417,185",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01 1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td bgcolor=green>
					12/28 Update Information<BR>
				<tr><td>
					12/21 Update Information<BR>
					12/14 Update Information<BR>
					12/7 Update Information<BR>
					11/30 Update Information ③<BR>
					11/30 Update Information ②<BR>
					11/30 Update Information ①<BR>
					11/23 Update Information<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>12/28 Update Information</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Anger of Heaven and Earth</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>12/28 Update Information</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Anger of Heaven and Earth】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Kokoto Village Chief<BR>It has been a long time my<BR>friends... Here is my<BR>challenge to you all! Defeat<BR>the two giant wyverns<BR>Rathalos and Rathian. Do you<BR>have the skill to drive them<BR>into submission?<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60022.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  02 1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					12/28 Update Information<BR>
				<tr><td bgcolor=green>
					12/21 Update Information<BR>
				<tr><td>
					12/14 Update Information<BR>
					12/7 Update Information<BR>
					11/30 Update Information ③<BR>
					11/30 Update Information ②<BR>
					11/30 Update Information ①<BR>
					11/23 Update Information<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>12/21 Update Information</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>The Visitor of Steel</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>12/21 Update Information</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【The Visitor of Steel】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Guild Master<BR>Emergency! Emergency! A<BR>brown Kushala Daora is<BR>closing in on our town! All<BR>hunters of worth should rush<BR>here as soon as possible! We<BR>need your help to save the<BR>town!!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60025.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  03 1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					12/28 Update Information<BR>
					12/21 Update Information<BR>
				<tr><td bgcolor=green>
					12/14 Update Information<BR>
				<tr><td>
					12/7 Update Information<BR>
					11/30 Update Information ③<BR>
					11/30 Update Information ②<BR>
					11/30 Update Information ①<BR>
					11/23 Update Information<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>12/14 Update Information</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Golden Thunder God</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>12/14 Update Information</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Golden Thunder God】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Arena Manager<BR>This is awful! Absolutely<BR>awful! A huge black monster<BR>took over my arena! With<BR>that thing in there, we<BR>can't do any business!! Get<BR>rid of it quickly! Please!!<BR>　　　　　　　　　　　　　　<br>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60019.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  04 1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					12/28 Update Information<BR>
					12/21 Update Information<BR>
					12/14 Update Information<BR>
				<tr><td bgcolor=green>
					12/7 Update Information<BR>
				<tr><td>
					11/30 Update Information ③<BR>
					11/30 Update Information ②<BR>
					11/30 Update Information ①<BR>
					11/23 Update Information<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>12/7 Update Information</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>The Remobra Den</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>12/7 Update Information</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【The Remobra Den】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Arena Manager<BR>The Arena! A place to show<BR>your skills to the world!<BR>Your opponents for this<BR>event are flying Remobras!<BR>With their poison filling<BR>the arena, it will take true<BR>courage to survive!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60018.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  05 1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					12/28 Update Information<BR>
					12/21 Update Information<BR>
					12/14 Update Information<BR>
					12/7 Update Information<BR>
				<tr><td bgcolor=green>
					11/30 Update Information ③<BR>
				<tr><td>
					11/30 Update Information ②<BR>
					11/30 Update Information ①<BR>
					11/23 Update Information<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>11/30 Update Information ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update will include<BR>2 new Bonus Items, meow!<BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR><BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>11/30 Update Information ③</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
The Bonus Items will be added.
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
<font color=orange>Title:<BR>&nbsp;&nbsp;Dondruma<BR>Peddling&nbsp;Granny's<BR>Special&nbsp;Items<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br></font>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/b00003.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  06 1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					12/28 Update Information<BR>
					12/21 Update Information<BR>
					12/14 Update Information<BR>
					12/7 Update Information<BR>
					11/30 Update Information ③<BR>
				<tr><td bgcolor=green>
					11/30 Update Information ②<BR>
				<tr><td>
					11/30 Update Information ①<BR>
					11/23 Update Information<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>11/30 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Ancestral Dragon</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>11/30 Update Information ②</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Ancestral Dragon】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Scarlet Mystery Man<BR>He he he... The time is<BR>come. Here is your<BR>invitation to the ball. Wear<BR>your Sunday best and bring<BR>your greatest weapon, for it<BR>is time to go to the dance<BR>with the king of disaster.<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60017.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  07 1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					12/28 Update Information<BR>
					12/21 Update Information<BR>
					12/14 Update Information<BR>
					12/7 Update Information<BR>
					11/30 Update Information ③<BR>
					11/30 Update Information ②<BR>
				<tr><td bgcolor=green>
					11/30 Update Information ①<BR>
				<tr><td>
					11/23 Update Information<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>11/30 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>Scarface</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>11/30 Update Information ①</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【Scarface】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Wounded Fighter<BR>I chased down the injured<BR>wyvern in the jungle;<BR>however, being injured<BR>myself, I reach the limit of<BR>my body's strength. Avenge<BR>my honor and hunt him down<BR>in my stead!<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60010.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
<!-- ########  08 1/2 ######################################################## -->
<a name=008></a>
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=2 4 2>
<tr>
	<td width=228>
		<table width=224 >
		<tr>
			<td>
				<table border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
				<tr>
					<td height=40 width=224 align=center valign=center>
						<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
							<tr>
								<td align=center>
								<B>１/５</B>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr><td>
					12/28 Update Information<BR>
					12/21 Update Information<BR>
					12/14 Update Information<BR>
					12/7 Update Information<BR>
					11/30 Update Information ③<BR>
					11/30 Update Information ②<BR>
					11/30 Update Information ①<BR>
				<tr><td bgcolor=green>
					11/23 Update Information<BR>
				</table>
			</td>
			<td width= 18>
			</td>
		</tr>
		</table>
	</td>
	<td width=242>
		<table width=238 background=GIF/KANBAN.gif height=187 cellspacing=0>
			<tr>
				<td align=center>
				<font size=2>
				<font color=yellow>11/23 Update Information</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=238>
				<font size=2><BR>
The next update is scheduled<BR>to include the following<BR>Quests, nya:<BR><font color=orange>The Hot, Dark Wind</font><BR><BR>Press the <img src=GIF/B_REC.gif width=16 height=16> button for more<BR>details, meow!<BR><BR>
				<BR>
				</font>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON5.gif></td></tr></table>
<!####### 08 2/2 #######-->
<img src=GIF/EN/LOGO14.gif width=200 height=50 alt="Information"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td>
		<table background=GIF/INFO_F.gif cellspacing=0 cellpadding width=468 height=188>
		<tr>
			<td width=468>
	<table width=458 height=177 cellspacing=1 cellpadding=0>
		<tr>
			<td height=16 align=center valign=top colspan=3>
				<font size=2>
				<font color=yellow>11/23 Update Information</font><br>
				</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td height=16 align=left colspan=2>
I'll let you in on what's in the next download.<BR>
<font color=orange>【The Hot, Dark Wind】</font>
			</td>
		</tr>
		<tr>
			<td width=5>
			</td>
			<td width=248 height=129 145 align=left valign=center>
				<font size=2>
Client:Arena Manager<BR>The Arena! A place to show<BR>your skills to the world!<BR>For this event, we have<BR>released not one, but two of<BR>the dreadful Black Gravios<BR>into the arena! Are you up<BR>to the challenge?<BR>
				</font>
			</td>
			<td width=200 height=129 align=center valign=center>
				<img src=PNG/e60012.png width=200 height=96><BR>
			</td>
		</tr>
	</table>
	</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/EN/BUTTON4.gif></td></tr></table>
</body>
</html>
