<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=3",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:7",
		"MOVE_CHAR=GIF/NEKO.gif,58,62,0,,16,,417,185",
		"MOVE_CHAR=GIF/PIG.gif,64,48,1,1,3,10,480,050",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,15,-50,180",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<img src=GIF/FR/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td><center>
		<table background=GIF/BONUS_F.gif cellspacing=0 cellpadding width=460 height=188>
		<form action="BONUS/bonus.mib" BDOWNLOAD method=post>
		<tr>
			<td width=460 height=136 valign=top>
			<BR>
　Tout les éléments bonus ont été libérés, miaou !<BR>
　Appuyer sur la touche <img src=GIF/B_REC.gif width=16 height=16> pour plus de détails.
			</td>
		</tr>
		<tr>
			<td height=27 align=center>
				<img ANIME=10 src=GIF/FR/BDL.gif width=210 height=27 alt="[X] DOWNLOAD"><BR>
				<input type=image src="" name=submit width=0 height=0>
			</td>
		</tr>
		<tr>
			<td align=right height=25>
			</td>
		</tr>
		</form>
		</table>
	</center></td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<a name=002></a>
<img src=GIF/FR/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td><center>
		<table background=GIF/BONUS_F.gif cellspacing=0 cellpadding=0 width=460 height=188>
		<tr>
			<td width=460 align=center>
				<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
						<B>１/６</B>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td width=460 height=64 80 valign=top>
<font color=orange>　Les éléments à télécharger sont en jaune, miaou.<BR></font>
　 -Mode Cochonet-<BR>
　Nouveaux vêtements pour Cochonet ajoutés !<BR>
<BR>
			</td>
		</tr>
		<tr>
			<td width=405 height=90 86 70 valign=top>
				<table width=405 cellspacing=0 cellpadding=0>
					<tr>
						<td width=200 valign=top>
　<a href=#002 qname=07>・Collant d'ange</a><BR>
　<a href=#002 qname=08>・Blanc endormi</a><BR>
						</td>
						<td width=205 align=right>
							<img src=PNG/bonus09.png width=200 height=90 86 70>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=right height=17 21>
			</td>
		</tr>
		</table>
	</center></td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<a name=003></a>
<img src=GIF/FR/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td><center>
		<table background=GIF/BONUS_F.gif cellspacing=0 cellpadding=0 width=460 height=188>
		<tr>
			<td width=460 align=center>
				<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
						<B>２/６</B>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td width=460 height=64 80 valign=top>
<font color=orange>　Les éléments à télécharger sont en jaune, miaou.<BR></font>
　 -Chef Felyne errant-<BR>
　Un Felyne coloré errerait dans le village.<BR>
　<BR>
			</td>
		</tr>
		<tr>
			<td width=405 height=90 86 70 valign=top>
				<table width=405 cellspacing=0 cellpadding=0>
					<tr>
						<td width=200 valign=top>
　<a href=#003 qname=00>・Tigre rge</a><BR>
　<a href=#003 qname=01>・Orange</a><BR>
　<a href=#003 qname=02>・Noir jais</a><BR>
						</td>
						<td width=205 align=right>
							<img src=PNG/bonus03.png width=200 height=90 86 70>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=right height=17 21>
			</td>
		</tr>
		</table>
	</center></td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<a name=004></a>
<img src=GIF/FR/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td><center>
		<table background=GIF/BONUS_F.gif cellspacing=0 cellpadding=0 width=460 height=188>
		<tr>
			<td width=460 align=center>
				<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
						<B>３/６</B>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td width=460 height=64 80 valign=top>
<font color=orange>　Les éléments à télécharger sont en jaune, miaou.<BR></font>
　 -Titres-<BR>
　Nouveaux titres ajoutés pour votre<BR>
　Carte de guilde, nya!<BR>
			</td>
		</tr>
		<tr>
			<td width=405 height=90 86 70 valign=top>
				<table width=405 cellspacing=0 cellpadding=0>
					<tr>
						<td width=200 valign=top>
　<a href=#004 qname=03>・Kokoto</a><BR>
　<a href=#004 qname=04>・Jumbo</a><BR>
　<a href=#004 qname=05>・Gardemine</a><BR>
　<a href=#004 qname=06>・Dondruma</a><BR>
						</td>
						<td width=205 align=right>
							<img src=PNG/bonus07.png width=200 height=90 86 70>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=right height=17 21>
			</td>
		</tr>
		</table>
	</center></td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<a name=005></a>
<img src=GIF/FR/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td><center>
		<table background=GIF/BONUS_F.gif cellspacing=0 cellpadding=0 width=460 height=188>
		<tr>
			<td width=460 align=center>
				<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
						<B>４/６</B>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td width=460 height=64 80 valign=top>
<font color=orange>　Les éléments à télécharger sont en jaune, miaou.<BR></font>
　 -Points Pokke-<BR>
　Vous pouvez gagner 1000 Points Pokke, nya.<BR>
<BR>
			</td>
		</tr>
		<tr>
			<td width=405 height=90 86 70 valign=top>
				<table width=405 cellspacing=0 cellpadding=0>
					<tr>
						<td width=200 valign=top>
　<a href=#005 qname=10>・1000 Points Pokke</a><BR>
						</td>
						<td width=205 align=right>
							<img src=PNG/bonus11.png width=200 height=90 86 70>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=right height=17 21>
			</td>
		</tr>
		</table>
	</center></td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<a name=006></a>
<img src=GIF/FR/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td><center>
		<table background=GIF/BONUS_F.gif cellspacing=0 cellpadding=0 width=460 height=188>
		<tr>
			<td width=460 align=center>
				<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
						<B>５/６</B>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td width=460 height=64 80 valign=top>
<font color=orange>　Les éléments à télécharger sont en jaune, miaou.<BR></font>
　 -Équipement de ferme-<BR>
　Vous pouvez ajouter le bateau de Trenya<BR>
　à la ferme, nya.<BR>
			</td>
		</tr>
		<tr>
			<td width=405 height=90 86 70 valign=top>
				<table width=405 cellspacing=0 cellpadding=0>
					<tr>
						<td width=200 valign=top>
　<a href=#006 qname=11>・bateau de Trenyat</a><BR>
						</td>
						<td width=205 align=right>
							<img src=PNG/bonus12.png width=200 height=90 86 70>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=right height=17 21>
			</td>
		</tr>
		</table>
	</center></td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<a name=007></a>
<img src=GIF/FR/LOGO13.gif width=200 height=50 alt="Bonus"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=4>
<tr>
	<td><center>
		<table background=GIF/BONUS_F.gif cellspacing=0 cellpadding=0 width=460 height=188>
		<tr>
			<td width=460 align=center>
				<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
					<tr>
						<td align=center>
						<B>６/６</B>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td width=460 height=64 80 valign=top>
<font color=orange>　Les éléments à télécharger sont en jaune, miaou.<BR></font>
　 -Les objets de Mémé colporteuse-<BR>
　La Mémé colporteuse a des objets encore<BR>
　meilleurs que d'habitude, nya!<BR>
			</td>
		</tr>
		<tr>
			<td width=405 height=90 86 70 valign=top>
				<table width=405 cellspacing=0 cellpadding=0>
					<tr>
						<td width=200 valign=top>
　<a href=#007 qname=12>・Objets spéciaux</a><BR>
						</td>
						<td width=205 align=right>
							<img src=PNG/bonus13.png width=200 height=90 86 70>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=right height=17 21>
			</td>
		</tr>
		</table>
	</center></td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
</body>
</html>
