<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=5",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_CMENU.PHP?lang=5&pg_no=0",
		"RB_LINK=DL_CMENU.PHP?lang=5&pg_no=0",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61004.mib" DOWNLOAD CSUM=13681 FSIZE=6732 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m61004.mib>Missione Sfida 4</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m61003.mib>Missione Sfida 3</a><BR>
					<a href=#003 qname=m61002.mib>Missione Sfida 2</a><BR>
					<a href=#004 qname=m61001.mib>Missione Sfida 1</a><BR>
					<BR>
					<BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. uccisione</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Missione Sfida 4
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 4200z<br>
<font color=orange>Contratto：</font> 0z<br>
<font color=orange>Tempo　　：</font> 30minuti<br>
<font color=orange>Zona 　　：</font> MontNev(notte)<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 1 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. uccisione</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Missione Sfida 4
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi il Blangonga<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Istruttore<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Sono io, il tuo stimato<BR>istruttore. Ora affronterai<BR>un Blangonga. Per batterlo<BR>rapidamente, devi<BR>concentrare i tuoi attacchi.<BR>Fai breccia nelle sue difese<BR>e colpisci con ferocia.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61003.mib" DOWNLOAD CSUM=18765 FSIZE=6852 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61004.mib>Missione Sfida 4</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m61003.mib>Missione Sfida 3</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m61002.mib>Missione Sfida 2</a><BR>
					<a href=#004 qname=m61001.mib>Missione Sfida 1</a><BR>
					<BR>
					<BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. uccisione</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Missione Sfida 3
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 3000z<br>
<font color=orange>Contratto：</font> 0z<br>
<font color=orange>Tempo　　：</font> 30minuti<br>
<font color=orange>Zona 　　：</font> Giungla(notte)<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 1 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. uccisione</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Missione Sfida 3
			</td>
			<td>
				&nbsp;★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi il Plesioth<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Istruttore<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Sono io, il tuo stimato<BR>istruttore. La tua prossima<BR>sfida è nella Giungla. Una<BR>frana ha bloccato la strada<BR>e le Bombe-botte non<BR>funzionano con la pioggia,<BR>quindi usa qualcos'altro!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61002.mib" DOWNLOAD CSUM=44012 FSIZE=3248 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61004.mib>Missione Sfida 4</a><BR>
					<a href=#002 qname=m61003.mib>Missione Sfida 3</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m61002.mib>Missione Sfida 2</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m61001.mib>Missione Sfida 1</a><BR>
					<BR>
					<BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. uccisione</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Missione Sfida 2
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 3000z<br>
<font color=orange>Contratto：</font> 0z<br>
<font color=orange>Tempo　　：</font> 30minuti<br>
<font color=orange>Zona 　　：</font> Grande arena<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 1 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. uccisione</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Missione Sfida 2
			</td>
			<td>
				&nbsp;★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi il Daimyo Hermitaur<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Istruttore<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Sono io, il tuo stimato<BR>istruttore. L'esercitazione<BR>di oggi è contro due Daimyo<BR>Hermitaur; basta ucciderne<BR>uno per concludere. Usa le<BR>Palle-pittura e concentra i<BR>tuoi attacchi!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61001.mib" DOWNLOAD CSUM=54161 FSIZE=4932 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61004.mib>Missione Sfida 4</a><BR>
					<a href=#002 qname=m61003.mib>Missione Sfida 3</a><BR>
					<a href=#003 qname=m61002.mib>Missione Sfida 2</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m61001.mib>Missione Sfida 1</a><BR>
			<tr><td height=62 valign=top>
					<BR>
					<BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. uccisione</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Missione Sfida 1
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 3000z<br>
<font color=orange>Contratto：</font> 0z<br>
<font color=orange>Tempo　　：</font> 30minuti<br>
<font color=orange>Zona 　　：</font> Palude(notte)<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 1 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. uccisione</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Missione Sfida 1
			</td>
			<td>
				&nbsp;★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi il Gypceros e il<BR>Gypceros viola<BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Istruttore<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Sono io, il tuo stimato<BR>istruttore. Due Gypceros<BR>contemporaneamente non vanno<BR>presi alla leggera. Separali<BR>e concentra gli attacchi su<BR>uno o combattili insieme.<BR>Non c'è un'unica via!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
</body>
</html>
