<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=4",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_CMENU.PHP?lang=4&pg_no=1",
		"RB_LINK=DL_CMENU.PHP?lang=4&pg_no=1",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61011.mib" DOWNLOAD CSUM=37412 FSIZE=3100 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m61011.mib>Misión de desafío 11</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m61010.mib>Misión de desafío 10</a><BR>
					<a href=#003 qname=m61009.mib>Misión de desafío 9</a><BR>
					<a href=#004 qname=m61008.mib>Misión de desafío 8</a><BR>
					<a href=#005 qname=m61007.mib>Misión de desafío 7</a><BR>
					<a href=#006 qname=m61006.mib>Misión de desafío 6</a><BR>
					<a href=#007 qname=m61005.mib>Misión de desafío 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión matanza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Misión de desafío 11
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 1200z<br>
<font color=orange>Contrato ：</font> 0z<br>
<font color=orange>Tiempo 　：</font> 30min<br>
<font color=orange>Zona 　　：</font> Gran arena<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 1 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión matanza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Misión de desafío 11
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Mata al Gravios negro <BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero <BR>Fin del tiempo <BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Instructor<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Soy tu querido instructor.<BR>El primer golpe contra<BR>un enemigo que duerme<BR>hace un daño tremendo<BR>Empieza por colocarle una<BR>bomba y te alzarás<BR>victorioso de un plumazo.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61010.mib" DOWNLOAD CSUM=1332 FSIZE=5220 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Misión de desafío 11</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m61010.mib>Misión de desafío 10</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m61009.mib>Misión de desafío 9</a><BR>
					<a href=#004 qname=m61008.mib>Misión de desafío 8</a><BR>
					<a href=#005 qname=m61007.mib>Misión de desafío 7</a><BR>
					<a href=#006 qname=m61006.mib>Misión de desafío 6</a><BR>
					<a href=#007 qname=m61005.mib>Misión de desafío 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión matanza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Misión de desafío 10
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 6000z<br>
<font color=orange>Contrato ：</font> 0z<br>
<font color=orange>Tiempo 　：</font> 40min<br>
<font color=orange>Zona 　　：</font> Bosque y colinas<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 4 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión matanza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Misión de desafío 10
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Mata al Rathalos y la<BR>Rathian <BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero <BR>Fin del tiempo <BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Instructor<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
En mi calidad de querido <BR>instructor, debo informarte<BR>de que los Wyverns de fuego<BR>macho y hembra se comportan<BR>de forma muy distinta.<BR>Usa todas tus herramientas<BR>y habilidades de cazador.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61009.mib" DOWNLOAD CSUM=29136 FSIZE=7444 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Misión de desafío 11</a><BR>
					<a href=#002 qname=m61010.mib>Misión de desafío 10</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m61009.mib>Misión de desafío 9</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m61008.mib>Misión de desafío 8</a><BR>
					<a href=#005 qname=m61007.mib>Misión de desafío 7</a><BR>
					<a href=#006 qname=m61006.mib>Misión de desafío 6</a><BR>
					<a href=#007 qname=m61005.mib>Misión de desafío 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión matanza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Misión de desafío 9
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 4500z<br>
<font color=orange>Contrato ：</font> 0z<br>
<font color=orange>Tiempo 　：</font> 30min<br>
<font color=orange>Zona 　　：</font> Jungla(N)<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 1 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión matanza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Misión de desafío 9
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Mata al Yian Garuga <BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero <BR>Fin del tiempo <BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Instructor<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Soy tu querido instructor.<BR>Pasemos ahora al Yian<BR>Garuga. Es una bestia muy<BR>capaz. Para estar a su<BR>altura debes esmerarte.<BR>Tal vez debas pulir tu<BR>estilo con el Arco.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61008.mib" DOWNLOAD CSUM=38065 FSIZE=3108 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Misión de desafío 11</a><BR>
					<a href=#002 qname=m61010.mib>Misión de desafío 10</a><BR>
					<a href=#003 qname=m61009.mib>Misión de desafío 9</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m61008.mib>Misión de desafío 8</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m61007.mib>Misión de desafío 7</a><BR>
					<a href=#006 qname=m61006.mib>Misión de desafío 6</a><BR>
					<a href=#007 qname=m61005.mib>Misión de desafío 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión matanza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Misión de desafío 8
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 6000z<br>
<font color=orange>Contrato ：</font> 0z<br>
<font color=orange>Tiempo 　：</font> 30min<br>
<font color=orange>Zona 　　：</font> Gran arena<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 4 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión matanza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Misión de desafío 8
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Mata a 2 Tigrex<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero <BR>Fin del tiempo <BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Instructor<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Soy tu querido instructor.<BR>¡Hoy te verás las caras<BR>contra dos Tigrex! Cuando<BR>rabian, no hay quien los<BR>toque, pero puedes valerte<BR>de tu habilidad para crear<BR>oportunidades de ataque.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61007.mib" DOWNLOAD CSUM=44630 FSIZE=7768 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Misión de desafío 11</a><BR>
					<a href=#002 qname=m61010.mib>Misión de desafío 10</a><BR>
					<a href=#003 qname=m61009.mib>Misión de desafío 9</a><BR>
					<a href=#004 qname=m61008.mib>Misión de desafío 8</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m61007.mib>Misión de desafío 7</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m61006.mib>Misión de desafío 6</a><BR>
					<a href=#007 qname=m61005.mib>Misión de desafío 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión matanza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Misión de desafío 7
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 1200z<br>
<font color=orange>Contrato ：</font> 0z<br>
<font color=orange>Tiempo 　：</font> 10min<br>
<font color=orange>Zona 　　：</font> Jungla(D)<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 1 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión matanza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Misión de desafío 7
			</td>
			<td>
				&nbsp;★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Mata a 30 Velocipreys<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero <BR>Fin del tiempo <BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Instructor<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Soy tu querido instructor.<BR>Al cazar, siempre hay un<BR>camino que es el más apto<BR>para la misión. ¿Cuál es la<BR>mejor ruta? Ya deberías ser<BR>capaz de decidirlo tú mismo.<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61006.mib" DOWNLOAD CSUM=30302 FSIZE=3460 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Misión de desafío 11</a><BR>
					<a href=#002 qname=m61010.mib>Misión de desafío 10</a><BR>
					<a href=#003 qname=m61009.mib>Misión de desafío 9</a><BR>
					<a href=#004 qname=m61008.mib>Misión de desafío 8</a><BR>
					<a href=#005 qname=m61007.mib>Misión de desafío 7</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m61006.mib>Misión de desafío 6</a><BR>
			<tr><td height=30 valign=top>
					<a href=#007 qname=m61005.mib>Misión de desafío 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión matanza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Misión de desafío 6
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 300z<br>
<font color=orange>Contrato ：</font> 0z<br>
<font color=orange>Tiempo 　：</font> 15min<br>
<font color=orange>Zona 　　：</font> Gran arena<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 1 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión matanza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Misión de desafío 6
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Mata al Bulldrome <BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero <BR>Fin del tiempo <BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Instructor<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Soy tu querido instructor.<BR>¡Hoy te verás las caras con<BR>un Bulldrome! ¡No te burles<BR>de esta misión! A estas<BR>alturas ya habrás aprendido<BR>que siempre hay un pez<BR>más grande en el agua.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61005.mib" DOWNLOAD CSUM=38044 FSIZE=3212 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Misión de desafío 11</a><BR>
					<a href=#002 qname=m61010.mib>Misión de desafío 10</a><BR>
					<a href=#003 qname=m61009.mib>Misión de desafío 9</a><BR>
					<a href=#004 qname=m61008.mib>Misión de desafío 8</a><BR>
					<a href=#005 qname=m61007.mib>Misión de desafío 7</a><BR>
					<a href=#006 qname=m61006.mib>Misión de desafío 6</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m61005.mib>Misión de desafío 5</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión matanza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Misión de desafío 5
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 5100z<br>
<font color=orange>Contrato ：</font> 0z<br>
<font color=orange>Tiempo 　：</font> 15min<br>
<font color=orange>Zona 　　：</font> Gran arena<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 4 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/ES/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión matanza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Misión de desafío 5
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Mata al Shogun Ceanataur<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero <BR>Fin del tiempo <BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Instructor<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Soy tu querido instructor.<BR>Hoy practicaremos contra<BR>dos Shogun Ceanataurs, pero<BR>sólo tienes que matar a uno<BR>para completar la misión.<BR>¡Demuéstrame tus<BR>verdaderas habilidades!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
</body>
</html>
