<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=5",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_CMENU.PHP?lang=5&pg_no=1",
		"RB_LINK=DL_CMENU.PHP?lang=5&pg_no=1",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61011.mib" DOWNLOAD CSUM=37412 FSIZE=3100 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m61011.mib>Missione Sfida 11</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m61010.mib>Missione Sfida 10</a><BR>
					<a href=#003 qname=m61009.mib>Missione Sfida 9</a><BR>
					<a href=#004 qname=m61008.mib>Missione Sfida 8</a><BR>
					<a href=#005 qname=m61007.mib>Missione Sfida 7</a><BR>
					<a href=#006 qname=m61006.mib>Missione Sfida 6</a><BR>
					<a href=#007 qname=m61005.mib>Missione Sfida 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. uccisione</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Missione Sfida 11
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 1200z<br>
<font color=orange>Contratto：</font> 0z<br>
<font color=orange>Tempo　　：</font> 30minuti<br>
<font color=orange>Zona 　　：</font> Grande arena<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 1 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. uccisione</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Missione Sfida 11
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi il Gravios nero<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Istruttore<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Sono io, il tuo stimato<BR>istruttore. Il primo colpo a<BR>un nemico addormentato crea<BR>tremendi danni. Inizia<BR>l'attacco colpendolo con una<BR>bomba e la vittoria sarà a<BR>portata di mano!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61010.mib" DOWNLOAD CSUM=1332 FSIZE=5220 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Missione Sfida 11</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m61010.mib>Missione Sfida 10</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m61009.mib>Missione Sfida 9</a><BR>
					<a href=#004 qname=m61008.mib>Missione Sfida 8</a><BR>
					<a href=#005 qname=m61007.mib>Missione Sfida 7</a><BR>
					<a href=#006 qname=m61006.mib>Missione Sfida 6</a><BR>
					<a href=#007 qname=m61005.mib>Missione Sfida 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. uccisione</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Missione Sfida 10
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 6000z<br>
<font color=orange>Contratto：</font> 0z<br>
<font color=orange>Tempo　　：</font> 40minuti<br>
<font color=orange>Zona 　　：</font> Foresta e coll.<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 4 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. uccisione</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Missione Sfida 10
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi il Rathalos e la<BR>Rathian<BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Istruttore<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Come tuo stimato istruttore,<BR>devo dirti che i maschi e le<BR>femmine degli wyvern di<BR>fuoco si comportano in modo<BR>diverso. Per sconfiggerli,<BR>devi usare tutti i mezzi e<BR>tutte le tue capacità.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61009.mib" DOWNLOAD CSUM=29136 FSIZE=7444 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Missione Sfida 11</a><BR>
					<a href=#002 qname=m61010.mib>Missione Sfida 10</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m61009.mib>Missione Sfida 9</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m61008.mib>Missione Sfida 8</a><BR>
					<a href=#005 qname=m61007.mib>Missione Sfida 7</a><BR>
					<a href=#006 qname=m61006.mib>Missione Sfida 6</a><BR>
					<a href=#007 qname=m61005.mib>Missione Sfida 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. uccisione</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Missione Sfida 9
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 4500z<br>
<font color=orange>Contratto：</font> 0z<br>
<font color=orange>Tempo　　：</font> 30minuti<br>
<font color=orange>Zona 　　：</font> Giungla(notte)<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 1 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. uccisione</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Missione Sfida 9
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi lo Yian Garuga<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Istruttore<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Sono io, il tuo stimato<BR>istruttore. Il prossimo è<BR>uno Yian Garuga. È sveglio,<BR>quindi non potrai essere<BR>all'altezza se non ti<BR>impegnerai totalmente. Forse<BR>dovresti provare con l'Arco.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61008.mib" DOWNLOAD CSUM=38065 FSIZE=3108 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Missione Sfida 11</a><BR>
					<a href=#002 qname=m61010.mib>Missione Sfida 10</a><BR>
					<a href=#003 qname=m61009.mib>Missione Sfida 9</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m61008.mib>Missione Sfida 8</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m61007.mib>Missione Sfida 7</a><BR>
					<a href=#006 qname=m61006.mib>Missione Sfida 6</a><BR>
					<a href=#007 qname=m61005.mib>Missione Sfida 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. uccisione</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Missione Sfida 8
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 6000z<br>
<font color=orange>Contratto：</font> 0z<br>
<font color=orange>Tempo　　：</font> 30minuti<br>
<font color=orange>Zona 　　：</font> Grande arena<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 4 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. uccisione</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Missione Sfida 8
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi 2 Tigrex<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Istruttore<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Sono io, il tuo stimato<BR>istruttore. Oggi affronterai<BR>non uno, ma due Tigrex di<BR>seguito! Se arrabbiati sono<BR>intoccabili, ma puoi usare<BR>le tue abilità e creare le<BR>occasioni per attaccare.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61007.mib" DOWNLOAD CSUM=44630 FSIZE=7768 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Missione Sfida 11</a><BR>
					<a href=#002 qname=m61010.mib>Missione Sfida 10</a><BR>
					<a href=#003 qname=m61009.mib>Missione Sfida 9</a><BR>
					<a href=#004 qname=m61008.mib>Missione Sfida 8</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m61007.mib>Missione Sfida 7</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m61006.mib>Missione Sfida 6</a><BR>
					<a href=#007 qname=m61005.mib>Missione Sfida 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. uccisione</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Missione Sfida 7
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 1200z<br>
<font color=orange>Contratto：</font> 0z<br>
<font color=orange>Tempo　　：</font> 10minuti<br>
<font color=orange>Zona 　　：</font> Giungla(giorno)<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 1 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. uccisione</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Missione Sfida 7
			</td>
			<td>
				&nbsp;★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi 30 Velociprey<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Istruttore<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Sono io, il tuo stimato<BR>istruttore. Quando si è a<BR>caccia, c'è sempre un<BR>percorso che è il più adatto<BR>alla missione in corso. Qual<BR>è il migliore? Ormai<BR>dovresti capirlo da solo!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61006.mib" DOWNLOAD CSUM=30302 FSIZE=3460 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Missione Sfida 11</a><BR>
					<a href=#002 qname=m61010.mib>Missione Sfida 10</a><BR>
					<a href=#003 qname=m61009.mib>Missione Sfida 9</a><BR>
					<a href=#004 qname=m61008.mib>Missione Sfida 8</a><BR>
					<a href=#005 qname=m61007.mib>Missione Sfida 7</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m61006.mib>Missione Sfida 6</a><BR>
			<tr><td height=30 valign=top>
					<a href=#007 qname=m61005.mib>Missione Sfida 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. uccisione</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Missione Sfida 6
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 300z<br>
<font color=orange>Contratto：</font> 0z<br>
<font color=orange>Tempo　　：</font> 15minuti<br>
<font color=orange>Zona 　　：</font> Grande arena<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 1 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. uccisione</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Missione Sfida 6
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi il Bulldrome<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Istruttore<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Sono io, il tuo stimato<BR>istruttore. Oggi affronterai<BR>un Bulldrome! Non schernire<BR>questa missione... Ormai<BR>dovresti avere imparato che<BR>nel mare c'è sempre un pesce<BR>più grande.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61005.mib" DOWNLOAD CSUM=38044 FSIZE=3212 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Missione Sfida 11</a><BR>
					<a href=#002 qname=m61010.mib>Missione Sfida 10</a><BR>
					<a href=#003 qname=m61009.mib>Missione Sfida 9</a><BR>
					<a href=#004 qname=m61008.mib>Missione Sfida 8</a><BR>
					<a href=#005 qname=m61007.mib>Missione Sfida 7</a><BR>
					<a href=#006 qname=m61006.mib>Missione Sfida 6</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m61005.mib>Missione Sfida 5</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. uccisione</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Missione Sfida 5
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 5100z<br>
<font color=orange>Contratto：</font> 0z<br>
<font color=orange>Tempo　　：</font> 15minuti<br>
<font color=orange>Zona 　　：</font> Grande arena<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 4 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/IT/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. uccisione</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Missione Sfida 5
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi lo Shogun Ceanataur<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Istruttore<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Sono io, il tuo stimato<BR>istruttore. L'esercitazione<BR>di oggi è contro due Shogun<BR>Ceanataur; basta ucciderne<BR>uno per concludere la<BR>missione. Mostrami le tue<BR>vere capacità!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
</body>
</html>
