<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=2",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_CMENU.PHP?lang=2&pg_no=1",
		"RB_LINK=DL_CMENU.PHP?lang=2&pg_no=1",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61011.mib" DOWNLOAD CSUM=37412 FSIZE=3100 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m61011.mib>Challenge-Quest 11</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m61010.mib>Challenge-Quest 10</a><BR>
					<a href=#003 qname=m61009.mib>Challenge-Quest 9</a><BR>
					<a href=#004 qname=m61008.mib>Challenge-Quest 8</a><BR>
					<a href=#005 qname=m61007.mib>Challenge-Quest 7</a><BR>
					<a href=#006 qname=m61006.mib>Challenge-Quest 6</a><BR>
					<a href=#007 qname=m61005.mib>Challenge-Quest 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Tötungsquest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Challenge-Quest 11
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 1200z<br>
<font color=orange>Gebühr 　：</font> 0z<br>
<font color=orange>Zeit 　　：</font> 30min<br>
<font color=orange>Zone 　　：</font> Große Arena<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  1 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Tötungsquest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Challenge-Quest 11
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Den schwarzen Gravios töten<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Ausbilder<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Ich bin's, dein Ausbilder.<BR>Der erste Schlag gegen ein <BR>schlafendes Monster fügt ihm<BR>großen Schaden zu. Wenn du <BR>es zuerst mit einer Bombe <BR>triffst, ist der Sieg zum <BR>Greifen nahe.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61010.mib" DOWNLOAD CSUM=1332 FSIZE=5220 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Challenge-Quest 11</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m61010.mib>Challenge-Quest 10</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m61009.mib>Challenge-Quest 9</a><BR>
					<a href=#004 qname=m61008.mib>Challenge-Quest 8</a><BR>
					<a href=#005 qname=m61007.mib>Challenge-Quest 7</a><BR>
					<a href=#006 qname=m61006.mib>Challenge-Quest 6</a><BR>
					<a href=#007 qname=m61005.mib>Challenge-Quest 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Tötungsquest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Challenge-Quest 10
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 6000z<br>
<font color=orange>Gebühr 　：</font> 0z<br>
<font color=orange>Zeit 　　：</font> 40min<br>
<font color=orange>Zone 　　：</font> Wald&Hügel<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  4 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Tötungsquest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Challenge-Quest 10
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Rathalos und Rathian töten<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Ausbilder<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Ich, dein Ausbilder, sage<BR>dir, dass sich männliche und<BR>weibliche Wyvern sehr <BR>unterschiedlich verhalten. <BR>Du musst alle Hilfsmittel <BR>und Fähigkeiten einsetzen, <BR>um sie zu besiegen.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61009.mib" DOWNLOAD CSUM=29136 FSIZE=7444 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Challenge-Quest 11</a><BR>
					<a href=#002 qname=m61010.mib>Challenge-Quest 10</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m61009.mib>Challenge-Quest 9</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m61008.mib>Challenge-Quest 8</a><BR>
					<a href=#005 qname=m61007.mib>Challenge-Quest 7</a><BR>
					<a href=#006 qname=m61006.mib>Challenge-Quest 6</a><BR>
					<a href=#007 qname=m61005.mib>Challenge-Quest 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Tötungsquest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Challenge-Quest 9
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 4500z<br>
<font color=orange>Gebühr 　：</font> 0z<br>
<font color=orange>Zeit 　　：</font> 30min<br>
<font color=orange>Zone 　　：</font> Dschungel(Nacht)<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  1 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Tötungsquest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Challenge-Quest 9
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Den Yian Garuga töten<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Ausbilder<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Ich bin's, dein Ausbilder.<BR>Jetzt kommt der Yian<BR>Garuga. Er ist sehr stark <BR>und du kannst ihm nicht mit <BR>halbherzigen Angriffen <BR>beikommen. Wie steht es mit <BR>deinen Bogenkünsten?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61008.mib" DOWNLOAD CSUM=38065 FSIZE=3108 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Challenge-Quest 11</a><BR>
					<a href=#002 qname=m61010.mib>Challenge-Quest 10</a><BR>
					<a href=#003 qname=m61009.mib>Challenge-Quest 9</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m61008.mib>Challenge-Quest 8</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m61007.mib>Challenge-Quest 7</a><BR>
					<a href=#006 qname=m61006.mib>Challenge-Quest 6</a><BR>
					<a href=#007 qname=m61005.mib>Challenge-Quest 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Tötungsquest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Challenge-Quest 8
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 6000z<br>
<font color=orange>Gebühr 　：</font> 0z<br>
<font color=orange>Zeit 　　：</font> 30min<br>
<font color=orange>Zone 　　：</font> Große Arena<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  4 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Tötungsquest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Challenge-Quest 8
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>2 Tigrexe töten<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Ausbilder<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Ich bin's, dein Ausbilder.<BR>Heute musst du gegen zwei <BR>Tigrexe hintereinander <BR>antreten. Im Zorn sind sie <BR>unangreifbar, aber du kannst<BR>dir durchaus Gelegenheiten <BR>zum Angriff eröffnen. <BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61007.mib" DOWNLOAD CSUM=44630 FSIZE=7768 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Challenge-Quest 11</a><BR>
					<a href=#002 qname=m61010.mib>Challenge-Quest 10</a><BR>
					<a href=#003 qname=m61009.mib>Challenge-Quest 9</a><BR>
					<a href=#004 qname=m61008.mib>Challenge-Quest 8</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m61007.mib>Challenge-Quest 7</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m61006.mib>Challenge-Quest 6</a><BR>
					<a href=#007 qname=m61005.mib>Challenge-Quest 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Tötungsquest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Challenge-Quest 7
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 1200z<br>
<font color=orange>Gebühr 　：</font> 0z<br>
<font color=orange>Zeit 　　：</font> 10min<br>
<font color=orange>Zone 　　：</font> Dschungel(Tag)<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  1 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Tötungsquest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Challenge-Quest 7
			</td>
			<td>
				&nbsp;★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>30 Velocipreys töten<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Ausbilder<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Ich bin's, dein Ausbilder.<BR>Bei jeder Quest gibt es <BR>einen optimalen Weg. Welche <BR>Route ist die beste? Das <BR>musst du inzwischen selbst <BR>herausfinden können!<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61006.mib" DOWNLOAD CSUM=30302 FSIZE=3460 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Challenge-Quest 11</a><BR>
					<a href=#002 qname=m61010.mib>Challenge-Quest 10</a><BR>
					<a href=#003 qname=m61009.mib>Challenge-Quest 9</a><BR>
					<a href=#004 qname=m61008.mib>Challenge-Quest 8</a><BR>
					<a href=#005 qname=m61007.mib>Challenge-Quest 7</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m61006.mib>Challenge-Quest 6</a><BR>
			<tr><td height=30 valign=top>
					<a href=#007 qname=m61005.mib>Challenge-Quest 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Tötungsquest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Challenge-Quest 6
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 300z<br>
<font color=orange>Gebühr 　：</font> 0z<br>
<font color=orange>Zeit 　　：</font> 15min<br>
<font color=orange>Zone 　　：</font> Große Arena<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  1 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Tötungsquest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Challenge-Quest 6
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Den Bulldrome töten<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Ausbilder<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Ich bin's, dein Ausbilder.<BR>Heute geht es gegen einen <BR>Bulldrome! Mach dich nicht <BR>darüber lustig. Du solltest <BR>inzwischen wissen, dass es <BR>immer noch größere Brocken <BR>gibt.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61005.mib" DOWNLOAD CSUM=38044 FSIZE=3212 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Challenge-Quest 11</a><BR>
					<a href=#002 qname=m61010.mib>Challenge-Quest 10</a><BR>
					<a href=#003 qname=m61009.mib>Challenge-Quest 9</a><BR>
					<a href=#004 qname=m61008.mib>Challenge-Quest 8</a><BR>
					<a href=#005 qname=m61007.mib>Challenge-Quest 7</a><BR>
					<a href=#006 qname=m61006.mib>Challenge-Quest 6</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m61005.mib>Challenge-Quest 5</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Tötungsquest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Challenge-Quest 5
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 5100z<br>
<font color=orange>Gebühr 　：</font> 0z<br>
<font color=orange>Zeit 　　：</font> 15min<br>
<font color=orange>Zone 　　：</font> Große Arena<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  4 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/DE/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Tötungsquest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Challenge-Quest 5
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Den Shogun Ceanataur töten<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Ausbilder<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Ich bin's, dein Ausbilder.<BR>Heute geht es gegen zwei <BR>Shogun Ceanatauren, aber du <BR>musst nur einen töten, um <BR>die Quest zu erfüllen. Zeig <BR>uns deine wahre Stärke!<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
</body>
</html>
