<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=3",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_CMENU.PHP?lang=3&pg_no=1",
		"RB_LINK=DL_CMENU.PHP?lang=3&pg_no=1",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61011.mib" DOWNLOAD CSUM=37412 FSIZE=3100 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m61011.mib>Quête défi 11</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m61010.mib>Quête défi 10</a><BR>
					<a href=#003 qname=m61009.mib>Quête défi 9</a><BR>
					<a href=#004 qname=m61008.mib>Quête défi 8</a><BR>
					<a href=#005 qname=m61007.mib>Quête défi 7</a><BR>
					<a href=#006 qname=m61006.mib>Quête défi 6</a><BR>
					<a href=#007 qname=m61005.mib>Quête défi 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête massacre</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Quête défi 11
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 1200z<br>
<font color=orange>Contrat：</font> 0z<br>
<font color=orange>Temps　：</font> 30min.<br>
<font color=orange>Zone 　：</font> Grande arène<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 1 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête massacre</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Quête défi 11
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tuer le Gravios noir<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Instructeur<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
C'est moi, votre instructeur<BR>estimé. Le premier<BR>coup porté à un ennemi<BR>endormi est dévastateur.<BR>Ajoutez une bombe et<BR>la victoire sera à<BR>portée de main !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61010.mib" DOWNLOAD CSUM=1332 FSIZE=5220 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Quête défi 11</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m61010.mib>Quête défi 10</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m61009.mib>Quête défi 9</a><BR>
					<a href=#004 qname=m61008.mib>Quête défi 8</a><BR>
					<a href=#005 qname=m61007.mib>Quête défi 7</a><BR>
					<a href=#006 qname=m61006.mib>Quête défi 6</a><BR>
					<a href=#007 qname=m61005.mib>Quête défi 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête massacre</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Quête défi 10
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 6000z<br>
<font color=orange>Contrat：</font> 0z<br>
<font color=orange>Temps　：</font> 40min.<br>
<font color=orange>Zone 　：</font> Forêt&col.<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 4 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête massacre</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Quête défi 10
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tuer le Rathalos<BR>et la Rathian<BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Instructeur<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Moi, votre instructeur<BR>estimé, ai le devoir de vous<BR>prévenir que les Wyvern de<BR>feu mâles et femelles se<BR>comportent différemment.<BR>Utilisez vos outiles et<BR>talents pour les vaincre.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61009.mib" DOWNLOAD CSUM=29136 FSIZE=7444 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Quête défi 11</a><BR>
					<a href=#002 qname=m61010.mib>Quête défi 10</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m61009.mib>Quête défi 9</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m61008.mib>Quête défi 8</a><BR>
					<a href=#005 qname=m61007.mib>Quête défi 7</a><BR>
					<a href=#006 qname=m61006.mib>Quête défi 6</a><BR>
					<a href=#007 qname=m61005.mib>Quête défi 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête massacre</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Quête défi 9
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 4500z<br>
<font color=orange>Contrat：</font> 0z<br>
<font color=orange>Temps　：</font> 30min.<br>
<font color=orange>Zone 　：</font> Jungle(nuit)<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 1 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête massacre</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Quête défi 9
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tuer le Yian Garuga<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Instructeur<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
C'est moi, votre instructeur<BR>estimé. Voici venir le<BR>Yian Garuga. C'est une bête<BR>douée, des efforts à moitié<BR>seront donc inutiles. Il est<BR>peut-être temps d'aguerrir<BR>vos talents d'archer.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61008.mib" DOWNLOAD CSUM=38065 FSIZE=3108 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Quête défi 11</a><BR>
					<a href=#002 qname=m61010.mib>Quête défi 10</a><BR>
					<a href=#003 qname=m61009.mib>Quête défi 9</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m61008.mib>Quête défi 8</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m61007.mib>Quête défi 7</a><BR>
					<a href=#006 qname=m61006.mib>Quête défi 6</a><BR>
					<a href=#007 qname=m61005.mib>Quête défi 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête massacre</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Quête défi 8
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 6000z<br>
<font color=orange>Contrat：</font> 0z<br>
<font color=orange>Temps　：</font> 30min.<br>
<font color=orange>Zone 　：</font> Grande arène<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 4 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête massacre</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Quête défi 8
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tuer 2 Tigrex<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Instructeur<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
C'est moi, votre instructeur<BR>estimé. Cette fois il<BR>faudra affronter non pas<BR>un, mais deux Tigrex ! Ils<BR>sont intouchables sous<BR>l'effet de la colère, à<BR>vous de créer l'ouverture. <BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61007.mib" DOWNLOAD CSUM=44630 FSIZE=7768 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Quête défi 11</a><BR>
					<a href=#002 qname=m61010.mib>Quête défi 10</a><BR>
					<a href=#003 qname=m61009.mib>Quête défi 9</a><BR>
					<a href=#004 qname=m61008.mib>Quête défi 8</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m61007.mib>Quête défi 7</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m61006.mib>Quête défi 6</a><BR>
					<a href=#007 qname=m61005.mib>Quête défi 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête massacre</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Quête défi 7
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 1200z<br>
<font color=orange>Contrat：</font> 0z<br>
<font color=orange>Temps　：</font> 10min.<br>
<font color=orange>Zone 　：</font> Jungle(jour)<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 1 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête massacre</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Quête défi 7
			</td>
			<td>
				&nbsp;★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tuer 30 Velociprey<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Instructeur<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
C'est moi, votre instructeur<BR>estimé. Il y a toujours un<BR>chemin approprié pour<BR>chaque quête.<BR>Vous devriez être capable<BR>de le trouver à l'heure<BR>qu'il est !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61006.mib" DOWNLOAD CSUM=30302 FSIZE=3460 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Quête défi 11</a><BR>
					<a href=#002 qname=m61010.mib>Quête défi 10</a><BR>
					<a href=#003 qname=m61009.mib>Quête défi 9</a><BR>
					<a href=#004 qname=m61008.mib>Quête défi 8</a><BR>
					<a href=#005 qname=m61007.mib>Quête défi 7</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m61006.mib>Quête défi 6</a><BR>
			<tr><td height=30 valign=top>
					<a href=#007 qname=m61005.mib>Quête défi 5</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête massacre</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Quête défi 6
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 300z<br>
<font color=orange>Contrat：</font> 0z<br>
<font color=orange>Temps　：</font> 15min.<br>
<font color=orange>Zone 　：</font> Grande arène<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 1 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête massacre</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Quête défi 6
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tuer le Bulldrome<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Instructeur<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
C'est moi, votre instructeur<BR>estimé. Le défi du<BR>jour concerne un<BR>Bulldrome ! Ne riez pas !<BR>Vous devriez savoir<BR>que les apparences sont<BR>souvent trompeuses.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m61005.mib" DOWNLOAD CSUM=38044 FSIZE=3212 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/２</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m61011.mib>Quête défi 11</a><BR>
					<a href=#002 qname=m61010.mib>Quête défi 10</a><BR>
					<a href=#003 qname=m61009.mib>Quête défi 9</a><BR>
					<a href=#004 qname=m61008.mib>Quête défi 8</a><BR>
					<a href=#005 qname=m61007.mib>Quête défi 7</a><BR>
					<a href=#006 qname=m61006.mib>Quête défi 6</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m61005.mib>Quête défi 5</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête massacre</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Quête défi 5
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 5100z<br>
<font color=orange>Contrat：</font> 0z<br>
<font color=orange>Temps　：</font> 15min.<br>
<font color=orange>Zone 　：</font> Grande arène<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 4 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/FR/LOGO15.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête massacre</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Quête défi 5
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tuer le Ceanataur Shogun<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Instructeur<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
C'est moi, votre instructeur<BR>estimé. L'entraînement<BR>du jour concerne deux<BR>Ceanataur Shogun, mais il<BR>suffit d'en tuer un pour<BR>compléter la quête. Montrez-<BR>vous à la hauteur !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
</body>
</html>
