<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=2",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=2&pg_no=1",
		"RB_LINK=DL_MENU.PHP?lang=2&pg_no=0",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60015.mib" DOWNLOAD CSUM=29233 FSIZE=2432 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60015.mib>Die Legende von Schrade</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m60009.mib>Yian Kut-Ku-Sturm</a><BR>
					<a href=#003 qname=m60002.mib>Eierdieb in der Nacht</a><BR>
					<a href=#004 qname=m60024.mib>Schwärme über Schwärme</a><BR>
					<a href=#005 qname=m60014.mib>Affen und Krabben</a><BR>
					<a href=#006 qname=m60013.mib>Krabben und Affen</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Sonder-Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Die Legende von Schrade
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 36000z<br>
<font color=orange>Gebühr 　：</font> 3000z<br>
<font color=orange>Zeit 　　：</font> 50min<br>
<font color=orange>Zone 　　：</font> SchlsSchrade<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  6 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Sonder-Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Die Legende von Schrade
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Den Fatalis töten<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Gildenmeister<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Der schwarze Drache Fatalis,<BR>der in der Legende von<BR>Schrade erwähnt wird, lebt<BR>wirklich! Er kann ganze<BR>Länder verwüsten. Wir<BR>brauchen deine Hilfe, um<BR>diesen Terror zu beenden!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60009.mib" DOWNLOAD CSUM=9441 FSIZE=6688 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>Die Legende von Schrade</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60009.mib>Yian Kut-Ku-Sturm</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m60002.mib>Eierdieb in der Nacht</a><BR>
					<a href=#004 qname=m60024.mib>Schwärme über Schwärme</a><BR>
					<a href=#005 qname=m60014.mib>Affen und Krabben</a><BR>
					<a href=#006 qname=m60013.mib>Krabben und Affen</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Jagd-Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Yian Kut-Ku-Sturm
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 2400z<br>
<font color=orange>Gebühr 　：</font> 200z<br>
<font color=orange>Zeit 　　：</font> 50min<br>
<font color=orange>Zone 　　：</font> Dschungel(Tag)<br>
<font color=orange>Sonderbedingungen：</font><br>Nein<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Jagd-Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Yian Kut-Ku-Sturm
			</td>
			<td>
				&nbsp;★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Bis zum Zeitablauf leben<BR>oder den Tatzenpass abgeben<BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Weniger als 2 Kut-Kus erjagt<BR>vor Zeitablauf, Belohnung 0<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Jägergilde<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Wir haben aus dem<BR>Dschungeldorf gehört, dass<BR>dort mehrere Yian Kut-Kus<BR>ihr Unwesen treiben. Begib<BR>dich dorthin und bring die<BR>Situation unter Kontrolle!<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60002.mib" DOWNLOAD CSUM=25196 FSIZE=9508 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>Die Legende von Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Yian Kut-Ku-Sturm</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60002.mib>Eierdieb in der Nacht</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m60024.mib>Schwärme über Schwärme</a><BR>
					<a href=#005 qname=m60014.mib>Affen und Krabben</a><BR>
					<a href=#006 qname=m60013.mib>Krabben und Affen</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Sammel-Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Eierdieb in der Nacht
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 4200ｚ<br>
<font color=orange>Gebühr 　：</font> 350z<br>
<font color=orange>Zeit 　　：</font> 50min<br>
<font color=orange>Zone 　　：</font> Dschungel(Nacht)<br>
<font color=orange>Sonderbedingungen：</font><br>Nein<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Sammel-Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Eierdieb in der Nacht
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>3 Wyvern-Eier abliefern<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Feinschmeckerin<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Ich bin verrückt nach Eier-<BR>gerichten und Wyvern-Eier<BR>sind die schmackhaftesten.<BR>Sei doch so gut und bring<BR>mir drei Wyvern-Eier!<BR>　　　　　　　　　　　　　　<br>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60024.mib" DOWNLOAD CSUM=4884 FSIZE=11028 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>Die Legende von Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Yian Kut-Ku-Sturm</a><BR>
					<a href=#003 qname=m60002.mib>Eierdieb in der Nacht</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60024.mib>Schwärme über Schwärme</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m60014.mib>Affen und Krabben</a><BR>
					<a href=#006 qname=m60013.mib>Krabben und Affen</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Tötungsquest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Schwärme über Schwärme
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 4500z<br>
<font color=orange>Gebühr 　：</font> 380z<br>
<font color=orange>Zeit 　　：</font> 50min<br>
<font color=orange>Zone 　　：</font> Dschungel(Tag)<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  4 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Tötungsquest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Schwärme über Schwärme
			</td>
			<td>
				&nbsp;★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>50 Vespoiden töten<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Erzürnte Magd<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Das Gebiet um das Dorf ist<BR>letzthin sehr laut, und das<BR>liegt an dem Insekten-<BR>schwarm. Ich kann nachts<BR>nicht mehr schlafen. Du bist<BR>doch ein Jäger, oder? Dann<BR>tu etwas!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60014.mib" DOWNLOAD CSUM=37718 FSIZE=2808 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>Die Legende von Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Yian Kut-Ku-Sturm</a><BR>
					<a href=#003 qname=m60002.mib>Eierdieb in der Nacht</a><BR>
					<a href=#004 qname=m60024.mib>Schwärme über Schwärme</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60014.mib>Affen und Krabben</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m60013.mib>Krabben und Affen</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Jagd-Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Affen und Krabben
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 7500z<br>
<font color=orange>Gebühr 　：</font> 620z<br>
<font color=orange>Zeit 　　：</font> 50min<br>
<font color=orange>Zone 　　：</font> Große Arena<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  4 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Jagd-Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Affen und Krabben
			</td>
			<td>
				&nbsp;★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Den Blangonga erjagen<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Arena-Manager<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Die Arena! Hier kann man der<BR>Welt sein Können zeigen!<BR>Heute steht ein Blangonga im<BR>Ring. Wir haben aber auch<BR>Ceanatauren und Hermitauren<BR>losgelassen! Achte auf die<BR>Krabben und erleg das Biest!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60013.mib" DOWNLOAD CSUM=40229 FSIZE=2816 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>Die Legende von Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Yian Kut-Ku-Sturm</a><BR>
					<a href=#003 qname=m60002.mib>Eierdieb in der Nacht</a><BR>
					<a href=#004 qname=m60024.mib>Schwärme über Schwärme</a><BR>
					<a href=#005 qname=m60014.mib>Affen und Krabben</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60013.mib>Krabben und Affen</a><BR>
			<tr><td height=30 valign=top>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Jagd-Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Krabben und Affen
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 4200z<br>
<font color=orange>Gebühr 　：</font> 350z<br>
<font color=orange>Zeit 　　：</font> 50min<br>
<font color=orange>Zone 　　：</font> Große Arena<br>
<font color=orange>Sonderbedingungen：</font><br>Nein<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Jagd-Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Krabben und Affen
			</td>
			<td>
				&nbsp;★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Den Daimyo Hermitaur erjagen<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Arena-Manager<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Die Arena! Hier kann man der<BR>Welt sein Können zeigen!<BR>Heute tritt der rote Daimyo<BR>Hermitaur an. Achte auf die<BR>umgebenden Congas und erleg<BR>die Krabbe! Wir erwarten,<BR>dass du zurückkehrst!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
</body>
</html>
