<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=2",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=2&pg_no=2",
		"RB_LINK=DL_MENU.PHP?lang=2&pg_no=1",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60022.mib" DOWNLOAD CSUM=51950 FSIZE=2816 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60022.mib>Zorn von Himmel und Erde</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m60025.mib>Der Besucher aus Stahl</a><BR>
					<a href=#003 qname=m60019.mib>Goldener Donnergott</a><BR>
					<a href=#004 qname=m60018.mib>Die Remobra-Höhle</a><BR>
					<a href=#005 qname=m60017.mib>Der Urdrache</a><BR>
					<a href=#006 qname=m60010.mib>Narbengesicht</a><BR>
					<a href=#007 qname=m60012.mib>Der heiße, dunkle Wind</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Jagd-Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Zorn von Himmel und Erde
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 9900z<br>
<font color=orange>Gebühr 　：</font> 830z<br>
<font color=orange>Zeit 　　：</font> 50min<br>
<font color=orange>Zone 　　：</font> Große Arena<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  4 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Jagd-Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Zorn von Himmel und Erde
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Silbernen Rathalos und<BR>goldene Rathian erjagen<BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Kokoto-Dorfchef<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Der große Moment ist da.<BR>Hier ist meine Aufgabe für<BR>dich. Besiege die beiden<BR>Riesenwyvern Rathalos und<BR>Rathian. Reicht dein Können<BR>aus, um sie zu töten?<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60025.mib" DOWNLOAD CSUM=40969 FSIZE=2716 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Zorn von Himmel und Erde</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60025.mib>Der Besucher aus Stahl</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m60019.mib>Goldener Donnergott</a><BR>
					<a href=#004 qname=m60018.mib>Die Remobra-Höhle</a><BR>
					<a href=#005 qname=m60017.mib>Der Urdrache</a><BR>
					<a href=#006 qname=m60010.mib>Narbengesicht</a><BR>
					<a href=#007 qname=m60012.mib>Der heiße, dunkle Wind</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Tötungsquest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Der Besucher aus Stahl
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 10500z<br>
<font color=orange>Gebühr 　：</font> 870z<br>
<font color=orange>Zeit 　　：</font> 50min<br>
<font color=orange>Zone 　　：</font> Stadt<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  6 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Tötungsquest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Der Besucher aus Stahl
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Den Kushala Daora töten<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Gildenmeister<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Notfall! Notfall! Ein<BR>brauner Kushala Daora nähert<BR>sich unserer Stadt! Alle<BR>guten Jäger sollten so<BR>schnell wie möglich zu uns<BR>eilen, um die Stadt zu<BR>retten!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60019.mib" DOWNLOAD CSUM=22657 FSIZE=2404 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Zorn von Himmel und Erde</a><BR>
					<a href=#002 qname=m60025.mib>Der Besucher aus Stahl</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60019.mib>Goldener Donnergott</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m60018.mib>Die Remobra-Höhle</a><BR>
					<a href=#005 qname=m60017.mib>Der Urdrache</a><BR>
					<a href=#006 qname=m60010.mib>Narbengesicht</a><BR>
					<a href=#007 qname=m60012.mib>Der heiße, dunkle Wind</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Jagd-Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Goldener Donnergott
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 9000z<br>
<font color=orange>Gebühr 　：</font> 750z<br>
<font color=orange>Zeit 　　：</font> 50min<br>
<font color=orange>Zone 　　：</font> Große Arena<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  4 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Jagd-Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Goldener Donnergott
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Den Rajang erjagen<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Arena-Manager<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Es ist grässlich! Absolut<BR>grässlich! Ein riesiges<BR>schwarzes Monster hat meine<BR>Arena überfallen! Solange es<BR>da ist, können wir das<BR>Geschäft vergessen. Du musst<BR>es loswerden. Bitte!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60018.mib" DOWNLOAD CSUM=31825 FSIZE=2704 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Zorn von Himmel und Erde</a><BR>
					<a href=#002 qname=m60025.mib>Der Besucher aus Stahl</a><BR>
					<a href=#003 qname=m60019.mib>Goldener Donnergott</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60018.mib>Die Remobra-Höhle</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m60017.mib>Der Urdrache</a><BR>
					<a href=#006 qname=m60010.mib>Narbengesicht</a><BR>
					<a href=#007 qname=m60012.mib>Der heiße, dunkle Wind</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Tötungsquest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Die Remobra-Höhle
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 6000z<br>
<font color=orange>Gebühr 　：</font> 500z<br>
<font color=orange>Zeit 　　：</font> 50min<br>
<font color=orange>Zone 　　：</font> Große Arena<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  4 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Tötungsquest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Die Remobra-Höhle
			</td>
			<td>
				&nbsp;★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>15 Remobras töten<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Arena-Manager<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Die Arena! Hier kann man der<BR>Welt sein Können zeigen!<BR>Heute musst du fliegende<BR>Remobras bekämpfen! Ihr Gift<BR>erfüllt die Arena und man<BR>braucht viel Mut, um zu<BR>bestehen!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60017.mib" DOWNLOAD CSUM=4766 FSIZE=5096 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Zorn von Himmel und Erde</a><BR>
					<a href=#002 qname=m60025.mib>Der Besucher aus Stahl</a><BR>
					<a href=#003 qname=m60019.mib>Goldener Donnergott</a><BR>
					<a href=#004 qname=m60018.mib>Die Remobra-Höhle</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60017.mib>Der Urdrache</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m60010.mib>Narbengesicht</a><BR>
					<a href=#007 qname=m60012.mib>Der heiße, dunkle Wind</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Sonder-Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Der Urdrache
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 36000z<br>
<font color=orange>Gebühr 　：</font> 3000z<br>
<font color=orange>Zeit 　　：</font> 50min<br>
<font color=orange>Zone 　　：</font> Turm<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  6 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Sonder-Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Der Urdrache
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Den Fatalis töten<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>MysteriöserRoterMann<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Die Zeit ist gekommen. Hier<BR>ist deine Einladung zum<BR>Ball. Zieh dich fein an und<BR>bring deine beste Waffe mit,<BR>denn dein Tanzpartner ist<BR>der König des Unheils<BR>selbst.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60010.mib" DOWNLOAD CSUM=31748 FSIZE=7188 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Zorn von Himmel und Erde</a><BR>
					<a href=#002 qname=m60025.mib>Der Besucher aus Stahl</a><BR>
					<a href=#003 qname=m60019.mib>Goldener Donnergott</a><BR>
					<a href=#004 qname=m60018.mib>Die Remobra-Höhle</a><BR>
					<a href=#005 qname=m60017.mib>Der Urdrache</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60010.mib>Narbengesicht</a><BR>
			<tr><td height=30 valign=top>
					<a href=#007 qname=m60012.mib>Der heiße, dunkle Wind</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Jagd-Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Narbengesicht
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 6600z<br>
<font color=orange>Gebühr 　：</font> 550z<br>
<font color=orange>Zeit 　　：</font> 50min<br>
<font color=orange>Zone 　　：</font> Dschungel(Nacht)<br>
<font color=orange>Sonderbedingungen：</font><br>Nein<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Jagd-Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Narbengesicht
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Den Yian Garuga erjagen<BR><BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Verletzter Kämpfer<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Ich habe die verletzte<BR>Wyvern im Dschungel<BR>aufgespürt, aber weil ich<BR>selbst verwundet bin, musste<BR>ich aufgeben. Räche mich und<BR>erlege das Monster an meiner<BR>Stelle!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60012.mib" DOWNLOAD CSUM=33090 FSIZE=2624 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Zorn von Himmel und Erde</a><BR>
					<a href=#002 qname=m60025.mib>Der Besucher aus Stahl</a><BR>
					<a href=#003 qname=m60019.mib>Goldener Donnergott</a><BR>
					<a href=#004 qname=m60018.mib>Die Remobra-Höhle</a><BR>
					<a href=#005 qname=m60017.mib>Der Urdrache</a><BR>
					<a href=#006 qname=m60010.mib>Narbengesicht</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60012.mib>Der heiße, dunkle Wind</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Jagd-Quest</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Der heiße, dunkle Wind
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Belohnung：</font> 9000z<br>
<font color=orange>Gebühr 　：</font> 750z<br>
<font color=orange>Zeit 　　：</font> 50min<br>
<font color=orange>Zone 　　：</font> Große Arena<br>
<font color=orange>Sonderbedingungen：</font><br>Nur JR  4 oder höher.<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/DE/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Jagd-Quest</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Quest-Stufe:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Der heiße, dunkle Wind
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Zielbedingung(en):</font><br>Die beiden schwarzen<BR>Gravios erjagen<BR><BR>
<font color=orange>Fehlbedingung(en):</font><br>Belohnung 0<BR>Zeit abgelaufen<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Kunde:</font>Arena-Manager<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Die Arena! Hier kann man der<BR>Welt sein Können zeigen!<BR>Heute haben wir nicht einen,<BR>sondern zwei der furchtbaren<BR>schwarzen Gravios in der<BR>Arena! Bist du bereit?<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/DE/BUTTON4.gif></td></tr></table>
</body>
</html>
