<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=4",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=4&pg_no=1",
		"RB_LINK=DL_MENU.PHP?lang=4&pg_no=0",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60015.mib" DOWNLOAD CSUM=29233 FSIZE=2432 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60015.mib>La leyenda de Schrade</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m60009.mib>Tempestad de Yian Kut-Ku</a><BR>
					<a href=#003 qname=m60002.mib>Ladrón de huevos nocturno</a><BR>
					<a href=#004 qname=m60024.mib>Enjambres de enjambres</a><BR>
					<a href=#005 qname=m60014.mib>¡Monos y cangrejos!</a><BR>
					<a href=#006 qname=m60013.mib>¡Cangrejos y monos!</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión especial</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					La leyenda de Schrade
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 36000z<br>
<font color=orange>Contrato ：</font> 3000z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Cast.Schrade<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 6 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión especial</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				La leyenda de Schrade
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Mata al Fatalis<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Maestro del Gremio<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
¡Fatalis, el dragón negro<BR>del que habla la leyenda de<BR>Schrade, existe de<BR>verdad! Si no lo atrapamos,<BR>el país caerá en sus<BR>manos. ¡Necesitamos tu<BR>ayuda para acabar con él!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60009.mib" DOWNLOAD CSUM=9441 FSIZE=6688 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>La leyenda de Schrade</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60009.mib>Tempestad de Yian Kut-Ku</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m60002.mib>Ladrón de huevos nocturno</a><BR>
					<a href=#004 qname=m60024.mib>Enjambres de enjambres</a><BR>
					<a href=#005 qname=m60014.mib>¡Monos y cangrejos!</a><BR>
					<a href=#006 qname=m60013.mib>¡Cangrejos y monos!</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión de caza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Tempestad de Yian Kut-Ku
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 2400z<br>
<font color=orange>Contrato ：</font> 200z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Jungla(D)<br>
<font color=orange>Condiciones especiales：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión de caza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Tempestad de Yian Kut-Ku
			</td>
			<td>
				&nbsp;★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Sobrevive hasta fin de<BR>tiempo o usa el Ticket zarpa<BR><BR>
<font color=orange>Cond. fracaso:</font><br>Si cazas menos de 2 Kut-Ku:<BR>recompensa cero, fin tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Gremio de cazadores<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
¡Nos han dicho que en el<BR>pueblo de la jungla hay una<BR>plaga de Yian Kut-Ku!<BR>¡Vete corriendo a esa<BR>zona y pon la<BR>situación bajo<BR>control!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60002.mib" DOWNLOAD CSUM=25196 FSIZE=9508 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>La leyenda de Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Tempestad de Yian Kut-Ku</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60002.mib>Ladrón de huevos nocturno</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m60024.mib>Enjambres de enjambres</a><BR>
					<a href=#005 qname=m60014.mib>¡Monos y cangrejos!</a><BR>
					<a href=#006 qname=m60013.mib>¡Cangrejos y monos!</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión recogida</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Ladrón de huevos nocturno
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 4200ｚ<br>
<font color=orange>Contrato ：</font> 350z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Jungla(N)<br>
<font color=orange>Condiciones especiales：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión recogida</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Ladrón de huevos nocturno
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Entrega 3 Huevos de Wyvern<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>La Señora Gourmet<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Como fanática de los huevos,<BR>puedo afirmar sin dudarlo<BR>que los huevos más sabrosos<BR>son los huevos de<BR>Wyvern. ¡Ayúdame a<BR>satisfacer mi capricho y<BR>tráeme 3 Huevos de Wyvern!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60024.mib" DOWNLOAD CSUM=4884 FSIZE=11028 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>La leyenda de Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Tempestad de Yian Kut-Ku</a><BR>
					<a href=#003 qname=m60002.mib>Ladrón de huevos nocturno</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60024.mib>Enjambres de enjambres</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m60014.mib>¡Monos y cangrejos!</a><BR>
					<a href=#006 qname=m60013.mib>¡Cangrejos y monos!</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión matanza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Enjambres de enjambres
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 4500z<br>
<font color=orange>Contrato ：</font> 380z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Jungla(D)<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 4 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión matanza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Enjambres de enjambres
			</td>
			<td>
				&nbsp;★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Mata 50 Vespoid<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Doncella enojada<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Últimamente, los alrededores<BR>del pueblo son muy ruidosos<BR>y la culpa es de ese<BR>enjambre de bichos. ¡Hacen<BR>tanto ruido que no puedo<BR>dormir! Tú eres cazador,<BR>¿no? ¡Pues haz algo!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60014.mib" DOWNLOAD CSUM=37718 FSIZE=2808 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>La leyenda de Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Tempestad de Yian Kut-Ku</a><BR>
					<a href=#003 qname=m60002.mib>Ladrón de huevos nocturno</a><BR>
					<a href=#004 qname=m60024.mib>Enjambres de enjambres</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60014.mib>¡Monos y cangrejos!</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m60013.mib>¡Cangrejos y monos!</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión de caza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					¡Monos y cangrejos!
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 7500z<br>
<font color=orange>Contrato ：</font> 620z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Gran arena<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 4 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión de caza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				¡Monos y cangrejos!
			</td>
			<td>
				&nbsp;★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Caza al Blangonga<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Jefe de la arena<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
¡La arena! ¡Un lugar para<BR>mostrar tus habilidades! En<BR>este evento, tu oponente es<BR>un Blangonga; también hay<BR>Ceanataurs y Hermitaurs.<BR>Cuidado con los cangrejos <BR>y mata a la bestia.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60013.mib" DOWNLOAD CSUM=40229 FSIZE=2816 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>La leyenda de Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Tempestad de Yian Kut-Ku</a><BR>
					<a href=#003 qname=m60002.mib>Ladrón de huevos nocturno</a><BR>
					<a href=#004 qname=m60024.mib>Enjambres de enjambres</a><BR>
					<a href=#005 qname=m60014.mib>¡Monos y cangrejos!</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60013.mib>¡Cangrejos y monos!</a><BR>
			<tr><td height=30 valign=top>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión de caza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					¡Cangrejos y monos!
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 4200z<br>
<font color=orange>Contrato ：</font> 350z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Gran arena<br>
<font color=orange>Condiciones especiales：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión de caza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				¡Cangrejos y monos!
			</td>
			<td>
				&nbsp;★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Caza al Daimyo Hermitaur<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Jefe de la arena<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
¡La arena! ¡Un lugar para<BR>mostrar tus habilidades! En<BR>este evento, tu oponente es<BR>un Daimyo Hermitaur rojo.<BR>¡Cuidado con los Congas de<BR>alrededor y mata al<BR>cangrejo! Te esperaremos.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
</body>
</html>
