<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=5",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=5&pg_no=0",
		"RB_LINK=DL_MENU.PHP?lang=5&pg_no=2",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60008.mib" DOWNLOAD CSUM=57641 FSIZE=2848 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60008.mib>Forte spada, forte scudo</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m60023.mib>Il misterioso Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>Il disastro cremisi</a><BR>
					<a href=#004 qname=m60007.mib>La stagione del verde</a><BR>
					<a href=#005 qname=m60006.mib>Trappola vulcanica!</a><BR>
					<a href=#006 qname=m60003.mib>Madre di tutte le battaglie</a><BR>
					<a href=#007 qname=m60021.mib>Concerto di luce e veleno</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. di caccia</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Forte spada, forte scudo
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 6000z<br>
<font color=orange>Contratto：</font> 500z<br>
<font color=orange>Tempo　　：</font> 50minuti<br>
<font color=orange>Zona 　　：</font> Grande arena<br>
<font color=orange>Condizioni speciali：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. di caccia</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Forte spada, forte scudo
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Caccia il Daimyo Hermitaur<BR>e lo Shogun Ceanataur<BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Gestore dell'arena<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
L'Arena! Un luogo in cui<BR>mostrare al mondo le tue<BR>capacità! Per questo evento,<BR>abbiamo messo sul ring due<BR>nemici simili a granchi!<BR>Benvenuto a chiunque voglia<BR>mettersi alla prova!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60023.mib" DOWNLOAD CSUM=15991 FSIZE=7800 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Forte spada, forte scudo</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60023.mib>Il misterioso Kut-Ku</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m60016.mib>Il disastro cremisi</a><BR>
					<a href=#004 qname=m60007.mib>La stagione del verde</a><BR>
					<a href=#005 qname=m60006.mib>Trappola vulcanica!</a><BR>
					<a href=#006 qname=m60003.mib>Madre di tutte le battaglie</a><BR>
					<a href=#007 qname=m60021.mib>Concerto di luce e veleno</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. di caccia</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Il misterioso Kut-Ku
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 7200z<br>
<font color=orange>Contratto：</font> 600z<br>
<font color=orange>Tempo　　：</font> 50minuti<br>
<font color=orange>Zona 　　：</font> Giungla(notte)<br>
<font color=orange>Condizioni speciali：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. di caccia</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Il misterioso Kut-Ku
			</td>
			<td>
				&nbsp;★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Sopravvivi fino al termine o<BR>consegna il buono Pass-zampa<BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Uccidi meno di 2 Kut-Ku:<BR>nessun premio, tempo term.<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Gilda dei cacciatori<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Abbiamo ricevuto una<BR>richiesta di aiuto dal<BR>villaggio della Giungla. È<BR>apparso uno strano branco di<BR>Kut-Ku che corrono<BR>sfrenatamente sui campi. Vai<BR>lì e prendi il controllo!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60016.mib" DOWNLOAD CSUM=23179 FSIZE=2392 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Forte spada, forte scudo</a><BR>
					<a href=#002 qname=m60023.mib>Il misterioso Kut-Ku</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60016.mib>Il disastro cremisi</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m60007.mib>La stagione del verde</a><BR>
					<a href=#005 qname=m60006.mib>Trappola vulcanica!</a><BR>
					<a href=#006 qname=m60003.mib>Madre di tutte le battaglie</a><BR>
					<a href=#007 qname=m60021.mib>Concerto di luce e veleno</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. speciale</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Il disastro cremisi
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 36000z<br>
<font color=orange>Contratto：</font> 3000z<br>
<font color=orange>Tempo　　：</font> 50minuti<br>
<font color=orange>Zona 　　：</font> Campo battaglia<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 6 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. speciale</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Il disastro cremisi
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi il Fatalis<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Direttore Gilda<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Fatalis... La sua ira può<BR>scuotere la terra e ardere i<BR>cieli. È un male senza fine.<BR>Cacciatori! Non indugiate!<BR>Inseguite il suo ruggito e<BR>abbattete la morte cremisi.<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60007.mib" DOWNLOAD CSUM=42073 FSIZE=7928 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Forte spada, forte scudo</a><BR>
					<a href=#002 qname=m60023.mib>Il misterioso Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>Il disastro cremisi</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60007.mib>La stagione del verde</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m60006.mib>Trappola vulcanica!</a><BR>
					<a href=#006 qname=m60003.mib>Madre di tutte le battaglie</a><BR>
					<a href=#007 qname=m60021.mib>Concerto di luce e veleno</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. di caccia</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					La stagione del verde
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 4500z<br>
<font color=orange>Contratto：</font> 380z<br>
<font color=orange>Tempo　　：</font> 50minuti<br>
<font color=orange>Zona 　　：</font> Foresta e coll.<br>
<font color=orange>Condizioni speciali：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. di caccia</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				La stagione del verde
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Sopravvivi fino al termine o<BR>consegna il buono Pass-zampa<BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Uccidi meno di 2 Rathian:<BR>nessun premio, tempo term.<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Ragazza in pensiero<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Mio fratello sta finalmente<BR>venendo a casa dopo tanto<BR>tempo. Ma tu devi occuparti<BR>delle Rathian sulle colline<BR>del villaggio vicino, in<BR>modo che non gli creino guai<BR>mentre torna a casa!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60006.mib" DOWNLOAD CSUM=20528 FSIZE=5756 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Forte spada, forte scudo</a><BR>
					<a href=#002 qname=m60023.mib>Il misterioso Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>Il disastro cremisi</a><BR>
					<a href=#004 qname=m60007.mib>La stagione del verde</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60006.mib>Trappola vulcanica!</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m60003.mib>Madre di tutte le battaglie</a><BR>
					<a href=#007 qname=m60021.mib>Concerto di luce e veleno</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. di caccia</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Trappola vulcanica!
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 3600z<br>
<font color=orange>Contratto：</font> 300z<br>
<font color=orange>Tempo　　：</font> 50minuti<br>
<font color=orange>Zona 　　：</font> Vulcano(giorno)<br>
<font color=orange>Condizioni speciali：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. di caccia</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Trappola vulcanica!
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Caccia 2 Basarios<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Mercante avido<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Sono venuto nella Cintura<BR>vulcanica per cercare<BR>minerali preziosi, ma ho una<BR>sensazione opprimente...<BR>La senti? Come tante minacce<BR>che si avvicinano<BR>strisciando. Controlla!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60003.mib" DOWNLOAD CSUM=21543 FSIZE=2572 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Forte spada, forte scudo</a><BR>
					<a href=#002 qname=m60023.mib>Il misterioso Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>Il disastro cremisi</a><BR>
					<a href=#004 qname=m60007.mib>La stagione del verde</a><BR>
					<a href=#005 qname=m60006.mib>Trappola vulcanica!</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60003.mib>Madre di tutte le battaglie</a><BR>
			<tr><td height=30 valign=top>
					<a href=#007 qname=m60021.mib>Concerto di luce e veleno</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. uccisione</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Madre di tutte le battaglie
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 2100z<br>
<font color=orange>Contratto：</font> 150z<br>
<font color=orange>Tempo　　：</font> 50minuti<br>
<font color=orange>Zona 　　：</font> Arena<br>
<font color=orange>Condizioni speciali：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. uccisione</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Madre di tutte le battaglie
			</td>
			<td>
				&nbsp;★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi 20 Felyne<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Eroe Lynian<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Questa è una sfida per tutti<BR>i cacciatori, nya! I miei<BR>compagni Lynian e io<BR>facciamo soffrire quelli che<BR>entrano nell'arena! Solo i<BR>più audaci possono<BR>affrontarci, nya!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60021.mib" DOWNLOAD CSUM=22434 FSIZE=2492 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Forte spada, forte scudo</a><BR>
					<a href=#002 qname=m60023.mib>Il misterioso Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>Il disastro cremisi</a><BR>
					<a href=#004 qname=m60007.mib>La stagione del verde</a><BR>
					<a href=#005 qname=m60006.mib>Trappola vulcanica!</a><BR>
					<a href=#006 qname=m60003.mib>Madre di tutte le battaglie</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60021.mib>Concerto di luce e veleno</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. di caccia</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Concerto di luce e veleno
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 5100z<br>
<font color=orange>Contratto：</font> 420z<br>
<font color=orange>Tempo　　：</font> 50minuti<br>
<font color=orange>Zona 　　：</font> Grande arena<br>
<font color=orange>Condizioni speciali：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. di caccia</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Concerto di luce e veleno
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Caccia 2 Gypceros<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Gestore dell'arena<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
L'Arena! Un luogo in cui<BR>mostrare al mondo le tue<BR>capacità! Preparati ad<BR>affrontare non uno, ma due<BR>divoratori volanti viola:<BR>i Gypceros! Mostraci la tua<BR>vera forza!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
</body>
</html>
