<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=3",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=3&pg_no=0",
		"RB_LINK=DL_MENU.PHP?lang=3&pg_no=2",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60008.mib" DOWNLOAD CSUM=57641 FSIZE=2848 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60008.mib>Épée forte, bouclier solide</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m60023.mib>Le mystérieux Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>Le désastre pourpre</a><BR>
					<a href=#004 qname=m60007.mib>La saison du vert</a><BR>
					<a href=#005 qname=m60006.mib>Piège volcanique !</a><BR>
					<a href=#006 qname=m60003.mib>L'ultime bataille</a><BR>
					<a href=#007 qname=m60021.mib>Concert lumière & poison</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête de chasse</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Épée forte, bouclier solide
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 6000z<br>
<font color=orange>Contrat：</font> 500z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Grande arène<br>
<font color=orange>Conditions spéciales：</font><br>Aucune<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête de chasse</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Épée forte, bouclier solide
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Chasser l'Hermitaur Daimyo<BR>et le Ceanataur Shogun<BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Directeur de l'arène<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
L'Arène ! L'endroit où mon-<BR>trer au monde vos talents !<BR>Cette fois nous avons lâché<BR>2 ennemis crabes sur le<BR>ring ! Tous ceux qui<BR>veulent tester leur force<BR>sont les bienvenus !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60023.mib" DOWNLOAD CSUM=15991 FSIZE=7800 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Épée forte, bouclier solide</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60023.mib>Le mystérieux Kut-Ku</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m60016.mib>Le désastre pourpre</a><BR>
					<a href=#004 qname=m60007.mib>La saison du vert</a><BR>
					<a href=#005 qname=m60006.mib>Piège volcanique !</a><BR>
					<a href=#006 qname=m60003.mib>L'ultime bataille</a><BR>
					<a href=#007 qname=m60021.mib>Concert lumière & poison</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête de chasse</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Le mystérieux Kut-Ku
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 7200z<br>
<font color=orange>Contrat：</font> 600z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Jungle(nuit)<br>
<font color=orange>Conditions spéciales：</font><br>Aucune<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête de chasse</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Le mystérieux Kut-Ku
			</td>
			<td>
				&nbsp;★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tenir jusqu'à fin du temps<BR>ou livrer Ticket Passechat<BR><BR>
<font color=orange>Condition échec:</font><br>Tuer moins de 2 Kut-Ku<BR>Aucune prime, délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Guilde des chasseurs<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Nous avons reçu un appel de<BR>détresse du village dans la<BR>jungle. Une volée de Kut-Ku<BR>a commencé à dévaster les<BR> champs. Rendez-vous<BR>là-bas pour maîtriser ces<BR>bêtes !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60016.mib" DOWNLOAD CSUM=23179 FSIZE=2392 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Épée forte, bouclier solide</a><BR>
					<a href=#002 qname=m60023.mib>Le mystérieux Kut-Ku</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60016.mib>Le désastre pourpre</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m60007.mib>La saison du vert</a><BR>
					<a href=#005 qname=m60006.mib>Piège volcanique !</a><BR>
					<a href=#006 qname=m60003.mib>L'ultime bataille</a><BR>
					<a href=#007 qname=m60021.mib>Concert lumière & poison</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête spéciale</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Le désastre pourpre
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 36000z<br>
<font color=orange>Contrat：</font> 3000z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Champ bataille<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 6 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête spéciale</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Le désastre pourpre
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tuer le Fatalis<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Directeur de Guilde<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Le Fatalis... Sa colère fait<BR>trembler la terre et le<BR>ciel. C'est le mal incar-<BR>né ! Chasseurs ! Que cela<BR>cesse ! Suivez son rugisse-<BR>ment et abattez la mort<BR>pourpre !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60007.mib" DOWNLOAD CSUM=42073 FSIZE=7928 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Épée forte, bouclier solide</a><BR>
					<a href=#002 qname=m60023.mib>Le mystérieux Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>Le désastre pourpre</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60007.mib>La saison du vert</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m60006.mib>Piège volcanique !</a><BR>
					<a href=#006 qname=m60003.mib>L'ultime bataille</a><BR>
					<a href=#007 qname=m60021.mib>Concert lumière & poison</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête de chasse</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					La saison du vert
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 4500z<br>
<font color=orange>Contrat：</font> 380z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Forêt&col.<br>
<font color=orange>Conditions spéciales：</font><br>Aucune<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête de chasse</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				La saison du vert
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tenir jusqu'à fin du temps<BR>ou livrer Ticket Passechat<BR><BR>
<font color=orange>Condition échec:</font><br>Tuer moins de 2 Rathian<BR>Aucune prime, délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Jeune fille enceinte<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Mon frère revient enfin<BR>après une longue absence.<BR>Mais il faut se débarrasser<BR>des nombreux Rathian<BR>aperçues dans les collines<BR>proches avant qu'ils ne<BR>l'empêchent de rentrer !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60006.mib" DOWNLOAD CSUM=20528 FSIZE=5756 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Épée forte, bouclier solide</a><BR>
					<a href=#002 qname=m60023.mib>Le mystérieux Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>Le désastre pourpre</a><BR>
					<a href=#004 qname=m60007.mib>La saison du vert</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60006.mib>Piège volcanique !</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m60003.mib>L'ultime bataille</a><BR>
					<a href=#007 qname=m60021.mib>Concert lumière & poison</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête de chasse</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Piège volcanique !
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 3600z<br>
<font color=orange>Contrat：</font> 300z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Volcan(jour)<br>
<font color=orange>Conditions spéciales：</font><br>Aucune<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête de chasse</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Piège volcanique !
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Chasser 2 Basarios<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Homme cupide<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Je suis venu dans la Cein-<BR>ture volcanique chercher du<BR>minerai rare, mais j'ai un<BR>mauvais pressentiment...<BR>Vous devez le sentir aussi,<BR>comme un danger en<BR>approche. Allez vérifier !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60003.mib" DOWNLOAD CSUM=21543 FSIZE=2572 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Épée forte, bouclier solide</a><BR>
					<a href=#002 qname=m60023.mib>Le mystérieux Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>Le désastre pourpre</a><BR>
					<a href=#004 qname=m60007.mib>La saison du vert</a><BR>
					<a href=#005 qname=m60006.mib>Piège volcanique !</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60003.mib>L'ultime bataille</a><BR>
			<tr><td height=30 valign=top>
					<a href=#007 qname=m60021.mib>Concert lumière & poison</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête massacre</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					L'ultime bataille
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 2100z<br>
<font color=orange>Contrat：</font> 150z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Arène<br>
<font color=orange>Conditions spéciales：</font><br>Aucune<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête massacre</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				L'ultime bataille
			</td>
			<td>
				&nbsp;★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tuer 20 Felynes<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Héros lynien<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Voici un défi écrit pour<BR>tous les chasseurs, nya !<BR>Mes amis lyniens et moi<BR>feront souffrir tous ceux<BR>qui pénètrent dans l'arène.<BR>Seuls les plus braves <BR>peuvent nous affronter !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60021.mib" DOWNLOAD CSUM=22434 FSIZE=2492 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Épée forte, bouclier solide</a><BR>
					<a href=#002 qname=m60023.mib>Le mystérieux Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>Le désastre pourpre</a><BR>
					<a href=#004 qname=m60007.mib>La saison du vert</a><BR>
					<a href=#005 qname=m60006.mib>Piège volcanique !</a><BR>
					<a href=#006 qname=m60003.mib>L'ultime bataille</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60021.mib>Concert lumière & poison</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête de chasse</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Concert lumière & poison
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 5100z<br>
<font color=orange>Contrat：</font> 420z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Grande arène<br>
<font color=orange>Conditions spéciales：</font><br>Aucune<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête de chasse</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Concert lumière & poison
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Chasser 2 Gypceros<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Directeur de l'arène<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
L'Arène ! L'endroit où mon-<BR>trer au monde vos talents !<BR>Préparez-vous à affronter<BR>non pas un mais deux<BR>mangeurs d'hommes volants,<BR>des Gypceros ! Montrez-nous<BR>votre force !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
</body>
</html>
