<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=4",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=4&pg_no=0",
		"RB_LINK=DL_MENU.PHP?lang=4&pg_no=2",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60008.mib" DOWNLOAD CSUM=57641 FSIZE=2848 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60008.mib>Espada fuerte, escudo fuerte</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m60023.mib>El misterioso Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>El desastre carmesí</a><BR>
					<a href=#004 qname=m60007.mib>La estación verde</a><BR>
					<a href=#005 qname=m60006.mib>¡Trampa volcánica!</a><BR>
					<a href=#006 qname=m60003.mib>Madre de todas las batallas</a><BR>
					<a href=#007 qname=m60021.mib>Concierto de luz y veneno</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión de caza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Espada fuerte, escudo fuerte
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 6000z<br>
<font color=orange>Contrato ：</font> 500z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Gran arena<br>
<font color=orange>Condiciones especiales：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión de caza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Espada fuerte, escudo fuerte
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Caza al Daimyo Hermitaur<BR>y al Shogun Ceanataur<BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Jefe de la arena<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
¡La arena! ¡Un lugar para<BR>mostrar tus habilidades!<BR>¡Para este evento, hemos<BR>sacado al ring a 2 enemigos<BR>con forma de cangrejo!<BR>¡Que venga todo el que esté<BR>listo para luchar!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60023.mib" DOWNLOAD CSUM=15991 FSIZE=7800 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Espada fuerte, escudo fuerte</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60023.mib>El misterioso Kut-Ku</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m60016.mib>El desastre carmesí</a><BR>
					<a href=#004 qname=m60007.mib>La estación verde</a><BR>
					<a href=#005 qname=m60006.mib>¡Trampa volcánica!</a><BR>
					<a href=#006 qname=m60003.mib>Madre de todas las batallas</a><BR>
					<a href=#007 qname=m60021.mib>Concierto de luz y veneno</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión de caza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					El misterioso Kut-Ku
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 7200z<br>
<font color=orange>Contrato ：</font> 600z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Jungla(N)<br>
<font color=orange>Condiciones especiales：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión de caza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				El misterioso Kut-Ku
			</td>
			<td>
				&nbsp;★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Sobrevive hasta fin de<BR>tiempo o usa el Ticket zarpa<BR><BR>
<font color=orange>Cond. fracaso:</font><br>Si matas menos 2 Kut-Ku:<BR>recomp. cero, fin tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Gremio de cazadores<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Hemos recibido una señal de<BR>socorro del pueblo de la<BR>jungla. Ha aparecido un<BR>extraño rebaño de Kut-Ku que<BR>se ha desbocado por todo el<BR>campo. ¡Ve a esa zona y pon<BR>todo bajo control!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60016.mib" DOWNLOAD CSUM=23179 FSIZE=2392 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Espada fuerte, escudo fuerte</a><BR>
					<a href=#002 qname=m60023.mib>El misterioso Kut-Ku</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60016.mib>El desastre carmesí</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m60007.mib>La estación verde</a><BR>
					<a href=#005 qname=m60006.mib>¡Trampa volcánica!</a><BR>
					<a href=#006 qname=m60003.mib>Madre de todas las batallas</a><BR>
					<a href=#007 qname=m60021.mib>Concierto de luz y veneno</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión especial</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					El desastre carmesí
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 36000z<br>
<font color=orange>Contrato ：</font> 3000z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Campo Batalla<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 6 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión especial</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				El desastre carmesí
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Mata al Fatalis<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Director del Gremio<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Fatalis... Su ira puede<BR>hacer temblar la tierra y<BR>abrasar el cielo. Su maldad<BR>no tiene fin... ¡Cazadores!<BR>¡Hay que hacer algo! Id en<BR>busca de su rugido y acabad<BR>con la muerte púrpura.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60007.mib" DOWNLOAD CSUM=42073 FSIZE=7928 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Espada fuerte, escudo fuerte</a><BR>
					<a href=#002 qname=m60023.mib>El misterioso Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>El desastre carmesí</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60007.mib>La estación verde</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m60006.mib>¡Trampa volcánica!</a><BR>
					<a href=#006 qname=m60003.mib>Madre de todas las batallas</a><BR>
					<a href=#007 qname=m60021.mib>Concierto de luz y veneno</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión de caza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					La estación verde
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 4500z<br>
<font color=orange>Contrato ：</font> 380z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Bosque y colinas<br>
<font color=orange>Condiciones especiales：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión de caza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				La estación verde
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Sobrevive hasta fin de<BR>tiempo o usa el Ticket zarpa<BR><BR>
<font color=orange>Cond. fracaso:</font><br>Si cazas menos de 2 Rathian:<BR>recompensa cero, fin tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Doncella expectante<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Mi hermano por fin vuelve a<BR>casa después de tanto<BR>tiempo. ¡Pero debes ocuparte<BR>de las Rathian que han visto<BR>en las colinas próximas al<BR>pueblo! ¡Puede que no le<BR>dejen volver a casa!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60006.mib" DOWNLOAD CSUM=20528 FSIZE=5756 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Espada fuerte, escudo fuerte</a><BR>
					<a href=#002 qname=m60023.mib>El misterioso Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>El desastre carmesí</a><BR>
					<a href=#004 qname=m60007.mib>La estación verde</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60006.mib>¡Trampa volcánica!</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m60003.mib>Madre de todas las batallas</a><BR>
					<a href=#007 qname=m60021.mib>Concierto de luz y veneno</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión de caza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					¡Trampa volcánica!
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 3600z<br>
<font color=orange>Contrato ：</font> 300z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Volcán(D)<br>
<font color=orange>Condiciones especiales：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión de caza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				¡Trampa volcánica!
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Caza a 2 Basarios<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Mercader ávido<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Vine a la región volcánica<BR>en busca de valiosos<BR>minerales, pero tengo una<BR>constante sensación de<BR>peligro... ¿Lo notas? Es<BR>como si se acercaran muchas<BR>amenazas. ¡Echa un vistazo!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60003.mib" DOWNLOAD CSUM=21543 FSIZE=2572 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Espada fuerte, escudo fuerte</a><BR>
					<a href=#002 qname=m60023.mib>El misterioso Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>El desastre carmesí</a><BR>
					<a href=#004 qname=m60007.mib>La estación verde</a><BR>
					<a href=#005 qname=m60006.mib>¡Trampa volcánica!</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60003.mib>Madre de todas las batallas</a><BR>
			<tr><td height=30 valign=top>
					<a href=#007 qname=m60021.mib>Concierto de luz y veneno</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión matanza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Madre de todas las batallas
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 2100z<br>
<font color=orange>Contrato ：</font> 150z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Arena<br>
<font color=orange>Condiciones especiales：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión matanza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Madre de todas las batallas
			</td>
			<td>
				&nbsp;★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Mata 20 Felynes<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>El héroe Lynian<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
¡Esto es un reto por escrito<BR>para todos los cazadores!<BR>¡Mis amigos Lynian y yo<BR>machacamos a todo el que <BR>pise la arena! ¡Hay que ser<BR>valiente para retarnos, nya!<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60021.mib" DOWNLOAD CSUM=22434 FSIZE=2492 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>２/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60008.mib>Espada fuerte, escudo fuerte</a><BR>
					<a href=#002 qname=m60023.mib>El misterioso Kut-Ku</a><BR>
					<a href=#003 qname=m60016.mib>El desastre carmesí</a><BR>
					<a href=#004 qname=m60007.mib>La estación verde</a><BR>
					<a href=#005 qname=m60006.mib>¡Trampa volcánica!</a><BR>
					<a href=#006 qname=m60003.mib>Madre de todas las batallas</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60021.mib>Concierto de luz y veneno</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión de caza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Concierto de luz y veneno
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 5100z<br>
<font color=orange>Contrato ：</font> 420z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Gran arena<br>
<font color=orange>Condiciones especiales：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión de caza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Concierto de luz y veneno
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Caza 2 Gypceros<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Jefe de la arena<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
¡La arena! ¡Un lugar para<BR>mostrar tus habilidades!<BR>Prepárate para luchar no<BR>con uno, sino dos,<BR>devoradores de humanos:<BR>¡Gypceros! ¡Veamos<BR>tu fuerza!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
</body>
</html>
