<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=4",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=4&pg_no=2",
		"RB_LINK=DL_MENU.PHP?lang=4&pg_no=1",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60022.mib" DOWNLOAD CSUM=51950 FSIZE=2816 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60022.mib>La ira del cielo y la tierra</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m60025.mib>El visitante de acero</a><BR>
					<a href=#003 qname=m60019.mib>Dios del trueno dorado</a><BR>
					<a href=#004 qname=m60018.mib>La guarida de Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Dragón ancestral</a><BR>
					<a href=#006 qname=m60010.mib>Cicatrices en la cara</a><BR>
					<a href=#007 qname=m60012.mib>El viento oscuro y caliente</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión de caza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					La ira del cielo y la tierra
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 9900z<br>
<font color=orange>Contrato ：</font> 830z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Gran arena<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 4 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión de caza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				La ira del cielo y la tierra
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Caza al Rathalos plateado<BR>y al Rathian dorado<BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Jefe pueblo Kokoto<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Amigos, cuánto tiempo ha<BR>pasado... ¡Éste es mi reto<BR>para todos vosotros! Matad<BR>a los dos Wyvern gigantes,<BR>el Rathalos y la Rathian. <BR>¿No tienes las habilidades<BR>para someterlos?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60025.mib" DOWNLOAD CSUM=40969 FSIZE=2716 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>La ira del cielo y la tierra</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60025.mib>El visitante de acero</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m60019.mib>Dios del trueno dorado</a><BR>
					<a href=#004 qname=m60018.mib>La guarida de Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Dragón ancestral</a><BR>
					<a href=#006 qname=m60010.mib>Cicatrices en la cara</a><BR>
					<a href=#007 qname=m60012.mib>El viento oscuro y caliente</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión matanza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					El visitante de acero
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 10500z<br>
<font color=orange>Contrato ：</font> 870z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Ciudad<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 6 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión matanza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				El visitante de acero
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Mata al Kushala Daora<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Maestro del Gremio<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
¡Emergencia! ¡Emergencia! <BR>¡Un Kushala Daora marrón se<BR>acerca a nuestra ciudad!<BR>¡Que vengan enseguida los<BR>cazadores más valientes!<BR>¡¡Necesitamos su ayuda para<BR>salvar la ciudad!!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60019.mib" DOWNLOAD CSUM=22657 FSIZE=2404 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>La ira del cielo y la tierra</a><BR>
					<a href=#002 qname=m60025.mib>El visitante de acero</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60019.mib>Dios del trueno dorado</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m60018.mib>La guarida de Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Dragón ancestral</a><BR>
					<a href=#006 qname=m60010.mib>Cicatrices en la cara</a><BR>
					<a href=#007 qname=m60012.mib>El viento oscuro y caliente</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión de caza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Dios del trueno dorado
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 9000z<br>
<font color=orange>Contrato ：</font> 750z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Gran arena<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 4 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión de caza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Dios del trueno dorado
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Caza al Rajang<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Jefe de la arena<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
¡Es terrible! ¡Absolutamente<BR>terrible! ¡Un gran monstruo<BR>negro ha entrado en mi<BR>arena! ¡Con esa cosa ahí<BR>es imposible comerciar! <BR>¡Ve a matarlo! ¡Por favor!<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60018.mib" DOWNLOAD CSUM=31825 FSIZE=2704 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>La ira del cielo y la tierra</a><BR>
					<a href=#002 qname=m60025.mib>El visitante de acero</a><BR>
					<a href=#003 qname=m60019.mib>Dios del trueno dorado</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60018.mib>La guarida de Remobra</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m60017.mib>Dragón ancestral</a><BR>
					<a href=#006 qname=m60010.mib>Cicatrices en la cara</a><BR>
					<a href=#007 qname=m60012.mib>El viento oscuro y caliente</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión matanza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					La guarida de Remobra
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 6000z<br>
<font color=orange>Contrato ：</font> 500z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Gran arena<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 4 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión matanza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				La guarida de Remobra
			</td>
			<td>
				&nbsp;★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Mata 15 Remobra<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Jefe de la arena<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
¡La arena! ¡Un lugar para<BR>mostrar tus habilidades!<BR>¡Tus oponentes en este<BR>evento son Remobra!<BR>¡Con su veneno por toda la<BR>arena, hay que tener valor<BR>para sobrevivir!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60017.mib" DOWNLOAD CSUM=4766 FSIZE=5096 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>La ira del cielo y la tierra</a><BR>
					<a href=#002 qname=m60025.mib>El visitante de acero</a><BR>
					<a href=#003 qname=m60019.mib>Dios del trueno dorado</a><BR>
					<a href=#004 qname=m60018.mib>La guarida de Remobra</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60017.mib>Dragón ancestral</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m60010.mib>Cicatrices en la cara</a><BR>
					<a href=#007 qname=m60012.mib>El viento oscuro y caliente</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión especial</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Dragón ancestral
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 36000z<br>
<font color=orange>Contrato ：</font> 3000z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Torre<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 6 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión especial</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Dragón ancestral
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Mata al Fatalis<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Hombre mister. esc.<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Je je je... Llegó la hora.<BR>Toma tu invitación al<BR>baile. Ponte tu mejor traje<BR>y lleva tu arma más preciada<BR>porque ha llegado la hora<BR>de bailar con el rey del<BR>desastre.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60010.mib" DOWNLOAD CSUM=31748 FSIZE=7188 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>La ira del cielo y la tierra</a><BR>
					<a href=#002 qname=m60025.mib>El visitante de acero</a><BR>
					<a href=#003 qname=m60019.mib>Dios del trueno dorado</a><BR>
					<a href=#004 qname=m60018.mib>La guarida de Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Dragón ancestral</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60010.mib>Cicatrices en la cara</a><BR>
			<tr><td height=30 valign=top>
					<a href=#007 qname=m60012.mib>El viento oscuro y caliente</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión de caza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Cicatrices en la cara
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 6600z<br>
<font color=orange>Contrato ：</font> 550z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Jungla(N)<br>
<font color=orange>Condiciones especiales：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión de caza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Cicatrices en la cara
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Caza al Yian Garuga<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Luchador herido<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Perseguí al Wyvern herido<BR>por la jungla, pero como yo<BR>también estaba herido, las<BR>fuerzas me fallaron.<BR>¡Venga mi honor y<BR>cázalo en mi<BR>nombre!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60012.mib" DOWNLOAD CSUM=33090 FSIZE=2624 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>La ira del cielo y la tierra</a><BR>
					<a href=#002 qname=m60025.mib>El visitante de acero</a><BR>
					<a href=#003 qname=m60019.mib>Dios del trueno dorado</a><BR>
					<a href=#004 qname=m60018.mib>La guarida de Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Dragón ancestral</a><BR>
					<a href=#006 qname=m60010.mib>Cicatrices en la cara</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60012.mib>El viento oscuro y caliente</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Misión de caza</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					El viento oscuro y caliente
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Recompen.：</font> 9000z<br>
<font color=orange>Contrato ：</font> 750z<br>
<font color=orange>Tiempo 　：</font> 50min<br>
<font color=orange>Zona 　　：</font> Gran arena<br>
<font color=orange>Condiciones especiales：</font><br>Sólo RC 4 o superior<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/ES/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Misión de caza</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Nv. misión:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				El viento oscuro y caliente
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Cond. éxito:</font><br>Caza al Gravios negro<BR><BR><BR>
<font color=orange>Cond. fracaso:</font><br>Recompensa cero<BR>Fin del tiempo<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Jefe de la arena<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
¡La arena! ¡Un lugar para<BR>mostrar tus habilidades!<BR>¡Para este evento, hemos<BR>sacado a la arena no a 1<BR>sino a 2 temibles Gravios<BR>negros! ¿Estás a la<BR>altura del reto?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/ES/BUTTON4.gif></td></tr></table>
</body>
</html>
