<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=5",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=5&pg_no=2",
		"RB_LINK=DL_MENU.PHP?lang=5&pg_no=1",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60022.mib" DOWNLOAD CSUM=51950 FSIZE=2816 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60022.mib>Ira di cielo e terra</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m60025.mib>Il visitatore d'acciaio</a><BR>
					<a href=#003 qname=m60019.mib>Dio del tuono dorato</a><BR>
					<a href=#004 qname=m60018.mib>Covo di Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Drago ancestrale</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>Il vento caldo e oscuro</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. di caccia</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Ira di cielo e terra
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 9900z<br>
<font color=orange>Contratto：</font> 830z<br>
<font color=orange>Tempo　　：</font> 50minuti<br>
<font color=orange>Zona 　　：</font> Grande arena<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 4 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. di caccia</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Ira di cielo e terra
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Caccia il Rathalos argentato<BR>e il Rathian dorato<BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Capovillaggio Kokoto<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
È passato molto tempo, amici<BR>miei... Ecco la mia sfida<BR>per tutti voi! Battete i 2<BR>wyvern giganti, il Rathalos<BR>e il Rathian. Siete in<BR>grado di sottometterli?<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60025.mib" DOWNLOAD CSUM=40969 FSIZE=2716 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Ira di cielo e terra</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60025.mib>Il visitatore d'acciaio</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m60019.mib>Dio del tuono dorato</a><BR>
					<a href=#004 qname=m60018.mib>Covo di Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Drago ancestrale</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>Il vento caldo e oscuro</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. uccisione</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Il visitatore d'acciaio
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 10500z<br>
<font color=orange>Contratto：</font> 870z<br>
<font color=orange>Tempo　　：</font> 50minuti<br>
<font color=orange>Zona 　　：</font> Città<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 6 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. uccisione</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Il visitatore d'acciaio
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi il Kushala Daora<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Maestro della Gilda<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Emergenza! Un Kushala Daora<BR>marrone si sta avvicinando<BR>alla nostra città! Tutti i<BR>cacciatori validi dovrebbero<BR>precipitarsi qui appena<BR>possibile! Ci serve aiuto<BR>per salvare la città!!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60019.mib" DOWNLOAD CSUM=22657 FSIZE=2404 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Ira di cielo e terra</a><BR>
					<a href=#002 qname=m60025.mib>Il visitatore d'acciaio</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60019.mib>Dio del tuono dorato</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m60018.mib>Covo di Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Drago ancestrale</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>Il vento caldo e oscuro</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. di caccia</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Dio del tuono dorato
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 9000z<br>
<font color=orange>Contratto：</font> 750z<br>
<font color=orange>Tempo　　：</font> 50minuti<br>
<font color=orange>Zona 　　：</font> Grande arena<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 4 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. di caccia</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Dio del tuono dorato
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Caccia il Rajang<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Gestore dell'arena<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
È terribile! Assolutamente<BR>terribile! Un enorme mostro<BR>nero ha occupato la mia<BR>arena! Con quello lì dentro,<BR>non possiamo fare affari!!<BR>Liberacene velocemente! Per<BR>favore!!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60018.mib" DOWNLOAD CSUM=31825 FSIZE=2704 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Ira di cielo e terra</a><BR>
					<a href=#002 qname=m60025.mib>Il visitatore d'acciaio</a><BR>
					<a href=#003 qname=m60019.mib>Dio del tuono dorato</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60018.mib>Covo di Remobra</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m60017.mib>Drago ancestrale</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>Il vento caldo e oscuro</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. uccisione</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Covo di Remobra
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 6000z<br>
<font color=orange>Contratto：</font> 500z<br>
<font color=orange>Tempo　　：</font> 50minuti<br>
<font color=orange>Zona 　　：</font> Grande arena<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 4 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. uccisione</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Covo di Remobra
			</td>
			<td>
				&nbsp;★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi 15 Remobra<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Gestore dell'arena<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
L'Arena! Un luogo in cui<BR>mostrare al mondo le tue<BR>capacità! I tuoi avversari<BR>per questo evento sono i<BR>Remobra volanti! Con tutto<BR>il loro veleno, ci vorrà<BR>coraggio per sopravvivere.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60017.mib" DOWNLOAD CSUM=4766 FSIZE=5096 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Ira di cielo e terra</a><BR>
					<a href=#002 qname=m60025.mib>Il visitatore d'acciaio</a><BR>
					<a href=#003 qname=m60019.mib>Dio del tuono dorato</a><BR>
					<a href=#004 qname=m60018.mib>Covo di Remobra</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60017.mib>Drago ancestrale</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>Il vento caldo e oscuro</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. speciale</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Drago ancestrale
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 36000z<br>
<font color=orange>Contratto：</font> 3000z<br>
<font color=orange>Tempo　　：</font> 50minuti<br>
<font color=orange>Zona 　　：</font> Torre<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 6 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. speciale</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Drago ancestrale
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Uccidi il Fatalis<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Uomo mister. scarl.<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Eh eh eh... È giunto il<BR>momento. Ecco il tuo invito<BR>al ballo. Indossa il tuo<BR>abito migliore e porta<BR>l'arma più grande, perché è<BR>ora di andare a danzare con<BR>il re del disastro.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60010.mib" DOWNLOAD CSUM=31748 FSIZE=7188 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Ira di cielo e terra</a><BR>
					<a href=#002 qname=m60025.mib>Il visitatore d'acciaio</a><BR>
					<a href=#003 qname=m60019.mib>Dio del tuono dorato</a><BR>
					<a href=#004 qname=m60018.mib>Covo di Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Drago ancestrale</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60010.mib>Scarface</a><BR>
			<tr><td height=30 valign=top>
					<a href=#007 qname=m60012.mib>Il vento caldo e oscuro</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. di caccia</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Scarface
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 6600z<br>
<font color=orange>Contratto：</font> 550z<br>
<font color=orange>Tempo　　：</font> 50minuti<br>
<font color=orange>Zona 　　：</font> Giungla(notte)<br>
<font color=orange>Condizioni speciali：</font><br>No<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. di caccia</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Scarface
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Caccia lo Yian Garuga<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Combattente ferito<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Ho inseguito il wyvern <BR>ferito nella Giungla;<BR>però, essendo ferito<BR>anch'io, ho esaurito le<BR>forze. Vendica il mio<BR>onore e caccialo in mia<BR>vece!<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60012.mib" DOWNLOAD CSUM=33090 FSIZE=2624 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Ira di cielo e terra</a><BR>
					<a href=#002 qname=m60025.mib>Il visitatore d'acciaio</a><BR>
					<a href=#003 qname=m60019.mib>Dio del tuono dorato</a><BR>
					<a href=#004 qname=m60018.mib>Covo di Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Drago ancestrale</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60012.mib>Il vento caldo e oscuro</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Miss. di caccia</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Il vento caldo e oscuro
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Premio 　：</font> 9000z<br>
<font color=orange>Contratto：</font> 750z<br>
<font color=orange>Tempo　　：</font> 50minuti<br>
<font color=orange>Zona 　　：</font> Grande arena<br>
<font color=orange>Condizioni speciali：</font><br>Solo GC 4 o superiore<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/IT/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Miss. di caccia</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Liv. miss.:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Il vento caldo e oscuro
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condizioni vittoria:</font><br>Caccia i due Gravios neri<BR><BR><BR>
<font color=orange>Condizioni sconfitta:</font><br>Nessun premio<BR>Tempo terminato<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Cliente:</font>Gestore dell'arena<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
L'Arena! Un luogo in cui<BR>mostrare al mondo le tue<BR>capacità! Per questo evento<BR>abbiamo messo nell'arena non<BR>uno, ma due terribili<BR>Gravios neri! Sei<BR>all'altezza di questa sfida?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON4.gif></td></tr></table>
</body>
</html>
