<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=3",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=3&pg_no=2",
		"RB_LINK=DL_MENU.PHP?lang=3&pg_no=1",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60022.mib" DOWNLOAD CSUM=51950 FSIZE=2816 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60022.mib>Furie sur terre et en l'air</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m60025.mib>Le visiteur d'acier</a><BR>
					<a href=#003 qname=m60019.mib>Le dieu doré du tonnerre</a><BR>
					<a href=#004 qname=m60018.mib>L'antre du Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Dragon ancestral</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>Le vent des ténèbres</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête de chasse</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Furie sur terre et en l'air
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 9900z<br>
<font color=orange>Contrat：</font> 830z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Grande arène<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 4 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête de chasse</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Furie sur terre et en l'air
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Chasser le Rathalos argenté<BR>et le Rathian doré<BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Chef Village Kokoto<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Cela faisait longtemps, mes<BR>amis... Voici mon défi pour<BR>vous ! Vaincre deux Wyvern<BR>Rathalos et Rathian géants.<BR>Avez-vous le niveau<BR>nécessaire pour les<BR>vaincre ?<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60025.mib" DOWNLOAD CSUM=40969 FSIZE=2716 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Furie sur terre et en l'air</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60025.mib>Le visiteur d'acier</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m60019.mib>Le dieu doré du tonnerre</a><BR>
					<a href=#004 qname=m60018.mib>L'antre du Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Dragon ancestral</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>Le vent des ténèbres</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête massacre</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Le visiteur d'acier
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 10500z<br>
<font color=orange>Contrat：</font> 870z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Ville<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 6 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête massacre</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Le visiteur d'acier
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tuer le Kushala Daora<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Maître de Guilde<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Alerte ! Alerte ! Un Kusha-<BR>la Daora marron approche<BR>de la ville ! Tous les<BR>chasseurs doivent venir ici<BR>le plus vite possible !<BR>Nous avons besoin de vous<BR>pour sauver la ville.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60019.mib" DOWNLOAD CSUM=22657 FSIZE=2404 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Furie sur terre et en l'air</a><BR>
					<a href=#002 qname=m60025.mib>Le visiteur d'acier</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60019.mib>Le dieu doré du tonnerre</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m60018.mib>L'antre du Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Dragon ancestral</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>Le vent des ténèbres</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête de chasse</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Le dieu doré du tonnerre
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 9000z<br>
<font color=orange>Contrat：</font> 750z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Grande arène<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 4 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête de chasse</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Le dieu doré du tonnerre
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Chasser le Rajang<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Directeur de l'arène<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
C'est absolument terrible !<BR>Un énorme monstre noir<BR>s'est emparé de mon arène !<BR>Nous ne pouvons rien faire<BR>tant qu'il est là !<BR>Débarrassez-nous vite<BR>de lui !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60018.mib" DOWNLOAD CSUM=31825 FSIZE=2704 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Furie sur terre et en l'air</a><BR>
					<a href=#002 qname=m60025.mib>Le visiteur d'acier</a><BR>
					<a href=#003 qname=m60019.mib>Le dieu doré du tonnerre</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60018.mib>L'antre du Remobra</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m60017.mib>Dragon ancestral</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>Le vent des ténèbres</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête massacre</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					L'antre du Remobra
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 6000z<br>
<font color=orange>Contrat：</font> 500z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Grande arène<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 4 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête massacre</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				L'antre du Remobra
			</td>
			<td>
				&nbsp;★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tuer 15 Remobra<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Directeur de l'arène<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
L'Arène ! L'endroit où mon-<BR>trer au monde vos talents !<BR>Cette fois vos adversaires<BR>sont des Remobra volants !<BR>Il faudra du courage pour<BR>survivre à leur poison qui<BR>envahit l'arène !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60017.mib" DOWNLOAD CSUM=4766 FSIZE=5096 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Furie sur terre et en l'air</a><BR>
					<a href=#002 qname=m60025.mib>Le visiteur d'acier</a><BR>
					<a href=#003 qname=m60019.mib>Le dieu doré du tonnerre</a><BR>
					<a href=#004 qname=m60018.mib>L'antre du Remobra</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60017.mib>Dragon ancestral</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
					<a href=#007 qname=m60012.mib>Le vent des ténèbres</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête spéciale</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Dragon ancestral
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 36000z<br>
<font color=orange>Contrat：</font> 3000z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Tour<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 6 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête spéciale</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Dragon ancestral
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tuer le Fatalis<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>L'homme écarlate<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Hé hé hé... L'heure est<BR>venue. Voici votre invita-<BR>tion. Mettez vos plus beaux<BR>vêtements et portez votre<BR>meilleure arme, car il est<BR>temps de danser avec le<BR>roi du désastre.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60010.mib" DOWNLOAD CSUM=31748 FSIZE=7188 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Furie sur terre et en l'air</a><BR>
					<a href=#002 qname=m60025.mib>Le visiteur d'acier</a><BR>
					<a href=#003 qname=m60019.mib>Le dieu doré du tonnerre</a><BR>
					<a href=#004 qname=m60018.mib>L'antre du Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Dragon ancestral</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60010.mib>Scarface</a><BR>
			<tr><td height=30 valign=top>
					<a href=#007 qname=m60012.mib>Le vent des ténèbres</a><BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête de chasse</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Scarface
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 6600z<br>
<font color=orange>Contrat：</font> 550z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Jungle(nuit)<br>
<font color=orange>Conditions spéciales：</font><br>Aucune<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête de chasse</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Scarface
			</td>
			<td>
				&nbsp;★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Chasser le Yian Garuga<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Combattant blessé<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
J'ai pourchassé le Wyvern<BR>blessé dans la jungle, mais<BR>étant moi-même touché j'ai<BR>vite atteint mes limites.<BR>Vengez mon honneur et<BR>chassez-le à ma place !<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  07  1/2 ######################################################## -->
<a name=007></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60012.mib" DOWNLOAD CSUM=33090 FSIZE=2624 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>１/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60022.mib>Furie sur terre et en l'air</a><BR>
					<a href=#002 qname=m60025.mib>Le visiteur d'acier</a><BR>
					<a href=#003 qname=m60019.mib>Le dieu doré du tonnerre</a><BR>
					<a href=#004 qname=m60018.mib>L'antre du Remobra</a><BR>
					<a href=#005 qname=m60017.mib>Dragon ancestral</a><BR>
					<a href=#006 qname=m60010.mib>Scarface</a><BR>
			<tr><td bgcolor=green>
				<a href=#007 qname=m60012.mib>Le vent des ténèbres</a><BR>
			<tr><td height=14 valign=top>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête de chasse</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Le vent des ténèbres
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 9000z<br>
<font color=orange>Contrat：</font> 750z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Grande arène<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 4 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 07 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête de chasse</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Le vent des ténèbres
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Chasser 2 Gravios noirs<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Directeur de l'arène<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
L'Arène ! L'endroit où mon-<BR>trer au monde vos talents !<BR>Cette fois nous avons lâché<BR>pas un mais deux terribles<BR>Gravios noirs ! Êtes-vous<BR>à la hauteur du défi ?<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
</body>
</html>
