<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_SELECT.PHP?lang=3",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:2",
		"LB_LINK=DL_MENU.PHP?lang=3&pg_no=1",
		"RB_LINK=DL_MENU.PHP?lang=3&pg_no=0",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<!-- ########  01  1/2 ######################################################## -->
<a name=001></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60015.mib" DOWNLOAD CSUM=29233 FSIZE=2432 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td bgcolor=green>
				<a href=#001 qname=m60015.mib>La légende de Schrade</a><BR>
			<tr><td height=110 valign=top>
					<a href=#002 qname=m60009.mib>Une tempête de Yian Kut-Ku</a><BR>
					<a href=#003 qname=m60002.mib>Voleur d'œuf nocturne</a><BR>
					<a href=#004 qname=m60024.mib>Nuées après nuées</a><BR>
					<a href=#005 qname=m60014.mib>Singes et crabes !</a><BR>
					<a href=#006 qname=m60013.mib>Crabes et singes !</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête spéciale</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					La légende de Schrade
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 36000z<br>
<font color=orange>Contrat：</font> 3000z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Chât. Schra.<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 6 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 01 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête spéciale</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				La légende de Schrade
			</td>
			<td>
				&nbsp;★★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tuer le Fatalis<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Maître de Guilde<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Le dragon noir Fatalis, évo-<BR>qué dans les légendes schra-<BR>diennes, existerait réelle-<BR>ment ! Si on le laisse, des<BR>pays entiers s'écrouleront.<BR>Nous avons besoin de vous<BR>pour achever son règne !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  02  1/2 ######################################################## -->
<a name=002></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60009.mib" DOWNLOAD CSUM=9441 FSIZE=6688 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>La légende de Schrade</a><BR>
			<tr><td bgcolor=green>
				<a href=#002 qname=m60009.mib>Une tempête de Yian Kut-Ku</a><BR>
			<tr><td height=94 valign=top>
					<a href=#003 qname=m60002.mib>Voleur d'œuf nocturne</a><BR>
					<a href=#004 qname=m60024.mib>Nuées après nuées</a><BR>
					<a href=#005 qname=m60014.mib>Singes et crabes !</a><BR>
					<a href=#006 qname=m60013.mib>Crabes et singes !</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête de chasse</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Une tempête de Yian Kut-Ku
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 2400z<br>
<font color=orange>Contrat：</font> 200z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Jungle(jour)<br>
<font color=orange>Conditions spéciales：</font><br>Aucune<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 02 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête de chasse</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Une tempête de Yian Kut-Ku
			</td>
			<td>
				&nbsp;★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tenir jusqu'à fin du temps<BR>ou livrer Ticket Passechat<BR><BR>
<font color=orange>Condition échec:</font><br>Tuer moins de 2 Kut-Ku<BR>Aucune prime, délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Guilde des chasseurs<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Nous venons d'apprendre que<BR>le village de la jungle<BR>est infesté par des Yian<BR>Kut-Ku ! Dépêchez-vous d'y<BR>aller et d'y ramener le<BR>calme !<BR>　　　　　　　　　　　　　　<br>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  03  1/2 ######################################################## -->
<a name=003></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60002.mib" DOWNLOAD CSUM=25196 FSIZE=9508 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>La légende de Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Une tempête de Yian Kut-Ku</a><BR>
			<tr><td bgcolor=green>
				<a href=#003 qname=m60002.mib>Voleur d'œuf nocturne</a><BR>
			<tr><td height=78 valign=top>
					<a href=#004 qname=m60024.mib>Nuées après nuées</a><BR>
					<a href=#005 qname=m60014.mib>Singes et crabes !</a><BR>
					<a href=#006 qname=m60013.mib>Crabes et singes !</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête collecte</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Voleur d'œuf nocturne
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 4200ｚ<br>
<font color=orange>Contrat：</font> 350z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Jungle(nuit)<br>
<font color=orange>Conditions spéciales：</font><br>Aucune<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 03 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête collecte</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Voleur d'œuf nocturne
			</td>
			<td>
				&nbsp;★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Livrer 3 Œufs de Wyvern<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>La Dame gourmet<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
En fanatique des plats aux<BR>œufs, je peux dire sans<BR>hésitation que les œufs<BR>les meilleurs sont ceux des<BR>Wyvern. Satisfaisez ma<BR>faim en m'apportant<BR>3 Œufs de Wyvern.<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  04  1/2 ######################################################## -->
<a name=004></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60024.mib" DOWNLOAD CSUM=4884 FSIZE=11028 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>La légende de Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Une tempête de Yian Kut-Ku</a><BR>
					<a href=#003 qname=m60002.mib>Voleur d'œuf nocturne</a><BR>
			<tr><td bgcolor=green>
				<a href=#004 qname=m60024.mib>Nuées après nuées</a><BR>
			<tr><td height=62 valign=top>
					<a href=#005 qname=m60014.mib>Singes et crabes !</a><BR>
					<a href=#006 qname=m60013.mib>Crabes et singes !</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête massacre</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Nuées après nuées
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 4500z<br>
<font color=orange>Contrat：</font> 380z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Jungle(jour)<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 4 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 04 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête massacre</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Nuées après nuées
			</td>
			<td>
				&nbsp;★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Tuer 50 Vespoid<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Jeune fille énervée<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
Le pourtour du village est<BR>devenu très bruyant à cause<BR>d'une nuée d'insectes !<BR>Impossible de dormir !<BR>Vous êtes chasseur,<BR>n'est-ce pas ? Alors faites<BR>quelque chose !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  05  1/2 ######################################################## -->
<a name=005></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60014.mib" DOWNLOAD CSUM=37718 FSIZE=2808 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>La légende de Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Une tempête de Yian Kut-Ku</a><BR>
					<a href=#003 qname=m60002.mib>Voleur d'œuf nocturne</a><BR>
					<a href=#004 qname=m60024.mib>Nuées après nuées</a><BR>
			<tr><td bgcolor=green>
				<a href=#005 qname=m60014.mib>Singes et crabes !</a><BR>
			<tr><td height=46 valign=top>
					<a href=#006 qname=m60013.mib>Crabes et singes !</a><BR>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête de chasse</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Singes et crabes !
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 7500z<br>
<font color=orange>Contrat：</font> 620z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Grande arène<br>
<font color=orange>Conditions spéciales：</font><br>Un Rang de plus de 4 est<BR>requis pour cette quête.<BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 05 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête de chasse</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Singes et crabes !
			</td>
			<td>
				&nbsp;★★★★★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Chasser le Blangonga<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Directeur de l'arène<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
L'Arène ! L'endroit où mon-<BR>trer au monde vos talents !<BR>Cette fois votre adversaire<BR>est un Blangonga, mais nous<BR>avons aussi lâché des Cea-<BR>nataur et des Hermitaur !<BR>Attention aux crabes !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
<!-- ########  06  1/2 ######################################################## -->
<a name=006></a>
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=4>
<tr>
	<td width=228>
		<table width=224 border=2 bordercolor=#1C64FE cellspacing=0 bgcolor=black >
		<form action="QUEST/m60013.mib" DOWNLOAD CSUM=40229 FSIZE=2816 method=post>
			<tr>
				<td height=40 width=224 align=center valign=center>
					<table width=103 height=17 cellspacing=0 cellpadding=0 background=GIF/LR.gif>
						<tr>
							<td align=center>
							<B>３/３</B>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td>
					<a href=#001 qname=m60015.mib>La légende de Schrade</a><BR>
					<a href=#002 qname=m60009.mib>Une tempête de Yian Kut-Ku</a><BR>
					<a href=#003 qname=m60002.mib>Voleur d'œuf nocturne</a><BR>
					<a href=#004 qname=m60024.mib>Nuées après nuées</a><BR>
					<a href=#005 qname=m60014.mib>Singes et crabes !</a><BR>
			<tr><td bgcolor=green>
				<a href=#006 qname=m60013.mib>Crabes et singes !</a><BR>
			<tr><td height=30 valign=top>
					<BR>
				<input type=image src="" name=submit width=0 height=0>
			</tr>
		</form>
		</table>
	</td>
	<td width=241>
		<table width=241 background=GIF/QBOARD.gif height=187 cellspacing=0 cellpadding=2>
			<tr>
				<td width=237 height=25 align=center valign=bottom>
					<table width=227 height=21 cellspacing=0 cellpadding=0 background=GIF/T_RED.gif>
						<tr>
							<td height=21 align=center valign=bottom>
								<font color=red>Quête de chasse</font>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align=center>
					Crabes et singes !
				</td>
			</tr>
			<tr>
				<td height=133 valign=top>
<font size=1><br></font>
<font color=orange>Prime　：</font> 4200z<br>
<font color=orange>Contrat：</font> 350z<br>
<font color=orange>Temps　：</font> 50min.<br>
<font color=orange>Zone 　：</font> Grande arène<br>
<font color=orange>Conditions spéciales：</font><br>Aucune<BR><BR>
				</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON3.gif></td></tr></table>
<!####### 06 2/2 #######-->
<img src=GIF/FR/LOGO11.gif width=200 height=50 alt="Event"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=476 height=197 cellspacing=5>
<tr>
	<td>
		<table background=GIF/QBOARD2.gif cellspacing=0 height=187>
		<tr>
			<td colspan=2>
				<table cellspacing=0 cellpadding=0 width=468 height=21>
					<tr>
						<td height=8 ></td>
					</tr>
					<tr>
						<td width=8></td>
						<td width=451 height=21 background=GIF/T_RED.gif>
							<table cellspacing=0 cellpadding=0><tr>
								<td width=209 align=center>
									<font color=red>Quête de chasse</font>
								</td>
								<td width=7></td>
								<td width=232>
									&nbsp;<font color=orange>Niv. quête:</font>
								</td>
							</tr></table>
						</td>
						<td width=8></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align=center>
				Crabes et singes !
			</td>
			<td>
				&nbsp;★★★
			</td>
		</tr>
		<tr>
			<td width=227 221 valign=top>
				<TABLE cellspacing=1><TR><TD>
<font color=orange>Condition succès:</font><br>Chasser l'Hermitaur Daimyo<BR><BR><BR>
<font color=orange>Condition échec:</font><br>Aucune prime<BR>Délai écoulé<BR>
				</TABLE>
			</td>
			<td width=238 242 valign=top>
<img src="" width=5 height=5><BR>
&nbsp;<font color=orange>Client:</font>Directeur de l'arène<BR>
				<TABLE cellspacing=0 cellpadding=0><TR>
				<TD width=8></TD>
				<TD width=230 align=left>
L'Arène ! L'endroit où mon-<BR>trer au monde vos talents !<BR>Cette fois votre adversaire<BR>est un Hermitaur Daimyo<BR>rouge. Tuez-le en faisant<BR>attention aux Conga autour !<BR>Revenez vite !<BR>
				</TABLE>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/FR/BUTTON4.gif></td></tr></table>
</body>
</html>
