<html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP?lang=5",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:6",
		"PIG_CHAR=GIF/PIG.gif",
		"MOVE_CHAR=GIF/rio.gif,82,52,1,1,0,40,-82,180",
		"MOVE_CHAR=GIF/taru.gif,50,50,2,1,1,10,480,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=GIF/BG.gif>
<basefont size=2>
<B>
<img src=GIF/IT/LOGO10.gif width=200 height=50 alt="Quest"><img src=GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0 cellpadding=0 border=0>
<tr>
		<form action="DL_MENU.PHP" method=get>
	<td width=240 height=196 align=center valign=center>
		 <input type=hidden name=lang value=5>
		 <input type=hidden name=pg_no value=0>
		 <input ANIME=1 type=image src="GIF/IT/SELECT1.gif" name=submit width=220 height=160 alt="Event">
	</td>
		</form>
		<form action="DL_CMENU.PHP" method=get>
	<td width=240 height=196 align=center valign=center>
		 <input type=hidden name=lang value=5>
		 <input type=hidden name=pg_no value=0>
		 <input ANIME=1 type=image src="GIF/IT/SELECT2.gif" name=submit width=220 height=160 alt="Challenge">
	</td>
		</form>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=GIF/IT/BUTTON2.gif></td></tr></table>
</body>
</html>
